### ISSUE TITLE
Call to undefined function use_block_editor_for_post() in qtx_admin_gutenberg.php

### ISSUE THREAD

**Issue by woutgg** [qtranslate/qtranslate-xt#1004]
While editing a page, all of a sudden previewing and updating failed due to an internal server error.
This appeared to be caused by `use_block_editor_for_post()` not being defined in [admin/qtx_admin_gutenberg.php:61](https://github.com/qtranslate/qtranslate-xt/blob/master/admin/qtx_admin_gutenberg.php#L61).

As mentioned in [this issue comment](https://github.com/WordPress/gutenberg/issues/14012#issuecomment-467015362), a `require_once` should be used to ensure the function is defined, and adding that indeed solves the problem for me.

**Comment by herrvigg** [comment]
This is rather a bug in WP, not qTranslate. Which version are you using?

**Comment by woutgg** [comment]
I am using Wordpress 5.7, with qTranslate 3.9.0.

**Comment by herrvigg** [comment]
In which situation does this happen?

**Comment by herrvigg** [comment]
> While editing a page, all of a sudden ... 

Was it just once or can you reproduce this problem? Which other plugins are you using?

**Comment by herrvigg** [comment]
All right, this sounds quite weird but it doesn't cost much to add this preventively. I've sent a small patch now in `master`.

**Comment by woutgg** [comment]
I agree that it seems strange. I'm not a Wordpress plugin author, but from what I gather, the require statement should indeed not be necessary in this context (i.e. admin area).

Just for (future) reference, I'll answer your questions here anyway.

I have been using the plugin for some months now (very happy with it!) and it always worked just fine.
Today I couldn't manage to reproduce the issue unfortunately. It happened while I was editing a page in the Gutenberg editor and both the preview and update buttons stopped working (nothing happened at all). Checking for console errors revealed that an XHR request was failing with a 500 status, which turned out to be this error. The same thing started happening to someone else who was editing a page as well.

Then while I was investigating the error by disabling plugins, things started working again for me (and kept working, even with all plugins re-enabled). And for the other person as well, after clearing all browser data. Soon after however, more or less the same problem returned and this time I found the source, and the 'fix' you have now added.

As far as I remember I have not added or activated any plugins before this started happening, but I might have done regular plugin updates. The active plugins are:

- Advanced noCaptcha & invisible Captcha @6.1.5
- Akismet Anti-Spam @4.1.9
- Collapse-O-Matic @1.7.13
- Editor Full Width Gutenberg @1.0.5
- File Upload Types @1.2.1
- Head & Footer Code @1.2.1
- Health Check & Troubleshooting @1.4.5
- Hello Dolly @1.7.2
- Jetpack by WordPress.com @9.6
- qTranslate-XT @3.9.0
- Smart Slider 3 @3.4.1.17
- Tracking code for Matomo, by Sergio Santos @1.1.3
- WPBakery Page Builder @6.2.0

**Comment by herrvigg** [comment]
Release in 3.10.0.
