### ISSUE TITLE
qTranslateConfig.qtx is undefined

### ISSUE THREAD

**Issue by smiddus** [qtranslate/qtranslate-xt#1006]
I am getting this js error on the Appearance/Menus page:
```
TypeError: can't access property "getActiveLanguage", qTranslateConfig.qtx is undefined 
mywebsite.local/app/plugins/qtranslate-xt-3.9.3/modules/acf/assets/common.js?ver=1616778581 line 62
```

This also blocks JS functionality such as expanding/collapsing under 'Add menu items', which means I can only add pages and not not for example custom links or a page switcher to my menus)

(Using qtranslate-xt 3.9.3, WP 5.6, ACF pro 5.9.5)

**Comment by herrvigg** [comment]
This could be the same issue as #988. Do you have the possibility to try with the current version on `master`? I have changed the way the ACF scripts are initialized. You may simply rename your current qtranslate-xt folder and unzip the last version from github for a test.

**Comment by smiddus** [comment]
I tried the current version and it gives me different errors:
In dashboard (general):
`ReferenceError: qTranslateConfig is not defined mywebsite.local/wp/wp-admin/ line 1578`
In appearence/menus and other places:
`TypeError: "repeaterFieldRemove" is read-only mywebsite.local/app/plugins/qtranslate-xt-3.10.0.dev.2/dist/modules/acf.js?ver=3.10.0.dev.2 line 1`

**Comment by MK-RD** [comment]
I was able to reproduce the behavior after changing the Internet connection throttling to Good 2G. 

**Throttling**
https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Throttling

**Comment by herrvigg** [comment]
@smiddus I've pushed a new patch to fix these 2 problems with JS. Could you please retry with this?

About `repeaterFieldRemove`  I have two questions:
- RepeaterField is not defined in acf.models though it was assumed to be the case in the past. Does anyone know if this has become obsolete?
- there was a `repeaterRemove` function supposed to do some cleanup but I have no clue who is supposed to call that or when. It's coming from the [legacy plugin](https://github.com/funkjedi/acf-qtranslate/blob/a7f3418327d355e2e8a2fb5be4b242939efe6311/assets/acf_5/qtranslatex.js#L100) but I don't think it was ever enabled, unless some script call "magically" a global function (which would be suprising).
https://github.com/qtranslate/qtranslate-xt/blob/cff7ec72584df0eb9766117d5b25568db5e4700d/modules/acf/js/qtranslatex.js#L74-L76

@MK-RD not sure I understand the effect of throttling. How is that related to this issue? The only possibility I see would be to shuffle the asynchronous events but that was a problem in 3.9.3 not with the last changes in `master` (3.10.0.dev.x).

**Comment by MK-RD** [comment]
@herrvigg The changes should fix the problem!

By throttling the network speed, certain problems like this can possibly be checked against.

**Comment by smiddus** [comment]
> @smiddus I've pushed a new patch to fix these 2 problems with JS. Could you please retry with this?

It works. Haven't encountered any of the previous errors yet. Thanks!
