### ISSUE TITLE
Add Support for wp-graphql

### ISSUE THREAD

**Issue by ShahriarKh** [qtranslate/qtranslate-xt#1011]
I'm not sure whether I should ask here or ask [wp-graphql](https://github.com/wp-graphql/wp-graphql) developers, but an extension to use data generated with qtranslate-xt is critical.

**Comment by herrvigg** [comment]
This sounds very specific, not critical, I don't mean it would not be useful but first the needs should be clarified.
You can first take a look at the integration guide: https://github.com/qtranslate/qtranslate-xt/wiki/Integration-Guide
Certainly the job of a full stack developer. On my side I will not work on this, sorry.

**Comment by Matoseb** [comment]
Would be a nice addition, I'm currently working on a headless multilingual wordpress which delivers the content using the graphql API for a Nuxt App. I could try using the Rest API feature but it's more tedious
