### ISSUE TITLE
Translation for custom post types

### ISSUE THREAD

**Issue by tlonovoi** [qtranslate/qtranslate-xt#1014]
Hello, I have 2 custom post types and I dont know how to translate them so they appear in breadrumbs translated. 
Thank you in advance!

**Comment by tlonovoi** [comment]
Sorry but I've found how to make it. Short function in functions.php 
function translate_ua_en_ru (  $text_ukr, $text_english, $text_russian ) { 
			switch ( qtranxf_getLanguage()  ) { 
				case "uk": return $text_ukr;
									break;
				case "en": return $text_english;
									break;
				case "ru": return $text_russian;
			}		
	}

After that you have to use it when declaring you post type in labels array

function my_custom_post_type() {
			$labels = array(
				'name'                => __( translate_ua_en_ru( "lang1","lang2","lang3" ) ),

**Comment by herrvigg** [comment]
You could also enter the text as ML content and let QTX do the translation - it's a bit what it's meant for ;)
For example:
```
'name' => __( "[:uk]content-uk[:en]content-en[:ru]content-russian[:]" ),
```

That's because there's a qTranslate hook on gettext.

Under the hook it's exactly as doing a QTX call like this:
```
'name' => qtranxf_useCurrentLanguageIfNotFoundUseDefaultLanguage("[:uk]content-uk[:en]content-en[:ru]content-russian[:}",
```
if you don't need any other functionality of gettext.

**Comment by tlonovoi** [comment]
Thank you!
