### ISSUE TITLE
class for the qtranslate flag

### ISSUE THREAD

**Issue by vonsch76** [qtranslate/qtranslate-xt#1015]
Please add a **class** to qtranslate flags, so lazy load can be set in a caching plugin and thus - with the class - the flags can be excluded.

I would do 

class="qtranxs-flag"

Works well with W3TC, when updated the frontend.
Having a class like no-lazy or skip_lazy will automatically exclude from lazy load.

**Comment by herrvigg** [comment]
We can surely add a `qtranxs-flag` class. Is that enough to have any class to enable lazy load?

For `no-lazy` that's surely up to the theme or plugin but I don't know how this would be set. Maybe there's a different way to say no lazy load for `qtranxs-flag` instead.

**Comment by vonsch76** [comment]
These are the standard excluded words

avia-bg-style-fixed
data-bgposition=
data-envira-src=
data-large_image=
data-lazy-original=
data-lazy-src=
data-lazyload=
data-lazysrc=
data-no-lazy=
data-src=
data-srcset=
fullurl=
lazy-slider-img=
loading="eager"
no-lazy
rev-slidebg
soliloquy-image
swatch-img
w3-total-cache
woocommerce/assets/images/placeholder.png
wpcf7_captcha
skip_lazy

Adding one of these as a class would elliminate the need to add a specific extra word to the list. One of these classes prohibit lazy load per se.

https://www.boldgrid.com/support/w3-total-cache/configuring-lazy-loading-for-your-wordpress-website-with-w3-total-cache/

By adding a class like I suggested this morning the class needs to be added to the exclude list. 

Here is the result from the latter

<img class="qtranxs-flag" src="wp-content/plugins/qtranslate-xt-3.10.0/flags/gb.png" alt="English">

![image](https://user-images.githubusercontent.com/11445377/117058840-6715b780-ad1f-11eb-9030-8a2995724c96.png)

skip_lazy (and preferably the other words) work the same

<img class="skip_lazy" src="/wp-content/plugins/qtranslate-xt-3.10.0/flags/gb.png" alt="English">

![image](https://user-images.githubusercontent.com/11445377/117059417-1488cb00-ad20-11eb-9b8c-7953210cca75.png)

without the class

<img class=" lazy" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%201%201'%3E%3C/svg%3E" data-src="/wp-content/plugins/qtranslate-xt-3.10.0/flags/gb.png" alt="English">

![image](https://user-images.githubusercontent.com/11445377/117059087-b52abb00-ad1f-11eb-91b7-5d6b5fe62798.png)

As you can see the class lazy was added by W3TC plugin and it is kind of a mess - half of the screen.

Either one is a good solution, maybe the standard excluded word is easier in a way that no extra setting is needed. Basically you would not want the flag to be not loaded (or loaded on-the-fly) as any other image which is not visible. In the mobile menu the image of the flag is usually in the non-visible territory.

**Comment by herrvigg** [comment]
@vonsch76 I just pushed a change on master to add `qtranxs-flag` class to the flags for the frontend. I hope I didn't forget anything, this applies to menus and widgets. Not so relevant for the admin part but we may add that later.

**Comment by vonsch76** [comment]
Thank you, maybe you need to add to the documentation to use the flag to disallow lazy load.

**Comment by herrvigg** [comment]
Updated wiki here: https://github.com/qtranslate/qtranslate-xt/wiki/Front-language-switching#how-can-i-prevent-lazy-loading-of-the-flags
