### ISSUE TITLE
Language change problem and ACF

### ISSUE THREAD

**Issue by jujutou** [qtranslate/qtranslate-xt#1017]
Hello,
First of all, I am quite a beginner in the field and do not master everything.
I took over the website of my work because I am the most competent for it among all.

I have a problem that I cannot solve:
For pages, articles and publications: there is no problem I can create English and French pages.
But for some pages (departments, team and job) the English / French change does not work
For some it is capricious and others the text is not displayed.

For history: the plugin had some problems because not updated to qtranslateXT. The old team had to set up a second language switch via ACF.
Today, I realized the replacement of the plugin by qtranslateXT and the second switch which had installed by ACF seems to be problematic.
Indeed, for example in the department area: the text that I write in the English frame is displayed and modified. Whereas if I write in the French context, the text disappears and does not change on the public site.

I can't find how to fix the problem. I tried to modify the ACFs but without success. But I may not have tried everything.

Do you have any ideas ?
Thank you !
Cordially !

**Comment by herrvigg** [comment]
> For history: the plugin had some problems because not updated to qtranslateXT. The old team had to set up a second language switch via ACF

No idea about your ACF setting, hard to understand what you are trying to do. What do you mean with "second language switch"? 

> For pages, articles and publications: there is no problem I can create English and French pages.
> But for some pages (departments, team and job) the English / French change does not work

What do you mean with "departments, team and job"? This looks like something specific to your environment. If those are specific post types, just look if they are checked in the advanced settings of QTX. Otherwise, impossible to say without more information from your part.
