### ISSUE TITLE
Broken editor with single language and visual mode

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#1018]
The editor content is corrupted when starting in visual mode and single language mode (advanced settings of QTX).
New lines disappear. The problem is related to the handling of `wpautop`.

It works when  starting in text mode and switching to visual mode.
The translatable class is missing in that case.

**Comment by MK-RD** [comment]
QTX 3.10.0

For some reason I cannot reproduce this behavior. 
Classic Editor or Block Editor?

**Comment by herrvigg** [comment]
Classic Editor, you have to start in Visual Mode when loading the post. The content was corrupted with new lines deleted.

Fixed in 3.10.1.
