### ISSUE TITLE
Issue with strings with %s in them

### ISSUE THREAD

**Issue by Hr0bar** [qtranslate/qtranslate-xt#1020]
qTranslateXT cant handle strings such as:

[:en]%s images[:sk]%s obrázkov[:]

Issue emerged as an compatibility issue with plugin FooGallery where maintainers pointed to qTranslate:

#https://wordpress.org/support/topic/warning-in-v2-sprintf-too-few-arguments-in-class-foogallery-php-on-line-372/

**Comment by herrvigg** [comment]
qTranslate-XT handles that correctly. It looks like a problem of integration on your side depending on how you use this string. I answered on the WP topic.
