### ISSUE TITLE
OG:DESCRIPTION is not translated

### ISSUE THREAD

**Issue by antonzol** [qtranslate/qtranslate-xt#1022]
Example: https://visimka.com/en/hub/
Wordpress: 5.7.2
qTranslate-XT 3.10.0
Yoast SEO 16.2
Integration: Yoast SEO & qTranslate-X  1.1.1

I fill it with [:en] tags and in frontend tags present.

`<meta property="og:description" content="[:ua]Оренда приміщень, робочих місць, комп&#039;ютерів для роботи з відео та фото. Postproduction HUB на Подолі [:en]Rent of premises, workplaces, computers for work with video and photo. Postproduction HUB in Podil[:]" />`

And description is work correctly. Text is in same field in admin panel.
`<meta name="description" content="Rent of premises, workplaces, computers for work with video and photo. Postproduction HUB in Podil" />
`
In code I do not find any difference between wpseo_opengraph_desc and wpseo_metadesc
Maybe somebody already fix it?

**Comment by herrvigg** [comment]
See https://developer.yoast.com/customization/apis/metadata-api/
- `wpseo_opengraph_desc` is for `og:description`
- `wpseo_metadesc` is for `description`

If `og:description` is not translated the problem looks similar to #989.

**Comment by herrvigg** [comment]
> Integration: Yoast SEO & qTranslate-X 1.1.1

This is obsolete, the Yoast module cannot be enabled in QT-XT if the legacy plugin is active.

**Comment by antonzol** [comment]
After disabling Integration: Yoast SEO & qTranslate-X this tag is OK


Or after adding 11 and 41 lines to config. Thanks, herrvigg!
`{"vendor":{"plugins/wp-seo-qtranslate-x":"1.0"},
"admin-config":{
"post":{
	"pages":{"post.php":"", "post-new.php":""},
	"forms":{
		"post":{
			"fields":{
				"yoast_wpseo_title":{},
				"yoast_wpseo_focuskw":{},
				"yoast_wpseo_metadesc":{"encode":"{"},
				"yoast_wpseo_opengraph_desc":{"encode":"{"},
				"yoast_wpseo_metakeywords":{},
				"wpseosnippet_title":{"encode":"display"}
			}
		}
	}
}
,
"edit-tag":{
	"pages":{"edit-tags.php":"action=edit"},
	"forms":{
		"edittag":{
			"fields":{
				"wpseo_title":{},
				"wpseo_desc":{},
				"wpseo_metakey":{},
				"wpseo_canonical":{}
			}
		}
	}
}
}
,
"front-config":{
"all-pages":{
	"filters":{
		"text":{
			"wpseo_title":"20",
			"wpseo_meta":"20",
			"wpseo_metadesc":"20",
			"wpseo_opengraph_desc":"20",
			"wpseo_replacements":"20"
		}
	}
}
}
}`

**Comment by herrvigg** [comment]
@antonzol good!
FYI the i18n config is now handled in the PHP code in `qtranslate-xt/modules/wp-seo/wp-seo-front.php`.
The old `plugins\wp-seo-qtranslate-x` should remain disabled, it's obsolete.
