### ISSUE TITLE
Qtranslate slug php8

### ISSUE THREAD

**Issue by andreysneg** [qtranslate/qtranslate-xt#1028]
"Qtranslate XT" and plugin "Qtranslate slug" always work together. 
It would be good if you add "Qtranslate slug" functionality into Qtranslate XT.  

Now problem with "Qtranslate slug" in php 8.  Something with Widget organization. I think this is very simpe problem.

This is error:
`Fatal error: Uncaught ArgumentCountError: Too few arguments to function WP_Widget::__construct(), 0 passed in D:\_Web\wpee\wp-includes\class-wp-widget-factory.php on line 61 and at least 2 expected in D:\_Web\wpee\wp-includes\class-wp-widget.php:162 Stack trace: 
#0 D:\_Web\wpee\wp-includes\class-wp-widget-factory.php(61): WP_Widget->__construct() 
#1 D:\_Web\wpee\wp-includes\widgets.php(115): WP_Widget_Factory->register() 
#2 D:\_Web\wpee\wp-content\plugins\qtranslate-slug\includes\class-qtranslate-slug.php(2546): register_widget() 
#3 D:\_Web\wpee\wp-includes\class-wp-hook.php(292): QtranslateSlug->widget_init() 
#4 D:\_Web\wpee\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filters() 
#5 D:\_Web\wpee\wp-includes\plugin.php(484): WP_Hook->do_action() 
#6 D:\_Web\wpee\wp-includes\widgets.php(1799): do_action() 
#7 D:\_Web\wpee\wp-includes\class-wp-hook.php(292): wp_widgets_init() 
#8 D:\_Web\wpee\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filters() 
#9 D:\_Web\wpee\wp-includes\plugin.php(484): WP_Hook->do_action() 
#10 D:\_Web\wpee\wp-settings.php(560): do_action() #11 D:\_Web\wpee\wp-config.php(118): require_once('D:\\_Web\\wpee\\wp...') #12 D:\_Web\wpee\wp-load.php(37): require_once('D:\\_Web\\wpee\\wp...') #13 D:\_Web\wpee\wp-admin\admin.php(34): require_once('D:\\_Web\\wpee\\wp...') #14 D:\_Web\wpee\wp-admin\edit.php(10): require_once('D:\\_Web\\wpee\\wp...') #15 {main} thrown in D:\_Web\wpee\wp-includes\class-wp-widget.php on line 162`

**Comment by vonsch76** [comment]
Agree, it would be good to have the slug function integrated. "Qtranslate slug" plugin is not downloadable for a while.

**Comment by herrvigg** [comment]
See #671. Sure it would be good, but I don't have the time to integrate and test all of this.
If developers using slug can prepare a PR to merge that could be already a first step.

**Comment by herrvigg** [comment]
This should be easy to fix but it's not part of the qTranslate-XT code yet. See main thread #671.
