### ISSUE TITLE
I switched from "qTranslate X" to "qTranslate-XT" and the translation disappeared.

### ISSUE THREAD

**Issue by correctness7** [qtranslate/qtranslate-xt#1029]
Hi,
I switched from "qTranslate X" to "qTranslate-XT" and the translation disappeared.

There was a reset error message, so I reset it.
Because there was no Khmer language. Added.
However, the translated content will not be reflected.

What should i do?

Kind Regards,

**Comment by correctness7** [comment]
Hi,
Thank you in advance.

I reverted to "qTranslate X".
"Then I received the following error message:
Option "Configuration Files" for plugin qTranslate-X has been auto-adjusted after recent changes in the site configuration. It might be a good idea to review the changes in the list of configuration files. "

After reverting to "qTranslate X", the Khmer translation was gone.
Recovered the data stored on the server.
However, the translated content is not restored.

Am i wrong?


Best Regard

**Comment by correctness7** [comment]
I solved it myself.

**Comment by herrvigg** [comment]
@correctness7 why are you reverting to QT-X? It's not maintained since 2016. There are dozens of bugs fixed in QT-XT plus new features.

**Comment by correctness7** [comment]
This issue was another part.
The problem is now resolved.
The translation was taken over by QT-XT.
I have enabled QT-XT and removed QT-X.
Thx.
