### ISSUE TITLE
Important: Never change the default language once it is chosen.

### ISSUE THREAD

**Issue by MK-RD** [qtranslate/qtranslate-xt#1031]
Has anyone had any experience with this or what (technical) disadvantage should I expect?

**Comment by herrvigg** [comment]
I don't see how this would be a problem, it should not impact the raw context that are defined for each languages independently.

**Comment by MK-RD** [comment]
Did you know that, according to the Startup Guide (First Steps), the site could become **unusable because** the default language **values are saved differently**?

[https://github.com/qtranslate/qtranslate-xt/wiki/Startup-Guide](url)

If that should really be the case, then this would be a reason not to use this plugin (anymore).

It is completely clear to me that a change in the standard language in connection with third parties (e.g. search engines) has consequences.

**Comment by herrvigg** [comment]
Right, the link is broken but here is what we have in the startup guide:
> Important: Never change the default language once it is chosen. Once the content is populated, the default language values are stored differently and changing of the default language may make site unusable. 

I recopied that from the old qTranslate-X and did not double check everything but in fact I find it very surprising, I have a website in production and I don't see anything special about the storage of the default language.

That could be obsolete... but I can't be 100% sure. Let's remain cautious until this is better tested.

**Comment by MK-RD** [comment]
I already assumed that, but maybe this should be rephrased a little.

**Comment by herrvigg** [comment]
Reformulated putting more emphasis on the two-letter code than default language.
> **_Important_**: It is very difficult to change two-letter codes of the languages, once the site is populated with translations. Please, think carefully about choosing two-letter codes and the default language to begin with. Do not plan on changing them in the future. It is not impossible to change it, but it would be a very difficult and time consuming manual operation on the database. Also, avoid changing the default language once it is chosen, the expected behavior is now well defined. 

https://github.com/qtranslate/qtranslate-xt/wiki/Startup-Guide/_compare/130791255fee2b53ce6fee97444fbe7254552591...64f975f46defcc53d26823a435e16c718b4a6ddc
