### ISSUE TITLE
FYI/help requested: qTranlate Slug CSRF vulnerability

### ISSUE THREAD

**Issue by The3IC** [qtranslate/qtranslate-xt#1036]
Sorry to misuse this section, but as I know there are a lot of qTranslate XT users also using qT slug, I hope this is OK. I was approached by my hosting provider with a message that qTranslate Slug has a vulnerability due to mishandling of CSRF nonce, see [https://wpscan.com/vulnerability/3725296b-c316-440a-875a-3068fb876b3b](url) and [https://wpscan.com/plugin/qtranslate-slug](url).

So first of all, this is a heads-up to all users of qT with qT slug. Also I know there are some quite capable coders around here that also use qTranslate Slug so this is kind a request/wish if someone could share a fix to the issue. Unfortunately, I'm not a coder so amnot able to contribute to a fix.

**Comment by bagaweb** [comment]
Thanks for pointing out this issue.
Which hosting provider warned you about it?
Anyway unfortunately I'm not able to help in fixing the code.

**Comment by The3IC** [comment]
Hi @bagaweb , the hosting provider is a local Finnish one called WP Cloud. But the info comes from the generic wpscan service.

**Comment by herrvigg** [comment]
It's fine to discuss slug here so people can coordinate. On my side, I won't work on this as I don't use slug and it would be harder for me to test this properly, see also #671. 

If developers can prepare a clean PR to merge slug, it could be added as a purely experimental support, I could just maintain the function API but as said, not able to test this.

**Comment by bagaweb** [comment]
Thanks for the updates. IMHO slugs should be part of the core.

**Comment by herrvigg** [comment]
Let's continue the discussion in the main thread #671.
