### ISSUE TITLE
Don't echo hreflang if returned value is empty

### ISSUE THREAD

**Issue by reekrd** [qtranslate/qtranslate-xt#1038]
Hi,

our site is translated into two languages and a subpart of it is translated into five languages.

We want to avoid having `<link hreflang=...>` to all languages on pages where content is only translated in english and dutch.

I have not installed the latest release so have not tried the new filter. But looking at `qtranxf_wp_head` if the returned value from the filter `qtranslate_hreflang` returns empty then don't `echo <link hreflang=...>`

Cheers and thank you for the excellent work
.rickard

**Comment by reekrd** [comment]
I was looking at code here: https://github.com/qtranslate/qtranslate-xt/blob/6837ebb4733a030fb0ef64f75ba0be59a747b9eb/qtranslate_frontend.php 

I know I see that is not part of a release

**Comment by herrvigg** [comment]
> I was looking at code here: https://github.com/qtranslate/qtranslate-xt/blob/6837ebb4733a030fb0ef64f75ba0be59a747b9eb/qtranslate_frontend.php
> 
> I know I see that is not part of a release

It was a temporary attempt but I removed it as I wasn't so happy with it for the handling of the locales, in relation to #668 and #1030.

Your need is different as I can see in #1039 but I have to rethink this better to come up with a filter better suited for all cases.

**Comment by herrvigg** [comment]
Closed by #1039 (still to be done).
