### ISSUE TITLE
php 7.4  Uninitialized string offset 2: qtranslate_utils.php on line 460   

### ISSUE THREAD

**Issue by andreysneg** [qtranslate/qtranslate-xt#1047]
Version 3.10.1

If set php 7.4 or php 8.0 when error:
Warning: Uninitialized string offset 2 in /wp-content/plugins/qtranslate-xt-master/qtranslate_utils.php on line 460

Php 7.3 - no error.

**Comment by herrvigg** [comment]
@andreysneg That's strange. In fact there's a check on the string size missing, but I don't see why it would be different with PHP 7.3: https://www.php.net/manual/en/migration74.php

The case you encounter is a very special case when the language name has no translation.

**Comment by herrvigg** [comment]
I pushed a fix to master just for that bug.

Beyond this minor issue, that function looks quite weird and should be reworked to fix #668 and maybe #1030.

**Comment by herrvigg** [comment]
Released in 3.11.0.

**Comment by andreysneg** [comment]
version 3.11 - there is still an error
