### ISSUE TITLE
Wrong link rel="alternate" links in HTML head

### ISSUE THREAD

**Issue by EasyEl** [qtranslate/qtranslate-xt#1054]
Hey there,

I noticed that the combination of the qtranslate-xt with the oldie but goldie qtranslate-slug stopped working. Somehow the creation of the alternate links in the header does not respect the slug settings anymore. I know that you do not support qtranslate-slug but maybe you can point me to a qtranslate-xt release that was prior to the change that broke it.

Example:
https://aerobis.com/de/does/exzentrisches-training/ 
https://aerobis.com/does/eccentric-training/

I run on 3.9.1. Any help is appreciated.

Best,
Elmar

**Comment by EasyEl** [comment]
Nevermind. I decided to retire the slug plugin and redirect everything.

**Comment by bagaweb** [comment]
I'm not encountering this problem.

**Comment by EasyEl** [comment]
Hey @herrvigg @bagaweb - I actually closed this and retired slug. Sometimes its hard to track down the root cause. I fused qtranslate with AI translation for all languages outside of DE/EN. This is working well but in the end it also causes friction sometimes... got it all working now and this case can retire. Thanks for looking into it regardless!
