### ISSUE TITLE
PHP Fatal error:  Allowed memory size bytes exhausted

### ISSUE THREAD

**Issue by valerensi** [qtranslate/qtranslate-xt#1064]
Hello, 
just to inform you that in several project the latest plugin version caused an error.
We see a 502 error on website and in file log we see a PHP fatal error "Allowed memory size of xxx bytes exhausted"
Also our hosting provider has confirm that is qtranslate-xt that cause this issue. 
With the previous version it seams that the problem doesn't occur.
I hope that this will helps for future fix.

**Comment by valerensi** [comment]
Hi,
I'm not sure that it is occurred with the latest version, but in some case when we have replaced the plugin with the previous one, this solved the issue. Maybe, I have found out which should be the problem talking with server support. 

We have to different type of configuration on our server:

1) mod_php 
2) mod_fastcgi (used by the most provider). 

It seams that error occurred when we turn to mod_php. 
So we have solved with this configuration but maybe you need to know :)

**Comment by MagicFab** [comment]
I had the same problem, had to change theme (Pilgrim) to a newer one.

**Comment by herrvigg** [comment]
@valerensi good that you solved it with mod_php. In fact fastCGI is consuming more: https://2bits.com/articles/apache-fcgid-acceptable-performance-and-better-resource-utilization.html

Still we should improve QTX to reduce the memory consumption. To be investigated better.

**Comment by herrvigg** [comment]
Seems the workaround holds but for the memory consumption see also #1286 .

**Comment by varoriya** [comment]
Today I install wordpress  and install qtranslate-xt 3.15.2 I found the memory was used from 2% to 99%, I romove than install qtranslate-xt 3.14.2 it's works normally.
