### ISSUE TITLE
language needs to be shown in url

### ISSUE THREAD

**Issue by andreysneg** [qtranslate/qtranslate-xt#1068]
How disable message - "language needs to be shown in url "  ?

Payment gateway Paysera.com dont work and send error:

'<br /> <b>Warning</b>: assert(): language needs to be shown in url - cancelled by can_redirect, url_info={ &quot;cookie_front_or_admin_found&quot;: false, &quot;scheme&quot;: &quot;https&quot;, &quot;host&quot;: &quot;kruvid24.ee&quot;, &quot;path&quot;: &quot;\/&quot;, &quot;query&quot;: &quot;wc-api=wc_gateway_paysera&quot;, &quot;original_url&quot;: &quot;\/?wc-api=wc_gateway_paysera&quot;, &quot;path-base&quot;: &quot;&quot;, &quot;doing_front_end&quot;: true, &quot;wp-path&quot;: &quot;\/&quot;, &quot;doredirect&quot;: &quot;language needs to be shown in url - cancelled by can_redirect&quot;, &quot;language&quot;: &quot;et&quot;, &quot;set_cookie&quot;: true } failed in <b>/home/kruvidee/public_html/wp-content/plugins/qtranslate-xt-master/qtranslate_core.php</b> on line <b>105</b><br /> OK'

**Comment by herrvigg** [comment]
In theory, the assert can be commented. But this means we are in a bad state that could lead to all kind of issues. I left such asserts intentionally to understand better this kind of issues. 

This error means:
-  the "expected language" is not in the URL and a redirection would be required to set the language state properly,
-  but... the redirection is not allowed because the request is on admin pages, AJAX, WP_CLI, CRON or REST. 

Your request appears as "doing_front_end: true" but who is triggering this? Maybe the problem comes  "cookie_front_or_admin_found": false.

**Comment by herrvigg** [comment]
It surely comes from the missing cookie. In that case it will try to detect the language from the browser or HTTP_REFERER, or take the default language. The error means that the resulting language does not match the URL settings. Let's say you have `en` as default language and the language detection finds `et` as shown here. Then the expected URL is `/et/?wc-api=wc_gateway_paysera`.

I suppose you have the front cookies enabled but why isn't the cookie set in that case? This may depend on how this request is triggered. Maybe that should be considered as a REST request? Currently it's not.

**Comment by andreysneg** [comment]
I think . Instead of this message  "Language needs to be shown in url"  plugin must automaticaly add Default language to url and all. 

Url   /?wc-api=wc_gateway_paysera  - make Payment plugin and impossible change this.  
I had this error with other plugins too .

Now i turned on - Detect the language of the browser and redirect accordingly. 
Let's see what happens.

If i comment line 446 in qtranslate_core.php  what will happen ?
$url_info['doredirect'] = 'language needs to be shown in url';

or do this:
$url_info['doredirect'] = '' ;

or replace line 446 to:
$url_info['lang_browser'] = $q_config['default_language'];;


I just need no errors to appear.

**Comment by herrvigg** [comment]
Related to #1326.

**Comment by herrvigg** [comment]
Fix released in 3.14.2.
