### ISSUE TITLE
W3C Markup Validation Failed

### ISSUE THREAD

**Issue by SeoDeveloper01** [qtranslate/qtranslate-xt#1074]
Let's drop some legacy

![legacy](https://user-images.githubusercontent.com/91273094/139066615-9fa81743-be66-4c62-ab3d-aa790b895fc5.PNG)

**Comment by herrvigg** [comment]
Yes good point, from HTML 5 it's not required for javascript and from HTML 5.2 it should not be used.

**Comment by herrvigg** [comment]
Fixed in master.

Do you also have a warning for `type="text/css"` in `style`? I'd rather leave it if it's not raised by the validation tool.

**Comment by SeoDeveloper01** [comment]
> Fixed in master.
> 
> Do you also have a warning for `type="text/css"` in `style`? I'd rather leave it if it's not raised by the validation tool.

Yes, it should be omitted for `<style>` tag too.

**Comment by herrvigg** [comment]
Fixed in master.

**Comment by SeoDeveloper01** [comment]
Nice, good job. Farewell to the Era of HTML 4.01!
