### ISSUE TITLE
qTranslate-XT integration with Yoast SEO

### ISSUE THREAD

**Issue by M-Bilal-Arshad** [qtranslate/qtranslate-xt#1075]
Hi,
I am not sure what I am doing wrong here and I hope anyone of you can help.
I just converted from qTranslate-X to qTranslate-XT
I am running 
WordPress version: 5.8.1
Yoast SEO version: 17.4

It is showing Yoast SEO as active in the module and plugin inside the Integration tab of qTranslate-XT.
But no fields are being translated. Is there any configuration I need to do to get it to work?

Please let me know if any additional information is needed.

**Comment by herrvigg** [comment]
At the moment there are many limitations. See [related tickets](https://github.com/qtranslate/qtranslate-xt/labels/plugin%3A%20yoast).
