### ISSUE TITLE
Woocommerce attribute no translated text admin page

### ISSUE THREAD

**Issue by dusanscheinherr** [qtranslate/qtranslate-xt#1076]
Hello, 
I'm testing the plugin, everything works great. Thanks to everyone who develops this plugin. 👍 
I encountered a problem creating product properties, where the individual properties are not translated. I enclose the screen administration:
![Snímek obrazovky 2021-10-27 v 19 38 59](https://user-images.githubusercontent.com/61521578/139118018-d96ca824-9c9e-4bf7-815f-63dea296fd33.png)
When creating a product variant:
![Snímek obrazovky 2021-10-27 v 19 40 47](https://user-images.githubusercontent.com/61521578/139118017-18365eff-e3c3-4120-abd2-028f886a6cc4.png)

Testing settings:
WooCommerce: 5.8.0
Wordpress: 5.8.1
qTranslate-XT: 3.11.0

Thank you for your help

**Comment by herrvigg** [comment]
Additional fix #1144 merged in master. Thank you @spleen1981 !
