### ISSUE TITLE
Fixes for Yoast SEO module

### ISSUE THREAD

**Issue by Komarovski** [qtranslate/qtranslate-xt#1077]
Hello everyone,
I've made some frontend fixes for Yoast SEO module that prevent outputting wrong language data in breadcrumbs from indexable tables and also added filters for schema, opengraph and next|prev links.

Tested on:
Wordpress version: 5.8.1
qTranslate XT version: 3.11.0
Yoast SEO version: 17.4

Here is the source-code for wp-seo-front.php, please review this fixes - maybe some refactoring will needed:
[wp-seo-front.zip](https://github.com/qtranslate/qtranslate-xt/files/7453960/wp-seo-front.zip)

**Comment by Komarovski** [comment]
All new lines of code contains "//NEW" comments.

**Comment by herrvigg** [comment]
Thanks! I'll take a look.

**Comment by herrvigg** [comment]
Created #1079. I have a few questions, but let's discuss them in the Pull Request. We can close this one.
