### ISSUE TITLE
Site homepage suddenly redirected to a recently edited post

### ISSUE THREAD

**Issue by caseymilne** [qtranslate/qtranslate-xt#1078]
The homepage of the site suddenly began redirecting yesterday to a post. This just happened suddenly. No changes that I'm aware of to the qtranslate configuration. We did edit the homepage (using Elementor), so possibly the settings of the homepage changed in a way qtranslate doesn't recognize it as a translated page anymore. I'm just theorizing. Not that familiar with how this plugin works. I can't see way to set the homepage for each language, so I'm not sure how that is supposed to work. We have a regular WP page set as the homepage, but for some reason this suddenly is no longer loaded and instead we're redirected to a random post. 

I have tried using the "qtranslate_language_detect_redirect" to manually override this behavior to get the site working again but the redirection behavior doesn't change, this filter never seems to be used to all, I tested it with var_dump() and die() statements and the page just redirected as before. 

We know for sure it's this plugin causing the redirect because we uninstalled all plugins and switched to a base them and then reactivated plugins one by one until we found the source of the bug. Upon reactivation of qtranslate the redirection began again, deactivating the plugin stops it. 

We have only 2 languages active on the site, German and English. Both the homepage / and the DE site /de/ redirect into a post. 

I've started looking at the source code of the plugin to see if we can find where the plugin does it's logic checks and redirects. That's how we found some of the filters involved, but I still don't see a place where we can block the redirection or put in place filtering to specify the homepage.

Does anybody know what is the logic of the redirection handling? What would cause the plugin to skip the normal homepage set as the homepage and then redirect off into a recently edited post?

**Comment by herrvigg** [comment]
More info in the [wiki / redirections](https://github.com/qtranslate/qtranslate-xt/wiki/Browser-redirection).

If this just happened suddenly it's not coming from qTranslate directly but from a change in the environment (there might be some cases that are not handled though). Is is just for one client? It could be a problem with the cookie in the browser. Otherwise some HTTP configuration on the web server.

**Comment by herrvigg** [comment]
I close this for now, re-open if there are more insights.
