### ISSUE TITLE
[WC] hook for privacy policy text

### ISSUE THREAD

**Issue by Komarovski** [qtranslate/qtranslate-xt#1083]
Hello,
I've added filter `woocommerce_get_privacy_policy_text` for custom privacy policy text on checkout page.
Line 36 marked with "//NEW" comment.
[qwc-front.zip](https://github.com/qtranslate/qtranslate-xt/files/7610030/qwc-front.zip)

**Comment by herrvigg** [comment]
Thanks! Merged in master.

Fixes and improvements on the code are much welcome. Even better if you can push a Pull Request with github. For small changes you can do that even with the website interface, without installing anything on your computer.

1) Go to the source file, for example
https://github.com/qtranslate/qtranslate-xt/blob/master/modules/woo-commerce/qwc-front.php

2) Click on the "Edit" button

3) Commit changes and create a new branch for a pull request. Then follow the instructions.

**Comment by Komarovski** [comment]
> Thanks! Merged in master.
> 
> Fixes and improvements on the code are much welcome. Even better if you can push a Pull Request with github. For small changes you can do that even with the website interface, without installing anything on your computer.
> 
> 1. Go to the source file, for example
>    https://github.com/qtranslate/qtranslate-xt/blob/master/modules/woo-commerce/qwc-front.php
> 2. Click on the "Edit" button
> 3. Commit changes and create a new branch for a pull request. Then follow the instructions.

I'm new on Github and didn't know how to push fixes and improvements, next time gonna use your instructions, thanks! :)
