### ISSUE TITLE
Is the plugin ready for new PHP 8.1?

### ISSUE THREAD

**Issue by SeoDeveloper01** [qtranslate/qtranslate-xt#1085]
I'm going to upgrade PHP on my server to 8.1, so I want to make sure everything goes smoothly.

**Comment by herrvigg** [comment]
Usually it's fine with minor upgrades (though they call it major).
But if you do experiments in production but it's at your own risk. Better try on dev sites first, 

First look at the depreciations, should be fine:
https://www.php.net/releases/8.1/en.php#deprecations_and_bc_breaks

But here I found something with `strftime` they didn't report on the official page:
https://php.watch/versions/8.1/strftime-gmstrftime-deprecated

There is an advanced option to use `strftime` in QTX but it's not the default. So for those using this you'll be forced to switch. We'll have to remove that option.

**Comment by alphp** [comment]
Deprecated: preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in wp-content\plugins\qtranslate-xt-3.11.4\qtranslate_core.php on line 832:
Fixed:
```php
$vals = preg_split( '/[\s,]+/', strtolower( $ignore_file_types ), -1, PREG_SPLIT_NO_EMPTY );
```

For `strftime` you can use this gist: https://gist.github.com/bohwaz/42fc223031e2b2dd2585aab159a20f30

**Comment by herrvigg** [comment]
More info about PHP 8.1
https://make.wordpress.org/core/2022/01/10/wordpress-5-9-and-php-8-0-8-1/

**Comment by herrvigg** [comment]
I don't recommend migrating to PHP 8.1 yet.

The fix for `strftime` might take more time. It's used in more places than expected. But I don't think we want to rewrite that function, we should make it more specific to every usage.

Also, there are so many deprecated notices triggered in WP core, even in 5.9. They say it's ["just notices in debug mode, no impact on production, no need to panic"](https://core.trac.wordpress.org/ticket/54672). But in practice it's very annoying when for developers. It seems they had a huge list of PHP 8.1 deprecations such as [Requests](https://core.trac.wordpress.org/ticket/53635) to be fixed but only a few of them made their way in WP 5.9.
For sure there are also many plugins and themes that need to be upgraded.

**Comment by alphp** [comment]
I'm doing the first impact assessments in test environments.
These tests allow me to detect incompatibilities with applications from other servers, such as databases.
It is in this scenario where I have tested the compatibility of WP with different plugins and themes that I use regularly.

**Comment by herrvigg** [comment]
@andreysneg All the `preg_split` have been fixed in this commit: https://github.com/qtranslate/qtranslate-xt/commit/6db0f3a0a7e0de42b6740d34e998ed7b82d66839

But `strftime` is still used and that should generate some deprecated warnings in PHP 8.1.

**Comment by herrvigg** [comment]
So back to the PHP 8.1 compatibility. 
The remaining problem `strftime`. There are options in the settings to use `strftime` or `date` format, but the code is always falling back to `strftime`, even if a format is given in the `date` fashion.
All the conversions must be done the other way around, using `IntlDateFormatter` as [done here](https://gist.github.com/bohwaz/42fc223031e2b2dd2585aab159a20f30).
This is a blocker for PHP 8.1.

**Comment by herrvigg** [comment]
It's been several days I'm looking at this code in [qtranslate_date_time.php](https://github.com/qtranslate/qtranslate-xt/blob/master/qtranslate_date_time.php) and still doesn't understand it fully... Such an incredible mess. It's a real nightmare to refactor.

**Comment by herrvigg** [comment]
These functions are so old that some functionalities don't make any sense to me, like allowing a format containing ML values... I'd like to simplify this but it's hard to understand the impact in the user code.

I start to have a plan in mind, at least to allow PHP 8.1 to work without warnings on the short run. This will also serve as an experimental API before rolling it out of all. After that there will surely be breaking changes in the legacy API because it's really a mess to maintain.

**Comment by herrvigg** [comment]
I have now merged a first workaround with #1228 specifically for PHP 8.1 (and above).
This keeps all the existing formats in place, I may have missed something because the legacy code is extremely hard to read but this is supposed to keep the current behavior.

However, it's clear we should abandon the [strftime formats](https://www.php.net/manual/en/function.strftime.php) completely in qTranslate and only use a standard [date format](https://www.php.net/manual/en/datetime.format.php) using [IntlDateFormatter](https://www.php.net/manual/en/intldateformatter.format.php). We should store the language date and time configuration only in this `date` format. I will open a new topic because this has several implications.

From now I ask everyone interested in PHP8.1 to test the last version with the `master` branch directly.

**Comment by rein2000** [comment]
I think this is related to the same problem?

It's an error notice from Wordpress, PHP 8.1;

Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 167 der Datei
/kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-content/plugins/qtranslate-xt/qtranslate_date_time.php
verursacht. Fehlermeldung: Uncaught InvalidArgumentException: Format
"%L" is unknown in time format in
/kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-content/plugins/qtranslate-xt/qtranslate_date_time.php:167
Stack trace:
#0 [internal function]: {closure}()
#1 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-content/plugins/qtranslate-xt/qtranslate_date_time.php(177):
preg_replace_callback()
#2 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-content/plugins/qtranslate-xt/qtranslate_date_time.php(356):
qxtranxf_intl_strftime()
#3 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-content/plugins/qtranslate-xt/qtranslate_date_time.php(470):
qtranxf_strftime()
#4 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-content/plugins/qtranslate-xt/qtranslate_date_time.php(501):
qtranxf_format_time()
#5 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-includes/class-wp-hook.php(307):
qtranxf_timeFromPostForCurrentLanguage()
#6 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-includes/plugin.php(191):
WP_Hook->apply_filters()
#7 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-includes/general-template.php(2707):
apply_filters()
#8 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-admin/includes/class-wp-posts-list-table.php(1152):
get_the_time()
#9 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-admin/includes/class-wp-list-table.php(1445):
WP_Posts_List_Table->column_date()
#10 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-admin/includes/class-wp-posts-list-table.php(1383):
WP_List_Table->single_row_columns()
#11 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-admin/includes/class-wp-posts-list-table.php(795):
WP_Posts_List_Table->single_row()
#12 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-admin/includes/class-wp-posts-list-table.php(772):
WP_Posts_List_Table->_display_rows()
#13 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-admin/includes/class-wp-list-table.php(1362):
WP_Posts_List_Table->display_rows()
#14 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-admin/includes/class-wp-list-table.php(1289):
WP_List_Table->display_rows_or_placeholder()
#15 /kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-admin/edit.php(477):
WP_List_Table->display()
#16 {main}
  thrown






Versions:

{
  "PHP_VERSION": "8.1.10",
  "WP_VERSION": "6.0.2",
  "QTX_VERSION": "3.12.1",
  "Plugins": [
    "Advanced Custom Fields PRO 6.0.0",
    "Age Gate 3.0.7",
    "Billbee - Auftragsabwicklung, Warenwirtschaft, Automatisierung 1.0.0",
    "Check &amp; Log Email 1.0.6",
    "Classic Editor 1.6.2",
    "Contact Form 7 5.6.3",
    "Disable Comments 2.4.2",
    "Yoast Duplicate Post 4.5",
    "Git Updater 11.1.1.3",
    "Health Check &amp; Troubleshooting 1.5.0",
    "Mailchimp for WooCommerce 2.7.5",
    "One Stop Shop for WooCommerce 1.3.0",
    "qTranslate-XT 3.12.1",
    "Simple Custom Post Order 2.5.6",
    "User Role Editor 4.63.1",
    "vendidero Helper 2.1.6",
    "WooCommerce Estimated Shipping Date 4.2.0",
    "WooCommerce Blocks 8.5.1",
    "WooCommerce Stripe Gateway 6.7.0",
    "Germanized for WooCommerce Pro 3.5.7",
    "Germanized for WooCommerce 3.10.6",
    "WooCommerce Menu Cart 2.12.0",
    "WooCommerce PayPal Payments 1.9.3",
    "WooCommerce Quantity Increment 1.1.0",
    "WooCommerce 6.9.4",
    "WP Mail SMTP 3.5.2",
    "WP Migrate 2.4.0",
    "WPForms Lite 1.7.6"
  ]
}


Configuration;

{
  "default_language": "de",
  "enabled_languages": [
    "de",
    "en"
  ],
  "flag_location": "plugins/qtranslate-xt/flags/",
  "language_name": {
    "de": "Deutsch",
    "en": "English"
  },
  "locale": {
    "de": "de_DE",
    "en": "en_US"
  },
  "locale_html": {
    "de": "",
    "en": ""
  },
  "not_available": {
    "de": "Leider ist der Eintrag nur auf %LANG:, : und % verfügbar.",
    "en": "Sorry, this entry is only available in %LANG:, : and %."
  },
  "date_format": {
    "de": "%A, \\d\\e\\r %e. %B %Y",
    "en": "%A %B %e%q, %Y"
  },
  "time_format": {
    "de": "%H:%M",
    "en": "%I:%M %p"
  },
  "flag": {
    "de": "de.png",
    "en": "gb.png"
  },
  "url_mode": 2,
  "use_strftime": 3,
  "filter_options_mode": 0,
  "language_name_case": 0,
  "detect_browser_language": true,
  "hide_untranslated": false,
  "show_displayed_language_prefix": true,
  "show_alternative_content": false,
  "hide_default_language": true,
  "use_secure_cookie": false,
  "header_css_on": false,
  "header_css": ".qtranxs_flag_de {background-image: url(https://freimeisterkollektiv.de/wp-content/plugins/qtranslate-xt/flags/de.png); background-repeat: no-repeat;}\n.qtranxs_flag_en {background-image: url(https://freimeisterkollektiv.de/wp-content/plugins/qtranslate-xt/flags/gb.png); background-repeat: no-repeat;}\n",
  "text_field_filters": [],
  "term_name": {
    "Orangenschalen": {
      "de": "Orangenschalen",
      "en": "Orange peels"
    },
    "Orangenblüten": {
      "de": "Orangenblüten",
      "en": "Orange blossoms"
    },
    "Kardamom": {
      "de": "Kardamom",
      "en": "Cardamom"
    },
    "Koriander": {
      "de": "Koriander",
      "en": "Coriander"
    },
    "Bergamotten": {
      "de": "Bergamotten",
      "en": "Bergamoth"
    },
    "Zitronenschalen": {
      "de": "Zitronenschalen",
      "en": "Zitronenschalen"
    },
    "Wacholder": {
      "de": "Wacholder",
      "en": "Juniper"
    },
    "Wasser": {
      "de": "Wasser",
      "en": "Water"
    },
    "Weizenfeindestillat": {
      "de": "Weizenfeindestillat",
      "en": "Wheat distillate"
    },
    "Eier": {
      "de": "Eier",
      "en": "Eggs"
    },
    "Nüsse": {
      "de": "Nüsse",
      "en": "Nuts"
    },
    "Gluten": {
      "de": "Gluten",
      "en": "Gluten"
    },
    "Versandfertig": {
      "de": "Versandfertig",
      "en": "Ready to be shipped"
    },
    "Spirituosen": {
      "de": "Spirituosen",
      "en": "Spirits"
    },
    "50 ml": {
      "de": "50 ml",
      "en": "50 ml"
    },
    "100 ml": {
      "de": "100 ml",
      "en": "100ml"
    },
    "500 ml": {
      "de": "500 ml",
      "en": "500 ml"
    },
    "Lavendelblüten": {
      "de": "Lavendelblüten",
      "en": "Lavender blossoms"
    },
    "Veilchenwurzel": {
      "de": "Veilchenwurzel",
      "en": "Violet root"
    },
    "Ingwerwurzel": {
      "de": "Ingwerwurzel",
      "en": "Ginger root"
    },
    "Muskatellertraube": {
      "de": "Muskatellertraube",
      "en": "Muscat grape"
    },
    "BRAND &amp; GEIST": {
      "de": "BRAND &amp; GEIST",
      "en": ""
    },
    "Freimeister &amp; Friends": {
      "de": "Freimeister &amp; Friends",
      "en": "Freimester &amp; Friends"
    },
    "Wild Herbs &amp; Spices": {
      "de": "Wild Herbs &amp; Spices",
      "en": "Wild herbs &amp; spices"
    },
    "5 Fragen – 1 Drink": {
      "de": "5 Fragen – 1 Drink",
      "en": ""
    },
    "Freimeister spricht": {
      "de": "Freimeister spricht",
      "en": ""
    },
    "Most popular": {
      "de": "Most popular",
      "en": "Most popular"
    },
    "Kaffeespirituosen": {
      "de": "Kaffeespirituosen",
      "en": "Coffee Spirits"
    },
    "Shrub": {
      "de": "Shrub",
      "en": "Shrubs"
    },
    "Likör &amp; Likörwein": {
      "de": "Likör &amp; Likörwein",
      "en": "Liqueur &amp; Fortified Wines"
    },
    "Baden-Wurttemberg": {
      "de": "Baden-Wurttemberg",
      "en": "Baden-Wurttemberg"
    },
    "Estland": {
      "de": "Estland",
      "en": "Estonia"
    },
    "Ruanda": {
      "de": "Ruanda",
      "en": "Rwanda"
    },
    "Mexiko": {
      "de": "Mexiko",
      "en": "Mexico"
    },
    "Schweiz": {
      "de": "Schweiz",
      "en": "Switzerland"
    },
    "Österreich": {
      "de": "Österreich",
      "en": "Austria"
    },
    "Bayern": {
      "de": "Bayern",
      "en": "Bavaria"
    },
    "Berlin": {
      "de": "Berlin",
      "en": "Berlin"
    },
    "Deutschland": {
      "de": "Deutschland",
      "en": "Germany"
    },
    "Hessen": {
      "de": "Hessen",
      "en": "Hesse"
    },
    "Niedersachsen": {
      "de": "Niedersachsen",
      "en": "Lower Saxony"
    },
    "Nordrhein-Westfalen": {
      "de": "Nordrhein-Westfalen",
      "en": "North Rhine-Westphalia"
    },
    "Rheinland-Pfalz": {
      "de": "Rheinland-Pfalz",
      "en": "Rhineland-Palatinate"
    },
    "Sachsen-Anhalt": {
      "de": "Sachsen-Anhalt",
      "en": "Saxony-Anhalt"
    },
    "Thüringen": {
      "de": "Thüringen",
      "en": "Thuringia"
    },
    "Bio-Spirituosen": {
      "de": "Bio-Spirituosen",
      "en": "Organic Liquor"
    },
    "Dänemark": {
      "de": "Dänemark",
      "en": "Denmark"
    },
    "Kräuter &amp; Bitter": {
      "de": "Kräuter &amp; Bitter",
      "en": "Herbal Liqueur &amp; Bitters"
    },
    "Getreide &amp; mehr": {
      "de": "Getreide &amp; mehr",
      "en": "Grains &amp; More"
    },
    "Spezialitäten": {
      "de": "Spezialitäten",
      "en": "Specialties"
    },
    "Wilde Kräuter &amp; Gewürze": {
      "de": "Wilde Kräuter &amp; Gewürze",
      "en": "Wild Herbs &amp; Spices"
    },
    "Frankreich": {
      "de": "Frankreich",
      "en": "France"
    },
    "Kenia": {
      "de": "Kenia",
      "en": "Kenya"
    },
    "Spanien": {
      "de": "Spanien",
      "en": "Spain"
    },
    "Provinz Toledo": {
      "de": "Provinz Toledo",
      "en": "Toledo"
    },
    "Neu vom FMK": {
      "de": "Neu vom FMK",
      "en": "NEW"
    },
    "FMK Survival Kit": {
      "de": "FMK Survival Kit",
      "en": "FMK Kits"
    },
    "Obst &amp; Wein": {
      "de": "Obst &amp; Wein",
      "en": "Fruit &amp; Wine"
    },
    "Whisk(e)y": {
      "de": "Whisk(e)y",
      "en": "Whisky"
    }
  },
  "disable_client_cookies": false,
  "ignore_file_types": [
    "gif",
    "jpg",
    "jpeg",
    "png",
    "svg",
    "pdf",
    "swf",
    "tif",
    "rar",
    "zip",
    "7z",
    "mpg",
    "divx",
    "mpeg",
    "avi",
    "css",
    "js",
    "mp3",
    "mp4",
    "apk"
  ],
  "url_info": {
    "cookie_lang_front": "en",
    "cookie_lang_admin": "en",
    "cookie_front_or_admin_found": true,
    "scheme": "https",
    "host": "freimeisterkollektiv.de",
    "path": "/wp-admin/admin-ajax.php",
    "query": "action=admin_debug_info&_fs_blog_admin=true",
    "path-base": "",
    "wp-path": "/wp-admin/admin-ajax.php",
    "language_neutral_path": true,
    "http_referer": "https://freimeisterkollektiv.de/wp-admin/options-general.php?page=qtranslate-xt",
    "referer_admin": true,
    "doing_front_end": false,
    "lang_cookie_admin": "en",
    "lang_admin": "en",
    "language": "en",
    "set_cookie": false,
    "page_referer": "options-general.php"
  },
  "language": "en",
  "editor_mode": 0,
  "highlight_mode": 1,
  "auto_update_mo": true,
  "hide_lsb_copy_content": false,
  "lsb_style": "Simple_Buttons.css",
  "config_files": [
    "./i18n-config.json"
  ],
  "custom_i18n_config": [],
  "custom_fields": [],
  "custom_field_classes": [
    "translatable"
  ],
  "post_type_excluded": [],
  "admin_enabled_modules": {
    "acf": true,
    "all-in-one-seo-pack": true,
    "events-made-easy": true,
    "jetpack": true,
    "google-site-kit": true,
    "gravity-forms": true,
    "woo-commerce": true,
    "wp-seo": true,
    "slugs": false
  },
  "translator": {},
  "qtrans_compatibility": false
}

**Comment by rein2000** [comment]
I received an error notice from Wordpress today.

Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 167 der Datei
/kunden/499355_10711/webseiten/b2c.freimeisterkollektiv.de/wordpress/wp-content/plugins/qtranslate-xt/qtranslate_date_time.php
verursacht. Fehlermeldung: Uncaught InvalidArgumentException: Format
"%L" is unknown in time format in
___EDITED___/wordpress/wp-content/plugins/qtranslate-xt/qtranslate_date_time.php:167

{
  "PHP_VERSION": "8.1.10",
  "WP_VERSION": "6.0.2",
  "QTX_VERSION": "3.12.1",
  "Plugins": [
    "Advanced Custom Fields PRO 6.0.0",
    "Age Gate 3.0.7",
    "Billbee - Auftragsabwicklung, Warenwirtschaft, Automatisierung 1.0.0",
    "Check &amp; Log Email 1.0.6",
    "Classic Editor 1.6.2",
    "Contact Form 7 5.6.3",
    "Disable Comments 2.4.2",
    "Yoast Duplicate Post 4.5",
    "Git Updater 11.1.1.3",
    "Health Check &amp; Troubleshooting 1.5.0",
    "Mailchimp for WooCommerce 2.7.5",
    "One Stop Shop for WooCommerce 1.3.0",
    "qTranslate-XT 3.12.1",
    "Simple Custom Post Order 2.5.6",
    "User Role Editor 4.63.1",
    "vendidero Helper 2.1.6",
    "WooCommerce Estimated Shipping Date 4.2.0",
    "WooCommerce Blocks 8.5.1",
    "WooCommerce Stripe Gateway 6.7.0",
    "Germanized for WooCommerce Pro 3.5.7",
    "Germanized for WooCommerce 3.10.6",
    "WooCommerce Menu Cart 2.12.0",
    "WooCommerce PayPal Payments 1.9.3",
    "WooCommerce Quantity Increment 1.1.0",
    "WooCommerce 6.9.4",
    "WP Mail SMTP 3.5.2",
    "WP Migrate 2.4.0",
    "WPForms Lite 1.7.6"
  ]
}

**Comment by rein2000** [comment]
I received an error notice from Wordpress today.

Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 167 der Datei
___EDITED___/wordpress/wp-content/plugins/qtranslate-xt/qtranslate_date_time.php
verursacht. Fehlermeldung: Uncaught InvalidArgumentException: Format
"%L" is unknown in time format in
___EDITED___/wordpress/wp-content/plugins/qtranslate-xt/qtranslate_date_time.php:167

{
  "PHP_VERSION": "8.1.10",
  "WP_VERSION": "6.0.2",
  "QTX_VERSION": "3.12.1",
  "Plugins": [
    "Advanced Custom Fields PRO 6.0.0",
    "Age Gate 3.0.7",
    "Billbee - Auftragsabwicklung, Warenwirtschaft, Automatisierung 1.0.0",
    "Check &amp; Log Email 1.0.6",
    "Classic Editor 1.6.2",
    "Contact Form 7 5.6.3",
    "Disable Comments 2.4.2",
    "Yoast Duplicate Post 4.5",
    "Git Updater 11.1.1.3",
    "Health Check &amp; Troubleshooting 1.5.0",
    "Mailchimp for WooCommerce 2.7.5",
    "One Stop Shop for WooCommerce 1.3.0",
    "qTranslate-XT 3.12.1",
    "Simple Custom Post Order 2.5.6",
    "User Role Editor 4.63.1",
    "vendidero Helper 2.1.6",
    "WooCommerce Estimated Shipping Date 4.2.0",
    "WooCommerce Blocks 8.5.1",
    "WooCommerce Stripe Gateway 6.7.0",
    "Germanized for WooCommerce Pro 3.5.7",
    "Germanized for WooCommerce 3.10.6",
    "WooCommerce Menu Cart 2.12.0",
    "WooCommerce PayPal Payments 1.9.3",
    "WooCommerce Quantity Increment 1.1.0",
    "WooCommerce 6.9.4",
    "WP Mail SMTP 3.5.2",
    "WP Migrate 2.4.0",
    "WPForms Lite 1.7.6"
  ]
}

**Comment by herrvigg** [comment]
> Uncaught InvalidArgumentException: Format "%L" is unknown in time format

@rein2000 ah nice, this is useful.
It turns out that `%L` is **not** a standard strftime format. So the error makes sense.
But... if you go back to PHP 8.0 it was converted in the legacy qTranslate code to date format `G` -> "24-hour format of an hour without leading zeros (0 through 23)".

Solutions:
To avoid adding new hacks, it's better to replace `%L` with `%k` which is an official format in strftime -> "Hour in 24-hour format, with a space preceding single digits" (0-23). There might be small variations with the spaces.
If you prefer the version with leading zeros you can use `%H` (00-23).

References
- [date format](https://www.php.net/manual/en/datetime.format.php)
- [strftime format](https://www.php.net/manual/en/function.strftime.php)

With the last patch I pushed, the strformat formats are still accepted in the settings but they are converted to date at runtime using `IntlDateFormatter` with PHP 8.1, but it's just a temporary solution.
Note the next step will be to convert everything to `date` as a native format in qtranslate. We should not store or use `strftime` formats but for now you can keep it like this.
Yes - it's quite complicated.

**Comment by herrvigg** [comment]
@rein2000 did you try replacing `%L` with `%k`?

**Comment by herrvigg** [comment]
I have uploaded a new patch that completes the support of non-standard formats like `%L`, there were many others...
The first value is for date, the second for strftime. The purpose was to mimic the date formats that don't exist in strftime.
```
'j' => '%E', // Day number no zero
'S' => '%q', // Day english ordinal
'w' => '%f', // Week number
'T' => '%v', // Timezone abbreviation, if known; otherwise the GMT offset.
'n' => '%i', // Numeric representation of a month, without leading zeros
't' => '%J', // Number of days in the given month
'B' => '%K', // Swatch internet time 000-999
'G' => '%L', // 24-hour format of an hour without leading zeros --> %L should be %k!
'u' => '%N', // Microseconds
'e' => '%Q', // Timezone identifier
'I' => '%o', // 1 if Daylight Saving Time, 0 otherwise.
'O' => '%O', // Difference to Greenwich time (GMT) without colon between hours and minutes
'Z' => '%1', // Timezone offset in seconds
'c' => '%2', // ISO 8601 date
'r' => '%3', // RFC 2822/» RFC 5322 formatted date
'U' => '%4'  // Seconds since the Unix Epoch
```
So these are supported, but ideally we should not use them because it's not standard.

Even worse, there are even three pairs that override the strftime format with something specific to qTranslate. 
```
'z' => '%F', // z: The day of the year (starting from 0) -- %F: Same as "%Y-%m-%d
'P' => '%s', // P: Difference to Greenwich time (GMT) with colon between hours and minutes -- %s: unix timestamp
'L' => '%k', // L: leap year -- %k: Hour in 24-hour format, single digit
```
So the conversions are inconsistent 😕 and we should not override them in the new `qxtranxf_intl_strftime`. Therefore there won't be supported anymore. Hopefully they are so specific that it should not be real problem.

It should now be possible to use PHP 8.1 in a (almost) transparent manner, thanks to this workaround for `strftime` that is connected to the current code. However I consider this only as a temporary solution. We should abandon the strftime formats completely and therefore migrate to date but this requires other changes. I will open a new post.

**Comment by herrvigg** [comment]
I have now generalized the usage of `qtranxf_intl_strftime` to any PHP version, not just PHP 8.1.
Merged in master, please test this so we can release it.
