### ISSUE TITLE
flag Irish language

### ISSUE THREAD

**Issue by stevr1it** [qtranslate/qtranslate-xt#1091]
Hello i need to add the Irish language the iso code is ga but the flag png associated with ga is not the Irish flag. Any suggestion?

**Comment by herrvigg** [comment]
Hi,
the ISO-3166 alpha-2 country code for Ireland is `ie`. Why do you think it's `ga` (Gabon)?
https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

The flag looks correct.
https://raw.githubusercontent.com/qtranslate/qtranslate-xt/master/flags/ie.png
