### ISSUE TITLE
Can't exclude ACF fields from translation

### ISSUE THREAD

**Issue by SeoDeveloper01** [qtranslate/qtranslate-xt#1094]
qTranslate-XT perfectly deals with Advanced Custom Fields translation, thanks!
But my problem is just something else - I can't make certain ACF fields or a whole Field Group untranslatable. Are there any solutions?

**Comment by herrvigg** [comment]
In settings > ACF qTranslate Settings, uncheck "Enable translation for Standard Field Types".
