### ISSUE TITLE
Not working with Nextgen Gallery

### ISSUE THREAD

**Issue by xaviurbs** [qtranslate/qtranslate-xt#1096]
In some old versions it was working... now not... Receiving unexpected json error when uploading images.

<img width="958" alt="Captura de pantalla 2022-01-05 a las 15 16 05" src="https://user-images.githubusercontent.com/60189296/148232383-4659a4c8-69a2-41bb-9b16-8af0596db7d3.png">

**Comment by herrvigg** [comment]
What is not working? Please explain better the issue  step by step so it can be reproduced.

**Comment by herrvigg** [comment]
Very likely duplicate #1266 that provided more information. See also #1326.
