### ISSUE TITLE
Updating from qtranslate x to qtranslate xt

### ISSUE THREAD

**Issue by MaxPietro** [qtranslate/qtranslate-xt#1100]
Hi, 

a current wordpress site is running qtranslate x and I have to switch it to the XT version. What do I have to do? First do a backup of the site, then install the XT version and then deactivating the X version? 

I don't want to input all the texts again. Is there a way to do the switch automatically, so the website is showing the same content as before?

**Comment by herrvigg** [comment]
Ha, welcome, I'm surprised you were still able to run with the very-old QT-X 😄 
To install, follow the instructions of the [README](https://github.com/qtranslate/qtranslate-xt#installation).
A DB backup is always a good idea before doing a major change. The main point to know when migrating is that QT-X and QT-XT (still) share the [same options](https://github.com/qtranslate/qtranslate-xt#im-still-using-qtranslate-x-can-i-test-qtranslate-xt). That matters mostly in case you maintain both while doing the transition. Just to say in principle you can still go back but a DB backup is always safer to have.

> I don't want to input all the texts again. 

Not sure what you mean with this. You can disable it by post type but it's not a new feature.
On the front-end side it will translate the ML tags that it finds in the WP DB, for each post. If the post doesn't contain any of those, it will simply display the raw text as it is.
