### ISSUE TITLE
Error "termmeta-core.php"

### ISSUE THREAD

**Issue by sviluppomania** [qtranslate/qtranslate-xt#1103]
Hi,
from PHP version 8 there is this error:
`Deprecated: Required parameter $term_id follows optional parameter $key in file on line 220`
in the file: **modules/slugs/includes/termmeta-core.php**

**Comment by herrvigg** [comment]
This function is not even used... All this code with `termmeta` looks much obsolete.

**Comment by herrvigg** [comment]
Deleted function and others that are not used.
