### ISSUE TITLE
Include qTranslate (-X) Separate Comments into -XT

### ISSUE THREAD

**Issue by sviluppomania** [qtranslate/qtranslate-xt#1108]
Hello,
will there also be an integration of qTranslate (-X) Separate Comments as per qtranslate-slug?

qTranslate (-X) Separate Comments: https://github.com/nikolov-tmw/qtranslate-separate-comments

This plugin also has [meta languages for mobile applications](https://github.com/nikolov-tmw/qtranslate-separate-comments/pull/3/files), useful for those who also develop mobile apps.

**Comment by sviluppomania** [comment]
@spleen1981

**Comment by sviluppomania** [comment]
@spleen1981

**Comment by spleen1981** [comment]
@sviluppomania IMHO it's not a good candidate to be a built-in module:
- qtranslate intent is to provide multilingual versions of the same content, intent of this plugin seems to be to filter content instead
- qtranslate is intended for site content, this plugin is for user content
- qtranslate actions are based on selected language and provides content for that language if available, this plugin actions are based on the (strong) assumption that language of the comment is the same as currently selected site language, which is not necessarily true. Actually you cannot know which is the language the comment has been written in based on selected site language only.

I think built in modules are supposed to add compatibility with other plugins and enable optional features within qtranslate scope, and plugins doing different things as this one should remain stand alone.

**Comment by herrvigg** [comment]
Great explanations, I agree. Better limit the QTX modules to site content.
