### ISSUE TITLE
Documentation fix: Syntax of “admin-config” branch

### ISSUE THREAD

**Issue by picasso** [qtranslate/qtranslate-xt#1119]
There is an error in the __"Syntax of “admin-config” branch"__ section, in __`pages`__ subsection on [this page](https://github.com/qtranslate/qtranslate-xt/wiki/JSON-Configuration)

__Now it's written:__

`page` is a regular expression, which is matched against WordPress global variable `$pagenow` with the operation `preg_match('!'.$page.'!', $_SERVER['QUERY_STRING'])`

__Should be written:__

`page` is a regular expression, which is matched against WordPress global variable `$pagenow` with the operation `preg_match('!'.$page.'!', $pagenow)`

**Comment by herrvigg** [comment]
Good catch, fixed [doc](https://github.com/qtranslate/qtranslate-xt/wiki/JSON-Configuration).

For the record, it's checked here: https://github.com/qtranslate/qtranslate-xt/blob/3617eede898455a709559449f206c66519f07b19/qtranslate_utils.php#L611-L624

The `$url_path` comes from `$q_config['url_info']['wp-path'];` but it's logically equivalent to `$pagenow`.
