### ISSUE TITLE
Translation shown as not present (sorry message), nested website content

### ISSUE THREAD

**Issue by Sagittarius4Star** [qtranslate/qtranslate-xt#1129]
Hello.

I have a question and would like to ask for some assitance. Being so that the theme's support is very bad, I am stuck on my own. A very long story is such that I was able to find the qtranslate-xt and dig in to it. I have a very simple website and I made it work for let say 90%. 

However, there is a section on the website which shows a "services" like list. The contect is a full website but links are disabled because I want it only to show text content. I can translate the content normally but if you check the URLs, you can see where my problem is.

I am breaking my teeth with this for the last 3 days, so at the end, I decided to write here asking for help. Thank you.
native lang: https://www.astop.si/
translated en: https://www.astop.si/en/
problem in en version: https://www.astop.si/en/

Direct URL for translated page would be: 
native: https://www.astop.si/izvensodni-prevzemi-premicnin-nepremicnin/
translated: https://www.astop.si/en/izvensodni-prevzemi-premicnin-nepremicnin/

What am I missing? Thanks a million.

**Comment by Sagittarius4Star** [comment]
I don't really now. It's like the website content:
https://www.astop.si/en/izvensodni-prevzemi-premicnin-nepremicnin/
Is nested on the front page. It's a theme's thing. But qTranslate only sees correctly the title (translated). The content, even though translated in full is not shown. 

I can't get the support from theme's guys and I can't really tell more.
I try searching for DIV or IDs to include them separately in the plugin but I was not successful.

**Comment by spleen1981** [comment]
Ok, to be clear that is the url of one of your pages.
It looks like an issue of this specific theme, and I guess nothing more can be said without knowing how the page is composed.
If that is the case, issue needs to be solved theme side anyways.
If I may suggest, for your specific use case I would just replace the dynamic content in the home page with plain text in both languages, and you are done.

**Comment by Sagittarius4Star** [comment]
Thank you for your suggestion. It did the trick in same way.
