### ISSUE TITLE
ACF fields translations not saving properly

### ISSUE THREAD

**Issue by llos** [qtranslate/qtranslate-xt#1131]
Hi,
We have some ACF fields that are not translating properly. I can write the content in each language correctly by clicking on each language flag. But, once I save the changes, only one of the languages is saved and the rest of the info is lost. I send you a short video that reproduce the problem https://vimeo.com/691617428/bb2fc0fd9f. I'm using the latest version of both ACF and qtranslate-XT, and also ACF qTranslate.
Any tips on how to fix that problem?

**Comment by herrvigg** [comment]
Is it recent regression but first time you try this? Did you try disabling all other plugins except QTX + ACF?

**Comment by MK-RD** [comment]
@llos If the problem only occurs in Firefox, I can help you!

**Comment by llos** [comment]
Hi,
I have tried with ACF, qTranslate XT and Classic editor plugins enabled and the problem persists. It happens also in Chrome.
Any ideas?

**Comment by MK-RD** [comment]
Yes, unfortunately I have a lot of ideas :-)

_Keep in mind that it can be a special case with the Firefox browser!_

For the problem identification I need some information about the used environment.

ACF (PRO) version
QTX version
Optional: Theme Version

If you want to use the ACF standard field types, the option "Enable translation for Standard Field Types" should be enabled too: Settings > ACF qTranslate Settings

**Test data: ACF field group (type: Post)**

[
    {
        "key": "group_623f25e5cbf36",
        "title": "QTX-TEST",
        "fields": [
            {
                "key": "field_623f25f354f79",
                "label": "Text (ACF)",
                "name": "text_acf",
                "type": "text",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "default_value": "",
                "placeholder": "",
                "prepend": "",
                "append": "",
                "maxlength": ""
            },
            {
                "key": "field_623f261bfbbff",
                "label": "Text (ACF-QTX)",
                "name": "text_acf-qtx",
                "type": "qtranslate_text",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "default_value": "",
                "placeholder": "",
                "maxlength": "",
                "prepend": "",
                "append": ""
            },
            {
                "key": "field_6240da95175b5",
                "label": "Flexible Content",
                "name": "flexible_content",
                "type": "flexible_content",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "layouts": {
                    "layout_6240da9f28bed": {
                        "key": "layout_6240da9f28bed",
                        "name": "Title",
                        "label": "Layout",
                        "display": "block",
                        "sub_fields": [
                            {
                                "key": "field_6240dab1175b6",
                                "label": "Text (ACF)",
                                "name": "text_acf",
                                "type": "text",
                                "instructions": "",
                                "required": 0,
                                "conditional_logic": 0,
                                "wrapper": {
                                    "width": "",
                                    "class": "",
                                    "id": ""
                                },
                                "default_value": "",
                                "placeholder": "",
                                "prepend": "",
                                "append": "",
                                "maxlength": ""
                            },
                            {
                                "key": "field_6240dac2175b7",
                                "label": "Text (QTX)",
                                "name": "text_qtx",
                                "type": "text",
                                "instructions": "",
                                "required": 0,
                                "conditional_logic": 0,
                                "wrapper": {
                                    "width": "",
                                    "class": "",
                                    "id": ""
                                },
                                "default_value": "",
                                "placeholder": "",
                                "prepend": "",
                                "append": "",
                                "maxlength": ""
                            }
                        ],
                        "min": "",
                        "max": ""
                    }
                },
                "button_label": "+",
                "min": "",
                "max": ""
            }
        ],
        "location": [
            [
                {
                    "param": "post_type",
                    "operator": "==",
                    "value": "post"
                }
            ]
        ],
        "menu_order": 0,
        "position": "normal",
        "style": "default",
        "label_placement": "top",
        "instruction_placement": "label",
        "hide_on_screen": "",
        "active": true,
        "description": "",
        "show_in_rest": 0
    }
]

**Comment by llos** [comment]
I have tested the sample field group you sent me and it works fine. In fact, it works fine even in the same page where the Textarea field from my video fails.
I've tried to add a Textarea field in your field group and it also works.
I'm not sure what else can I test in order to discover the source of the problem.

I'm using ACF 5.12.1 and qTranslate-XT 3.11.4
I'm also using the option https://snipboard.io/ILfhxW.jpg

Any tips will be welcome, thanks

**Comment by llos** [comment]
Hi,
Those are the languages I have https://snipboard.io/wnPF1y.jpg and here you can download the JSON file for that field group:
[acf-export-2022-03-29.json.zip](https://github.com/qtranslate/qtranslate-xt/files/8374774/acf-export-2022-03-29.json.zip)

Thanks

**Comment by MK-RD** [comment]
I could not detect any misbehavior.

For an intensive error analysis, I have to be able to **reproduce** the incorrect behavior.
If that were the case, then I would first examine the behavior on a second page with
**initial data entry** using the developer tools (cache, load order, inspector, console).

Let me know if you notice anything new! 


![grafik](https://user-images.githubusercontent.com/79551145/160711850-6efed6e2-d0a0-412c-82a5-5e8d20ea7829.png)

**Comment by llos** [comment]
Hi,

Thanks for checking that.

I finally could fix the issue, it was related to a piece of code a previous developer set as a mu-plugin. I paste it here for your reference. Commenting that code, it works fine.

```
function my_translatable_acf_fields($field){
    if (strpos($field['wrapper']['class'], 'translatable') !== false){
        if ((isset($_GET['page']) || isset($_GET['menu'])) {
            $field['class'] = 'translatable qtranxs-translatable';
        } else {
            $field['class'] = 'translatable';
        }

    }
    return $field;
}
```

Thanks again for your help.

**Comment by MK-RD** [comment]
Thank you for the clarification!
