### ISSUE TITLE
Error: /qtranslate-xt-master/modules/qtx_modules_handler.php on line 158

### ISSUE THREAD

**Issue by renad** [qtranslate/qtranslate-xt#1148]
Hi,
I have a problem, I upgraded from qTranslate-X (3.4.6.8) to qTranslate-XT (latest).
Here is my frontend - with errors.
Can you advise me?

![Safari](https://user-images.githubusercontent.com/1554402/162614585-03718b32-482c-479f-ba52-3427cc7127be.jpg)

**Comment by herrvigg** [comment]
Yes, it was a very recent regression, the fix is already in `master`: https://github.com/qtranslate/qtranslate-xt/commit/211b833fd28522cc134754258cfc73d93a3de406. So if you pull the last version again the problem will disappear.
