### ISSUE TITLE
Integration with Pods

### ISSUE THREAD

**Issue by northword** [qtranslate/qtranslate-xt#1149]
I use the [pods plugin](https://github.com/pods-framework/pods) to create custom post types and custom fields, and use qtranslate-xt for multi-language, but qtranslate-xt can only take effect on the title and default editor, not on the custom fields created by Pods.

> The Pods Framework is a Content Development Framework for WordPress - It lets you create and extend content types that can be used for any project. Add fields of various types we've built in, or add your own with custom inputs, you have total control.
> https://github.com/pods-framework/pods

![title and default editor have LSB](https://user-images.githubusercontent.com/44738481/163137777-72d5aaea-80d8-45c8-9f58-ccd478e9ef2d.png)
Fig. Title and default editor have LSB

![custom fields no LSB](https://user-images.githubusercontent.com/44738481/163137790-2d1bb98c-a703-44cd-9867-6fdb91ac8d9f.png)
Fig. custom fields(毕业去向, text area) no LSB

**Comment by herrvigg** [comment]
I won't work on this, but I let the ticket open to see if there's some interest.

**Comment by spleen1981** [comment]
[Integration Guide](https://github.com/qtranslate/qtranslate-xt/wiki/Integration-Guide) is plenty of info to approach adding support for new plugins/themes, for those interested.
In the meantime as a workaround the `[:en]word[:it]parola[:]` syntax should be working for untranslated custom fields.

**Comment by herrvigg** [comment]
If someone can propose an integration module we can take it. Pods looks quite popular but I won't have time for this.
