### ISSUE TITLE
QTS: permalink bases with UTF8 characters not working

### ISSUE THREAD

**Issue by spleen1981** [qtranslate/qtranslate-xt#1159]
Confirmed issue in slugs module from legacy qtranslate-slugs plugin README.md, reported here for better tracking and visibility

> In slug options you can change the bases for taxonomies and custom post types.
So, for example, you can change /category/ for /category/ for english and /categoria/ for spanish version. But these won't work:
>- slug with UTF8 characters in taxonomies bases: example: /類別/... instead of /category/... UTF8 in taxonomies works just fine: /category_zh/魚/
>- slug with UTF8 characters in custom post type bases : example: /圖書/... instead of /books/... UTF8 in custom post slugs works just fine: /tushu/彩繪中國經典名著/
>- translating custom post types archives with custom base name /tushu/ isn't working. Using UTF8 in the the default slug works as expected : /中國/

**Comment by herrvigg** [comment]
Merged in master.
