### ISSUE TITLE
wp-content/plugins/qtranslate-xt-3.11.4/qtranslate_utils.php on line 460

### ISSUE THREAD

**Issue by nabi009** [qtranslate/qtranslate-xt#1175]
[](url
![Screen Shot 2022-05-26 at 11 54 01](https://user-images.githubusercontent.com/3170831/170439053-c38878f5-ccde-43ef-9b46-4468fbed155f.png)
)

**Comment by herrvigg** [comment]
It was supposed to be fix in #1047 but in fact there's a bug in case the string (language) has length = 2. Quite surprising it didn't happen before... Though many locales are like `en_US` `en_GB` there are also quite many with just the 2 letters language.

**Comment by herrvigg** [comment]
New fix merged in master.
