### ISSUE TITLE
ClassicPress Directory Plugin Entry

### ISSUE THREAD

**Issue by smileBeda** [qtranslate/qtranslate-xt#1178]
Hello!

We have noticed that you (someone) listed the qTranslate Plugin in the ClassicPress Directory https://directory.classicpress.net/plugins
Both the Profile which listed the Plugin and the Plugin itself are however not published because some details are missing for a complete review and publication.

We miss for starters a private communication channel which is required for the Directory listing.
Would you, if you intend to proceed with the ClassicPress Plugin listing, please either complete your profile or contact us at plugins@classicpress.net, so we can sort it out?

If you do not intend to continue the ClassicPress support, please let us know so we can remove it. The Profile and Plugin will stay in the system for the coming 7 working days and if we don't hear back, we will assume that you do not intend to continue with the ClassicPress Support and remove the profile and plugin from the listing.

We do also understand that there has been an unacceptable delay in response and review, something that we fixed now and can guarantee a timely interaction.

We hope to see you around!

Kind regards

**Comment by herrvigg** [comment]
hello,
I don't know where this request to the ClassicPress directory comes from. The authors of the  two original plugins qTranslate and qTranslate-X have disappeared completely, from WordPress and github. So I can't answer this.

The qTranslate-XT project has been created to continue the development from the last available qTranslate-X plugin, back to 2018. One goal for is to bring it back to the active WP plugins, but we have to give it a different name and do some preparations (e.g. migrate data and options). We'll get there, but it will still take some time.

**Comment by TukuToi** [comment]
Well, the entry in the ClassicPress directory features this GitHub repo as the repository of the plugin submitted, so I had assumed someone of the contributors here had submitted that.

If this is not the case, we can remove the plugin from the ClassicPress Directory, no problem at all with that.
Just wanted to be sure that we don't delete something that has been intended to be maintained for the ClassicPress CMS.

Thank you!

**Comment by herrvigg** [comment]
I understand, thank you for asking us. I can't answer who asked it, it's possible some of the users/developers here did it, but I'm not aware of it. We have a copy of qTranslate-X in github. The original qTranslate plugin is so outdated that I don't see any point of keeping it in ClassicPress, apart for the nostalgy ;) Maybe wait a few days, and if no answer, delete it.

**Comment by herrvigg** [comment]
No reaction so it can be deleted from our side.

**Comment by bagaweb** [comment]
I think it would be positive to have qTranslate-XT listed in the ClassicPress plugin directory, I've been using ClassicPress for a couple of projects and qTranslate-XT is fully comptilble with it.
