### ISSUE TITLE
Woocommerce webhooks

### ISSUE THREAD

**Issue by tonysilva16** [qtranslate/qtranslate-xt#1179]
Hello,

With a variable product, if i update the variation price and click on save changes, woocommerce will send two webhooks, one of them have the raw data (parent product update), and the other webhook (variation update) all the fields are translated.

Example:
https://i.imgur.com/IBz5MiE.png

I already tried with the latest published version, and also with the current plugin files on the master branch.

Thanks.

**Comment by spleen1981** [comment]
Not clear to me.
Can you explain in detail:

- what is the expected result
- what is the actual result instead

Also please copy/paste complete code/outputs here.

**Comment by spleen1981** [comment]
@tonysilva16 can you test this [branch](https://github.com/qtranslate/qtranslate-xt/tree/wc_webhook_fix)

**Comment by tonysilva16** [comment]
Hello @spleen1981 ,

For what i could test, one of the problems remains. When the product is a variation type, the returning data has translated attributes.
I installed xdebug and the data used in the webhook is retrieved in **get_product_data** function inside **WC_REST_Products_V2_Controller** class.

The function in the screenshoot bellow is called to get the attributes field.

![image](https://user-images.githubusercontent.com/65446091/174839819-c4982cad-b18c-4409-ab92-233aadbb3b8a.png)

The result of the get_attribute_taxonomy_name function is this one, that contains the translated attribute

![image](https://user-images.githubusercontent.com/65446091/174840955-f8384c28-ac89-4d6a-b5a2-61caadc5a80b.png)

If the product type is not a variation, the attribute name is correct.

![image](https://user-images.githubusercontent.com/65446091/174842050-e508332e-700f-43a3-9763-4e26a9e4bfdb.png)

**Comment by spleen1981** [comment]
ok, it seems undes some circumnstances (e.g. variations updates) the webhook is generated through AJAX instead of cron, and in that case `qwc-admin.php` is loaded instead of `qwc-front.php` (would not work anyways as needed filter is added only if `wp_doing_cron()` is `true`).
Added a fix in the same branch above, let me know if it's working now.

**Comment by tonysilva16** [comment]
Hello,

Its seems that is fixed, at least for what i could tried it was working allright. Tomorrow i am gonna test it better and i will give you feedback.
Thanks.

**Comment by tonysilva16** [comment]
Hello,

I am getting an error on a coupon update. I am not sure, but the webhook must be trigger using the admin page and the webhook function is using a function only available when doing frontend

```
[23-Jun-2022 10:59:07 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function qtranxf_get_front_page_config() in /wp-content/plugins/qtranslate-xt/modules/woo-commerce/woo-commerce.php:50
Stack trace:
#0 /wp-includes/class-wp-hook.php(307): qtranxf_wc_deliver_webhook_async()
#1 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#2 /wp-includes/plugin.php(524): WP_Hook->do_action()
#3 /wp-content/plugins/woocommerce/packages/action-scheduler/classes/actions/ActionScheduler_Action.php(22): do_action_ref_array()
#4 /wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php(65): ActionScheduler_Action->execute()
#5 /wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueRunner.php(162): ActionScheduler_Abstract_QueueRunner->process_action()
#6 /wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueRunner.php(132): ActionScheduler_QueueRunner->do_batch()
#7 /wp-includes/class-wp-hook.php(307): ActionScheduler_QueueRunner->run()
#8 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#9 /wp-includes/plugin.php(476): WP_Hook->do_action()
#10 /wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_AsyncRequest_QueueRunner.php(52): do_action()
#11 /wp-content/plugins/woocommerce/includes/libraries/wp-async-request.php(147): ActionScheduler_AsyncRequest_QueueRunner->handle()
#12 /wp-includes/class-wp-hook.php(307): WP_Async_Request->maybe_handle()
#13 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#14 /wp-includes/plugin.php(476): WP_Hook->do_action()
#15 /wp-admin/admin-ajax.php(187): do_action()
#16 {main}
  thrown in /wp-content/plugins/qtranslate-xt/modules/woo-commerce/woo-commerce.php on line 50
```

**Comment by spleen1981** [comment]
Right, that part shouldn't be needed if not doing frontend.
That's a confirmation filters are working as expected anyways.
Fixed now in the same branch

**Comment by herrvigg** [comment]
Merged in master.
