### ISSUE TITLE
The page redirected you too many times - On plugin activation

### ISSUE THREAD

**Issue by l1z0b** [qtranslate/qtranslate-xt#1190]
When I activated the plugin I reloaded the page and I got the following error:

**The page redirected you too many times**

And I noticed that the URL looked like this:

https://website.com/it/?glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=&glang=it&gurl=

I had qtranslate-x and before I activated qtranslate-xt I deactivated it. Does someone know why this error occurs?

**Comment by herrvigg** [comment]
See https://github.com/qtranslate/qtranslate-xt/wiki/Browser-redirection.
There's nothing we can do without more information from your part, sorry.
