### ISSUE TITLE
Meta tag ACF 

### ISSUE THREAD

**Issue by webmaxo** [qtranslate/qtranslate-xt#1201]
Hello, I've run into a problem with the acf. Created the Text fields, tied them to the Product Category. wrote meta tags in 2 languages. and in the head I try to put it out like this

```
<?php
$queried_object = get_queried_object();
?>
```

`<title><?php the_field('title_cat', $queried_object);?></title>`

as a result, I get [:ua]test 1[:ru]test 2[:]

**Comment by spleen1981** [comment]
Hi, you should translate your content first, so code above should be something like:

```
<title><?php echo qtranxf_useCurrentLanguageIfNotFoundUseDefaultLanguage(get_field('title_cat', $queried_object));?></title>
```

**Comment by webmaxo** [comment]
Thank you very much. Problem solved
