### ISSUE TITLE
PHP warning qtranslate_core.php on line 183

### ISSUE THREAD

**Issue by Hr0bar** [qtranslate/qtranslate-xt#1202]
Hi, using latest release, some bot/vulnerability scanner/scraper request triggered this:

PHP Warning:  Undefined array key "host" in /opt/bitnami/wordpress/wp-content/plugins/qtranslate-xt/qtranslate_core.php on line 183', referer: /gbook.html

PHP 8.0.x

access log:
143.92.32.144 - - [16/Jul/2022:00:41:15 +0000] "GET /gbook.html HTTP/2.0" 404 126879

thanks for checking

**Comment by herrvigg** [comment]
Looks like a special case, possibly setting a wrong referrer. The host is derived from the origin, which should always be set.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer

Do you know more precisely how this happens? Can it be reproduced?

**Comment by Hr0bar** [comment]
Hi, no I dont know how to reproduce it. This was 100% some
bot/spambot/vulnerability scanner hacker request and not a regular request.

So I imagine its very unpredictable. Likely a custom curl request, not a
browser issued request.

**Comment by herrvigg** [comment]
OK added a new check, it doesn't cost much and it will be more robust.

**Comment by herrvigg** [comment]
Fix released in 3.12.1.
