### ISSUE TITLE
PHP error and irrelevant Slugs metabox in custom admin pages

### ISSUE THREAD

**Issue by yoancutillas** [qtranslate/qtranslate-xt#1207]
Hello,

The Slugs module causes a PHP error on any admin pages using metaboxes if they are not a WP_Post:
[qtranslate-xt\modules\slugs\admin\slugs-admin.php line 130](https://github.com/qtranslate/qtranslate-xt/blob/3.12.0/modules/slugs/admin/slugs-admin.php#L130)

The reason is that the Slugs module assumes that the passed variable $post is a WP_Post object.
Of course, a page displaying metaboxes isn't necessarily a WP_Post.

A workaround would be to exit the qts_draw_meta_box() function early if the passed variable isn't a WP_Post.
For example, by adding at line 124:
`if( ! ( is_object( $post ) && ! empty( $post->ID ) ) ) { return; } `

A better solution would be to not display the "Slugs per language" metabox at all on irrelevant pages (that is, on pages that are not WP_Post).

**Comment by spleen1981** [comment]
good catch, can you try this [branch](https://github.com/qtranslate/qtranslate-xt/tree/slugs_fix_unneeded_metabox)?

**Comment by yoancutillas** [comment]
Yes it is working, Thank you!
