### ISSUE TITLE
some Product showing in both language

### ISSUE THREAD

**Issue by alanefzi** [qtranslate/qtranslate-xt#1213]
some Product showing in both language in woocommerce in my website wordpress 

<img width="573" alt="Screen Shot 2022-08-17 at 8 49 22 AM" src="https://user-images.githubusercontent.com/111410884/185037543-1a6f141c-1285-4f22-b841-7847a51c5397.png">

**Comment by herrvigg** [comment]
We'd need more info from your side to understand the problem better.

**Comment by spleen1981** [comment]
@alanefzi which are exactly the parameters not translated properly?
Which are the corresponding fields admin side?

**Comment by herrvigg** [comment]
No update so I close this ticket. Re-open if you can provide more relevant data and how to reproduce it.
