### ISSUE TITLE
Problem with default language

### ISSUE THREAD

**Issue by Beast22** [qtranslate/qtranslate-xt#1214]
I have such settings 
![Screenshot](https://user-images.githubusercontent.com/13337448/186012247-fa17ddf8-700f-42a9-b778-8451dd2317c2.png)
Detect language by browser enabled
Url modification: ?lang=ru

I would like "de" language as default in all ip and browsers
But default lang is russian which is used in admin panel
Url: http://tld-pro.de/

**Comment by herrvigg** [comment]
I don't understand the problem. If I follow the link on your website, it appears in German for me. This depends on your browser settings.
If you switch language to RU in the URL it will switch.
What do you expect?
