### ISSUE TITLE
Critical error between Complianz plugin integration and qTranslate-XT

### ISSUE THREAD

**Issue by sviluppomania** [qtranslate/qtranslate-xt#1220]
Hi, I have this problem: https://wordpress.org/support/topic/qtranslate-xt-plugin/#post-15997642, I tried all the proposed solutions with no results, they advised me to contact qTranslate-XT support, as the critical error mentioned can be caused by the latter.

**Comment by herrvigg** [comment]
This is being discussed here: #1069 so I close it as duplicate.
I'll let people using Complianz solving this.
