### ISSUE TITLE
qTranslate - Title problem

### ISSUE THREAD

**Issue by JashuaTr** [qtranslate/qtranslate-xt#1223]
Hello, I am having the problem that I linked below. In the integration of not only facebook but also google merchant and Turkey marketplace sites. Is there any solution to this problem?

Thank you.

https://github.com/woocommerce/facebook-for-woocommerce/issues/30

**Comment by spleen1981** [comment]
Can you explain in detail the issue, plugins/extension involved and where is this happening, frontend or admin, without asking us to going through the entire 5y old closed issue above?
Like we didn't know the plugin, which is actually the case

**Comment by JashuaTr** [comment]
Thank you for the feedback. However, I found the solution by switching to
Translatepress.

Thank you again though.

Giovanni Cascione ***@***.***>, 3 Eki 2022 Pzt, 17:49
tarihinde şunu yazdı:

**Comment by spleen1981** [comment]
Good, I guess you can close this issue then...
