### ISSUE TITLE
Function strftime() is deprecated

### ISSUE THREAD

**Issue by extremecarver** [qtranslate/qtranslate-xt#1224]
With php 8.1 strftime already throws a warning notice. It has to be replaced for future compatibility:
https://php.watch/versions/8.1/strftime-gmstrftime-deprecated

**Comment by extremecarver** [comment]
Actually if you enable WP Debug with PHP 8.1 this already causes problems - as where it is used it will put a warninng notice in front of the date - for me regarding comments. With debugging disabled it is still fine.

**Comment by herrvigg** [comment]
We know, it's in the top priority, but it's not trivial to replace. Duplicate #1085.
