### ISSUE TITLE
Problems with jetpack and worpress.com recognition

### ISSUE THREAD

**Issue by stevr1it** [qtranslate/qtranslate-xt#1229]
Hello, I have installed the following version:
[version.odt](https://github.com/qtranslate/qtranslate-xt/files/9653428/version.odt)

with the following configuration:
[configuration.odt](https://github.com/qtranslate/qtranslate-xt/files/9653423/configuration.odt)

When i attach jetpack with wordpress.com with qTranslate-XT installed, something block the recognition on the site on wordpress.com/marketing saying that This site cannot be accessed. But the site is accessible. If i disactivate qtranslate-xt everything works well, can you help me? thank you

**Comment by herrvigg** [comment]
I have Jetpack connected with qTranslate-XT, no problem. I can't reproduce this.
You have many other plugins, try to disable all the others before disabling qTranslate-XT.

**Comment by stevr1it** [comment]
I did it already, i had to delete qtranslate-xt
I have disabled all the other plug in and the problem remain. only disabling qtranslate-xt wordpress was recognising jetpack.

**Comment by herrvigg** [comment]
It's impossible to understand the problem if you don't give more technical information.
See also https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting.
We can re-open this ticket if you provide more insights.
