### ISSUE TITLE
Language Switching Buttons missing in ACF options

### ISSUE THREAD

**Issue by schalkjoubert** [qtranslate/qtranslate-xt#1233]
Since version 3.12.1, the language Switching buttons are missing, even though that is selected under Editor Mode
Instead the Simple Language Mode is used.

If I revert back to 3.12.0, the buttons show, but then the front en display both language with theur tags, ie.

:en]The family’s philosophy is structured around a simple principle: selecting the best terroir and partners: Sancerre and Provence in France, Stellenbosch in South Africa and Sicily in Italy, relying on local expertise in each of these estates.[:]

This only happens for custom fields on Options Pages.
Standard wordpress Pages and Post do however display the buttons.

Please see screenshots attached,
Thank you
![qtranslate](https://user-images.githubusercontent.com/4852452/195293884-88abd3ad-addb-47d6-a307-d1b75294ee18.jpg)
![Domains_–_Oddo_Vins___Domaines](https://user-images.githubusercontent.com/4852452/195294023-b82b3049-49da-4ed8-9a64-b8d904ed4fd1.jpg)

**Comment by herrvigg** [comment]
> This only happens for custom fields on Options Pages.

What do you mean with Option Pages, which one? How did you configure the Field Group to be active on such pages?

As a side note - with ACF 6 there's a brand new UI and I can't find the language buttons for the Field Group Title for example, this seems broken... But it's another problem, better create separate issues.

![image](https://user-images.githubusercontent.com/19155375/196557713-88bc3f93-4c45-4746-b756-3f83ec4d66f0.png)

**Comment by schalkjoubert** [comment]
I created an Option page for each of my main "Features", and then in ACF set the Rule to Options. I prefer to work this way to simplify he UI for the client. They don't have to go to pages then. See attached screenshots.

`if( function_exists('acf_add_options_page') ) {
  acf_add_options_page(array(
    'page_title'  => 'Domain',
    'menu_title'  => 'Domain',
    'menu_slug'   => 'tsum-domain',
    'capability'  => 'edit_posts',
    'redirect'    => false,
    'icon_url'    => 'dashicons-awards',
    // 'position'    =>  2,
  ));
  }

add_action( 'storefront_before_content', 'tsum_before_content_domain_header', 1 );
function tsum_before_content_domain_header () {
    if(
      is_page(array('domains','domaines')) ) :
  ?>

<div id="page-header" class="module module-par module-par-head">
  <div class="par-background" style="background-image: url(
    <?php if( get_field('domain_image', 'option') ): ?>
      <?php echo the_field('domain_image', 'option'); ?>
    <?php endif; ?>">
  </div>
  
  <div class="par-content">
    <div class="par-content-inner">
      <h2><?php the_title() ?></h2>
      <div class="grid">
        <div class="box">
          <?php if( get_field('domain_introduction', 'option') ): ?>
            <p>
              <?php the_field('domain_introduction', 'option'); ?>
            </p>
          <?php endif; ?>
        </div>
      </div>
    </div>
  </div>
</div>
<?php
   endif;
}`

**Comment by schalkjoubert** [comment]
WP Dash Screenshot
![acf-domain](https://user-images.githubusercontent.com/4852452/197114591-dcbaddc2-1822-42ef-bac1-e782284b1dbd.jpg)

**Comment by herrvigg** [comment]
The options page are only available in the PRO version that I don't have 😕 
https://www.advancedcustomfields.com/add-ons/options-page/
There used to be a free addon plugin just for the options page... but obviously they have removed it - how annoying 😞    
Ideally I should have a copy of ACF PRO for debugging, But can't this addon plugin be retrieved somewhere?

**Comment by herrvigg** [comment]
> Since version 3.12.1, the language Switching buttons are missing, even though that is selected under Editor Mode
Instead the Simple Language Mode is used.
> If I revert back to 3.12.0, the buttons show, but then the front en display both language with theur tags

Between 3.12.0 and 3.1.22.1 I refactored the ACF structure in #1191 but it was supposed to maintain all the existing functionalities. What is surprising is that you also had issues in 3.12.0. Has this page already worked before?

@ChristophJeworutzki do you observe the same problem? Did it work with 3.12.0, and if not, did it work before?

**Comment by herrvigg** [comment]
@schalkjoubert @ChristophJeworutzki I found the problem with the LSB in ACF options page, it was a regression in 3.12.1 with the init sequence, now fixed in master. I don't know about the problem on the front-end with the tags, I expect it to work normally. Could you test the current version on master?

Note there's a known problem with ACF 6 for the field group name but that's another topic, see #1227.

**Comment by MKRD-SUPPORT** [comment]
Strange, why is this working for me?

WP 6.1.1 (Twenty Twenty-One)
ACF PRO 6.0.4 / 6.0.5 (Option page)
QTX 3.12.1

Edge, Firefox

**Comment by herrvigg** [comment]
Strange indeed, but the fix from 7a660fe6bd1fefd83b858a1c506618639e08006a is needed.
Before that, the `QTX_Module_Acf_Admin` would be initialized too late `plugins_loaded` priority 3.
It sets a `qtranslate_admin_config` filter but this is needed in `qtranslate_init_language` called first on `plugins_loaded` priority 2 and the result is cached in a static variable... This init sequence is quite tricky.
If it works without that fix there must be something else that changes that regular scenario.

**Comment by herrvigg** [comment]
Many ACF fixes released in 3.13.0.
