### ISSUE TITLE
The page isn’t redirecting properly error

### ISSUE THREAD

**Issue by yycgk** [qtranslate/qtranslate-xt#1237]
in wp-admin, if i click "view" for any of the "Pages", i get "**The page isn’t redirecting properly error**". The problem is resolved once i deactivate qTranslate-XT plugin. **Does anybody know how to fix this?** The site was built a while ago and we never had any problems caused by qTranslate-XT plugin until now. 
__________________________________________
![Screen Shot 2022-10-21 at 8 24 56 PM](https://user-images.githubusercontent.com/116393455/197315054-cb484227-e173-4ab4-8d2f-9e7b1059283c.png)
__________________________________________
![Screen Shot 2022-10-21 at 4 10 29 PM](https://user-images.githubusercontent.com/116393455/197316299-24bdff37-3b3e-40bb-92b5-c0d57c575bad.png)

**Comment by herrvigg** [comment]
This is impossible to investigate without more information from your side. See [browser redirection](https://github.com/qtranslate/qtranslate-xt/wiki/Browser-redirection) and [wiki troubleshooting](https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting).

**Comment by yycgk** [comment]
we've performed a few tests... it is important to mention that wp-config.php looks fine, there are no rules in place and the same REDIRECT issue also happens when using a default theme such as "twentytwentytwo".

The mentioned redirect loop is a 302 between the same requested URL. I am sharing screenshots below. Reaching out to you as you might have some further information on this issue. Thank you.
![unnamed(1)](https://user-images.githubusercontent.com/116393455/197342091-7daf6b90-62a6-4a2b-9cb4-168561a37094.png)
![unnamed(2)](https://user-images.githubusercontent.com/116393455/197342217-be911a2e-1047-45e9-b638-bb77e40da51a.png)

**Comment by yycgk** [comment]
we've performed a few tests... it is important to mention that wp-config.php looks fine, there are no rules in place and the same REDIRECT issue also happens when using a default theme such as "twentytwentytwo".

The mentioned redirect loop is a 302 between the same requested URL. I am sharing screenshots below. Reaching out to you as you might have some further information on this issue. Thank you.
![unnamed(1)](https://user-images.githubusercontent.com/116393455/197342443-126e165f-2225-4229-9125-2ac97c43e3a9.png)
![unnamed(2)](https://user-images.githubusercontent.com/116393455/197342446-d1108619-59b0-430c-9e98-41d209f926f2.png)

**Comment by herrvigg** [comment]
Do you have some special configuration, what are the URL Modification Mode and cookies settings?
See config from options-general.php?page=qtranslate-xt#troubleshooting
Redirection loop is often a sign there's something wrong with cookies that can't be written or read.

**Comment by yycgk** [comment]
Thank you [herrvigg](https://github.com/herrvigg)

Maybe this will help. The site is hosted at wpengine.com https://wpengine.com/support/platform-settings/
Perhaps you could review their platform to see if you notice anything there that might be causing this REDIRECT issue.

I just chatted with Support from WP Engine. This is what they had to say: 
"We would need more details on this. For example is there cookie we can perhaps cache exclude related to this plugin. We're not sure if there would be since wp-admin login is already cache excluded. Perhaps that plugin used .htaccess coding and since the deprecation .htaccess; The issue is now a major problem."

**Comment by yycgk** [comment]
[herrvigg](https://github.com/herrvigg), please see below what happens according to the logs. I’ve hidden the URL and computer/browser versions. If you like, I can give you access to the dev environment — let me know.

184.64.167.332 - - [22/Oct/2022:22:16:21 +0000] “GET /wp-admin/load-scripts.php?c=1&load%5Bchunk_0%5D=hoverIntent&ver=6.0.2 HTTP/1.0” 200 1500 “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***************”
184.64.167.332 - - [22/Oct/2022:22:16:22 +0000] “POST /wp-admin/admin-ajax.php? HTTP/1.0” 200 71 “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:28 +0000] “GET /empietements/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:29 +0000] “GET /empietements/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:29 +0000] “GET /empietements/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:29 +0000] “GET /empietements/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:29 +0000] “GET /empietements/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:29 +0000] “GET /empietements/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:29 +0000] “GET /empietements/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:30 +0000] “GET /empietements/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “”Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:31 +0000] “GET /empietements/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:31 +0000] “GET /empietements/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:31 +0000] “GET /empietements/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:32 +0000] “GET /empietements/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:32 +0000] “GET /empietements/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:39 +0000] “POST /wp-admin/admin-ajax.php? HTTP/1.0” 200 71 “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********””
184.64.167.332 - - [22/Oct/2022:22:16:42 +0000] “GET /wp-admin/edit.php?post_type=page HTTP/1.0” 200 43912 “https://xxxx.ca/wp-admin/plugins.php” “Mozilla***********””
184.64.167.332 - - [22/Oct/2022:22:16:43 +0000] “GET /wp-admin/load-scripts.php?c=1&load%5Bchunk_0%5D=jquery-core,jquery-migrate,jquery-ui-core,utils,regenerator-runtime,wp-polyfill,wp-hooks&ver=6.0.2 HTTP/1.0” 200 153860 “https://xxxx.ca/wp-admin/edit.php?post_type=page” “”Mozilla***********””
184.64.167.332 - - [22/Oct/2022:22:16:43 +0000] “GET /wp-admin/load-scripts.php?c=1&load%5Bchunk_0%5D=hoverIntent&ver=6.0.2 HTTP/1.0” 200 1500 “https://xxxx.ca/wp-admin/edit.php?post_type=page” “”Mozilla***********””
184.64.167.332 - - [22/Oct/2022:22:16:43 +0000] “GET /wp-admin/load-styles.php?c=1&dir=ltr&load%5Bchunk_0%5D=farbtastic&ver=6.0.2 HTTP/1.0” 200 529 “https://xxxx.ca/wp-admin/edit.php?post_type=page” “”Mozilla***********””
184.64.167.332 - - [22/Oct/2022:22:16:43 +0000] “GET /wp-admin/load-styles.php?c=1&dir=ltr&load%5Bchunk_0%5D=dashicons,admin-bar,common,forms,admin-menu,dashboard,list-tables,edit,revisions,media,themes,about,nav-menus,wp-pointer,widgets&load%5Bchunk_1%5D=,site-icon,l10n,buttons,wp-auth-check,media-views,wp-color-picker,code-editor&ver=6.0.2 HTTP/1.0” 200 440077 “https://xxxx.ca/wp-admin/edit.php?post_type=page” “”Mozilla***********””
184.64.167.332 - - [22/Oct/2022:22:16:44 +0000] “POST /wp-admin/admin-ajax.php? HTTP/1.0” 200 71 “https://xxxx.ca/wp-admin/edit.php?post_type=page” “”Mozilla***********””
184.64.167.332 - - [22/Oct/2022:22:16:49 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********””
184.64.167.332 - - [22/Oct/2022:22:16:49 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:49 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:49 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:50 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:50 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:50 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:51 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:51 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:51 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:51 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:51 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:51 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:52 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:52 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:52 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:57 +0000] “GET /wp-admin/load-styles.php?c=1&dir=ltr&load%5Bchunk_0%5D=dashicons,admin-bar,common,forms,admin-menu,dashboard,list-tables,edit,revisions,media,themes,about,nav-menus,wp-pointer,widgets&load%5Bchunk_1%5D=,site-icon,l10n,buttons,wp-auth-check,media-views,wp-color-picker,code-editor&ver=6.0.2 HTTP/1.0” 200 440077 “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”
184.64.167.332 - - [22/Oct/2022:22:16:58 +0000] “POST /wp-admin/admin-ajax.php? HTTP/1.0” 200 71 “https://xxxx.ca/wp-admin/edit.php?post_type=page” “Mozilla***********”

**Comment by herrvigg** [comment]
> We're not sure if there would be since wp-admin login is already cache excluded. Perhaps that plugin used .htaccess coding and since the deprecation .htaccess; The issue is now a major problem."

No, we don't use any strange things, all is PHP/WP standard with `setcookie` and `wp_redirect`.
The problem is not `wp-admin` here. When you click on view, it opens a regular "frontend" link, no admin. You have very likely a problem with the cookie management. or something else with the web server or WP setup.

Please copy-paste the settings using "collect info" from `wp-admin/options-general.php?page=qtranslate-xt#troubleshooting`

**Comment by herrvigg** [comment]
FYI
```
184.64.167.332 - - [22/Oct/2022:22:16:52 +0000] “GET /contractor-toolkit/? HTTP/1.0” 302 - “[https://xxxx.ca/wp-admin/edit.php?post_type=page”](https://xxxx.ca/wp-admin/edit.php?post_type=page%E2%80%9D) “Mozilla***********”
```
The problem comes from frontend page `/contractor-toolkit/?` that loops on itself. The other link `https://xxxx.ca/wp-admin/edit.php?post_type=page”` is the origin (from wp-admin), but this is should not be involved with the redirection.
If you open your website on any other frontend page you will certainly have the same problem. You can also take a look at the cookies in your browser console.

**Comment by yycgk** [comment]
thank you, [herrvigg](https://github.com/herrvigg)
We have 3 sites (one main + 2 subdomains) that use the qtranslate-xt plugin. PHP and WP versions range from 7.4.3 to 8.0 and 5.8.1 to 6.0.2 respectively. As I mentioned earlier, the sites worked flawlessly for many years, but then something happened...

**As per your message, please see below the collected information** (the site URL was changed):

**Versions**
{
  "PHP_VERSION": "7.4.30",
  "WP_VERSION": "5.9.3",
  "QTX_VERSION": "3.8.1",
  "Plugins": [
    "Advanced Custom Fields: Extended 0.8.8.10",
    "Advanced Custom Fields PRO 6.0.3",
    "All-in-One WP Migration 7.66",
    "Better Admin Bar 4.0.4",
    "Better Delete Revision 1.6.1",
    "Classic Editor 1.6.2",
    "Contact Form 7 5.6.4",
    "Download Monitor 4.7.1",
    "Duplicate Page 4.4.9",
    "Easy FancyBox 1.9.4",
    "Flamingo 2.3",
    "Invisible reCaptcha 1.2.3",
    "No Comments 1.0.9",
    "qTranslate-XT 3.8.1",
    "Really Simple SSL 5.3.5",
    "Shortcodes Ultimate 5.12.2",
    "Advanced Editor Tools (previously TinyMCE Advanced) 5.6.0",
    "WordPress Importer 0.8"
  ]
}

**Configuration**
{
  "default_language": "en",
  "enabled_languages": [
    "en",
    "fr"
  ],
  "flag_location": "plugins/qtranslate-xt-3.8.1/flags/",
  "language_name": {
    "en": "English",
    "fr": "Français"
  },
  "locale": {
    "en": "en_US",
    "fr": "fr_FR"
  },
  "locale_html": {
    "en": "",
    "fr": ""
  },
  "not_available": {
    "en": "Sorry, this entry is only available in %LANG:, : and %.",
    "fr": "Désolé, cet article est seulement disponible en %LANG:, : et %."
  },
  "date_format": {
    "en": "%A %B %e%q, %Y",
    "fr": "%A %e %B %Y"
  },
  "time_format": {
    "en": "%I:%M %p",
    "fr": "%H:%M"
  },
  "flag": {
    "en": "gb.png",
    "fr": "fr.png"
  },
  "url_mode": "2",
  "use_strftime": "4",
  "filter_options_mode": 0,
  "language_name_case": 0,
  "detect_browser_language": true,
  "hide_untranslated": true,
  "show_displayed_language_prefix": true,
  "show_alternative_content": false,
  "hide_default_language": true,
  "use_secure_cookie": false,
  "header_css_on": true,
  "header_css": ".qtranxs_flag_en {background-image: url(https://qtranslate123.wpengine.com/wp-content/plugins/qtranslate-xt-3.8.1/flags/gb.png); background-repeat: no-repeat;}\n.qtranxs_flag_fr {background-image: url(https://qtranslate123.wpengine.com/wp-content/plugins/qtranslate-xt-3.8.1/flags/fr.png); background-repeat: no-repeat;}\n",
  "text_field_filters": [],
  "front_config": {
    "all-pages": {
      "filters": {
        "text": {
          "widget_title": "20",
          "widget_text": "20",
          "the_title": "20",
          "category_description": "20",
          "list_cats": "20",
          "wp_dropdown_cats": "20",
          "term_name": "20",
          "get_comment_author": "20",
          "the_author": "20",
          "tml_title": "20",
          "term_description": "20"
        },
        "term": {
          "cat_row": "0",
          "cat_rows": "0",
          "wp_get_object_terms": "0",
          "single_cat_title": "0",
          "single_tag_title": "0",
          "single_term_title": "0",
          "the_category": "0",
          "get_term": "0",
          "get_terms": "0",
          "get_category": "0"
        },
        "url": {
          "author_feed_link": "10",
          "author_link": "10",
          "get_comment_author_url_link": "10",
          "post_comments_feed_link": "10",
          "day_link": "10",
          "month_link": "10",
          "year_link": "10",
          "page_link": "10",
          "post_link": "10",
          "category_link": "10",
          "category_feed_link": "10",
          "tag_link": "10",
          "term_link": "10",
          "the_permalink": "10",
          "feed_link": "10",
          "tag_feed_link": "10"
        }
      }
    }
  },
  "term_name": {
    "News": {
      "en": "News",
      "fr": "Uncategorized"
    }
  },
  "disable_client_cookies": false,
  "ignore_file_types": [
    "gif",
    "jpg",
    "jpeg",
    "png",
    "svg",
    "pdf",
    "swf",
    "tif",
    "rar",
    "zip",
    "7z",
    "mpg",
    "divx",
    "mpeg",
    "avi",
    "css",
    "js",
    "mp3",
    "mp4",
    "apk"
  ],
  "url_info": {
    "cookie_enabled": true,
    "cookie_lang_front": "en",
    "cookie_lang_admin": "en",
    "scheme": "https",
    "host": "qtranslate2fix.wpengine.com",
    "path": "/wp-admin/admin-ajax.php",
    "query": "action=admin_debug_info",
    "path-base": "",
    "path-base-length": 0,
    "wp-path": "/wp-admin/admin-ajax.php",
    "language_neutral_path": true,
    "http_referer": "https://qtranslate123.wpengine.com/wp-admin/options-general.php?page=qtranslate-xt",
    "referer_admin": true,
    "doing_front_end": false,
    "lang_cookie_admin": "en",
    "lang_admin": "en",
    "language": "en",
    "set_cookie": false
  },
  "language": "en",
  "editor_mode": 0,
  "highlight_mode": 1,
  "auto_update_mo": true,
  "hide_lsb_copy_content": false,
  "lsb_style": "Simple_Buttons.css",
  "config_files": [
    "./i18n-config.json"
  ],
  "admin_config": {
    "post": {
      "pages": {
        "post.php": "",
        "post-new.php": ""
      },
      "anchors": {
        "post-body-content": {
          "where": "first last"
        }
      },
      "forms": {
        "post": {
          "fields": {
            "title": [],
            "excerpt": [],
            "attachment_caption": [],
            "attachment_alt": [],
            "view-post-btn": {
              "encode": "display"
            },
            "wp-editor-area": {
              "jquery": ".wp-editor-area"
            },
            "gallery-caption": {
              "jquery": ".gallery-caption",
              "encode": "none"
            },
            "wp-caption-text": {
              "jquery": ".wp-caption-text",
              "encode": "display"
            },
            "img-alt": {
              "jquery": "img",
              "attrs": [
                "alt"
              ],
              "encode": "display"
            }
          }
        },
        "wpbody-content": {
          "fields": {
            "wrap-h1": {
              "jquery": ".wrap h1",
              "encode": "display"
            },
            "wrap-h2": {
              "jquery": ".wrap h2",
              "encode": "display"
            }
          }
        }
      },
      "js-exec": {
        "post-exec": {
          "src": "./admin/js/post-exec.min.js"
        }
      }
    },
    "options-general": {
      "preg_delimiter": "#",
      "pages": {
        "options-general.php": "^(?!.*page=[^=&]+).*$"
      },
      "forms": {
        "options": {
          "fields": {
            "blogname": [],
            "blogdescription": [],
            "head-title": {
              "jquery": "head title",
              "encode": "display"
            }
          }
        }
      }
    },
    "widgets": {
      "pages": {
        "widgets.php": ""
      },
      "anchors": {
        "widgets-right": {
          "where": "before after"
        }
      },
      "forms": {
        "widgets-right": {
          "fields": {
            "widget-title": {
              "jquery": "input[id^='widget-'][id$='-title']"
            },
            "widget-text-text": {
              "jquery": "textarea[id^='widget-text-'][id$='-text']"
            },
            "in-widget-title": {
              "jquery": "span.in-widget-title",
              "encode": "display"
            }
          }
        }
      },
      "js-exec": {
        "widgets-exec": {
          "src": "./admin/js/widgets-exec.min.js"
        }
      }
    },
    "edit-term": {
      "pages": {
        "term.php": "",
        "edit-tags.php": "action=edit"
      },
      "forms": {
        "edittag": {
          "fields": {
            "name": [],
            "description": [],
            "parent": {
              "encode": "display"
            }
          }
        }
      }
    },
    "edit-tags": {
      "preg_delimiter": "#",
      "pages": {
        "edit-tags.php": "^(?!.*action=edit).*$"
      },
      "anchors": {
        "posts-filter": {
          "where": "before after"
        }
      },
      "forms": {
        "addtag": {
          "fields": {
            "tag-name": [],
            "tag-description": [],
            "parent": {
              "encode": "display"
            }
          }
        },
        "col-left": {
          "fields": {
            "tagcloud": {
              "jquery": ".tagcloud > a",
              "encode": "display"
            }
          }
        },
        "the-list": {
          "fields": {
            "row-title": {
              "jquery": ".row-title",
              "encode": "display"
            },
            "description": {
              "jquery": ".description",
              "encode": "display"
            }
          }
        }
      },
      "js-exec": {
        "edit-tags-exec": {
          "src": "./admin/js/edit-tags-exec.min.js"
        }
      }
    },
    "nav-menus": {
      "pages": {
        "nav-menus.php": "action=edit|menu=\\d+|^$"
      },
      "anchors": {
        "menu-to-edit": {
          "where": "before after"
        }
      },
      "forms": {
        "update-nav-menu": {
          "fields": {
            "title": {
              "jquery": "[id^=edit-menu-item-title-]"
            },
            "attr-title": {
              "jquery": "[id^=edit-menu-item-attr-title-]"
            },
            "description": {
              "jquery": "[id^=edit-menu-item-description-]"
            },
            "span.title": {
              "jquery": "span.menu-item-title",
              "encode": "display"
            },
            "link-to-original": {
              "jquery": ".link-to-original >a",
              "encode": "display"
            }
          }
        },
        "side-sortables": {
          "fields": {
            "label.title": {
              "jquery": "label.menu-item-title",
              "encode": "display"
            },
            "accordion-section-title": {
              "jquery": "h3.accordion-section-title",
              "encode": "display"
            }
          }
        }
      },
      "js-exec": {
        "nav-menus-exec": {
          "src": "./admin/js/nav-menus-exec.min.js"
        }
      }
    },
    "all-pages": {
      "filters": {
        "text": {
          "admin_title": "20"
        }
      }
    }
  },
  "custom_i18n_config": [],
  "custom_fields": [],
  "custom_field_classes": [],
  "post_type_excluded": [
    "attachment",
    "custom_css",
    "customize_changeset",
    "oembed_cache",
    "user_request",
    "wp_block",
    "acf-field-group",
    "flamingo_contact",
    "flamingo_inbound",
    "flamingo_outbound",
    "dlm_download",
    "dlm_download_version"
  ],
  "translator": {},
  "qtrans_compatibility": true,
  "i18n-cache": {
    "admin_page_configs": {
      "": {
        "filters": {
          "text": {
            "admin_title": "20"
          }
        }
      }
    }
  }
}


**Browser**
{
  "cookies": [],
  "navigator": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[105.0.0.0](http://105.0.0.0/) Safari/537.36"
}

**Comment by herrvigg** [comment]
> "QTX_VERSION": "3.8.1",

This is a **very old** version... May 2020. Please update to a more recent version. It could be something with the cookie policy on the browser side, see #1053 (related updates in QTX 3.11.0). The last release is 3.12.1 from Sept 4.
Until we're back to WP official plugins, it's recommended to use Github updater:
https://github.com/qtranslate/qtranslate-xt#how-to-update-qtranslate-xt-with-the-last-release

Otherwise it's another plugin creating problems, for example "Really Simple SSL 5.3.5" or any network/security functionality. Try disabling all plugins except QT-XT. All of this is described in the troubleshooting pages.

**Comment by yycgk** [comment]
Thank you [herrvigg](https://github.com/herrvigg)

We've updated qTranslate-XT to the latest version, deleted "Really Simple SSL 5.3.5" plugin and disabled all plugins except QT-XT. This still hasn't fixed the Redirect issue. Also just learned that the site can’t be viewed in either Chrome or Edge on PC
We are investigating network/security settings with the hosting company

**Comment by yycgk** [comment]
[herrvigg](https://github.com/herrvigg) this is from the wp engine support... they do not think this a security related issue or ssl related issue. If you have any suggestions on specific things we can try — please let me know. 

Please see the notes from WP Engine Support:
********************************
Looking at the headers on the redirect:

HTTP/2 302
server: nginx
date: Mon, 24 Oct 2022 19:45:57 GMT
content-type: text/html; charset=UTF-8
location: https://qtranslate123.wpengine.com/about-us/
set-cookie: qtrans_front_language=en; expires=Tue, 24-Oct-2023 19:45:57 GMT; Max-Age=31536000; path=/; HttpOnly; SameSite=Lax
x-redirect-by: WordPress
expires: Wed, 11 Jan 1984 05:00:00 GMT
cache-control: no-cache, must-revalidate, max-age=0
x-powered-by: WP Engine
x-pass-why: custom-path

x-redirect-by: WordPress Means our platform is not handling the redirect at all. It's something on wordpress.

Only live domains can be behind GES. So qtranslate2fix.wpengine.com is not using GES. Since the issue is happening here, we know it is not GES that is the cause.

I did some basic troubleshooting for you:

Only qtranslate-xt-master and classic-editor are active.

There is a default theme active.

I tried downgrading the wordpress version as far back as 5.8.2 with no effect.

Changing settings within the plugin didn't seem to have any effect at all.

The php version is on the lowest setting we have avail, 7.4.

Looking through the access logs, we're not blocking anything. There isn't an error here, just a redirect loop. It is NOT looping between http -> https. It's just a loop to the same URL:

https://qtranslate123.wpengine.com/about-us/ -> https://qtranslate123.wpengine.com/about-us/

I can confirm this is not a security related issue. This is not a ssl related issue.

I suggest relaying this to the plugin devs, and if they have any suggestions on specific things we can try here.

**Comment by yycgk** [comment]
[herrvigg](https://github.com/herrvigg) thank you for all your help! we got to the bottom of this. It was a combination of things that caused the redirect issue

**Comment by herrvigg** [comment]
As a curiosity, what was it? Related to cookies?

**Comment by herrvigg** [comment]
Or a bad HTTP/rewrite config?

**Comment by yycgk** [comment]
Herrvigg, thanks again for all your help with this.

I’d like to share all the info I have on this in private. What is the best email to contact you at?

**Comment by yycgk** [comment]
neither
[herrvigg](https://github.com/herrvigg), please send me a private message

**Comment by herrvigg** [comment]
Write me to my gmail, the username is my nickname.

**Comment by yycgk** [comment]
Hey :-) just emailed you
