### ISSUE TITLE
WooCommerce Shop is Hooked not Shortcoded (this might seem weird, but please read and help)

### ISSUE THREAD

**Issue by nevesdeveloper** [qtranslate/qtranslate-xt#1242]
Hello. I noticed that the WooCommerce Shop Page is Hooked (it doesn't have a shortcode).  
That's probably why the slug feature is not working with the WooCommerce Shop page. 
When we use a language other than the primary (for slug redirection) it will redirect us to a blank page (without showing the products, an unhooked page then). 
I don't have an idea how to make it work, so I left the slugs for both languages in the shop page the same, so the products can be shown in both languages. Anyway, i've been searching and I think nobody came here to tell this (the shop page is hooked, not shortcoded), meaning you will probably have to set a hook for the page when a new slug is set. Just speculating here. But if you have any help for me on this, on how to do it, I will appreciate it. I'm kinda rusty in PHP right now, and the plugin is working so well, I'm so happy with it, but really don't have time to have my hands dirty with this, so I will leave the both slugs with the same translation. Not the best solution, but for now is what it works. Really hope someone can fix this. Thank you all for the great work with this plugin, I haven't been using it for a while, but it really is awesome nowadays.

**Comment by spleen1981** [comment]
Slug for shop page itself can be changed like for any other page, just go in the admin page list and find the relevant one.
If you mean to change shop base slug for products and WC taxonomies, you can do that in qtranslate settings, slugs tab.
Not sure what this has to do with hooks and shortcodes though.

**Comment by herrvigg** [comment]
@nevesdeveloper did you read the last answer? Otherwise provide more info. I'll close the issue if inactive.
