### ISSUE TITLE
Hook to qtranxf_isMultilingual

### ISSUE THREAD

**Issue by Buildbetter** [qtranslate/qtranslate-xt#1244]
Please allow one hook to this function 
qtranxf_isMultilingual

Becouse of bug with Custom Fields Plugin - 2 years i have a problem whit this.

**Comment by herrvigg** [comment]
Please explain better why you need this.

>  2 years i have a problem whit this.

It's the first time we see this.

**Comment by Buildbetter** [comment]
Hi here is my problem 
https://github.com/qtranslate/qtranslate-xt/issues/1037
