### ISSUE TITLE
Issue with plugin Metaslider after updating to WP 6.1

### ISSUE THREAD

**Issue by bagaweb** [qtranslate/qtranslate-xt#1247]
Do not know if this issue is related to qTranslate-XT or the Metaslider plugin... anyway:

With WordPress 6.0.3 I was simply inserting these captions "[:en]English caption[:it]Italian caption" in the slider settings and it was working as expected, "English caption" was shown on the English version and "Italian caption" on the Italian version.

After updating to WordPress 6.1, captions are showing up like this even on front-end, "[:en]English caption[:it]Italian caption" on both English and Italian versions.

**Comment by vonsch76** [comment]
Edit 
[inc/slide/metaslide.image.class.php](http://inc/slide/metaslide.image.class.php)

search for 
		//add caption
        if (strlen($slide['caption'])) {
            $html .= '<div class="caption-wrap"><div class="caption">' . $tst2. $slide['caption'] . '</div></div>';
        }

change like this

//add caption
		_if (function_exists('qtranxf_useCurrentLanguageIfNotFoundUseDefaultLanguage')) $slide['caption']=qtranxf_useCurrentLanguageIfNotFoundUseDefaultLanguage($slide['caption']);_
        if (strlen($slide['caption'])) {
            $html .= '<div class="caption-wrap"><div class="caption">' . $tst2. $slide['caption'] . '</div></div>';
        }

**Comment by bagaweb** [comment]
Thanks a lot for you help @vonsch76 !
Your solution works.

Is the issue related to Metaslider plugin or WordPress 6.1. itself?
I suppose I should change those lines everytime Metaslider receives an update. Maybe is there a way to add some lines to functions.php file inside the theme?

**Comment by vonsch76** [comment]
Haven't really checked in details, but Metaslider would need to have a filter for that. At the moment there is no such. Also the issue would not exists if Metaslider would get the caption with a function like get_post().

**Comment by bagaweb** [comment]
Do you think we should point this issue to Metaslider authors?

**Comment by vonsch76** [comment]
Yes, I believe adding filters would be a valuable add-on.

**Comment by vonsch76** [comment]
Either a filter before caption is put out or some other method to get the
caption like get_post where the filtest are ran.

**Comment by vonsch76** [comment]
Seems that something has changed in Metaslider and it works now without extra code changes. Still testing, though.

**Comment by bagaweb** [comment]
I can read this on their changelog:

FIXED: Fix compatibility with plugin qTranslate-XT, #294;

But I can still see the same issue... What am I missing?

WordPress 6.1.1
qTranslate-XT 3.12.1
MetaSlider 3.28.2

Please have a look at campingmarmolada[dot]com

**Comment by vonsch76** [comment]
The closing backet.

Looks like

[:it]La tua vacanza in Val di Fassa[:en]Your holiday in Val di Fassa[:de]Ihr Urlaub in Fassatal[:fr]Vos vacances en Val di Fassa

While it should look like

[:it]La tua vacanza in Val di Fassa[:en]Your holiday in Val di Fassa[:de]Ihr Urlaub in Fassatal[:fr]Vos vacances en Val di Fassa[:]

for all for qTranslate-xt to operate.

**Comment by vonsch76** [comment]
check the wiki https://github.com/qtranslate/qtranslate-xt/wiki/Multilingual-fields

**Comment by bagaweb** [comment]
> While it should look like
> 
> [:it]La tua vacanza in Val di Fassa[:en]Your holiday in Val di Fassa[:de]Ihr Urlaub in Fassatal[:fr]Vos vacances en Val di Fassa[:]
> 
> for all strings to allow qTranslate-xt to operate.

I tried to add the closing bracket and now it looks as it is, e.g. closing bracket appering at the end of the caption... Still not separating the languages.

**Comment by vonsch76** [comment]
I have the same. Are the captions entered manually? Do you have any error codes?

**Comment by bagaweb** [comment]
> I have the same. Are the captions entered manually? Do you have any error codes?

Please have a look at the attache screenshot:

![screenshot-www campingmarmolada com-2022 12 23-12_37_31](https://user-images.githubusercontent.com/14122970/209330027-1e1c125d-f100-4d5d-8c9f-aeedbae612c9.png)

**Comment by vonsch76** [comment]
Should see the server side what is happening. Obviously the filter is not running. Check if at qtranslate-xt setting in the advance part the ml-slider and the ml-slide is checked.

**Comment by bagaweb** [comment]
Yes both ml-slide and ml-slider are checked in the advance settings of qtranslate-xt,

**Comment by vonsch76** [comment]
Only you have access to the backend, start checking in the ml code why the filter is not called. Try to change, call the filter manually, etc. Manual labour as usual.
Quoted where you should start. Others haven't reported, mine is different - as it works.

**Comment by bagaweb** [comment]
Yes I do have the access to the backend, how can I check this filter? Thanks for your help.

**Comment by vonsch76** [comment]
You have the code, save the $html in a file before and after. This is kind of DIY work.
I have installed the latest 3.28.3 and still seems fine.

**Comment by vonsch76** [comment]
Works flawless for me. Upgraded only for your sake. As I told you earlier the issue is something local with your setup.

**Comment by bagaweb** [comment]
Did you also update WordPress to its last version or just the plugin?

**Comment by vonsch76** [comment]
I never update to the latest WP, always behind with 1 major version.

**Comment by bagaweb** [comment]
That's why you don't see the error.
I'd like to understand if the issue is related to QTX rather tham MetaSlider.

**Comment by vonsch76** [comment]
Made a test with my other page. Newest WP 6.1.1, Metaslider 3.29.0 There is no error, qtranslate works as it should. Check for yourself https://portumlines.hu/en/metaslider-test/

**Comment by vonsch76** [comment]
Thanks for reminding me, I have checked without cache. Works now, you can
see for yourself. When you click the flag, the legend under the picture
will change as it should. Seems that the error is somewhere on your side,
but you need to check the local logs to figure it out.

**Comment by bagaweb** [comment]
> > I have the same. Are the captions entered manually? Do you have any error codes?
> 
> Please have a look at the attache screenshot:
> 
> ![screenshot-www campingmarmolada com-2022 12 23-12_37_31](https://user-images.githubusercontent.com/14122970/209330027-1e1c125d-f100-4d5d-8c9f-aeedbae612c9.png)

Thanks for your help @vonsch76 
 
Do you have the same settings in your backend?

**Comment by bagaweb** [comment]
Anyway, on the troubleshooting section, there are these info:

`{
  "PHP_VERSION": "7.4.3",
  "WP_VERSION": "6.1.1",
  "QTX_VERSION": "3.13.0",
  "Plugins": [
    "MetaSlider 3.29.1",
    "qTranslate-XT 3.13.0"
  ]
}`

**Comment by bagaweb** [comment]
`{
  "default_language": "it",
  "enabled_languages": [
    "it",
    "en",
    "de",
    "fr"
  ],
  "flag_location": "plugins/qtranslate-xt/flags/",
  "language_name": {
    "it": "IT",
    "en": "EN",
    "de": "DE",
    "fr": "FR"
  },
  "locale": {
    "it": "it_IT",
    "en": "en_US",
    "de": "de_DE",
    "fr": "fr_FR"
  },
  "locale_html": {
    "it": "",
    "en": "",
    "de": "",
    "fr": ""
  },
  "not_available": {
    "it": "Ci spiace, ma questo articolo è disponibile soltanto in %LANG:, : e %.",
    "en": "Sorry, this entry is only available in %LANG:, : and %.",
    "de": "Leider ist der Eintrag nur auf %LANG:, : und % verfügbar.",
    "fr": "Désolé, cet article est seulement disponible en %LANG:, : et %."
  },
  "date_format": {
    "it": "%e %B %Y",
    "en": "%A %B %e%q, %Y",
    "de": "%A, \\d\\e\\r %e. %B %Y",
    "fr": "%A %e %B %Y"
  },
  "time_format": {
    "it": "%H:%M",
    "en": "%I:%M %p",
    "de": "%H:%M",
    "fr": "%H:%M"
  },
  "flag": {
    "it": "it.png",
    "en": "gb.png",
    "de": "de.png",
    "fr": "fr.png"
  },
  "url_mode": 2,
  "use_strftime": 3,
  "filter_options_mode": 0,
  "language_name_case": 0,
  "detect_browser_language": true,
  "hide_untranslated": false,
  "show_menu_alternative_language": false,
  "show_displayed_language_prefix": true,
  "show_alternative_content": false,
  "hide_default_language": true,
  "use_secure_cookie": false,
  "header_css_on": false,
  "header_css": ".qtranxs_flag_it {background-image: url(https://www.campingmarmolada.com/wp-content/plugins/qtranslate-xt/flags/it.png); background-repeat: no-repeat;}\r\n.qtranxs_flag_en {background-image: url(https://www.campingmarmolada.com/wp-content/plugins/qtranslate-xt/flags/gb.png); background-repeat: no-repeat;}\r\n.qtranxs_flag_de {background-image: url(https://www.campingmarmolada.com/wp-content/plugins/qtranslate-xt/flags/de.png); background-repeat: no-repeat;}\r\n.qtranxs_flag_fr {background-image: url(https://www.campingmarmolada.com/wp-content/plugins/qtranslate-xt/flags/fr.png); background-repeat: no-repeat;}\r\n",
  "text_field_filters": [],
  "term_name": [],
  "disable_client_cookies": false,
  "ignore_file_types": [
    "gif",
    "jpg",
    "jpeg",
    "png",
    "svg",
    "pdf",
    "swf",
    "tif",
    "rar",
    "zip",
    "7z",
    "mpg",
    "divx",
    "mpeg",
    "avi",
    "css",
    "js",
    "mp3",
    "mp4",
    "apk"
  ],
  "url_info": {
    "cookie_lang_front": "it",
    "cookie_lang_admin": "it",
    "cookie_front_or_admin_found": true,
    "scheme": "http",
    "host": "localhost",
    "path": "/campingmarmolada.com/wp-admin/admin-ajax.php",
    "query": "action=admin_debug_info",
    "path-base": "/campingmarmolada.com",
    "wp-path": "/wp-admin/admin-ajax.php",
    "language_neutral_path": true,
    "http_referer": "https://www.campingmarmolada.com/wp-admin/options-general.php?page=qtranslate-xt",
    "referer_admin": true,
    "doing_front_end": false,
    "lang_cookie_admin": "it",
    "lang_admin": "it",
    "language": "it",
    "set_cookie": false
  },
  "language": "it",
  "editor_mode": 0,
  "highlight_mode": 1,
  "auto_update_mo": true,
  "hide_lsb_copy_content": false,
  "lsb_style": "Simple_Tabs.css",
  "config_files": [
    "./i18n-config.json"
  ],
  "custom_i18n_config": [],
  "custom_fields": [],
  "custom_field_classes": [],
  "post_type_excluded": [],
  "admin_enabled_modules": {
    "slugs": true,
    "acf": false,
    "all-in-one-seo-pack": false,
    "events-made-easy": false,
    "jetpack": false,
    "google-site-kit": false,
    "gravity-forms": false,
    "woo-commerce": false,
    "wp-seo": false
  },
  "translator": {},
  "qtrans_compatibility": false
}`

**Comment by vonsch76** [comment]
Yes, the same

[image: image.png]

As written, Metaslider, Wordpress the newest, PHP 8.1

**Comment by bagaweb** [comment]
I should try to upgrade to PHP 8.1 and see what happens.

**Comment by vonsch76** [comment]
Seen no effect on that. You have some other problem, as told you earlier.
Try to switch off the other plugins.

**Comment by bagaweb** [comment]
No other plugins are active.

**Comment by bagaweb** [comment]
> Check at advanced whether ml-slider and ml-slide is enabled for translation.

Yes that was already been checked.
Will you be so kind to send me some screenshots or the troubleshooting export?

**Comment by herrvigg** [comment]
Can someone summarize the status of this ticket?
From QTX 3.14.0 the debug information becomes more compact, to help reproducing the problems.

**Comment by vonsch76** [comment]
Seems some isolated problem at @bagaweb with regard the translation of the language. Tried, but unable to reproduce, works fine on my end.

**Comment by bagaweb** [comment]
`{
  "PHP_VERSION": "7.4.3",
  "WP_VERSION": "6.2",
  "QTX_VERSION": "3.14.0",
  "Plugins": [
    "MetaSlider 3.29.1",
    "qTranslate-XT 3.14.0"
  ]
}`

I can confirm with the latest updates the problem is finally solved!!!
We can close this issue.
Thank you
