### ISSUE TITLE
Error between "Slugs translation" integration and Burst plugin

### ISSUE THREAD

**Issue by sviluppomania** [qtranslate/qtranslate-xt#1259]
Hello,

I'm having problems with the "Slugs translation" integration which, with the new update of the "Burst" Plugin (  https://wordpress.org/plugins/burst-statistics/ ), if the integration is active, does not show the statistics dashboard.

I also opened a post on the Burst forum: https://wordpress.org/support/topic/error-with-new-update-5/#post-16237014

Is it possible to solve this problem or maybe create an integration with this plugin?

**Comment by sviluppomania** [comment]
https://github.com/Really-Simple-Plugins/burst/commit/893dee1bf723ca193bd0413be8738e00864b2035

**Comment by spleen1981** [comment]
> [Really-Simple-Plugins/burst@893dee1](https://github.com/Really-Simple-Plugins/burst/commit/893dee1bf723ca193bd0413be8738e00864b2035)

supposed to be closed, right?

**Comment by sviluppomania** [comment]
Perhaps, if there is the possibility of creating more integration between the two also on the qTranslate-XT side.

**Comment by herrvigg** [comment]
That's not a very good solution, it's too specific to qTranslate and a given API that may change in the future.
Between plugins they should use some hooks (filters in that case).
But it's such a tiny plugin, I don't have time to deal with that for now.
