### ISSUE TITLE
With Slugs enabled Woocommerce dont show 404 page for products

### ISSUE THREAD

**Issue by spleen1981** [qtranslate/qtranslate-xt#1260]
### Discussed in https://github.com/qtranslate/qtranslate-xt/discussions/1250

<div type='discussions-op-text'>

<sup>Originally posted by **andreysneg** November 12, 2022</sup>
If Slugs enabled ( new extension or old slugs plugin ) Woocommerce does not show 404 page for missing products.

If product missing site go to Shop page.

But must show 404 page if product missing.  Its bad for SEO. 

How remove redirect to shop page ?</div>

**Comment by spleen1981** [comment]
Screenshots in #1250 shows that issue is relevant to an old version of this plugin, as `class-qtranslate-slug.php` has been renamed some time ago.
@andreysneg can you update to current master and try to replicate the issue?
I've tested briefly and everything seems to work properly.

**Comment by herrvigg** [comment]
@andreysneg Please try again with last release 3.14.0 and if it still fails re-open this ticket (not discussion) with more info to reproduce the problem.
