### ISSUE TITLE
PHP Warning wp-seo-front.php

### ISSUE THREAD

**Issue by sviluppomania** [qtranslate/qtranslate-xt#1262]
I am getting the PHP Warning error below:

- `PHP Warning: Undefined array key "image" in /plugins/qtranslate-xt/modules/wp-seo/wp-seo-front.php on line 173`

- `PHP Warning: Trying to access array offset on value of type null in /plugins/qtranslate-xt/modules/wp-seo/wp-seo-front.php on line 173
`
Is there solution?

**Comment by herrvigg** [comment]
Fixed in master. The `isset` check was missing, that should solve it.

**Comment by sviluppomania** [comment]
Great, thanks! :-)
If it helps, I get other errors below:

`PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /plugins/qtranslate-xt/qtranslate_utils.php on line 389`
