### ISSUE TITLE
The site stopped showing one page in one language 

### ISSUE THREAD

**Issue by VadVor** [qtranslate/qtranslate-xt#1265]
The site stopped showing one page in one language - RU.  Other pages in this language are visible normally.
https://hotelalabriga.com/ru/

Using:

Wordpress v6.03.
qtranslate-xt v3.11.0
WP-Bakery Visual Composer v6.10

If somebody has an idea
Thanks

**Comment by herrvigg** [comment]
This seems to work fine also in RU so I close it. If we miss something please provide more details about what is failing.
