### ISSUE TITLE
slug issues after updating to 3.13.0

### ISSUE THREAD

**Issue by vonsch76** [qtranslate/qtranslate-xt#1272]
Just updated to 3.13.0 and some slugs failed to work for certain post types. (With the previous 3.12.1 everything was OK.) Seems that I needed to resave the configuration - without changing anything - and then everything went back to normal. Guess it is a bug. Maybe add a note for others to do so.

**Comment by herrvigg** [comment]
Mmmm now that you say it, I could understand it's needed for ACF as the page hooks have been moved to admin, but for Slugs I don't see why. Do you also use ACF? Was that necessary in admin or front (for the main users)?

**Comment by vonsch76** [comment]
It was a kind of weird issue as I remember. The redirection itself worked fine, so the landing page in the url is the one expected, still received a 404, but only for one of the post types.
No ACF, it is not installed.

**Comment by SasaHref01** [comment]
Hello,
I just installed version 3.13.0
and I have a problem to manage the slug
Can you help me
Thank you

**Comment by vonsch76** [comment]
What is the problem exactly. I am experiencing data loss with 3.13.0, so went back to 3.12.1 temporarily.

**Comment by SasaHref01** [comment]
Hello, thank you for your answer,
I happen to have an older version of qtranslate and just updated to QTranslate XT
apparently I did not set up the correct configuration of the parameters. but after some research I managed to configure it

Thanks

**Comment by herrvigg** [comment]
So it works as expected with 3.13.0? I don't see any reason why there would be a regression. The only change is about the initialization sequence. If the init fails you would not even see the slugs fields.

**Comment by vonsch76** [comment]
Yes, I have cheked the commits in the meantime and nothing seemed to ground this lost data. Maybe the save settings is also connected, will try to dig in. 
The page works ok, but nobody likes to loose the fancy links - per language.

**Comment by SasaHref01** [comment]
Hello

indeed I still have a problem, the slug by language is well invited by qtranslate TX
on the other hand the canonical url is not the right one for the 2nd language
knowing that I use Yoast SEO, and apparently it is the slug of the latter which is invited in the canonical url

Thanks for your help

**Comment by vonsch76** [comment]
It works, though you need to set basically by post. Also you need to set the categories, etc. From this I have no clue what you are experiencing.

**Comment by herrvigg** [comment]
> It works, though you need to...

I'm not following anymore, is it working or not?

**Comment by vonsch76** [comment]
@SasaHref01 comments are not related to the issue.

**Comment by herrvigg** [comment]
It's getting confusing. Is your issue described in #1275 ? If so we can close this one.

@SasaHref01 if it's not the same issue - apparently another topic with canonical - can you open a new one?

**Comment by herrvigg** [comment]
I close this ticket for now, it's mixing too many different topics.
