### ISSUE TITLE
Deprecated: Some notices with PHP 8.1

### ISSUE THREAD

**Issue by X-Raym** [qtranslate/qtranslate-xt#1277]
Hi,
when updated to PHP 8.1, I got some notices with debug activated. Here are formatted log:

**Deprecated:** preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in **qtranslate-xt/qtranslate_core** on line 821

**Deprecated:** setcookie(): Passing null to parameter #5 ($domain) of type string is deprecated in **qtranslate-xt/qtranslate_core** on line 456

**Deprecated:** explode(): Passing null to parameter #2 ($string) of type string is deprecated in **qtranslate-xt/modules/acf/src/plugin.php** on line 168

 Doesnt looks too bad, just some compatibility regarding some arguments.

Can we have a fix for these?

This would be very appreciated :) Thx!

**Comment by herrvigg** [comment]
This should be fixed long ago. See #1085. 
What version are you using? See readme to update to a more recent version.

**Comment by X-Raym** [comment]
@herrvigg Oh, it seems my update fails as I can see on admin it is still in Version 3.10.1 | 

I will update with last, and reopen if needed, thx for the support!
