### ISSUE TITLE
Disable translation for Standard Field Types

### ISSUE THREAD

**Issue by rsfreire** [qtranslate/qtranslate-xt#1279]
Hello there!

I believe the option to "Enable translation for Standard Field Types" was removed on the latest update, however I feel it's VERY useful to have some text fields non-translatable.

Is there any way to keep some fields non-translatable on the last version of the plugin, since the option to enable/disable this feature was removed?

<img width="258" alt="Screen Shot 2023-01-25 at 07 34 40" src="https://user-images.githubusercontent.com/12953614/214541289-497895e0-4c12-43a8-96dd-694a27fc5c0d.png">

Thanks!

**Comment by herrvigg** [comment]
> I feel it's VERY useful to have some text fields non-translatable.

The problem is it didn't even allow to make _some_ text fields non-translatable, it's all or nothing.
If you have ACF with qTranslate-XT which fields do you use the translations for? You can disable all translations in ACF by disabling the module.

**Comment by filtah** [comment]
> > I feel it's VERY useful to have some text fields non-translatable.
> 
> The problem is it didn't even allow to make _some_ text fields non-translatable, it's all or nothing. If you have ACF with qTranslate-XT which fields do you use the translations for? You can disable all translations in ACF by disabling the module.

You can translate 'some' fields easily, by selecting the qTranslate versions of those fields, and just use standard fields for those you don't want translated.

See: https://github.com/qtranslate/qtranslate-xt/issues/1282

We depend on this feature (Enable translation for Standard Field Types), so cannot upgrade to [3.13.0](https://github.com/qtranslate/qtranslate-xt/releases/tag/3.13.0).

**Comment by herrvigg** [comment]
> Now, as this checkbox has been removed, functionally it is set to ON, which changes the default behaviour and also renders the custom qTranslate-XT fields that get added at the bottom pretty useless.

In fact the idea for the long term is to remove the specific qTranslate-XT fields because they are harder to maintain. W

> It is really useful to have the option, because (in our case at least), there are often standard text fields which we don't want to translate for each language. For example, if we have a field for 'Villa Name', this would remain the same for each language, and we don't want to give the clients the option to change this text for each language.

The global option is not enough to select where the standard field should be translated, all or nothing for all posts is too restrictive. We'd need an additional option to extend the standard field. Using the "qTranslate-XT ACF" fields should only be seen a workaround.

Until then we can restore a global option. It could by refined by (standard) field type but there are only two supported: text, wysiwyg.

**Comment by herrvigg** [comment]
ACF settings restored and improved. Added new checkboxes for a finer tuning of the ACF std fields:
- content fields: text, textarea, wysiwyg
 - group meta fields: label, description, default value.

For the default value, the type of content field associated with the group field being edited must also be set e.g. text + default value.

![image](https://user-images.githubusercontent.com/19155375/224514550-1a4ffa6c-0b85-4f9d-9091-bb6048d730c1.png)

**Comment by herrvigg** [comment]
See also #1300. New panel for the extended fields.

![image](https://user-images.githubusercontent.com/19155375/227725952-706ddb6e-d825-4e64-a568-d13a6f86520a.png)
