### ISSUE TITLE
Please help to solve the problem with the incorrect work of the plugin (displays all languages instead of one)

### ISSUE THREAD

**Issue by Sty1ist** [qtranslate/qtranslate-xt#1280]
[https://i.postimg.cc/J0zsDTZx/2023-01-27-17-53-40.png](url)
[https://i.postimg.cc/sXq2xVfj/2023-01-27-17-54-49.png](url)

Hello, please help me to solve this problem:
in some fields, the text is displayed in all languages instead of one, both in the admin panel and on the frontend. Tell me how this can be solved?

Versions

{
  "PHP_VERSION": "7.3.31-1~deb10u1",
  "WP_VERSION": "6.1.1",
  "QTX_VERSION": "3.10.0.P1",
  "Plugins": [
    "ACF to REST API 3.3.2",
    "Admin Menu Editor 1.10",
    "Advanced CF7 DB 1.8.5",
    "Додаткові поля Pro 5.9.3",
    "All in One SEO 4.1.6.2",
    "Application Passwords 0.1.3",
    "Classic Editor 1.6.2",
    "Contact Form 7 5.5.4",
    "Custom Post Type UI 1.10.1",
    "Cyr-To-Lat 5.2.6",
    "Duplicate Page 4.4.7",
    "FTP loader by RIBS! 1.0",
    "Mailgun 1.7.9",
    "Open External Links in a New Window 1.42",
    "qTranslate-XT 3.10.0",
    "Resize Image After Upload 1.8.6",
    "REST API - Head Tags 1.2.1",
    "Simple Custom Post Order 2.5.6",
    "JAMstack Deployments 1.1.1",
    "WP RSS Aggregator 4.21.1"
  ]
}

Configuration

{
  "default_language": "uk",
  "enabled_languages": {
    "2": "uk",
    "3": "ru",
    "4": "en"
  },
  "flag_location": "plugins/qtranslate-xt-master/flags/",
  "language_name": {
    "uk": "Українська",
    "ru": "Русский",
    "en": "English"
  },
  "locale": {
    "uk": "uk",
    "ru": "ru_RU",
    "en": "en_US"
  },
  "locale_html": {
    "uk": "",
    "ru": "",
    "en": ""
  },
  "not_available": {
    "uk": "Вибачте цей текст доступний тільки в &ldquo;%LANG:&rdquo;, &ldquo;: і &ldquo;%&rdquo;.",
    "ru": "Извините, этот текст доступен только на &ldquo;%LANG:&rdquo;, &ldquo;:&rdquo; и &ldquo;%&rdquo;.",
    "en": "Sorry, this entry is only available in %LANG:, : and %."
  },
  "date_format": {
    "uk": "%A %B %e%q, %Y",
    "ru": "%A %B %e%q, %Y",
    "en": "%A %B %e%q, %Y"
  },
  "time_format": {
    "uk": "%H:%M",
    "ru": "%H:%M",
    "en": "%I:%M %p"
  },
  "flag": {
    "uk": "ua.png",
    "ru": "ru.png",
    "en": "gb.png"
  },
  "url_mode": "1",
  "use_strftime": 3,
  "filter_options_mode": 0,
  "language_name_case": "1",
  "detect_browser_language": false,
  "hide_untranslated": false,
  "show_displayed_language_prefix": false,
  "show_alternative_content": false,
  "hide_default_language": true,
  "use_secure_cookie": false,
  "header_css_on": true,
  "header_css": ".qtranxs_flag_uk {background-image: url(https://api.bontoy.ua/wp-content/plugins/qtranslate-xt-master/flags/ua.png); background-repeat: no-repeat;}\n.qtranxs_flag_ru {background-image: url(https://api.bontoy.ua/wp-content/plugins/qtranslate-xt-master/flags/ru.png); background-repeat: no-repeat;}\n.qtranxs_flag_en {background-image: url(https://api.bontoy.ua/wp-content/plugins/qtranslate-xt-master/flags/gb.png); background-repeat: no-repeat;}\n",
  "text_field_filters": [],
  "term_name": {
    "Дитячі Конструктори": {
      "uk": "Дитячі Конструктори",
      "ru": "Детские Конструкторы",
      "en": "Constructors"
    },
    "Ігрові фігурки та Набори": {
      "uk": "Ігрові фігурки та Набори",
      "ru": "Игровые фигурки и наборы",
      "en": "Game figures and Sets"
    },
    "Іграшки для малюків": {
      "uk": "Іграшки для малюків",
      "ru": "Игрушки для Малышей",
      "en": "Toys for kids"
    },
    "Брязкальця та Гризуни": {
      "uk": "Брязкальця та Гризуни",
      "ru": "Погремушки и Грызуны",
      "en": "Rattles"
    },
    "Розвиваючі Іграшки": {
      "uk": "Розвиваючі Іграшки",
      "ru": "Развивающие Игрушки",
      "en": "Educational Toys"
    },
    "Світильники": {
      "uk": "Світильники",
      "ru": "Светильники",
      "en": "Lamp"
    },
    "Машинки та Треки": {
      "uk": "Машинки та Треки",
      "ru": "Машинки и Треки",
      "en": "Cars and Tracks"
    },
    "Дівчинка": {
      "uk": "Дівчинка",
      "ru": "Девочка",
      "en": "Girl"
    },
    "Хлопчик": {
      "uk": "Хлопчик",
      "ru": "Мальчик",
      "en": "Boy"
    },
    "Унісекс": {
      "uk": "Унісекс",
      "ru": "Унисекс",
      "en": "Unisex"
    },
    "Від 10 років": {
      "uk": "Від 10 років",
      "ru": "От 10 лет",
      "en": "From 10 years"
    },
    "Від 12 років": {
      "uk": "Від 12 років",
      "ru": "От 12 лет",
      "en": "From 12 years"
    },
    "Від 14 років": {
      "uk": "Від 14 років",
      "ru": "От 14 лет",
      "en": "From 14 years"
    },
    "Від 18 місяців": {
      "uk": "Від 18 місяців",
      "ru": "От 18 месяцев",
      "en": "From 18 months"
    },
    "Від 2 років": {
      "uk": "Від 2 років",
      "ru": "От 2 лет",
      "en": "From 2 years"
    },
    "Від 3 років": {
      "uk": "Від 3 років",
      "ru": "От 3 лет",
      "en": "From 3 years"
    },
    "Від 3 місяців": {
      "uk": "Від 3 місяців",
      "ru": "От 3 месяцев",
      "en": "From 3 months"
    },
    "Від 4 років": {
      "uk": "Від 4 років",
      "ru": "От 4 лет",
      "en": "From 4 years"
    },
    "Від 5 років": {
      "uk": "Від 5 років",
      "ru": "От 5 лет",
      "en": "From 5 years"
    },
    "Від 6 років": {
      "uk": "Від 6 років",
      "ru": "От 6 лет",
      "en": "From 6 years"
    },
    "Від 6 місяців": {
      "uk": "Від 6 місяців",
      "ru": "От 6 месяцев",
      "en": "From 6 months"
    },
    "Від 7 років": {
      "uk": "Від 7 років",
      "ru": "От 7 лет",
      "en": "From 7 years"
    },
    "Від 8 років": {
      "uk": "Від 8 років",
      "ru": "От 8 лет",
      "en": "From 8 years"
    },
    "Від народження": {
      "uk": "Від народження",
      "ru": "С рождения",
      "en": "From birth"
    },
    "Бежевий": {
      "uk": "Бежевий",
      "ru": "Бежевый",
      "en": "Beige"
    },
    "Білий": {
      "uk": "Білий",
      "ru": "Белый",
      "en": "White"
    },
    "Блакитний": {
      "uk": "Блакитний",
      "ru": "Голубой",
      "en": "Blue"
    },
    "Жовтий": {
      "uk": "Жовтий",
      "ru": "Желтый",
      "en": "Yellow"
    },
    "Зелений": {
      "uk": "Зелений",
      "ru": "Зеленый",
      "en": "Green"
    },
    "Коричневий": {
      "uk": "Коричневий",
      "ru": "Коричневый",
      "en": "Brown"
    },
    "Червоний": {
      "uk": "Червоний",
      "ru": "Красный",
      "en": "Red"
    },
    "Помаранчевий": {
      "uk": "Помаранчевий",
      "ru": "Оранжевый",
      "en": "Orange"
    },
    "Різнокольоровий": {
      "uk": "Різнокольоровий",
      "ru": "Разноцветный",
      "en": "Multicolored"
    },
    "Рожевий": {
      "uk": "Рожевий",
      "ru": "Розовый",
      "en": "Pink"
    },
    "Сірий": {
      "uk": "Сірий",
      "ru": "Серый",
      "en": "Grey"
    },
    "Синій": {
      "uk": "Синій",
      "ru": "Синий",
      "en": "Dark blue"
    },
    "Бузковий": {
      "uk": "Бузковий",
      "ru": "Сиреневый",
      "en": "Lilac"
    },
    "Фіолетовий": {
      "uk": "Фіолетовий",
      "ru": "Фиолетовый",
      "en": "Purple"
    },
    "Фуксія": {
      "uk": "Фуксія",
      "ru": "Фуксия",
      "en": "Fuchsia"
    },
    "Чорний": {
      "uk": "Чорний",
      "ru": "Черный",
      "en": "Black"
    },
    "Акція": {
      "uk": "Акція",
      "ru": "Акция",
      "en": "Promotion"
    },
    "Хіт продажу": {
      "uk": "Хіт продажу",
      "ru": "Хит продаж",
      "en": "Bestseller"
    },
    "Новинка": {
      "uk": "Новинка",
      "ru": "Новинка",
      "en": "New"
    },
    "Рюкзаки та Cумки": {
      "uk": "Рюкзаки та Cумки",
      "ru": "Рюкзаки и Cумки",
      "en": "Backpacks and Bags"
    },
    "М'які Іграшки": {
      "uk": "М'які Іграшки",
      "ru": "Мягкие Игрушки",
      "en": "Stuffed Toys"
    },
    "Дитячі Палатки": {
      "uk": "Дитячі Палатки",
      "ru": "Детские палатки",
      "en": "Kids Tents"
    },
    "Дитяча біжутерія": {
      "uk": "Дитяча біжутерія",
      "ru": "Детская бижутерия",
      "en": "Children's jewelry"
    },
    "Дитяча Зброя": {
      "uk": "Дитяча Зброя",
      "ru": "Детское Оружие",
      "en": "Children's Weapons"
    },
    "Малювання": {
      "uk": "Малювання",
      "ru": "Рисование",
      "en": "Painting"
    },
    "Рукоділля": {
      "uk": "Рукоділля",
      "ru": "Рукоделие",
      "en": "Needlework"
    },
    "Настільні Ігри": {
      "uk": "Настільні Ігри",
      "ru": "Настольные игры",
      "en": "Board Games"
    },
    "Пазли": {
      "uk": "Пазли",
      "ru": "Пазлы",
      "en": "Puzzles"
    },
    "Дитяча Косметика": {
      "uk": "Дитяча Косметика",
      "ru": "Детская Косметика",
      "en": "Cosmetic for Girl"
    }
  },
  "disable_client_cookies": false,
  "ignore_file_types": [
    "gif",
    "jpg",
    "jpeg",
    "png",
    "svg",
    "pdf",
    "swf",
    "tif",
    "rar",
    "zip",
    "7z",
    "mpg",
    "divx",
    "mpeg",
    "avi",
    "css",
    "js",
    "mp3",
    "mp4",
    "apk"
  ],
  "url_info": {
    "cookie_lang_front": "uk",
    "cookie_lang_admin": "uk",
    "cookie_front_or_admin_found": true,
    "scheme": "https",
    "host": "api.bontoy.ua",
    "path": "/wp-admin/admin-ajax.php",
    "query": "action=admin_debug_info",
    "path-base": "",
    "wp-path": "/wp-admin/admin-ajax.php",
    "language_neutral_path": true,
    "http_referer": "https://api.bontoy.ua/wp-admin/options-general.php?page=qtranslate-xt",
    "referer_admin": true,
    "doing_front_end": false,
    "lang_cookie_admin": "uk",
    "lang_admin": "uk",
    "language": "uk",
    "set_cookie": false
  },
  "language": "uk",
  "editor_mode": 0,
  "highlight_mode": 1,
  "auto_update_mo": true,
  "hide_lsb_copy_content": false,
  "lsb_style": "Simple_Buttons.css",
  "config_files": [
    "./i18n-config.json"
  ],
  "custom_i18n_config": [],
  "custom_fields": [],
  "custom_field_classes": [],
  "post_type_excluded": [],
  "translator": {},
  "qtrans_compatibility": false
}

Browser

{
  "cookies": [],
  "navigator": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
}

**Comment by spleen1981** [comment]
You could start indicating which fields are you referring to...

**Comment by herrvigg** [comment]
No update so I close this ticket. Re-open if you can provide more relevant data and how to reproduce it.
