### ISSUE TITLE
Feature regression of ACF Module - Standard (non-qTranslate-XT) text fields are always translated.

### ISSUE THREAD

**Issue by filtah** [qtranslate/qtranslate-xt#1282]
Hi guys, firstly thanks for all you work on this project so far.

With the latest update ([3.13.0](https://github.com/qtranslate/qtranslate-xt/releases/tag/3.13.0)), the basic text (and other native fields) are always getting translated.

Previous versions have always had the checkbox to decide if standard fields should be translated, which is OFF by default.

<img width="268" alt="image" src="https://user-images.githubusercontent.com/3319153/216012024-8afaa76d-c979-44c5-943f-eaf12afe0743.png">

Now, as this checkbox has been removed, functionally it is set to ON, which changes the default behaviour and also renders the custom qTranslate-XT fields that get added at the bottom pretty useless.

It is really useful to have the option, because (in our case at least), there are often standard text fields which we don't want to translate for each language.

For example, if we have a field for 'Villa Name', this would remain the same for each language, and we don't want to give the clients the option to change this text for each language.

<img width="254" alt="image" src="https://user-images.githubusercontent.com/3319153/216005926-0c17b7fa-f228-4f6f-85b5-03aae20d6472.png">

Is there a way to revert to the standard OFF position without rolling back to version 3.12.1?

Thanks,
Phil.

**Comment by herrvigg** [comment]
Duplicate #1279, let's keep one ticket.
