### ISSUE TITLE
ACF WYSIWYG only in Text mode after saving post

### ISSUE THREAD

**Issue by dansjirgensons** [qtranslate/qtranslate-xt#1283]
I seem to be having a problem, that once the post has been saved, the WYSIWYG field shows only in Text mode, though Visual and Text buttons are visible, but when clicking either of them it shows Text mode.

Using the (qTranslate-XT) WYSIWYG field.

**Comment by herrvigg** [comment]
I don't manage to reproduce this. Is it for a regular post? Do you see error in the console log?

**Comment by herrvigg** [comment]
No update so I close this ticket. Re-open if you can provide more relevant data and how to reproduce it.
