### ISSUE TITLE
Translation switching flags not appearing when editing in dashboard

### ISSUE THREAD

**Issue by MarkArgent** [qtranslate/qtranslate-xt#1285]
On the wordpress dashboard I have translatable content things edited with wp-admin/user-edit.php and with wp-admin/edit.php. Although the thick blue border indicating translatable content is present in both, the flags to indicate language switching are only visible in things reached by wp-admin/edit.php. How do I enable them also on wp-admin/edit.php?

I'm using  ACF Pro 6.0.7 and qTranslate-XT 3.13.0

**Comment by MarkArgent** [comment]
I've been hunting through the code for the plugin (this one is becoming urgent) and failing to find anything obvious, so any help would be welcome

**Comment by herrvigg** [comment]
Remaining case with user-edit.php discussed in #1287. The case edit.php is solved apparently so I close this.
