### ISSUE TITLE
How can I change only the language code for ISO

### ISSUE THREAD

**Issue by francescocortese** [qtranslate/qtranslate-xt#1289]
I added Korean as a language and I need to change only the language code from kor to ko. How can I change it without loosing all the content already added?
I tried to change in edit part of language but I loose all the content. :/
Thanks.

**Comment by herrvigg** [comment]
Unfortunately there's no such option currently. The content is not lost but it remains with the old tag. You'd have to update the DB manually looking for [kor] tags.
