### ISSUE TITLE
Purpose of qtranslate-xt

### ISSUE THREAD

**Issue by Soldream0** [qtranslate/qtranslate-xt#1295]
The original qtranslate does not currently translate the text and gives different errors depending on the translator. (google - Script service error. yandex - No data (Timed out waiting for data to be sent). )
All the information I found on the Internet about qtranslate was 2012-2016. Of all the new information, I find only your plugin.
Sorry for the possible spam, but could you tell me if your plugin is some kind of update of the original qtranslate?

**Comment by herrvigg** [comment]
You can find all the information in the wiki: https://github.com/qtranslate/qtranslate-xt/wiki.
To my knowledge qTranslate-X was essentially an extension of qTranslate adding the switching buttons to edit multiple languages and other features. I have never seen anything about online translation of content and it would be very surprising if it has been removed when cloned from qTranslate.
