### ISSUE TITLE
Slug with dash (-)

### ISSUE THREAD

**Issue by vonsch76** [qtranslate/qtranslate-xt#1306]
@herrvigg seems that the slugs translation does not work when the category (maybe other as well) has a dash (-) character. So when I had "our-services" then no translation when changed to "services", then the translation went fine. The other slug translations with the dash just work fine.

**Comment by herrvigg** [comment]
Surprising, I don't think we have anything special where this character would be a problem.

@spleen1981 please could you take a look at this?

**Comment by spleen1981** [comment]
Both terms and posts slugs are sanitized before saving with `sanitize_title`, which allows dashes (and it works based on my test).
Also, uniqueness of candidate slug is tested per language, but a suffix should be automatically added in that case.
Is your slug unique per language?

**Comment by vonsch76** [comment]
I also thought weird, still here is the example.

[image: Screenshot from 2023-04-02 15-45-33.png]

[image: Screenshot from 2023-04-02 15-46-42.png]
[image: Screenshot from 2023-04-02 15-46-15.png]

while without the dash
[image: Screenshot from 2023-04-02 15-47-53.png]
[image: Screenshot from 2023-04-02 15-48-18.png]
[image: Screenshot from 2023-04-02 15-48-35.png]

**Comment by spleen1981** [comment]
something is wrong with attached images

**Comment by vonsch76** [comment]
> something is wrong with attached images

originally sent from email, edited here

**Comment by spleen1981** [comment]
I'm confused, "our-services" slug (which is not a category slug but categories base slug) is working or not?
It looks like is working and online.

**Comment by vonsch76** [comment]
Our services - that is a slug from a category - does not work when it has
the dash in it..When changed just to services it works fine.

**Comment by spleen1981** [comment]
What is currently [https://hajoznijo.hu/hu/our-services/](https://hajoznijo.hu/hu/our-services/), which I can see it's working? A separate page?
What happens if instead of `our-services` you use `test-services` as the category slug?

**Comment by vonsch76** [comment]
by surprise test-services also seem to work fine. Seems that I have the conflict elsewhere.

**Comment by spleen1981** [comment]
No surprise, as said above, slug uniqeness is tested before saving, and you already seem to have a page with that slug.
Category slug will also be used for items archive page, so it would be in conflict with existing page.
To use that slug for the category, you should remove the existing page, set the slug for the category and use the resulting archive page to do the same job of current `our-services` page, maybe using templates to have the same result.

I think we can close here anyways.
