### ISSUE TITLE
Erorr translate comment in UA

### ISSUE THREAD

**Issue by sterfri227A** [qtranslate/qtranslate-xt#1310]
Gives out incomprehensible characters when I switch to ua in comments. The month does not translate correctly, how to decide?
 �����

**Comment by spleen1981** [comment]
Do you mind filling in the "Bug Report" issue template?

**Comment by sterfri227A** [comment]
I described the problem, tell me what to do

**Comment by sterfri227A** [comment]
поддержка говна ;)

**Comment by spleen1981** [comment]
You look to your attitude in this thread and give yourself an explanation...

**Comment by herrvigg** [comment]
I have now enforced the bug or feature templates.

@sterfri227A it is absolutely impossible to understand the error you are reporting. You have to provide MUCH more details. This doesn't even look related to qTranslate but rather character encoding. We don't do any transformation about the encoding so this comes likely from your website or system configuration.
