### ISSUE TITLE
[url.php] php 8 function str_starts_with() used without check

### ISSUE THREAD

**Issue by justinbb** [qtranslate/qtranslate-xt#1334]
**Describe the bug**
str_starts_with() is a new function in php 8. It cannot be used without protection while php 7 is still supported.

New issue in qtranslate-xt 3.15.0. Workaround: revert to 3.14.2 or upgrade php

**Debug info**
`Call to undefined function str_starts_with() in /public_html/wp-content/plugins/qtranslate-xt/src/url.php:288`

**Comment by herrvigg** [comment]
Good catch! Sorry about that. I will sent a hotfix.

**Comment by herrvigg** [comment]
Fixed in master.

This came from one of my recent change in #1324. I thought my editor (PhpStorm) would detect such incompatibilities, but I got fooled by some polyfills (!) bringing this function to a PHP 7.1 environment... so it all looked fine. 😕

**Comment by herrvigg** [comment]
Fix released in 3.15.1.
