### ISSUE TITLE
[Slug translation module] hreflang has wrong value of Locale at front-end

### ISSUE THREAD

**Issue by FLAME007R** [qtranslate/qtranslate-xt#1359]
When Slugs active and "Locale at front-end" have value in Language Editor, hreflang is set "Language Code" and ignore "Locale at front-end". When Slugs deactivated hreflang is set from value of "Locale at front-end". Some small bug. 

1. Go to page wp-admin/options-general.php?page=qtranslate-xt&edit=ua
2. Edit value 'Locale at front-end' to "uk"
3. Click Save
4. Go to page wp-admin/options-general.php?page=qtranslate-xt#integration
5. Slugs translation (activate / deactivate)
6. See in code of page (<link hreflang="uk" if deactivated Slugs, <link hreflang="ua" if activated Slugs )

**Expected behavior**
On all states of Slugs, hreflang have value "Locale at front-end" if is set.
```
qTranslate-XT  3.15.2
```
Thanks =)

**Comment by spleen1981** [comment]
Can you test the [slug_fixes](https://github.com/qtranslate/qtranslate-xt/tree/slugs_fixes) branch?

**Comment by FLAME007R** [comment]
> Can you test the [slug_fixes](https://github.com/qtranslate/qtranslate-xt/tree/slugs_fixes) branch?

Hello.
Im replace strings in slugs.php.
Same issue.

Slugs on.
<link hreflang="ua" href="[http://localhost/faq/](view-source:http://localhost/faq/)" rel="alternate" />
<link hreflang="en" href="[http://localhost/en/faq/](view-source:http://localhost/en/faq/)" rel="alternate" />

Slugs off.
<link hreflang="uk" href="[http://localhost/faq/](view-source:http://localhost/faq/)" rel="alternate" />
<link hreflang="en" href="[http://localhost/en/faq/](view-source:http://localhost/en/faq/)" rel="alternate" />

...
New bug incomming, slugs and incorrect url forward to blog part over 404.

**Comment by spleen1981** [comment]
I just checked and it's working on my test environment:
![image](https://github.com/qtranslate/qtranslate-xt/assets/43221199/9319c7de-c7c2-4e20-b7ba-55f911f66a46)
That `xyz` is the "Locale at front-end" set up for the primary language. Slugs module is now using exactly the same function as QTX to define hreflang, so I don't see how the output can be same as before.
Maybe you need to flush some cache or something.
Also I suggest to avoid replacing strings in the source, just checkout to that branch (or replace the entire plugin content folder with the zip file of that branch, if you are not familiar with git).

The rest of the comment is quite unclear. Make sure you are testing the branch as it is, then if new bug is there please provide more detail.

**Comment by FLAME007R** [comment]
Im re save lang settings, clear cache. It work fine. Thanks.
