### ISSUE TITLE
[Slugs translation] qtranxf_convertURL doesnt translate slug translation urls

### ISSUE THREAD

**Issue by salt-istanbul** [qtranslate/qtranslate-xt#1366]
qtranxf_convertURL function does not translate URLs that use Slugs translation. 
Translated slugs in urls are coming in currently selected language.
How can we translate such URLs to another languages?

**Comment by spleen1981** [comment]
You can use `qtranxf_slugs_get_url( $lang )` to get current url translated

**Comment by spleen1981** [comment]
I guess the reply given covers the issue, closing this.
