### ISSUE TITLE
crash with Classic editor 

### ISSUE THREAD

**Issue by raeuske** [qtranslate/qtranslate-xt#1379]
Hi .. i seriously need help .. still haven't heard from anyone from my last post. 

I uploaded the developer version from here already. But the problem still exists. 

Do not want to use Gutenberg as it's not the block design with wpbakery page builder. I also have the WPBakery Visual Composer & qTranslate-X plugin on the website. 

Much appreciated if someone can help me

<img width="1283" alt="Screenshot 2023-09-16 at 11 33 36 PM" src="https://github.com/qtranslate/qtranslate-xt/assets/145250760/68c8efb1-dd5b-44f9-bfc1-49c66e31e610">

<img width="1251" alt="Screenshot 2023-09-16 at 11 58 49 PM" src="https://github.com/qtranslate/qtranslate-xt/assets/145250760/c58c94cd-7dd5-4cc5-87b7-8c31a3b369fb">

**Comment by herrvigg** [comment]
Duplicate #1374. Please keep a single ticket open, this creates only confusion. I close this one.
