### ISSUE TITLE
Can't use wp-admin due to a typo in code

### ISSUE THREAD

**Issue by asbestomolesto** [qtranslate/qtranslate-xt#1385]
**Describe the bug**
I can't enter the wp-admin section, i got this error

Fatal error: Uncaught Error: Undefined constant "QTX_EDITOR_MODE_SINGLGE" in /var/www/html/museo.freaknet.org/wp-content/plugins/wp-seo-qtranslate-x/wordpress-seo-qtranslate-x.php:26 

**To Reproduce**

just try to go to the admin page of your wordpress

**Expected behavior**

it must work

**Screenshots**
none

**Debug info**

**Additional context**

I just edited [dir]/wp-content/plugins/wp-seo-qtranslate-x/wordpress-seo-qtranslate-x.php at line 26 and corrected "SINGLGE" into "SINGLE"

and it worked.

**Comment by herrvigg** [comment]
This plugin https://github.com/qTranslate-Team/wp-seo-qtranslate-x has been abandoned for many years, it's an old integration plugin for the old qTranslate-X. In our repo, which is qTranslate-XT we have replaced this plugin with modules.

Moreover, this looks like a local issue on your website, as the last version has not the wrong string you're referring to:
https://github.com/qTranslate-Team/wp-seo-qtranslate-x/blob/master/wordpress-seo-qtranslate-x.php

Please read our README and update to qTranslate-XT to get the correct updates.
