### ISSUE TITLE
Compatibility with Divi theme in Elegant themes 

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#203]
<a href="https://github.com/dingzj"><img src="https://avatars1.githubusercontent.com/u/865551?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dingzj](https://github.com/dingzj)**
_Thursday Jul 30, 2015 at 05:27 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/203_

----

Had issues when using Divi them and qtranslate-x
The title of a page can have 2+ languages, but the content seems only have one language version.

Any ways to fix it?

![image](https://cloud.githubusercontent.com/assets/865551/8976365/e907fa66-3659-11e5-922d-75018aad9cbc.png)

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Sunday Aug 02, 2015 at 16:46 GMT_

----

We do not have Divi Builder. It should be possible to integrate: https://qtranslatexteam.wordpress.com/integration/?

**Comment by herrvigg** [comment]
<a href="https://github.com/dingzj"><img src="https://avatars1.githubusercontent.com/u/865551?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dingzj](https://github.com/dingzj)**
_Monday Aug 03, 2015 at 22:45 GMT_

----

Thanks, I used the work around way: enable Single Language Edit mode.

Then I found a bug, `setTinyMceInit()` is not defined. Which coming from admin/js/common.min.js file, the first occurrence of this function call needs definition. 

Copied a later definition of this call along with a function called  `n`  will solve the problem.

Thanks.

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Saturday Aug 08, 2015 at 03:30 GMT_

----

Which browser is that? I wonder why other people did not have this problem. Could you describe more accurately which lines need to be moved where in file `admin/js/common.js` (non-minimized version)?
Thanks a lot, @dingzj !

**Comment by herrvigg** [comment]
<a href="https://github.com/dingzj"><img src="https://avatars1.githubusercontent.com/u/865551?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dingzj](https://github.com/dingzj)**
_Saturday Aug 08, 2015 at 04:21 GMT_

----

I am using Chrome, Version 44.0.2403.125 (64-bit) on Mac.
Here is a screen short. 
![image](https://cloud.githubusercontent.com/assets/865551/9148989/8e98abd4-3d61-11e5-9ef4-0533fd50fe99.png)

The reason is weird. I am not sure this is the issue in `common.js` file, but it's most likely an issue in `common.min.js` file. Just double check a few minutes ago, after fixing the `common.min.js`, the error is gone.

My fixing strategy to `common.min.js` is simple, use a standard js formatter to convert it properly so I can see it btter, and then find the first occurrence of `setTinyMceInit ()`, and then copied its definition from the 2nd occurrence of `setTinyMceInit()` and `n()` before first occurrence, it solved the problem.

To answer your question directly, assuming `common.min.js` is mapping properly to `common.js`, it means:
- copy Line 887 to Line 915 of file `https://github.com/qTranslate-Team/qtranslate-x/blob/master/admin/js/common.js` before Line 703. 
- the function `n()` in `common.min.js` seems mapping to `setEditorHooks()` in `common.js`, so need to copy `setEditorHooks()` before Line 703 too, since `setTinyMceInit()` is using `setEditorHooks()` internally.

**Comment by herrvigg** [comment]
<a href="https://github.com/esiao"><img src="https://avatars3.githubusercontent.com/u/1942801?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [esiao](https://github.com/esiao)**
_Sunday Aug 23, 2015 at 14:02 GMT_

----

Had the same issue, thanks to @dingzj it's solved. I just had to copy the definition of `setTinyMceInit ()` before it was used further down, same for `setEditorHooks()` used in the content.
Actually edited directly common.js that I minified after.

**Comment by herrvigg** [comment]
<a href="https://github.com/mchan7"><img src="https://avatars2.githubusercontent.com/u/14123454?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mchan7](https://github.com/mchan7)**
_Friday Sep 04, 2015 at 08:56 GMT_

----

Hi @dingzj,
I also experience the same problem in Divi Theme.
I have no experience in js script.
Is it possible for you to send me the fixed js files?

Many thanks.

**Comment by herrvigg** [comment]
<a href="https://github.com/dingzj"><img src="https://avatars1.githubusercontent.com/u/865551?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dingzj](https://github.com/dingzj)**
_Friday Sep 04, 2015 at 14:09 GMT_

----

@mchan7 see this gist file: https://gist.github.com/dingzj/74a4803b9c667248e208

**Comment by herrvigg** [comment]
<a href="https://github.com/mchan7"><img src="https://avatars2.githubusercontent.com/u/14123454?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mchan7](https://github.com/mchan7)**
_Friday Sep 04, 2015 at 14:40 GMT_

----

@dingzj,

Got it. Many Thanks.

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Saturday Sep 19, 2015 at 01:15 GMT_

----

`setTinyMceInit()` problem should be fixed under the latest version from GitHub: https://github.com/qTranslate-Team/qtranslate-x/issues/247. Could you please test it?
Thanks a lot.

Is the original problem with Divi theme still a problem?

**Comment by herrvigg** [comment]
<a href="https://github.com/fulviods"><img src="https://avatars1.githubusercontent.com/u/736198?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fulviods](https://github.com/fulviods)**
_Friday Nov 13, 2015 at 15:31 GMT_

----

I'm on the last version of divi and on qtranslate-x 3.4.6.4 and it doesnt work. 
I didnt edit any js file...

here is my workaround.
In fact when i edit a page you have the 2 flags/language on top. For example english and french. If editing the page "english" is activated you'll be able to edit the english content and save the page.
If you want to edit the second language you just select it and you reload/refresh the page....and the second language content will be there.

Do I have to follow the instructions mentionned here?

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Friday Nov 13, 2015 at 17:21 GMT_

----

This sounds like manual use of "Single Language Mode", a choice of option "Editor Mode" on page /wp-admin/options-general.php?page=qtranslate-x#advanced. I am glad this works, which means that all fields that need to be multilingual are already multilingual, but they do not respond to Language Switching Buttons (LSB).

Somebody needs to [integrate](https://qtranslatexteam.wordpress.com/integration/) the theme properly, since apparently it is not that hard, as @dingzj  already figured out the script needed for that.

However, It needs to be implemented, using interface functions, something like it is done in plugin [WPBakery Visual Composer & qTranslate-X](https://wordpress.org/plugins/js-composer-qtranslate-x). I believe that this can be now done with .json file only, without a necessity to create a new integrating plugin. I would appreciate if somebody get busy with this, I can help answering questions if needed.

**Comment by herrvigg** [comment]
<a href="https://github.com/fulviods"><img src="https://avatars1.githubusercontent.com/u/736198?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fulviods](https://github.com/fulviods)**
_Friday Nov 13, 2015 at 17:49 GMT_

----

No i did not choose Single language mode. My website is witht the first option "use buttons" (i have the options in french because my website is in french

But I have to reload the page each time I want to change the language, if not i loose the content....
Hope there is a workaround  soon

Thanks

**Comment by herrvigg** [comment]
<a href="https://github.com/ivanperez-keera"><img src="https://avatars0.githubusercontent.com/u/1162320?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ivanperez-keera](https://github.com/ivanperez-keera)**
_Thursday Aug 18, 2016 at 08:24 GMT_

----

Hi. What is the status of this? Is it now solved?

**Comment by sevontheedge** [comment]
Hello @herrvigg , I need to use both Divi and qTranslate-xt to a very important project of mine, I am willing to try integrating the plugins. Since I am kind new to the WordPress framework would you mind telling me the guidelines to do this? Thanks for your response

**Comment by herrvigg** [comment]
Old issue but certainly not solved for Divi yet. See #769 for more recent updates.
