### ISSUE TITLE
the_content output - all spaces replaced with &nbsp;

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#246]
<a href="https://github.com/SteveHoneyNZ"><img src="https://avatars1.githubusercontent.com/u/7669892?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SteveHoneyNZ](https://github.com/SteveHoneyNZ)**
_Sunday Sep 06, 2015 at 08:08 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/246_

----

Using latest versions of everything, no other plugins that should be inteferring with content filters generally.

If you check out [this URL](http://ofekroncarmel.com/he/%D7%94/) you can see every space within the content is is replaced with `&nbsp;`

Checking in DB the content isn't being stored like this. I tried just out of desperation the below but makes no difference:

```
add_filter( 'the_content', 'content_spaces', 99 );

function content_spaces( $content ){

    $content = str_replace( "&nbsp;", " ", $content );

    return $content;

}
```

Not at all familiar with hebrew characters in UTF8 etc so any pointers greatfully received, quite time sensitive now...
Cheers

Update:
I've also just realised it does the same with the 'hebrew' translation of [this page](http://ofekroncarmel.com/he/about/) even though it's just a copy of the english all in latin characters, but not the english, so unlikely to be related to the hebrew characters specifically...

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Monday Oct 05, 2015 at 04:35 GMT_

----

How is that related to qtx? If you turn qtx off, it probably still do it? It is somewhere in your theme, I guess.

**Comment by axodjakov** [comment]
This is not related to qTranslate. I disabled the plugin but the problem persisted.

**Comment by herrvigg** [comment]
ok i close this, it's something else than qTranslate interfering with the content.
