### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#350]
<a href="https://github.com/eriksvec"><img src="https://avatars3.githubusercontent.com/u/17217188?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eriksvec](https://github.com/eriksvec)**
_Saturday Feb 13, 2016 at 12:38 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/350_

----

Hi, 
I installed qTranslate X plugin. Then I tried to set it up accordingly to your manual:
https://qtranslatexteam.wordpress.com/startup-guide/

Now my website is completely messed up and I can't fix it even after disabling your plugin. Can you please help me to fix it? I have no idea what is wrong.
http://test.eriksvec.com/?lang=en

thank you
Erik

**Comment by herrvigg** [comment]
<a href="https://github.com/eriksvec"><img src="https://avatars3.githubusercontent.com/u/17217188?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eriksvec](https://github.com/eriksvec)**
_Saturday Feb 13, 2016 at 12:47 GMT_

----

Now I checked:
Use Pre-Path Mode (Default, puts /en/ in front of URL). SEO friendly.
And the site isn't working absolutely

**Comment by herrvigg** [comment]
<a href="https://github.com/eriksvec"><img src="https://avatars3.githubusercontent.com/u/17217188?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eriksvec](https://github.com/eriksvec)**
_Saturday Feb 13, 2016 at 13:02 GMT_

----

Your plugin is exactly what I am looking for. I don't like the idea of creating duplicates for each language. But I would really appreciate if you'll help me with this problem :-)

**Comment by herrvigg** [comment]
<a href="https://github.com/ghost"><img src="https://avatars3.githubusercontent.com/u/10137?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ghost](https://github.com/ghost)**
_Saturday Feb 13, 2016 at 13:24 GMT_

----

Hey eriksvec,

Why is the option at http://http://test.eriksvec.com/wp-admin/options-permalink.php looks not set into _Post name_?

**Comment by herrvigg** [comment]
<a href="https://github.com/eriksvec"><img src="https://avatars3.githubusercontent.com/u/17217188?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eriksvec](https://github.com/eriksvec)**
_Saturday Feb 13, 2016 at 13:41 GMT_

----

In Settings - Permalinks
I have checked:
Post name   http://test.eriksvec.com/sample-post/

In Languages - General
I have checked:

Use Pre-Path Mode (Default, puts /en/ in front of URL). SEO friendly.
Show displayed language prefix when content is not available for the selected language.
Detect the language of the browser and redirect accordingly.

**Comment by herrvigg** [comment]
<a href="https://github.com/ghost"><img src="https://avatars3.githubusercontent.com/u/10137?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ghost](https://github.com/ghost)**
_Saturday Feb 13, 2016 at 13:48 GMT_

----

Hmm the default page http://test.eriksvec.com/sample-post/ even doesn't work. Maybe you would like to go to http://qtranslate-x.com/support/ and ask the plugin owner

**Comment by knyttl** [comment]
have you solved the problem? I am having the same issue.
