### ISSUE TITLE
500 internal server error when activate q translate plugin 

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#451]
<a href="https://github.com/Farrukhzaman"><img src="https://avatars1.githubusercontent.com/u/14215030?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Farrukhzaman](https://github.com/Farrukhzaman)**
_Wednesday Nov 02, 2016 at 09:01 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/451_

----

Why my website given 500 internal server error when i activate qtranslate-x plugin?

**Comment by herrvigg** [comment]
<a href="https://github.com/ToeiRei"><img src="https://avatars3.githubusercontent.com/u/5990591?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ToeiRei](https://github.com/ToeiRei)**
_Wednesday Jan 11, 2017 at 18:05 GMT_

----

Is there anything in your php error log?
Looks like you're running nginx or at least some fpm...

**Comment by happybrain-developers** [comment]
Hi, 
we are experiencing this problem also with the latest version of the plugin. 
It happens to us in some cases as soon as we do core updates.
Unfortunately on a specific site it happens even after 30 minutes
The only way we have found to solve is to change the permissions of the htaccess file but, after some updates, now the hosting provider does not allow us to set the file permissions in this way
Does anyone know how we could solve?

**Comment by herrvigg** [comment]
This is a far too generic issue, impossible to resolve without more information from your side. A web developer has to dig more in deep, here some of the actions you can take to understand better: https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting.

**Comment by herrvigg** [comment]
@happybrain-developers what you are mentioning about htaccess and core updates makes it pretty clear it is not due to qTranslate. We don't touch this file so the cause is external, though it may crash after a call in qTranslate if the code uses a WP function that could trigger this error.

Since it is a too generic issue, i close it. Please check the wiki and send a precise issue if there is something really due to qTranslate.
