### ISSUE TITLE
Cookie qtrans_admin_language

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#467]
<a href="https://github.com/Rbcafe"><img src="https://avatars3.githubusercontent.com/u/2713634?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Rbcafe](https://github.com/Rbcafe)**
_Wednesday Dec 28, 2016 at 08:09 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/467_

----

Greetings,

Apparently the Cookie "qtrans_admin_language" is created without the **httponly flag**.

More information : https://www.owasp.org/index.php/HttpOnly

Best regards
@rbcafe

**Comment by yucolabjames** [comment]
Looking forward to a resolution of this item. Running security audit in Nikto v2.1.6 reveals the following:

```
+ Cookie qtrans_admin_language created without the secure flag
+ Cookie qtrans_admin_language created without the httponly flag
```

**Comment by herrvigg** [comment]
Indeed for the admin cookies these flags are always left to default, i.e. `false`.

Recently a user asked for the `secure` flag for the front cookie: https://github.com/qtranslate/qtranslate-xt/issues/644. But this option already exists. 

I didn't even know about this `httponly` flag. It should not be a big deal to add this.
Now would it make sense to share these options for both front and admin cookies? I'd like to avoid having too many options. I can't see a case where you would want different options between admin and front cookies. What do you think?

**Comment by herrvigg** [comment]
Currently the secure flag is assigned to the front options so this would require a bit more work to reorganize the options. 

The biggest risk is for the admin cookie and the `secure` flag. My fear is that If you set it unintentionally and you don't have a secure connection you might be screwed. This would require some tests to see how it behaves.

**Comment by herrvigg** [comment]
@yucolabjames @Rbcafe i have now pushed a fix for both **httponly** and **secure** flags, concerning the `qtrans_admin_language` cookie. So this part should be entirely solved... finally! 😄 

Sorry for having delayed that so much, but it's only recently that many things have been cleaned up with all this cookie mess. See all the recent commits in master.

About the future of the **secure** option, more discussion follows in https://github.com/qtranslate/qtranslate-xt/issues/742.
