### ISSUE TITLE
Locale for Ukraine

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#487]
<a href="https://github.com/soxepo"><img src="https://avatars2.githubusercontent.com/u/15784554?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [soxepo](https://github.com/soxepo)**
_Wednesday Feb 15, 2017 at 08:09 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/487_

----

Change default locale for Ukraine language to the -  uk_UA  - and for Locale at front-end to the - uk-ua

**Comment by herrvigg** [comment]
<a href="https://github.com/VaLeXaR"><img src="https://avatars0.githubusercontent.com/u/11210374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [VaLeXaR](https://github.com/VaLeXaR)**
_Wednesday Feb 15, 2017 at 11:01 GMT_

----

Locale for ukrainian language in Wordpress is 'uk'. If you change it, you localisation will be in english. I am not recommending to change your localisation prefix.

**Comment by herrvigg** [comment]
<a href="https://github.com/soxepo"><img src="https://avatars2.githubusercontent.com/u/15784554?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [soxepo](https://github.com/soxepo)**
_Wednesday Feb 15, 2017 at 11:08 GMT_

----

hmmm ! When we try to open blog page with date on hosting in Ukraine we have sum bags in names of month - but when we change locale to the uk_UA we have good translate and correct work

And we have some errors from google analytics about hreflang in Ukraine

**Comment by herrvigg** [comment]
<a href="https://github.com/VaLeXaR"><img src="https://avatars0.githubusercontent.com/u/11210374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [VaLeXaR](https://github.com/VaLeXaR)**
_Wednesday Feb 15, 2017 at 11:14 GMT_

----

The problem not in qTranslate. Default locale in Wordpress for Ukrainian language is "uk". Not "uk_UA".

**Comment by herrvigg** [comment]
<a href="https://github.com/soxepo"><img src="https://avatars2.githubusercontent.com/u/15784554?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [soxepo](https://github.com/soxepo)**
_Wednesday Feb 15, 2017 at 11:16 GMT_

----

When we change this - its works ))
WP the latest version

**Comment by herrvigg** [comment]
<a href="https://github.com/soxepo"><img src="https://avatars2.githubusercontent.com/u/15784554?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [soxepo](https://github.com/soxepo)**
_Wednesday Feb 15, 2017 at 11:16 GMT_

----

i don't now why but its true

**Comment by Komarovski** [comment]
> [<img alt="" width="48" height="48" src="https://avatars2.githubusercontent.com/u/15784554?v=4">](https://github.com/soxepo) **Comment by [soxepo](https://github.com/soxepo)** _Wednesday Feb 15, 2017 at 11:08 GMT_
> 
> hmmm ! When we try to open blog page with date on hosting in Ukraine we have sum bags in names of month - but when we change locale to the uk_UA we have good translate and correct work
> 
> And we have some errors from google analytics about hreflang in Ukraine

I had same issue with date names but in both russian and ukrainian localizations, I think the problem in converting cyrillic symbols, not in localization. Add this filters to your `functions.php` file, to fix it:

`
remove_filter('get_the_time', 'qtranxf_timeFromPostForCurrentLanguage',0,3);
remove_filter('get_the_date', 'qtranxf_dateFromPostForCurrentLanguage',0,3);
remove_filter('get_the_modified_date', 'qtranxf_dateModifiedFromPostForCurrentLanguage',0,2);
`
