### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#494]
<a href="https://github.com/ngopee"><img src="https://avatars1.githubusercontent.com/u/9159446?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ngopee](https://github.com/ngopee)**
_Sunday Mar 12, 2017 at 09:03 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/494_

----

I have having problem with my .htaccess. So, following previous issues I fixed:

(1)
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /ar/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /ar/index.php [L]
</IfModule>

```
to
(2)
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
```

However, once in a while the .htaccess is overwritten again from (2) to (1) and cause the internal server error again. What should I do to prevent this?

Wordpress version: version 4.7.3
qTranslate Version: 3.4.6.8

**Comment by herrvigg** [comment]
<a href="https://github.com/fabri-imk"><img src="https://avatars1.githubusercontent.com/u/4408401?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fabri-imk](https://github.com/fabri-imk)**
_Tuesday Jul 25, 2017 at 16:55 GMT_

----

Wordpress automatically changes the htaccess to include the $ home_root subdirectory, maybe with the qtranslate redirect causing the infinite loop.

the same happened to me, I have solved avoiding that wordpress change the htaccess,

In the functions.php

add_filter ('flush_rewrite_rules_hard', function () {
return false;
});

Or possibly can be made better by using the filters

apply_filters ('mod_rewrite_rules', $ rules);

or 
apply_filters ('rewrite_rules', $ rules);

And preventing it from adding the active languages in the htaccess rules

**Comment by herrvigg** [comment]
@happybrain-developers could this be the problem you mentioned with htaccess in #451?

**Comment by happybrain-developers** [comment]
Yes! It is.
