### ISSUE TITLE
Hey everyone are you still using q-translate-x ?

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#524]
<a href="https://github.com/floopyzicer"><img src="https://avatars0.githubusercontent.com/u/14939541?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [floopyzicer](https://github.com/floopyzicer)**
_Friday Jul 21, 2017 at 11:26 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/524_

----

Since John is unable to find time to work on this plugin for couple of months is there any other plugin that offers migration from q-translate-x to it? 
I just updated to latest wordpress jetpack context widget etc on one of my sites and everything seems to work perfectly.

**Comment by herrvigg** [comment]
<a href="https://github.com/Blackbam"><img src="https://avatars1.githubusercontent.com/u/1703552?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Blackbam](https://github.com/Blackbam)**
_Sunday Sep 03, 2017 at 13:39 GMT_

----

Hey there I am still using it as I prefer it 10 times more than WPML. However development seems to be stuck. Can anybody tell me about the future and if it will be compatible with WordPress 5 ?

**Comment by herrvigg** [comment]
<a href="https://github.com/glenndavey83"><img src="https://avatars3.githubusercontent.com/u/6992344?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [glenndavey83](https://github.com/glenndavey83)**
_Thursday Oct 05, 2017 at 23:39 GMT_

----

We are using it for a client's site, and we've persisted with making it work due to all its features and the style of translation it offers. But we've just run into a problem adding a new language and all the Menu labels are missing, etc. We can probably go through and fix it all up manually, but to come here and find that the developer is AWOL is really disturbing. I guess some people just don't understand the responsibility they have to a community when you offer a plugin, it's not just a fun hobby -- businesses will be affected.

That's why if you're the developer of this plugin, you MUST open it up for other admins to come on board and manage its development. You can't be selfish and keep yourself as the only admin. 

Let this plugin be developed by a group of people, so it can continue to live.

**Comment by herrvigg** [comment]
@floopyzicer @Blackbam @glenndavey83 i don't know if this is still actual but qTranslate-X has been abandoned. We have been reviving it with qTranslate-XT, you're welcome to give it a try.

**Comment by Blackbam** [comment]
@herrvigg Still using qTranslateX in some old projects but to scared to use it in new projects currently. Would greatly appreciate if you continue it and would also report bugs. Maybe even help fixing them!

**Comment by herrvigg** [comment]
We are here in qTranslate-XT (note i duplicated the original issue from qTranslate-X for traceability). Many bugs are already fixed compared to the legacy repo plus new features.  No one has control over qTranslate-X as its author disappeared. I can guarantee you the migration is safe, as the full compatibility is kept even by sharing the options so far (it might change in the future). Check the [README.md](https://github.com/qtranslate/qtranslate-xt/blob/master/README.md) for more detailed info.

**Comment by Blackbam** [comment]
@herrvigg Thats awesome that you want to continue it! I will report any bugs I may encounter and event help with fixes. Did not find qTranslateXT in the WordPress Plugin repository yet. Will you publish it officially?

**Comment by herrvigg** [comment]
Hehe thanks. But not too many bug reports please, the backlog is already huge 😝 

Yes it will hopefully become a new official plugin one day. The problem is that qTranslate-X is frozen and no one knows what happened to its author. This fork is a transitory state to move forward patiently with all the legacy code and users, without breaking too much compatibility. We still need more significant changes before we can deliver it as a new plugin but we're on good track now. Slowly but surely.
