### ISSUE TITLE
Gutenberg Support

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#555]
<a href="https://github.com/rogerburkhard"><img src="https://avatars3.githubusercontent.com/u/642677?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rogerburkhard](https://github.com/rogerburkhard)**
_Wednesday Nov 22, 2017 at 16:13 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/555_

----

With WP 5.0. WordPress plans to change to the Gutenberg Editor. Today I tested some pages where I used Q-Translate-X with the Gutenberg Plugin and unfortunately I couldn’t even switch the language or save any content in the Backend. Are you planning to add support for Gutenberg or not? If not it would be good to have alternatives. Thanks a lot!

**Comment by herrvigg** [comment]
<a href="https://github.com/mrfoxtalbot"><img src="https://avatars3.githubusercontent.com/u/4452464?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mrfoxtalbot](https://github.com/mrfoxtalbot)**
_Wednesday Nov 22, 2017 at 21:45 GMT_

----

I´m not sure this will fix your problem with Gutenberg, but you can try changing the language interface in:  Settings > Languages > Advanced > Editor Mode and choose "Single Language Mode"
www.yoursite.com/wp-admin/options-general.php?page=qtranslate-x#option_editor_mode

**Comment by herrvigg** [comment]
<a href="https://github.com/mrfoxtalbot"><img src="https://avatars3.githubusercontent.com/u/4452464?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mrfoxtalbot](https://github.com/mrfoxtalbot)**
_Wednesday Nov 22, 2017 at 22:18 GMT_

----

Follow up comment: I tried it and it does not work, Guteberg gets rid of qTranslate-X´s shortcodes :(

**Comment by herrvigg** [comment]
<a href="https://github.com/rogerburkhard"><img src="https://avatars3.githubusercontent.com/u/642677?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rogerburkhard](https://github.com/rogerburkhard)**
_Thursday Nov 23, 2017 at 08:09 GMT_

----

Thanks a lot for looking into this. Currently I have a lot of problems with many different Plugins + Gutenberg, so I really hope they add the possibility to opt out of Gutenberg.

**Comment by herrvigg** [comment]
<a href="https://github.com/X-Raym"><img src="https://avatars1.githubusercontent.com/u/7224315?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [X-Raym](https://github.com/X-Raym)**
_Tuesday Dec 05, 2017 at 11:28 GMT_

----

+1 for Gutenberg support ! 👍
Currently, the edit page is completely messed up if you edit with Guteberg (v1.8) and I think some things have to be done from qTranslate side to make it work (but I don't know the details about how Gutenberg plan to be backward compatible with some older features).
But I understand that this could be a very difficult task, and for those who want to use Gutenberg, I'm afraid they will have to change their translation plugin... or to deactivate Gutenberg (I'm sure they're will be a way, plugin or whatever).

**Comment by herrvigg** [comment]
<a href="https://github.com/k9t9"><img src="https://avatars0.githubusercontent.com/u/23067654?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [k9t9](https://github.com/k9t9)**
_Saturday Jan 20, 2018 at 04:35 GMT_

----

@X-Raym 

> and for those who want to use Gutenberg, I'm afraid they will have to change their translation plugin..or to deactivate Gutenberg 

This is not really a long term solution. If WP really will migrate to Gutenberg as a permanent editor - all the plugins will have to adapt - or die .

**Comment by herrvigg** [comment]
<a href="https://github.com/colinloretz"><img src="https://avatars1.githubusercontent.com/u/36084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [colinloretz](https://github.com/colinloretz)**
_Sunday Mar 25, 2018 at 20:42 GMT_

----

@k9t9 WordPress intends to have Gutenberg shipped as the standard editor in WP version 5.0 with an optional plugin that can disable it.

**Comment by herrvigg** [comment]
<a href="https://github.com/k9t9"><img src="https://avatars0.githubusercontent.com/u/23067654?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [k9t9](https://github.com/k9t9)**
_Tuesday Mar 27, 2018 at 05:19 GMT_

----

@colinloretz - that was exactly my point.

**Comment by herrvigg** [comment]
<a href="https://github.com/rogerburkhard"><img src="https://avatars3.githubusercontent.com/u/642677?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rogerburkhard](https://github.com/rogerburkhard)**
_Tuesday Mar 27, 2018 at 07:01 GMT_

----

I think a short Term Solution is the Classic Editor Plugin to deactivate Gutenberg. Long term I think I will switch to Polylang as I made some tests with WPML and Polylang.

**Comment by herrvigg** [comment]
<a href="https://github.com/colinloretz"><img src="https://avatars1.githubusercontent.com/u/36084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [colinloretz](https://github.com/colinloretz)**
_Tuesday Mar 27, 2018 at 15:47 GMT_

----

I'm working on adding QTranslate to Gutenberg, it is necessary for our site to stay up to date with what comes standard in WordPress instead of opting out of the new editor.

**Comment by herrvigg** [comment]
<a href="https://github.com/marciomarim"><img src="https://avatars1.githubusercontent.com/u/6030177?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marciomarim](https://github.com/marciomarim)**
_Friday May 18, 2018 at 23:10 GMT_

----

I would really appreciate if QtranslateX could work with Gutenberg! I have many websites running multilanguage with Qtranslate X, and migrate all of them to another plugin would be really painfull... Any updates?

**Comment by herrvigg** [comment]
This is definitely going to be the biggest task for the survival of this plugin. Hopefully the classic editor can still be used for a while but we need a plan for Gutenberg. I started only recently to begin reading about it. The main task is to handle all the transformations done in TinyMCE, first of all for the post edition: when reading the post (selection for the active language) and then when posting it back to the DB (recompose the multi-block stuff). I have zero idea yet how it can be done with Gutenberg but i hope there is a solution. So any help is much welcome!

**Comment by rinurinu** [comment]
Is there maybe a solution to introduce the language switcher to the tiniest input element in gutenberg? i.e. the Text box of the respective block where you insert the text? It probably has to be done in React directly?

I'm sorry I can't help with better suggestions.

**Comment by emyawasap** [comment]
Hi I think this post can somehow lessen your worries for `Gutenberg`

It explains actually how to disable Gutenberg and go back to Classic Wordpress layout.
https://digwp.com/2018/04/how-to-disable-gutenberg/

**Comment by emyawasap** [comment]
Works for me.. 

![image](https://user-images.githubusercontent.com/11808545/43939429-ba147dae-9c9c-11e8-8183-c42095184c52.png)

**Comment by herrvigg** [comment]
Aha yes this could just give a bit of time but we need a plan for Gutenberg ;) 

@colinloretz told me he will begin to look at it but we should start gather technical info about it. 

I really don't know about how the Gutenberg blocks work yet it but just at first sight it seems possible to have some callbacks on load and save, so that's the most important!

https://wordpress.org/gutenberg/handbook/block-api/

However i know that Gutebenger performs some hard checks on the HTML, and qTranslate doesn't save valid HTML so with the current data format we'd also need to turn this check off. The other options would be to change the internal format to comply but that's another story.

At the same time we have to retro-engineer the JS part of qTranslate-X to understand how to plug the new stuff in, there will be some work there! It's mainly done in `admin/js/common.js`.

**Comment by herrvigg** [comment]
Oops, about the Gutenberg API i wanted to mention rather this page:

https://wordpress.org/gutenberg/handbook/block-api/block-edit-save/

**Comment by herrvigg** [comment]
Closed for now, for investigations with Gutenberg see https://github.com/qtranslate/qtranslate-xt/issues/605.
