### ISSUE TITLE
Any sign of John Clause?

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#579]
<a href="https://github.com/herrvigg"><img src="https://avatars2.githubusercontent.com/u/19155375?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [herrvigg](https://github.com/herrvigg)**
_Wednesday Mar 21, 2018 at 14:07 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/579_

----

It seems the qTranslate-Team is only 1 person and the author: @johnclause. Can you read us?

See also: https://github.com/qTranslate-Team/qtranslate-x/issues/476, https://github.com/qTranslate-Team/qtranslate-x/issues/538. He has not replied or given any sign of life for more than 1 year. I wondered if he even was alive but there is a short activity in dec 2017. So what is going on with this plugin? Is there someone who can get in touch with him?

It would be really great if we could know his intentions about this plugin which is very popular. If no answer this community should have enough good developers to make the plugin live from a fork or whatever as long as it follows the GNU GPL license. There has been some dicussions (see tickets mentioned above) but nothing is really moving to a clear direction.

Any other suggestion?

**Comment by herrvigg** [comment]
<a href="https://github.com/colinloretz"><img src="https://avatars1.githubusercontent.com/u/36084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [colinloretz](https://github.com/colinloretz)**
_Sunday Mar 25, 2018 at 20:39 GMT_

----

I've been thinking about adopting this and setting it up as a new version/plugin that supports all of the features qTranslate-X has now. I'd also like to recruit some others to make sure that this doesn't happen in the future. I use this plugin on a pretty well trafficked site and I've been making my own modifications to it over time to make sure it works for us.

**Comment by herrvigg** [comment]
<a href="https://github.com/picasso"><img src="https://avatars1.githubusercontent.com/u/399395?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [picasso](https://github.com/picasso)**
_Monday Mar 26, 2018 at 12:15 GMT_

----

Good idea, Colin!
I'm also ready to share my own modifications to this plugin.

**Comment by herrvigg** [comment]
<a href="https://github.com/mutantspy"><img src="https://avatars1.githubusercontent.com/u/37793022?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mutantspy](https://github.com/mutantspy)**
_Wednesday Mar 28, 2018 at 05:01 GMT_

----

Yeah, it would be good but are we allowed to launch our own version of the plugin?

**Comment by herrvigg** [comment]
<a href="https://github.com/herrvigg"><img src="https://avatars2.githubusercontent.com/u/19155375?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [herrvigg](https://github.com/herrvigg)**
_Wednesday Mar 28, 2018 at 07:51 GMT_

----

Would you fork the current project or start a new project from scratch?
In the first case, it would be good to carry the current state with all issues and PRs. It could take a bit of time to review them but i guess it's worth. For instance there are already some big refactoring PRs and you keep all the history.
It the second case, you might have some regressions especially in the beginning. That's not necessarily the easiest to start with if you want people to follow from the current state of the plugin.

**Comment by herrvigg** [comment]
<a href="https://github.com/mayaliny"><img src="https://avatars0.githubusercontent.com/u/11426730?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mayaliny](https://github.com/mayaliny)**
_Wednesday Mar 28, 2018 at 09:37 GMT_

----

I was considering the same idea, since i run qtranslateX on a lot of sites and i don't like the alternatives i've seen so far. 
So if you want to start a new supporting team count me in as a contributor. I also think we should contact the creator of https://it.wordpress.org/plugins/acf-qtranslate/ plugin (and other integration plugins) to see if we can collab together.

**Comment by herrvigg** [comment]
<a href="https://github.com/mayaliny"><img src="https://avatars0.githubusercontent.com/u/11426730?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mayaliny](https://github.com/mayaliny)**
_Wednesday Mar 28, 2018 at 09:39 GMT_

----

I think also this plugin https://it.wordpress.org/plugins/qtranslate-slug/ should be natively integrated in "qtranslate2018"

**Comment by herrvigg** [comment]
<a href="https://github.com/colinloretz"><img src="https://avatars1.githubusercontent.com/u/36084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [colinloretz](https://github.com/colinloretz)**
_Wednesday Mar 28, 2018 at 16:06 GMT_

----

@herrvigg I would vote for the first situation. We can also notify John and get his blessing if he can not continue. This has happened before when qTranslate became qTranslate-x when it was taken over from the original creator.

@mayaliny definitely. I didn't want to overstep as I know many use the plugin and have contributed to it but I think making this an open collaboration benefits everyone.

**Comment by herrvigg** [comment]
<a href="https://github.com/herrvigg"><img src="https://avatars2.githubusercontent.com/u/19155375?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [herrvigg](https://github.com/herrvigg)**
_Friday Mar 30, 2018 at 17:37 GMT_

----

Sounds good!
Also, be ready for a huge mess with Wordpress 5.0 which will replace TinyMCE with Gutenberg. This is probably going to have big impacts on qTranslateX. I hope version 4 can still survive for a few months, the transition is going to be quite heavy for many plugins (Wordpress is quite a messy framework).

https://web242.com/wordpress-5-what-you-need-to-know/

**Comment by herrvigg** [comment]
<a href="https://github.com/benjibee"><img src="https://avatars2.githubusercontent.com/u/620119?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [benjibee](https://github.com/benjibee)**
_Tuesday Apr 17, 2018 at 11:45 GMT_

----

@colinloretz I'd be really interested to see what your fork looks like now. There's no reason we couldn't open PRs and close issues on a fork so some progress could be made, no?

This plugin is the simplest and most intuitive solution out there, I really don't want to have to switch over to using WPML or Polylang after this 😞

**Comment by herrvigg** [comment]
<a href="https://github.com/janeschindler"><img src="https://avatars3.githubusercontent.com/u/30444613?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [janeschindler](https://github.com/janeschindler)**
_Tuesday Apr 24, 2018 at 14:36 GMT_

----

I'd love to help this project if I can. So glad someone is talking about it. Any news? Also worried about wordpress 5.0!

**Comment by herrvigg** [comment]
<a href="https://github.com/colinloretz"><img src="https://avatars1.githubusercontent.com/u/36084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [colinloretz](https://github.com/colinloretz)**
_Tuesday Apr 24, 2018 at 16:25 GMT_

----

@benjibee @janeschindler + all:  I'm still running on the latest version but there's a lot of cleanup and support that is going to be needed going forward. 

I've messaged the contact form on https://qtranslatexteam.wordpress.com/ and we've posted here to no response so I think it's time we start to discuss how we want to proceed with a new fork.

**Comment by herrvigg** [comment]
<a href="https://github.com/mayaliny"><img src="https://avatars0.githubusercontent.com/u/11426730?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mayaliny](https://github.com/mayaliny)**
_Tuesday Apr 24, 2018 at 16:48 GMT_

----

I think we should start a new project and release it immediately with the actual code (updating the "tested with  wordpress version [latest]") and start gather new installations.

Then we'll work on this forum to suggest people to switch to new version (which would be only download turnoff/turnon thing)

Once we got that, and a multi author staff, we can work on new version (i'd prefer a solid compatibility with wordpress against new features).

Maybe I'm not the best php programmer out there, but i know some stuff and I can donate some hours per week to this project, so please, let me know.

PS- I suggest some names here, just to start discussion: openQtranslate, qTranslateXXL (i'd prefer the first one, but maybe the second is more effective when moving people from old plugin to new one)

**Comment by herrvigg** [comment]
<a href="https://github.com/colinloretz"><img src="https://avatars1.githubusercontent.com/u/36084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [colinloretz](https://github.com/colinloretz)**
_Tuesday Apr 24, 2018 at 20:57 GMT_

----

Ideally it would be nice to be able to maintain this repository and keep the name with a new major version going forward. I've contacted Github and will reach out to WordPress as well to see if there is any known procedure for this.

If not, we'll have to do as suggested above and start a fork with a new name and move forward. There are pros and cons to each, for sure.

**Comment by herrvigg** [comment]
<a href="https://github.com/mayaliny"><img src="https://avatars0.githubusercontent.com/u/11426730?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mayaliny](https://github.com/mayaliny)**
_Monday Apr 30, 2018 at 08:28 GMT_

----

Any news from github?

**Comment by herrvigg** [comment]
<a href="https://github.com/colinloretz"><img src="https://avatars1.githubusercontent.com/u/36084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [colinloretz](https://github.com/colinloretz)**
_Tuesday May 01, 2018 at 18:15 GMT_

----

>Thanks for reaching out to GitHub Support!

>If you haven't had any success contacting the owner, I'm afraid there's no other way to take over the project. Your best bet would indeed be to fork the project and continue development in your fork.

>If you'd like, we can detach your fork from the original repository so that you can start over in a new network without being shown as a fork of the original?

>Let us know if this is something you'd like to pursue, or if you have any other questions!

**Comment by herrvigg** [comment]
<a href="https://github.com/abclution"><img src="https://avatars3.githubusercontent.com/u/10130237?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abclution](https://github.com/abclution)**
_Tuesday May 01, 2018 at 18:34 GMT_

----

I think getting any new / continuation of the project will find its most difficulty being listed on WordPress plugin page and avoiding user confusion and plugin mismatches.

I think when Qtranslate which eventually became QtranslateX, the small name change was a good idea. It made a clear line in plugins and names where the new group took over and compatibility and searching for addons to it became easier.

QtranslateX2
QtranslateXtc
QtranslateXce
QtranslateX-CE (Community Edition)

That way any plugins additions have a clear demarcation on when / what they were developed for.
Just an idea.

**Comment by herrvigg** [comment]
<a href="https://github.com/colinloretz"><img src="https://avatars1.githubusercontent.com/u/36084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [colinloretz](https://github.com/colinloretz)**
_Tuesday May 01, 2018 at 18:50 GMT_

----

Agreed. I like the name openQtranslateX, as suggested above. No matter what name we use, we need to write up some documentation that explains what happened to Qtranslate-X and a roadmap of what is to come.

I think the WordPress plugin gatekeepers will be more open to marking the old version as abandoned and link to the new plugin page. I can reach out to them when we are ready.

**Comment by herrvigg** [comment]
<a href="https://github.com/mayaliny"><img src="https://avatars0.githubusercontent.com/u/11426730?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mayaliny](https://github.com/mayaliny)**
_Wednesday May 02, 2018 at 05:33 GMT_

----

I think no matter what the name will be (even if the right naming will simplify the user moving to the new plugin) we need to move quickly to a new space/plugin. 
That because the plugin is currently marked as "abandoned" from some security plugins like Wordfence.

After we have rolled up the new plugin we can send some press release to tech blogs to inform the community there's a new boss in town ;-)

**Comment by herrvigg** [comment]
<a href="https://github.com/wedme"><img src="https://avatars3.githubusercontent.com/u/38943156?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wedme](https://github.com/wedme)**
_Friday May 04, 2018 at 13:23 GMT_

----

I'm just a regular user (and pretty new to WP at that) but I've been using qTx for a website I'm setting up. It really is an awesome plugin and there's nothing out there that compares. But it has been very frustrating not to have a community to turn to when I hit a brick wall or even developers to take on paid projects when need be. I would love to see a fork come out. You have my support, albeit moral ;)

**Comment by herrvigg** [comment]
<a href="https://github.com/herrvigg"><img src="https://avatars2.githubusercontent.com/u/19155375?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [herrvigg](https://github.com/herrvigg)**
_Friday May 04, 2018 at 15:07 GMT_

----

The sooner the better.

The question of the name may sound a bit futile but it's important to find a good name now because it's very hard to change later. My two cents: keep it simple!

Historically, qTranslate-X was derived from qTranslate which was already open source. Everyhing already being open source, I don't see the point of prefixing with `open` in the name. 

Also i would rather rebase the name from `qTranslate` rather than `qTranslate-X` to not make it too complicated. No need to carry the whole history in the name. People looking for qTranslate-X should find anything based on qTranslate quite easily. All the details can then be described in the description of the plugin and on the new git repo.

**Comment by herrvigg** [comment]
<a href="https://github.com/herrvigg"><img src="https://avatars2.githubusercontent.com/u/19155375?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [herrvigg](https://github.com/herrvigg)**
_Friday May 04, 2018 at 15:21 GMT_

----

Also, the author of the original of qTranslate was [Qian Qin](http://www.qianqin.de/) aka [chineseleper]( https://profiles.wordpress.org/chineseleper). He even participated to qTranslate-X, certainly one of its main developer. Maybe we should contact him as well, he should be of great advice to continue on this project. He has a page on [wordpress ](https://profiles.wordpress.org/chineseleper) but has been inactive for 3 years. There were also two other developers on qT-X.

Here is the list of authors found on qTranslate-X readme: 

> Developed by: qTranslate Team based on original code by Qian Qin
> Contributors: johnclause, chineseleper, Vavooon, grafcom

**Comment by herrvigg** [comment]
<a href="https://github.com/wedme"><img src="https://avatars3.githubusercontent.com/u/38943156?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wedme](https://github.com/wedme)**
_Friday May 04, 2018 at 15:26 GMT_

----

@herrvigg I agree that the whole history of the plugin does not need to be represented in the name. As such like abclution suggested (with a slight change) I think "qTranslate-CE" is very good and makes the most sense.

**Comment by herrvigg** [comment]
<a href="https://github.com/wimstefan"><img src="https://avatars3.githubusercontent.com/u/4605934?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wimstefan](https://github.com/wimstefan)**
_Thursday May 10, 2018 at 08:06 GMT_

----

Keeping "qTranslate" in the name certainly is a good idea but the suffix "-CE" needs some translation/explanation ... why not using the prefix "Open" to emphasize the open character of the new plugin? I prefer `OpenQtranslate` above `qTranslate-CE` I have to admit ...

**Comment by herrvigg** [comment]
<a href="https://github.com/herrvigg"><img src="https://avatars2.githubusercontent.com/u/19155375?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [herrvigg](https://github.com/herrvigg)**
_Thursday May 10, 2018 at 12:52 GMT_

----

Well i don't really see the point of adding "open" to a public github repo, it is open-source implicitly as any public repo. The link to the repo should be very easy to find once the plugin respawns. I didn't come up with it, but CE makes more sense to me because we, as a community, are trying to resurrect it. Indeed it could also be something like qTranslateRebirth or qTranslateNeo. I won't diverge on a more religious theme ;)

**Comment by herrvigg** [comment]
<a href="https://github.com/mayaliny"><img src="https://avatars0.githubusercontent.com/u/11426730?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mayaliny](https://github.com/mayaliny)**
_Thursday May 10, 2018 at 13:41 GMT_

----

I don't really care about what the name should be, in this phase.. i think we should hurry up to re-animate the code, no matter the name. 
Although i think the string "qTranslate" should be absolutely present at least at the beginning not to confuse people about what the aim of the plugin is.

how are we with the fork thing? can we go for the "detach fork from the original repository" as suggested by github to @colinloretz ?

@colinloretz would you follow this operation for all of us?

**Comment by herrvigg** [comment]
<a href="https://github.com/colinloretz"><img src="https://avatars1.githubusercontent.com/u/36084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [colinloretz](https://github.com/colinloretz)**
_Friday May 11, 2018 at 17:07 GMT_

----

@mayaliny we can have them disconnect it when we're ready.

I can get the new fork going and add some guidelines for contributing and we can start identifying what we want to tackle as first priorities. 

In addition to getting the plugin up to date with the latest version of WordPress, I think some priorities include adding support for gutenberg, doing some code clean up and start looking at issues in this repo that still need addressing. We will also want to identify and reach out to anyone who is actively working on their own forks or the ecosystem of integration plugins for things like WooCommerce, etc.

**Comment by herrvigg** [comment]
<a href="https://github.com/mayaliny"><img src="https://avatars0.githubusercontent.com/u/11426730?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mayaliny](https://github.com/mayaliny)**
_Friday May 11, 2018 at 19:59 GMT_

----

For sure Gutemberg is an issue.. but i think it's secondary to gather the attention of the qTranslate* community around our new project.
My personal roadmap will be:

-start the new plugin
-do some public relations to gain attentions
-fix qtranslate for current wordpress and php7
-work on gutemberg integration (and if needed consider refactoring the whole code)

**Comment by herrvigg** [comment]
<a href="https://github.com/colinloretz"><img src="https://avatars1.githubusercontent.com/u/36084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [colinloretz](https://github.com/colinloretz)**
_Friday May 11, 2018 at 20:40 GMT_

----

I'd vote for fixing the code for current WP and php7 before we try to do any announcements outside this repo to avoid confusion.

**Comment by herrvigg** [comment]
<a href="https://github.com/mayaliny"><img src="https://avatars0.githubusercontent.com/u/11426730?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mayaliny](https://github.com/mayaliny)**
_Friday May 11, 2018 at 20:45 GMT_

----

well, seems legit ;-) let's move my point 2 to point 3 ;-)

**Comment by herrvigg** [comment]
<a href="https://github.com/wedme"><img src="https://avatars3.githubusercontent.com/u/38943156?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wedme](https://github.com/wedme)**
_Friday May 11, 2018 at 23:15 GMT_

----

I agree with getting the fork going (for absolutely selfish reasons) but I have nothing to offer by way of coding as I am absolutely clueless. HOWEVER, I can offer my excellent moral support and I can also finish the Greek translation if that would help at all...

**Comment by herrvigg** [comment]
Hooray, the new repo is now ready for a new life!
I propose to name the new project qTranslate-XT for eXTended, while managing to keep a reference of the previous name (i didn't plan to, but it sounds quite good to me). The new project is now moved under the new organization: https://github.com/qTranslate/qtranslate-xt

The last official release is 3.4.6.8 which correspond to the last WP version. There has actually been quite some work done since then under the stable branch.
The last official pre-release was 3.4.6.9 but there were two other pre-releases prepared internally, but never tagged: 3.4.7 and 3.4.8. So i added these tags and i consider the last commit by John Clause corresponds to the 3.4.8 version, even though the last commits go slightly beyond the initial 3.4.8. It's mostly about notice and integration of plugins. I can't really say much about them but let's take everything as it is.

Then i re-organized the branches. The previous master was very much obsolete so i renamed it old-master just to keep it. We should now work on the master branch and then move the new stuff to the releases when it's ready.

The first tasks would now to prepare the first official release. One of the first thing would be to rename the internal references to qTranslateXT if you agree with this. Then my priority would be the most urgent fixes to make it run with a recent PHP7. On my side i made some custom fixes but in the old PR i found this one which looks pretty good to me.: https://github.com/qTranslate-Team/qtranslate-x/pull/581

Keep in touch!

**Comment by mayaliny** [comment]
XT sounds perfect to me.. thanks for the effort herrvigg!

I think we can start integrating the fix you found.. for php 7.1 maybe contacting the guy that released it if stil around..

I need to get familiar with git versioning since i never committed anything.. (my shame)
