### ISSUE TITLE
Fixed reference errors for PHP7.1 in frontend

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#581]
<a href="https://github.com/GasimGasimzada"><img src="https://avatars1.githubusercontent.com/u/807231?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GasimGasimzada](https://github.com/GasimGasimzada)**
_Tuesday Apr 03, 2018 at 19:44 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/pull/581_

----

----

_**[GasimGasimzada](https://github.com/GasimGasimzada)** included the following code: https://github.com/qTranslate-Team/qtranslate-x/pull/581/commits_

**Comment by herrvigg** [comment]
@GasimGasimzada Most of the requested changes are fixed in qTranslate-**XT** 3.5.0: https://github.com/qtranslate/qtranslate-xt/commit/612c9f72629ec4d12d94e3c97c1cadffe62a1503

This should fix all the reference errors. However your [PR/581](https://github.com/qTranslate-Team/qtranslate-x/pull/581/commits/bc59d9f83963d74ad214c7b791a1ee1bcd6f2030) had some other stuff:

- remove references from functions:
  - `qtranxf_add_language_menu_item(&$items, &$menu_order, &$itemid, $key, $language )`
  - `qtranxf_remove_detached_children(&$items,&$itemsremoved)`
- in function `qtranxf_translate_metadata` remove references from these assignements:
  - `$meta_unserialized = &$meta_cache_unserialized[$meta_type][$object_id];`
  - `$meta_key_unserialized = &$meta_unserialized[$meta_key];`

I'm not sure why we you asked to remove these references. They are still in the current version of qTranslate-XT and i have not seen such warnings anymore. The 2 functions are not related to WP hooks but called internally. Also, removing the refs from the variables could have some undesired side-effects so it has to be done carefully. Are you sure you want to remove those? If so, could you better explain?

Also your PR asked for other things such as Composer but for the moment this -XT plugin is only on github so we should look at this later.

**Comment by GasimGasimzada** [comment]
To be honest, I just removed all references when I saw the error and everything worked. It might have been a mistake on my part at the time. You can close this issue if there is no problem.

**Comment by herrvigg** [comment]
OK :)
Yes i don't think the other changes are necessary for now but they might be reviewed again in the future if we refactor some stuff. I don't really know why references are used in the existing code here, in general i think they should be avoided because it generates many side-effect errors. But removing them could also create some regressions so i'm super cautious with that ^^
