### ISSUE TITLE
How can I get an updated code. rather changing it manually according to pull requests.

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#595]
<a href="https://github.com/wisamx"><img src="https://avatars3.githubusercontent.com/u/1258782?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wisamx](https://github.com/wisamx)**
_Sunday Jul 15, 2018 at 23:05 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/595_

----

is there project being maintained in another place.
How can I get an updated code. rather changing it manually according to pull requests.

**Comment by wisamx** [comment]
qtranslate was famous for its **free** woocommerce-qtranslate-x plugin unlike other translation plugins which limit access to its woocommerce extensions.
do you have any plan of maintaining a community version of woocommerce-qtranslate-x.

**Comment by herrvigg** [comment]
Sorry no plan at the moment. I don't even use woocommerce so i have no clue. But maybe if some people are willing to take it over you could setup a similar parallel project.

**Comment by herrvigg** [comment]
See related ticket: https://github.com/qtranslate/qtranslate-xt/issues/608
I close this one.
