### ISSUE TITLE
qTranslate-XT versions for support plugins

### ISSUE THREAD

**Issue by The3IC** [qtranslate/qtranslate-xt#600]
Question: Do you have a plan for upgrading also the different support plugins? Currently, the most urgent would be WooCommerce as WC 3.x is deprecating a number of APIs and some of these are causing issues (currently shown as Warnings) with the current support plugin. Also the plugin could do with some new features, for instance the current plugin together with WC 3.x does not properly translate structured data.

**Comment by herrvigg** [comment]
I know there are many WooCommerce users needing that, but i have no plan to do so myself. I don't use it so it would be a bit hard to be active on that topic. You should discuss with all people of interest and come up with propositions. If it's clearly confined changes i could merge them through PR. But i would also need some help to validate all of this properly.

**Comment by herrvigg** [comment]
See related ticket: https://github.com/qtranslate/qtranslate-xt/issues/608
I close this one.
