### ISSUE TITLE
FIRST RELEASE 3.5.0 AVAILABLE!

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#602]
I am very happy to announce the **first release** of qTranslate-XT!
Everyone is much welcome to give it a try! All the instructions have been updated, so read carefully. Ask me anything in case of doubt.

**Comment by TheDubliner** [comment]
Herr Vigg, you deserve a medal. Thanks for picking up the baton!

**Comment by rinurinu** [comment]
Awesome, I'll test it in the next days, thank you a lot!

**Comment by phil4literacy** [comment]
It's a relief that people are planing to continue the project. We rely very much on this plugin at webonary.org and I might look into contributing to it. Have you had a look at how much needs to be done in order to make it Gutenberg compatible?

**Comment by herrvigg** [comment]
Happy to read this! 

For those who tried qT-XT i'm also curious about your feedback. No regression compared to qT-X? Did you try the new features (see changelog)? Is there sill other annoying/important bug to fix?

For Gutenberg i only began to read the API doc but didn't try anything yet. It's a small project on its now so we need to organize it better. I can try to give a bit of a structure if we are several people working on it. For now i'd say the first task is to study the feasability and build a small prototype showing we can handle load/save events to handle the content in Gutenberg. Then we need to retro-engineer the current JS code, there will be some work there.

**Comment by herrvigg** [comment]
New release:
https://github.com/qtranslate/qtranslate-xt/releases/tag/3.5.1
