### ISSUE TITLE
Categories spanning multiple lines in category selector shown in brackets

### ISSUE THREAD

**Issue by JohanWinther** [qtranslate/qtranslate-xt#603]
Multiline categories are shown in brackets when editing a post or a page.

![image](https://user-images.githubusercontent.com/28558941/43990113-33510664-9d57-11e8-8b5b-61a5ae9e7678.png)

The other categories which don't span multiple lines are translated.
The strings are not multiline in the database though.

I'm using the latest version 3.5.0.

**Comment by JohanWinther** [comment]
Apparently this has nothing to do with multilines. I'll open another issue for the problem with a better title.

**Comment by JohanWinther** [comment]
I resaved the categories which had the error and now they appear as normal.

**Comment by herrvigg** [comment]
hejsan ;)
Indeed i don't see any multiline here, this is just coming from the layout on the client side. 
Also, the format looked correct even the first time. So this probably came from the client script that didn't parse the blocks or failed for some other reason before setting up these items.
The most important is that it doesn't corrupt the data before sending it back to DB and i don't think this happened.
Let me know if you see this again.
