### ISSUE TITLE
Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by emyawasap** [qtranslate/qtranslate-xt#613]
I'm not really sure if this is a big issue or not. it just bothers me to have this error in the admin side. if anyone can tell what this is, it would be helpful.

![Admin Error Message](https://user-images.githubusercontent.com/11808545/46459473-9a041180-c7eb-11e8-9e75-ecd320ce532a.png)
![remove undefined](https://user-images.githubusercontent.com/11808545/46459505-b0aa6880-c7eb-11e8-88cb-13223bf25416.png)

**Comment by emyawasap** [comment]
Here is a file path BTW 
```/wp-content/plugins/acf-qtranslate/assets/acf_5/qtranslatex.js```

**Comment by herrvigg** [comment]
hello,
this code is not part of qTranslate-XT. This is related to another integration plugin, ACF qTranslate: https://github.com/funkjedi/acf-qtranslate

I don't know if the author is maintaining it or is considering to switch to qTranslate-XT.

**Comment by mayaliny** [comment]
Hello got the same problem, i thik, basically this error is throwing where there's an advanced custom field repeater. I think that stops javascript execution and in my case it prevents the "file" field from ACF to show all the media types (i need to choose a video insteas of an image).

I think this discussion is related:

https://github.com/funkjedi/acf-qtranslate/issues/122

going to see if i can figure out how to solve it.

@herrvigg i about 100% of my sites i use qtranslate with ACF, i wonder if we should consider to make qtranslateXT natively compatible with that.. (maybe merge efforts with funkjedi)

**Comment by herrvigg** [comment]
Fixed in ACF qTranslate.
