### ISSUE TITLE
init redirect causing exit from cli

### ISSUE THREAD

**Issue by Ryvix** [qtranslate/qtranslate-xt#618]
Hi there,

I'm using the php command to run a php file which loads WP and runs a cron task to sync a database. I'm not completely sure when this issue started but I've tracked it down to this plugin causing the cron that's being run from the cli to not fire due to exiting on the redirect on line 105 in qtranslate_core.php.

I discovered if I change the line 101 in qtranslate_core.php to check if $target is empty it seems to fix it for me. Is there a better way to do this?

```			if ( !empty($target) && $target !== false && $target != $url_orig ) {```

**Comment by herrvigg** [comment]
If you look in `qtranxf_can_redirect` defined in qtranslate_utils.php there is a check on `DOING_CRON` which should prevent the redirection. Is this global properly defined for you in the cron task? Note there is also `WP_CLI` which is handled similarly.

**Comment by Ryvix** [comment]
It seems the plugin doesn't have that yet so I added it and will tell the authors about it. Awesome, thank you!
