### ISSUE TITLE
Multiple LSB buttons

### ISSUE THREAD

**Issue by asanti82** [qtranslate/qtranslate-xt#619]
There is 1 LSB Switcher at the top and 2 at the bottom and I can't seem to find the option to remove them and in some cases there are 2 at top before the title and 2 at the bottom.

**Comment by herrvigg** [comment]
This is mostly handled by the i18n-config.json through the `anchors` field. Can you give a screenshot or describe which page?

**Comment by asanti82** [comment]
![screen shot 2018-11-30 at 9 30 54 am](https://user-images.githubusercontent.com/957595/49295055-c1412d00-f482-11e8-895b-831a67e7eb18.png)
![screen shot 2018-11-30 at 9 31 02 am](https://user-images.githubusercontent.com/957595/49295056-c1412d00-f482-11e8-9d37-70f559658c71.png)

**Comment by herrvigg** [comment]
Ah you can simply disable the metabox from the screen options (top right), uncheck "Languages".

**Comment by herrvigg** [comment]
@asanti82 i think we can close this, do you agree?
