### ISSUE TITLE
Uncaught TypeError: jQuery(...) is not a function

### ISSUE THREAD

**Issue by reddo** [qtranslate/qtranslate-xt#625]
I'm trying to create an `i18n-config.json` file for `gravityforms`, but I get an `Uncaught TypeError: jQuery(...) is not a function` when accessing the page, even though other scripts _are_ using jquery on that page. Any ideas?

My `i18n-config.json` so far: 

```
{
  "vendor": {
    "plugins/gravityforms": "2.4.x"
  },
  "admin-config": {
    "post": {
      "pages": {
        "admin.php": "?page=gf_edit_forms&id="
      },
      "anchors": {
        "post-body-content": {
          "where": "first last"
        }
      },
      "forms": {
        "gform_fields": {
          "form": {
            "jquery": ".gfield"
          },
          "fields": {
            "field_label": {
              "jquery": "input[id='field_label']"
            },
            "field_description": {
              "jquery": "textarea[id='field_description']"
            }
          }
        }
      }
    }
  }
}
```

**Comment by herrvigg** [comment]
Actually there was an issue in master with the fix i sent yesterday for the js scripts... though i tested it i got fooled with the browser cache. So i fixed it again and increased the QTX_VERSION with a sub-version so that the last scripts are loaded. I've updated the gravity forms again.

I'm not really used with this json config file, but at first sight it looks so you can try again.

**Comment by reddo** [comment]
Thanks, your fix worked, but my JSON doesn't. I'll give it a go again this evening when I get home.

**Comment by herrvigg** [comment]
Merged into a new `modules` branch and PR sent: https://github.com/qtranslate/qtranslate-xt/pull/627

So please check from this one. All the last commits are there, together with the release 3.5.2 and the new fix for the API REST so this will be the best new context for validation.

**Comment by herrvigg** [comment]
@reddo any news about the problem with JSON?

**Comment by reddo** [comment]
To be honest, other things came up and I didn't have much time to look into this. Feel free to close this issue for now.

**Comment by herrvigg** [comment]
All right, we can re-open it later if you have issues with this again.
