### ISSUE TITLE
Woocommerce Shop Site

### ISSUE THREAD

**Issue by RalfJaeger** [qtranslate/qtranslate-xt#626]
My problem:

i use qtranslate-xt for my site and shop. Everything works fine, but the shop mainpage (categories) will not be translated. The rest is ok.

**Comment by herrvigg** [comment]
Glad to hear! Are you using the `woo-commerce` branch, the `master` branch or a release with the old "WooCommerce & qTranslate-X" plugin? I merged this last one in the woo-commerce branch, the last version comes with new fixes compared to the official plugin but we know there are still some stuff to be fixed. I will cleanup and merge all of this soon so we can continue with the fixes from a unique reference.

**Comment by RalfJaeger** [comment]
I use qtranslate-xt with the WooCommerce & qTranslate-X plugin.

I have the problem only on the main shop page where i show the categories.
![shop](https://user-images.githubusercontent.com/45788379/49798079-b2d7f880-fd41-11e8-8b29-370c68912276.jpg)

**Comment by herrvigg** [comment]
Mmm i've seen a fix for the category (i didn't write it myself) but it was for the admin pages. So this is probably due to something else.  However it will be easier to handle once i've merged the new module. From that point it will be handled internally and the "WooCommerce & qTranslate-X" plugin will become completely obsolete.

**Comment by RalfJaeger** [comment]
OK, when will it be released?

**Comment by janeschindler** [comment]
Not sure if this is relevant here, but I've generally had a lot of problems with qtranslate-x and taxonomies. Once I changed the main language of a site and all my translations were erased, for example. I've also never been totally clear on why taxonomies are saved in a global variable rather than with the regular [:lang] tags. Do you know anything about that, @herrvigg ? It would be a relief if the logic could somehow be the same.

**Comment by RalfJaeger** [comment]
Crazy:

When i go to the Homepage, switch from german to english, then go to the Shop-Catgegories, they will show in english. But when i switch back to german, they stay in english. I have to open the shop-page in the backend, save the page and then the Shop-Catgegories will show in german again.

**Comment by herrvigg** [comment]
The module for woo-commerce is now available in this PR: https://github.com/qtranslate/qtranslate-xt/pull/627. You can also check out the `modules` branch. I should be merged to master in the next days and a release will follow.

About taxonomies i can't really tell, i've only used the standard categories and tags and it works as expected.

About the category translation i can't tell either why this is happening. I suggest you check in the DB what is going on. If it's only a problem of front-end language, then it could be related to some cookie with a URL setting.

**Comment by RalfJaeger** [comment]
I tried the woocommerce & qtranslate plugin version 1.4 and it works all fine now.

Thanks for your top support...

**Comment by herrvigg** [comment]
Great! To be honest i don't know about woocommerce and i only knew the official plugin was a bit behind.

But for the long run that's also why i'm moving these plugins internally in qTranslate-XT so we can handle them more easily in there. Having all in a single repo make it much easier if we refactor the core qTranslate. But for woocommerce itself, my vision is that this community come with the fixes.
If you could just try the `modules` branch that would be great, but for woocommerce it's simply the 1.4 that i merged so you should find everything in place there when i merge this to the main branch.

Eventually the goal is also to move the whole qTranslate-XT to an official plugin. I'd say we can do this when we have at least a basic support for Gutenberg. There's only the question of the qTranslate brand, which i don't really care about to be honest. I just want this project to become autonomous in some way so its own community can make it live.

**Comment by herrvigg** [comment]
As this problem with the categories was fixed in WC & qTranslate 1.4 this can be closed. This should also be the case in the modules branch with PR https://github.com/qtranslate/qtranslate-xt/pull/627.
