### ISSUE TITLE
Release 3.5.2 and last news

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#628]
Just a short summary about the last release and updates:
- release 3.5.2: mostly to freeze the current state for WP5.0 coming with Gutenberg as default editor! You should install the Classic Editor plugin so i added an admin notice for this. The good news is that the Classic Editor will be supported at least to 2021 so it gives us a bit more time for Gutenberg. You can breathe again ;)
- Fix for API REST: now merged in master so i'd like more people here to validate this :P
- Integration modules for Woo-Commerce and Gravity Forms (to start with). This is now in the pipe with a new PR sent here: https://github.com/qtranslate/qtranslate-xt/pull/627
- experimental Gutenberg: not ready yet, still a lot to do and not easy at all... but preliminar results tend to show something might be feasible ^^'

**Comment by Webonary** [comment]
Thanks for all your work on this. 
Just wondering, if I should stay for the moment with qTranslate X or already migrate to qtranslate XT?

**Comment by herrvigg** [comment]
You should move to qTranslate-XT, that's the whole purpose of this repo. The official qTranslate-X is not maintained, it's been abandoned by its main author since 2016 and it's full of bugs (some fixed here), so i don't even see why people are still using  it.
