### ISSUE TITLE
PHP 7.3 Warning: "continue" targeting switch is equivalent to "break"

### ISSUE THREAD

**Issue by CurtisBelt** [qtranslate/qtranslate-xt#629]
`PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in Wordpress/wp-content/plugins/qtranslate-xt/qtranslate_frontend.php on line 536`

**Comment by herrvigg** [comment]
I haven't switched to PHP7.3. This one is simple to fix, just replace `continue` with `break`. Did you find other warnings?

**Comment by CurtisBelt** [comment]
@herrvigg Hello, sorry for delay. I have not seen any others, but I will post here if I do :+1:.

**Comment by herrvigg** [comment]
Fixed: https://github.com/qtranslate/qtranslate-xt/commit/93ef436126a2cce49457d68ed2f1e7539c8e1fff
