### ISSUE TITLE
qTranslate-XT and Wordpress 5.0.2

### ISSUE THREAD

**Issue by leomil72** [qtranslate/qtranslate-xt#631]
I'm trying to switch from qTranslate-X but I'm having some severe issues.
I downloaded the plugin, then I disabled qTranslate-X and finally enabled qTranslate-XT but, after the last step, I cannot open the config panel. If I go to Setting/Languages I just get a page half-empty: at the middle of the page I just have the tabs of the options, then the browser that tries to load something and nothing more, no option tab appears in the page. I have to keep both plugins up and running to get the options. Is this an issue related to the Wordpress version I'm using (5.0.2) or is something else?

**Comment by herrvigg** [comment]
Note if you use qTranslate-XT the options page is:
`/wp-admin/options-general.php?page=qtranslate-xt`

(and not qtranslate-x)

**Comment by leomil72** [comment]
I'm using a Wordpress release, installed by the automatic updater.
I cannot reach the config file, and it seems to me that the plugin is overlapping with qTranslate-X. I tried to remove the old plugin but nothing changed. Moreover, qTranslate-XT says that the file ".t/i18n-config.json" is missing. What's the prefix ".t"?? Did it recover some buggy config file from qTranslate-X?

**Comment by leomil72** [comment]
I removed the plugin, then I reinstalled it. Now I get 2 errors:

qTranslate‑XT: Error: Could not find file ".t/i18n-config.json" listed in option "Configuration Files". Please, either put file in place or update the option. Once the problem is fixed, re-save the configuration by pressing button "Save Changes" on plugin settings page.

qTranslate‑XT: Error: Could not find file "plugins/qtranslate-x/i18n-config.json" listed in option "Configuration Files". Please, either put file in place or update the option. Once the problem is fixed, re-save the configuration by pressing button "Save Changes" on plugin settings page.

In the first one there is ".t" like sub-dir but I don't know what is it. In the second one it seems that it still continues to look for the old plugin. Is there any config file to be manually deleted?

**Comment by leomil72** [comment]
I solved by completely removing both the plugins, qTranslate-X and qTranslate-XT, and then re-installing qTranslate-XT from scratch.
IMHO it is not completely correct to assert that BOTH plugins can live together in WP.
I reccomend to remove the old ones before to install qTranslate-XT.

**Comment by herrvigg** [comment]
Thanks for keeping us updated. Sincerely i have no idea why it failed like that. Having a double install should not be a problem as long as you don't have both active at the same time. I hope it was not your case. Eventually yes we should have separate options, but the current solution was only to make the transition easier.

**Comment by bagaweb** [comment]
I did this transition on more than 20 websites and never had an issue.

**Comment by hiniesta** [comment]
Have just download last version and the issues continues. 

> qTranslate‑XT: Error: Could not find file ".t/i18n-config.json" listed in option "Configuration Files". Please, either put file in place or update the option. Once the problem is fixed, re-save the configuration by pressing button "Guardar Cambios" on plugin settings page. 

and setting page is not working, when I enter it, I get

 The link you have followed has expired.
