### ISSUE TITLE
Detect "No Gutenberg" plugin

### ISSUE THREAD

**Issue by alphp** [qtranslate/qtranslate-xt#634]
No Gutenberg plugin also works whith Qtranstalte-XP
https://wordpress.org/plugins/no-gutenberg/

Sugested change:

Line 1037 of /admin/qtx_activation_hook.php
```php
function qtranxf_admin_notices_block_editor() {
	global $wp_version;
	if ( version_compare( $wp_version, '5.0' ) >= 0 && ! ( class_exists( 'Classic_Editor' ) || is_plugin_active( 'no-gutenberg/no-gutenberg.php' ) ) ) {

```

**Comment by herrvigg** [comment]
OK done also for [Disable Gutenberg](https://wordpress.org/plugins/disable-gutenberg/) (100.000+ installs). See commit https://github.com/qtranslate/qtranslate-xt/commit/35ab2931a52f9d81ca4d016de7a1640ff7c7a14a
