### ISSUE TITLE
Woocommerce-qtranslate-x plugin

### ISSUE THREAD

**Issue by hubosh** [qtranslate/qtranslate-xt#637]
I don't know if you're working on Woocommerce-qtranslate-x as well but I just found this error and how to fix it in the plugin.
woocommerce_product_get_attributes instead of woocommerce_get_product_attributes because it's deprecated, in the qwc-front.php file.

**Comment by herrvigg** [comment]
I have this PR that i'm supposed to merge soon ;)
https://github.com/qtranslate/qtranslate-xt/pull/627

Essentially it brings the last version 1.4 from this git repo: https://github.com/qTranslate-Team/woocommerce-qtranslate-x. So if you see the bug there it will still be the case. If you find a fix let me know and we'll bring it here

**Comment by herrvigg** [comment]
OK i close this for now. The PR is still there but it requires more work with better options, i'll explain this in the PR.
