### ISSUE TITLE
Yoast Seo and qtranslate-xt

### ISSUE THREAD

**Issue by Majimbu** [qtranslate/qtranslate-xt#638]
Is there a way to make them work togheter? The old plugin "Integration: Yoast SEO & qTranslate-X" is not working for me with aqtranslate-xt

**Comment by herrvigg** [comment]
I don't use this, but did you try with the last version (1.2) from the git repo? https://github.com/qTranslate-Team/wp-seo-qtranslate-x

As for WooCommerce, the official plugin on WP,org is a bit behind, here it's 1.1.1: https://wordpress.org/plugins/wp-seo-qtranslate-x/

Note this change in 1.2:
```
Fix: the functionality after Yoast has re-designed his plugin in version 3.0.
```

But yes it's 3 years old, so probably outdated. If some people can make this legacy plugin to work, we could integrate it as i'm doing for WooCommerce and Gravity Forms in this PR: https://github.com/qtranslate/qtranslate-xt/pull/627

**Comment by Majimbu** [comment]
I installed the 1.2 version and works better. Thanks!

**Comment by herrvigg** [comment]
If it works well, we can add it to the plugins supported natively. Yoast SEO is among the most popular ones.

**Comment by Majimbu** [comment]
It's working good so far and it would be great if the plugin to connect to Yoast Seo was integrated in qtranslate-xt

**Comment by denzel94** [comment]
> If it works well, we can add it to the plugins supported natively. Yoast SEO is among the most popular ones.

it work not correct. I need refresh page for see any content on other language

**Comment by Majimbu** [comment]
> > If it works well, we can add it to the plugins supported natively. Yoast SEO is among the most popular ones.
> 
> it work not correct. I need refresh page for see any content on other language

True, same for me.  Forgot to tell because I had the same problem before too.

**Comment by denzel94** [comment]
> > > If it works well, we can add it to the plugins supported natively. Yoast SEO is among the most popular ones.
> > 
> > 
> > it work not correct. I need refresh page for see any content on other language
> 
> True, same for me. Forgot to tell because I had the same problem before too.

I think we need support that issue [https://github.com/Yoast/wordpress-seo/issues/12088](url)

**Comment by herrvigg** [comment]
OK but i don't know yet what this refresh bug is about, can you explain this a bit better?

I don't expect Yoast SEO to do very much if it's specific to qTranslate. Integrating properly this plugin can be quite a big work depending on the level of translations you want and if it's a lot to do on the client side.

I'll wait a bit before integrating this until the main issues are fixed. For any fix let me know and we'll bring it in here.

**Comment by denzel94** [comment]
i found some think

> OK but i don't know yet what this refresh bug is about, can you explain this a bit better?
> 
> I don't expect Yoast SEO to do very much if it's specific to qTranslate. Integrating properly this plugin can be quite a big work depending on the level of translations you want and if it's a lot to do on the client side.
> 
> I'll wait a bit before integrating this until the main issues are fixed. For any fix let me know and we'll bring it in here.

i founded some things in integration plugin, the problem with updating data in fields. I have almost working code) but i dont sure i can finish it) i can provide more datils if you want

**Comment by Majimbu** [comment]
> i found some think
> 
> > OK but i don't know yet what this refresh bug is about, can you explain this a bit better?
> > I don't expect Yoast SEO to do very much if it's specific to qTranslate. Integrating properly this plugin can be quite a big work depending on the level of translations you want and if it's a lot to do on the client side.
> > I'll wait a bit before integrating this until the main issues are fixed. For any fix let me know and we'll bring it in here.
> 
> i founded some things in integration plugin, the problem with updating data in fields. I have almost working code) but i dont sure i can finish it) i can provide more datils if you want

If you solve this issue let me know. Thanks

**Comment by herrvigg** [comment]
All right, I have now moved added a module for Yoast SEO in the new modules branch: https://github.com/qtranslate/qtranslate-xt/pull/627.

This corresponds to the last version (1.2) of the legacy plugin [Integration: Yoast SEO & qTranslate-X](https://github.com/qTranslate-Team/wp-seo-qtranslate-x) (aka WP SEO).

So i propose to close this ticket, we should now focus on make the new `modules` branch work! Try it out, and you can send me corrections in that PR or (later). You can also create new issues if you are able to describe the problem well.

Also, we should not count on Yoast SEO to fix stuff for us as the situation of qTranslate is very messy right now but it should become easier once we have all this in and migrated to a new plugin.

**Comment by ashabelnikov** [comment]
Hi, 
I've migrated from qTranslate-X to qTranslate-XT and I use Yoast SEO plugin. Yoast SEO (WP-SEO) plugin is active but it is absent in the list of modules on the "integration" tab in settings. I see other inactive and active modules, but WP-SEO is missing.
What may be wrong?

qTranslate-XT 3.7.2
Yoast SEO 13.2
Wordpress 5.3.2

**Comment by herrvigg** [comment]
@ashabelnikov i had to disable it because it had too many problems. To clarify a bit, I just created a new issue to keep track of the state, but this will be a low priority for my part.

**Comment by ashabelnikov** [comment]
herrvigg, Thank you!
