### ISSUE TITLE
Content in neighboring languages get replaced when image inserted

### ISSUE THREAD

**Issue by axodjakov** [qtranslate/qtranslate-xt#642]
I'm using the latest versions of qTranslate-XT 3.5.2 and WordPress 5.0.3.
There are 3 languages on my website: Uzbek, Russian and English.

When I enter just text into all languages and publish the post - it works fine. But when I try to insert image (or any other media) into the content text of one language, the content gets copied to all other languages replacing their text. Titles stay unchanged - each language has it's own title intact. But the content becomes identical for all languages.

There're no errors in inspector console.

I've made a screen recording of the issue. Please, take a minute to watch what's happening: https://streamable.com/fvh4r

**Comment by herrvigg** [comment]
Thanks the video makes it very clear to understand!
I never use the visual editor, only text, so i thought it was the problem but no. I tried with the visual editor and i can't reproduce the problem. You're right to check the console, but if there's nothing i can't understand.

This looks really weird. Please can someone else help and try to reproduce this?

**Comment by herrvigg** [comment]
Just to be sure, can you try with the raw "Text" editor (not "Visual")?

**Comment by axodjakov** [comment]
> Just to be sure, can you try with the raw "Text" editor (not "Visual")?

I tried inserting image into text in "Text" mode of the editor. Everything worked just fine this time, no errors, no content replacement! So, the problem persists only in "Visual" mode.

I still need a fix for this issue. We mostly use Visual mode.

**Comment by herrvigg** [comment]
OK good we are precising the context. Still it doesn't happen for me so i'm wondering if it's not due to another conflicting plugin. Could you possibly try with only qTranslate-XT (and the Classic Editor) enabled?

**Comment by axodjakov** [comment]
We use the Classic Editor by default, we've the Classic Editor plugin installed. I've already tried deactivating all plugins except qTranslate-XT and Classic Editor - the problem persists.

We have multisite enabled (if this makes any difference).

**Comment by herrvigg** [comment]
All right then there's something going wrong with the TinyMCE events.  I don't think it is related to the multisite, this part should only affect the server side as far as i know. 

Maybe could it be something with the browser? Which one are you using? Do you have browser extensions?

**Comment by axodjakov** [comment]
> Maybe could it be something with the browser? Which one are you using? Do you have browser extensions?

I tried with freshly installed Mozilla Firefox - problem persisted. Also tried with Chrome browsers on other computers. I don't think any extension is causing this problem.

**Comment by alphp** [comment]
I have performed a test:
WordPress 5.0.3 / PHP 7.3.2 / qTranslate-XT "master"
Two languages configured, tested with both published entry and new entry. I have not detected any problem.

**Comment by herrvigg** [comment]
Thanks @alphp this confirms there's something very specific. 

@axodjakov what is the 3rd toolbar you have in the Visual Editor? I only have two like this:

![image](https://user-images.githubusercontent.com/19155375/52885307-0d8e3600-3171-11e9-8cb2-834eb67c3c7f.png)

**Comment by axodjakov** [comment]
@herrvigg Thank you for mentioning the toolbar. I switched to a standard Twenty Twelve theme and now the issue is gone! It was my Fraction (https://themeforest.net/item/fraction-multipurpose-news-magazine-theme/8655281) theme that was causing it.

You can remove the "bug" label now.

**Comment by axodjakov** [comment]
I managed to solve the problem. Custom buttons added to Classic Editor by my theme were causing qTranslate XT to replace the content. As I didn't ever use those buttons and didn't need them, I just disabled the theme function:
