### ISSUE TITLE
New plugin migration

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#648]
I'll give a bit of time before deciding for a new name (see https://github.com/qtranslate/qtranslate-xt/issues/601). The main goal is to become a new official plugin in wordpress.org and give this plugin a new community-driven life.

Meanwhile i have other questions coming up with the brand migration:

- git repo: should i create a new one or rename this one? My first idea was to rename because i imported all the history with the tickets in github and i don't want to do it again (the mass notifications have been bothering a lot of people). The counterpart is that it's going to be a bit confusing for those having their local git pointing to qtranslate-xt but with proper notice and info it should be feasible. Some external hyperlinks will also break but i think it's more important to carry the history. Alternatively we could archive this one with its backlog and refer to the old tickets here. What's the best?
- versioning: should i restart from 0.1 or 1.0 or continue from the current version (probably from a 4.x). Somehow i'd like to restart from zero but this is also related to the first question with regard to the releases and all the history. It might also depend if it is a continuation or a clear break.
- options: from that point the new tool will not share the options anymore with qTranslate-X so i need to find the good way to migrate/import all those. It might be the opportunity to rethink a bit how they are handled, i find the code very hard to understand/maintain for all this part. This is maybe the main point to be solved before being able to restart somewhere else. Apart from this I don't plan to do any DB migration for the translated data itself (in the posts and so on).

**Comment by herrvigg** [comment]
Last but not least... the `qtranxf_` prefix should actually be renamed or better we should have a specific namespace. Think that qTranslate-X/XT is already carrying the retro-compatibility with the old `qtrans_` functions. Maybe it's time to deprecate old stuff, we shouldn't carry obsolete code forever.

**Comment by TheHeat** [comment]
Hello, quick name suggestion: **CuteTranslate** - references the qTrans history

**Comment by bagaweb** [comment]
> 
> 
> Hello, quick name suggestion: **CuteTranslate** - references the qTrans history

Thumbs up

**Comment by Ruaphoc** [comment]
I think a new git repo should be created. We can reference the bugs in this and the older repos, but let’s make it a clean break. We should also look at a code cleanup at that time.

As for version, from an upgrade/migration standpoint, let’s go with 4.0. Just never know what might mess up if we start over with a lower version number.

I am kind of tempted to suggest we establish a new table in the WordPress database, and provide an upgrade/migration function to convert legacy qtranslate/qtranslate-X/qtranslate-XT installs. This will allow us to not have any conflict with legacy versions and we can handle plugin options how we want.

**Comment by majekw** [comment]
For me, it should only be name of repository change.
Why:
- old links to qtranslate-xt will redirect to new repository, so people could clearly notice name change without going into 404 or old not maintained repo (see https://help.github.com/en/articles/renaming-a-repository)
- starting new repository (AGAIN) with full history it's just fork, it will confuse people who will visit old repo, and probably some people could stick to old versions (most of using github-updater)
- squashing everything and start 'from the beginning' it's not fair to old contributors. You could add CREDITS/AUTHORS file to list all contributors as GPL require, but you will not differentiate scale and importance of each contribution. Information in 'git blame' will be also lost.
- whatever you think, this is still building on top of someone's earlier work, so why pretend that's this is something 'new'? It's 12000 lines of code, no one will rewrite it from the beginning to justify such move. It's plugin with history and in my opinion this should be preserved.

**Comment by Peter-HVD** [comment]
My understanding of repository rules is that new plugins cannot have the same namespace / text domain / function names as existing plugins. That's why I think it would be better for you to apply to take over the existing repository plugin - I've done it myself with an abandoned plugin and it's a relatively painless process!

**Comment by herrvigg** [comment]
About the naming please use this topic -> https://github.com/qtranslate/qtranslate-xt/issues/601.

The problem is not really about taking over the existing repo but using a brand outside of WordPress that no one here can claim. Just as an example consider this site: https://qtranslatexteam.wordpress.com/. It's still responding but it's not maintained so that's already misleading and it will only become worse. 

After thinking a bit and reading your answers i'm more in favor of creating a new repo but in my scenario i intended to do it with the git commit history, no squash. Technically speaking it would bootstrap as fork or full clone. But it would directly become a new plugin with a different name and other drastic changes. The first phase may even be private the time to sort the most important out for the transition. An idea could also be to start from version 0 and not pushing it to WP before version 1 with the proper setup.

In that case i agree it's better to keep the old tickets and releases here. This repo would then be archived. This solves the question of versioning and any referencing from the old tickets. No problem to move backwards in the version number as the plugin will have a different name. I don't worry so much about people visiting the old archive, all people here moved well from qTranslate-X and we'll give enough notice to migrate to the new one, hopefully for a long run.
