### ISSUE TITLE
qtranslate and LSB on pages other than `$post` related

### ISSUE THREAD

**Issue by krembo99** [qtranslate/qtranslate-xt#654]
How to add a functioning language switching button to pages other than `edit.php` or `post.php` ?
More specifically, how can I enable fields in custom setting page ( for plugin ) or in options-general.php or in the WP_customizer ? Just inserting the respective classes will not work ( becasue the `custom.js` is not loading ..)

( <! -- open BIG venting parenthesis 

I am using qtranslate ( and derivatives ) for 10 years if not more ...
Unfortunately the quasi-last iteration (qtranslate-x) made a lot of complicated ( IMHO ) unnecessary features. Chief among them was the so - called  `" LSB meta box". ` 
The main problem of this approach is that a meta-box by definition can only create when `$post-type` is available . Another cavet is that only 1 can be create - highly uncomfortable for `lllllooooong` pages.
Before that `meta-box` ( and `JSON` ) approach - if I remember correctly, the languagee buttons were available whenever the translated class was found ..
Anyhow, enough ranting :-)

 close big ranting parenthesis -- > )

 Is there another way of doing it without using the LSB meta-box ?
How to switch language on `back-end` areas that are not `post.php' or 'edit.php' ( more specifically - custom setting pages for themes / plugins / customizer ?

**Comment by herrvigg** [comment]
@krembo99 it should definitely be possible, this is a very old feature with the i18 config. Have you looked at the old website explainin how to write the JSON files for integration? https://qtranslatexteam.wordpress.com/json-configuration-syntax/

See for example this one, enabling LSB for `admin.php`:
https://github.com/qtranslate/qtranslate-xt/blob/master/i18n-config/plugins/events-made-easy/i18n-config.json

However about WP_customizer i can't really tell because i don't use this.

About the possibility of doing it without LSB, nothing should prevent it but the JS interface is so complicated that i couldn't even tell you how to do that.

**Comment by janeschindler** [comment]
Not sure this is the right place to post this, but I've used the JSON configuration some and it's a really tough way to integrate. As the old site itself notes, it's more or less impossible to debug, and it's not very readable either. I don't understand how it works in any depth, but wouldn't there be some way to have qtranslate-xt come with some function I could implement from anywhere to access the event 'on switched language'? Also would be great if there was an easy and clear way to replace the default LSB(s) with your own. In my opinion, there should only ever be one set of LSBs per page – i dislike how my admin interface gets populated with a million of these little flags...

**Comment by herrvigg** [comment]
I totally agree, i also dislike this JSON interface a lot. Believe me it's also a hell of maintenance in the code, it's an absolute giant mess to understand what's going on. There's a lot that can be done both as features and for the state of the code. But at least, the functionality is there. Though it's user-unfriendly, we should try to stick to it as it is now. Just try to create a i18n-config.json and experiment with this.

About new features or ideas for new integration i'd be happy to see it evolve but a lot of stuff has to be fixed before that, i'm preparing the modules part to bring all the legacy code back before we migrate as a new plugin. From that point it should become easier to manage and i hope to get some help from other people. Anyway we'll have to do a transition for this JSON thing so if you spend time on that it should still be upgradable later on.

Let's take every part separately to make it easier to follow:
- the integration of LSB for other pages that post should work, so this issue can be closed imo.  You can still comment on this and let us know if something does not work as expected, in that case we may re-open the ticket.
- please create new tickets explaining in details what you'd like to have or better, send us new suggestions with a PR. But this will be low priority for now.

**Comment by k9t9** [comment]
I will also look at the code .
In short - I somehow think it will be easier to take the last Qtranslate version taht was released by the ORIGINAL author , and just fix compatibility issues with newer wp versions. The last original version should be pre-JSON, pre-LSB and very clean and elegant code if I remember correctly .

**Comment by herrvigg** [comment]
I don't think it would be reasonable, qTranslate is way behind, it was closed more than 3 years ago so most of users switched to qTranslate-X which has still 100.000+ active installations (including some having double install qT-X and -XT but i have no numbers for -XT). Many people definitely want the LSB so it's better to go on with qTranslate-X (now -XT). We are all aware some deep refactoring is necessary and all the integration should be reworked (we should get rid of json i18n) but let's move forward, one step a a time.
