### ISSUE TITLE
Single language button

### ISSUE THREAD

**Issue by tmorgan1967** [qtranslate/qtranslate-xt#656]
How can I have just the language word as a button/switch? For example, i want on my english menu for word Francais and you click on that word and the french site has English in the menu. So, no drop down chooser.

**Comment by herrvigg** [comment]
See FAQ https://qtranslatexteam.wordpress.com/faq/
-> What language switching methods are available at front end?

Use for example a Language Switch menu: https://qtranslatexteam.wordpress.com/faq/#LanguageSwitcherMenuConfig
with URL=`#qtransLangSwLM?type=AL&current=none`

**Comment by tmorgan1967** [comment]
Thanks! I found the code page in the faq. All good thanks!!!!Kind regards,Todd Morgan416-451-8388 cell-------- Original Message --------Subject: Re: [qtranslate/qtranslate-xt] Single language button (#656)From: Herr Vigg To: qtranslate/qtranslate-xt CC: tmorgan1967 ,Author See FAQ https://qtranslatexteam.wordpress.com/faq/
-> What language switching methods are available at front end?
Use for example a Language Switch menu: https://qtranslatexteam.wordpress.com/faq/#LanguageSwitcherMenuConfig
with URL=#qtransLangSwLM?type=AL&current=none

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/qtranslate/qtranslate-xt","title":"qtranslate/qtranslate-xt","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/qtranslate/qtranslate-xt"}},"updates":{"snippets":[{"icon":"PERSON","message":"@herrvigg in #656: See FAQ https://qtranslatexteam.wordpress.com/faq/\r\n-\u003e What language switching methods are available at front end?\r\n\r\nUse for example a Language Switch menu: https://qtranslatexteam.wordpress.com/faq/#LanguageSwitcherMenuConfig\r\nwith URL=`#qtransLangSwLM?type=AL\u0026current=none`"}],"action":{"name":"View Issue","url":"https://github.com/qtranslate/qtranslate-xt/issues/656#issuecomment-475066500"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/qtranslate/qtranslate-xt/issues/656#issuecomment-475066500",
"url": "https://github.com/qtranslate/qtranslate-xt/issues/656#issuecomment-475066500",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
