### ISSUE TITLE
Text widget disappears

### ISSUE THREAD

**Issue by whitesnake1976** [qtranslate/qtranslate-xt#658]
Any good news about this issue? The text or HTML widtget (also the classic text plugin widget) disappears after save. The info still visible in the public web but not in the admin area :(

**Comment by herrvigg** [comment]
"This issue"? I don't see what you are referring to.
Recently there was this one related to widget: https://github.com/qtranslate/qtranslate-xt/issues/616. But it doesn't seem to be the same problem.

**Comment by whitesnake1976** [comment]
Well, I don't know is is exactly the same error or not. What I see is that if you type some text in HTML or text widget and save it, once you refresh the page, the text is gone. Is saved in the database but you cannot see it in the admin area. So any need modification, you should type it again.

**Comment by herrvigg** [comment]
@whitesnake1976 keep us updated if you want the issue fixed. I close for now, feel free to re-open if you can provide more info.
