### ISSUE TITLE
Built-in Modules Status displays broken tags

### ISSUE THREAD

**Issue by mel-7** [qtranslate/qtranslate-xt#662]
Status displays "> "> instead of check, x and block.

**Comment by herrvigg** [comment]
Oh that's unfortunate. I tried to used the simplest thing ever with the dashicons:
https://developer.wordpress.org/resource/dashicons/#yes

The check is this: `<span class="dashicons dashicons-yes"></span>`

What about the other icons in WP?

**Comment by herrvigg** [comment]
Oh i think i found the problem, missing "php" in the opening tag. Some PHP interpreters accept it but others not. Will fix. Thanks for testing!

**Comment by mel-7** [comment]
Thank you @herrvigg and thank you guys for the update! Please keep it up!

**Comment by mel-7** [comment]
![fixed-status](https://user-images.githubusercontent.com/38182380/55543239-ba991f80-56d9-11e9-8844-2748950b7689.JPG)
I fixed mine. Thanks!

**Comment by herrvigg** [comment]
Good to know! Fix sent (i also changes some quotes just for readability).
Thanks!

**Comment by mel-7** [comment]
Thank you!
