### ISSUE TITLE
Compatibility with Extra theme in Elegant themes

### ISSUE THREAD

**Issue by zerneto** [qtranslate/qtranslate-xt#666]
I am trying to use a feature of Extra theme that allows for a category layout to be used as home page, but I have also tried to do it using regular pages. The problem is, when I use a module, its content, e.g. using the Blog Feed Module, the posts, are correctly translated. But the module title does not get translated. 

[http://novoblog.myscrumhalf.com](url) 

This happens to any theme module I use. 

Anyone ran into this? 

Best.

**Comment by herrvigg** [comment]
You should look at the integration features, it's certainly a field other than the standard post title that you need to translate explicitly on the client-side through 18n json config or PHP code.

**Comment by zerneto** [comment]
I did try explicit php calls, creating a child theme and altering the related file. Still does not work.

**Comment by herrvigg** [comment]
Sorry but I need more technical details to understand if this is a real issue or just a problem doing the integration properly. I close this for now, feel free to re-open if you can provide more info for a fix.
