### ISSUE TITLE
Multiple redirects with Restaurant Menu plugin

### ISSUE THREAD

**Issue by alelkin** [qtranslate/qtranslate-xt#669]
I tried to use XT with [Restaurant Menu Plugin](https://motopress.com/products/restaurant-menu/)

For button delete in Checkout it makes [multiple redirects](www.mydomain.ee/checkout/?q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&q=/checkout/&cart_item=0&mprm_action=remove&controller=cart) 

And also for [Submit Order](www.mydomain.ee/checkout/ru-zakaz-prinjat-fr-commande-accept-e/?q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&q=/checkout/ru-zakaz-prinjat-fr-commande-accept-e/&payment_key=6453ff40fdb8070bdf2d322e6a92a317)

When I deactivate XT this Page start working.

What could it be?

**Comment by herrvigg** [comment]
This should be quite a specific problem, depending on what URL they call and how. The redirects in qTranslate should mostly be due to language switches through the client cookies. You should first try to track all the HTTP requests done, filtered to those made on your own website.

**Comment by herrvigg** [comment]
@alelkin you can use the browser inspectors for that and look what happens in the Network tab.

**Comment by alelkin** [comment]
What exactly info do you need? I've tried with Network.
First it goes to: https://xxx.com/ru/checkout/?cart_item=0&mprm_action=remove&controller=cart
Then it starts to add "q=/ru/checkout/&" after "?" multiple time, so it looks like https://xxx.com/ru/checkout/?q=/ru/checkout/&cart_item=0&mprm_action=remove&controller=cart

I can give you access to the website, if needed.

**Comment by herrvigg** [comment]
I'm not completely sure about the reasons but isn't that a bit strange to have `?q=/ru/checkout/` in the URL? I can be wrong but i think the slashes should be URL encoded before redirecting. If this is causing the problem but in the case it could be a problem in that plugin.

**Comment by alelkin** [comment]
So problem was in nginx configuration
better to use try_files $uri $uri/ /index.php?$query_string; instead try_files $uri $uri/ /index.php?q=$uri&$args;

**Comment by herrvigg** [comment]
OK great you found the reason so i close this.
