### ISSUE TITLE
Enable LSB for non supported modules

### ISSUE THREAD

**Issue by paketos** [qtranslate/qtranslate-xt#672]
Hi

i am using https://wordpress.org/plugins/yikes-inc-easy-custom-woocommerce-product-tabs/ which enables custom tabs in woocommerce products. I suppose this is not related to woocommerce module itself, the request is for 3rd party plugins that include fields where a user can give a title and description. 
The problem is that i have to use the bracket notation to make translations. I have already done so and it works. However it would make it easier if there were more LSB buttons where fields created by other plugins appear as in the case described above. 
The above plugin adds custom tabs. In the backend a user can creates a tab and title and editor appear. Is there a way this can be done with the creation of an i18n-config.json file and if so what are the contents to this file?

Thank you for your time and efforts reviving this plugin.

**Comment by herrvigg** [comment]
You mean in the frontend not backend? I guess it's possible but you should first read about the integration part: https://qtranslatexteam.wordpress.com/integration/. Sorry but i won't do more support on this topic so i close it for now. Tickets should be first of all about bug reports that can be reproduced or precise feature requests (ideally with a PR in that case).
