### ISSUE TITLE
ACF post object titles not translated

### ISSUE THREAD

**Issue by hencca** [qtranslate/qtranslate-xt#677]
I've was able to fix this with the following pull request, but I'm not familiar with HerrVigg's thinking, so there are surely other considerations. Not sure why we need the filrer **qtranxf_admin_the_title**

https://github.com/qtranslate/qtranslate-xt/pull/678

**Comment by hencca** [comment]
![image](https://user-images.githubusercontent.com/286391/56879077-ccaf7900-6a5f-11e9-8a46-df4f5588ffcf.png)

**Comment by herrvigg** [comment]
All right it took me a bit of time to test this with ACF but i managed to reproduce it. Follow-up in PR https://github.com/qtranslate/qtranslate-xt/pull/678.

**Comment by herrvigg** [comment]
Tested with ACF and PR https://github.com/qtranslate/qtranslate-xt/pull/678 merged in master. It works with no regression for the nav menus (add & update)!
