### ISSUE TITLE
Group same type of language

### ISSUE THREAD

**Issue by JulienHe** [qtranslate/qtranslate-xt#682]
Hey everyone!

I was wondering, does qtranslate-xt allows me to group language together?
I'm working for a big client with a possibility of more than 100 languages and to make it easier to manage we want to group same family languages together like: 

- Japanese, Chinese, Korean
- Arabic, Persian, Pashto
- English, French, Spanish

This is to work on the styling mostly cause the way fonts are managed are different.
Asian fonts are bigger than English and Arabic one are small than English.

Thank you for you help!

**Comment by herrvigg** [comment]
By grouping what do you mean? Having the raw blocks saved in DB close to each others? Anyway there's no such feature related to language grouping.

**Comment by herrvigg** [comment]
I don't really understand the question here. Note you can order the languages as you want, in the options. The values should be stored in given order.
