### ISSUE TITLE
Very basic built-in integration modules?

### ISSUE THREAD

**Issue by rekollekt** [qtranslate/qtranslate-xt#683]
ACF Pro?
WPBakery Page Builder?
Slider Revolution?
Contact Form 7?

**Comment by herrvigg** [comment]
- ACF pro: should be already supported though i didn't test it.
- WPBakery Page Builder: as written [before](https://github.com/qtranslate/qtranslate-xt/issues/661#issuecomment-480496123) there was this [legacy plugin](https://github.com/qTranslate-Team/js-composer-qtranslate-x) but it doesn't seem to do anything valuable.
- others: feel free to send PR for new integration support. I will not work on this.

**Comment by herrvigg** [comment]
@rekollekt did you really try with ACF Pro? It should work if the plugin path `advanced-custom-fields-pro/acf.php` is correct. If this is not the case, let us know.
For the other plugins including WPBakery i mean new PRs are welcome and i will help to integrate those as modules but i can't spend time coming up with the integration work itself. Closing this for now.

**Comment by rekollekt** [comment]
@herrvigg THX (the problem was the url path of acf pro).

**Comment by herrvigg** [comment]
@rekollekt great! But do you mean you had a custom installation or did you change it in qTranslate code? Eventually we may add some filters to allow custom paths but this can come later once we have cleaned up all the existing ones.

**Comment by rekollekt** [comment]
I didnt change qTranslate XT code I just renamed plugin folder slug to `advanced-custom-fields-pro` and it works perfect. But custom filter would be better.

**Comment by herrvigg** [comment]
As the Pro is not a plugin from wordpress.org but installed separately, i was wondering what the default path should be. Now I don't remember where i found this, but was the previous installation path something you changed explicitly? For now the goal is to provide a default path that works for the majority of users.

**Comment by rekollekt** [comment]
> was the previous installation path something you changed explicitly?

Yes.

**Comment by jimmyadaro** [comment]
How much harder would be to create a "WPBakery Page Builder" plugin for qXT?
