### ISSUE TITLE
How to disable the plugin on the ACF group edit page?

### ISSUE THREAD

**Issue by jonytrano** [qtranslate/qtranslate-xt#684]
Url example: **wp-admin/post.php?post=371&action=edit**

**Comment by herrvigg** [comment]
Can you better explain this? What do you want to disable and why?

**Comment by herrvigg** [comment]
@jonytrano i can't understand the issue like this so i close for now. You can re-open if you provide more accurate information about the problem / requested evolution.

**Comment by jonytrano** [comment]
![123](https://user-images.githubusercontent.com/50478886/58096464-ee32f900-7bf6-11e9-88fe-dbd67dd5d3e3.png)

**Comment by jonytrano** [comment]
How to disable the plugin on this page? (ACF)
