### ISSUE TITLE
Admin column for Language in WooCommerce product outside the table

### ISSUE THREAD

**Issue by teaone** [qtranslate/qtranslate-xt#685]
Found a way to join the column for Language into the table.

Put into qtranslate_configuration.css

`.column-language {width:10% !important; overflow:hidden}`

Thanks.

**Comment by herrvigg** [comment]
This looks specific to WC so it should not go in the main css file. As a quick fix it could be done since there's only one entry but it would be better handled separately for this plugin.

**Comment by teaone** [comment]
But I think it’s part of qtranslate-xt. With just WC only plugin, the language column was not exist in admin product page. After installed, the column for language get created and looks pulled out from the main table and the width was so tiny. If I exclude the language column, everything was OK.

**Comment by herrvigg** [comment]
Sure it's part of qTranslate-XT but as a general rule we should not bloat the common/core parts with changes that are specific for integration with one plugin. We should keep things isolated as much as possible.

**Comment by teaone** [comment]
Make sense for general common rule. Just remember, the integration qtranslate-xt/modules/woo-commerce/woo-commerce.php is part of qtranslate-xt. So why not create qtranslate-xt /modules/woo-commerce/assets/css/admin.css as most plugin dev do? And activate/deactivate to satisfy the integration.

**Comment by herrvigg** [comment]
Precisely! It would be good to have a general pattern for all modules. I'll look at this, i keep it open until then.

**Comment by spleen1981** [comment]
fixed by c6df46b41997bdb7ae1a1b6d01f7c83e201ab27f
