### ISSUE TITLE
Problem with password reset

### ISSUE THREAD

**Issue by sviluppomania** [qtranslate/qtranslate-xt#687]
The previous qtranslateX plugin and now also this (qtranslateXT) conflict with a security plugin and a custom url (WP CERBER), from the new WordPress Version 5.2. updating the plugin 4 days ago I thought it was that WP CERBER plugin, but doing a test by disabling all the plugins and keeping only qtranslate and wp cerber active kept generating the error, only disabling qtraslate the error disappears. I have already reported the error on the wp cerber support forum, here: https://wordpress.org/support/topic/reset-page-does-not-reset-the-password/

What can be the solution in qtranslate?

IMG: https://ibb.co/rkQBrsq

![Cattura](https://user-images.githubusercontent.com/26438200/57712568-15c31800-7671-11e9-88e1-404007918a85.PNG)

**Comment by pimoGit** [comment]
Have you tried also the opposite, so disabling so disable WP CERBER and keeping q-translateX active?

**Comment by sviluppomania** [comment]
It works, but it is relative because it returns the original url with wp-login.php, it remains that if it is also active wp cerber with custom Url and qtranslate deactivated it works the reset.  Always qtranslate creates an error with the wordpress social login plugin that makes me an unintentional redirect with wp content.

**Comment by pimoGit** [comment]
I use WPS Hide Login and qtranslate-x and I had no issue with updating on WP 5.2.
So, yep it would seem the issue would be specific with these 3 plugins, having conflicts with each other.
Have you tried to deactivate Gutenberg editor?

**Comment by sviluppomania** [comment]
No, because I do not have the gutenberg plugin, is integrated into the word word (?). The error is caused by something in QTranslate-XT

**Comment by pimoGit** [comment]
Yep, Gutenberg is part of the new core in WP.
But it's the most frequent cause of plugin issues in the 5.-- WP version.
That's why WP team itself is involved in plugin like this: https://wordpress.org/plugins/classic-editor/
to fall back to the classic editor.
That's what I meant.

**Comment by herrvigg** [comment]
I don't understand the problem. If it worked before WP5.2 why would it be a problem in qTranslate? You need to investigate better and provide synthetic and more accurate information. This is too confusing, i close this for now.

**Comment by herrvigg** [comment]
For precision, maybe it's the underlying functions called by WP Core that have changed, impacting qTranslate as a side-effect, but we'd need more info to do something here.
