### ISSUE TITLE
Problem with qTranslate (-x) Separate Comments

### ISSUE THREAD

**Issue by sviluppomania** [qtranslate/qtranslate-xt#688]
I decided to switch from qtranslate-x to the more updated qtranslate-xt.

In the qtranslate separate comment plugin file I had to change the url that was previously pointing to the x version at xt
But on the site as soon as I try to comment nothing comes out, in the back end it appears in number among the comments, but there is no "physically".

Thanks to those who will help.
I also attach the separate comment file, maybe something will be missed.

[qtranslate-separate-comments.zip](https://github.com/qtranslate/qtranslate-xt/files/3178834/qtranslate-separate-comments.zip)

**Comment by tuncbz** [comment]
Why did you close the issue. I need the solution for this issue. Thanks

**Comment by sviluppomania** [comment]
What is your problem?

**Comment by tuncbz** [comment]
Plugin "qTranslate(T) Separate Comments" is not working with qTranslate XT. But, it was working with qTranslate X.

**Comment by sviluppomania** [comment]
I solved it this way:

I opened the qtranslate file separated comment and changed from qtranslate-x / qtranslate.php to qtranslate-xt / qtranslate.php

**Comment by tuncbz** [comment]
Thank you sooo much.

**Comment by herrvigg** [comment]
Good you solved it! There are certainly other plugins that could be worth reviving, but all this should be done once things are more stabilized after we have migrated to the new repo with the new name.
