### ISSUE TITLE
qTranslate-XT not working properly with Asgaros Forum

### ISSUE THREAD

**Issue by hanzicode** [qtranslate/qtranslate-xt#694]
I have reported the issue here: https://wordpress.org/support/topic/not-working-with-qtranslate-xt as I thoght initally that the problem was due to the Asgaros Forum plugin. After talking to the plugin's developer, he suggested that I bring the issue here.

Basically qTranslate-XT somehow does not translate the Asgaros Forum menu items with the language switch. It displays the menu according to WordPress' default language setting. 

For items that it does translate, those are custom entries that are within my control so that I can enter using the [:] codes for each language.

**Comment by herrvigg** [comment]
This looks like a specific job of integration. You should look at the [integration guide](https://github.com/qtranslate/qtranslate-xt/wiki/Integration-Guide) that i have recently created as Wiki. Some links are still to be updated but the content should be correct.
Sorry but there is no support for integration tasks so i have to close this ticket unless you report a real bug. Maybe other users can also help you.
