### ISSUE TITLE
LSB on Profile Builder Pro

### ISSUE THREAD

**Issue by Kaique-Masi** [qtranslate/qtranslate-xt#695]
Hi, 
I'm building a multilingual website and I need that on subscribe the person submit some infomations and for this propouse I'm using Profile Builder Pro. 
Some of this information need to be translated and I want to let the person to set the translation.

How may I activate LSB on the input field? It's a Frontend field.

**Comment by herrvigg** [comment]
This looks like a specific job of integration. You should look at the [integration guide](https://github.com/qtranslate/qtranslate-xt/wiki/Integration-Guide) that i have recently created as Wiki. Some links are still to be updated but the content should be correct.
Sorry but there is no support for integration tasks so i have to close this ticket unless you report a real bug. Maybe other users can also help you.
