### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by sviluppomania** [qtranslate/qtranslate-xt#698]
Hi, the language plugin creates a redirect with the link of another plugin ... Turning off qtranslate xt there is no such problem.

the link is similar to this: https:/xxx.xxxxx.xxx/wp-content/plugins/wordpress-social-login/hybridauth/

the redirect makes it become with / it / or with / en /

**Comment by herrvigg** [comment]
@sviluppomania i can't do anything and i'd have to close this if you provide so little information. Try to put yourself as a developer reading this. Where does this link come from? What page, what context? Some redirects might be correct depending on what the user is doing. The only things we don't want for sure are redirects on API calls.

You didn't reply to my comments in your PR https://github.com/qtranslate/qtranslate-xt/pull/691. Did you update the permalinks structure from the admin permalinks page? It is a prerequisite to make things work as expected.

**Comment by sviluppomania** [comment]
What do you think there is little information?

The plugin, if active, starts a redirect to the aforementioned url.
How does that url come from? wp-content!

**Comment by herrvigg** [comment]
Sorry but i don't understand anything about the problem you are trying to describe. Put yourself as someone reading your ticket and trying to reproduce. Also. `wp-content` doesn't tell anything about the page you are trying to open. What is the "link" you are talking about? What are your settings? What are your trying to do? You have to describe the context way better. 

Just a side note, it is normal that you have some redirects on the front-end side depending on your current language and your URL settings of qTranslate. The current language is set with a cookie then there is a redirection. This is how qTranslate works.

**Comment by sviluppomania** [comment]
@herrvigg 

https://www.sviluppomania.com/it/wp-content/plugins/wordpress-social-login/hybridauth/

**Comment by herrvigg** [comment]
@sviluppomania again, it's really hard to understand you if you don't describe anything. I have no clue what this links points to, is that a post/page or something else?

But from what i see there is nothing wrong. Your URL is prefixed with the language after a redirection, this is the perfectly normal behavior of qTranslate (with the default URL options = pre-path mode which is also the recommended mode). Note you have a checkbox option to hide the default language.

The fact that the page doesn't load depends on your website, wordpress and/or web server configuration. I don't know what the link is and i can't debug your website. You might need some rewrite rules to handle this properly.

**Comment by herrvigg** [comment]
Also, You still haven't replied about the rewrite rules. You should update through the permalink admin page as stated earlier.

**Comment by herrvigg** [comment]
Moreover, i don't know the "wordpress social login" plugin but it doesn't look good to access a page through an "internal URL" with `wp-content` as you do.  I'm pretty sure it is not meant to be used like this. In general in WP you have friendly URLs that are handled through rewrite rules. This is certainly the problem here as the language prefix is not handled correctly by the underlying routine. You can add custom rewrite rules to you web server but before that i'd rather reconsider how the page is accessed from its user URL.

**Comment by sviluppomania** [comment]
Based on your last answer I say I don't know how you log in but that's a callback url and everyone uses that kind of url.

**Comment by herrvigg** [comment]
I don't know exactly how this plugin works and what you mean with the login but if the page doesn't load like this it's rather a problem of WP rewrites and/or web server configuration. Sorry but i can't do nothing at this point. You need to investigate more on this topic and provide more accurate information from a developer point of view.

**Comment by herrvigg** [comment]
@sviluppomania as i have revived the old help pages and transformed them to Wiki pages, i figured out there was a whole page describing the redirect stuff. You can find more info here: https://github.com/qtranslate/qtranslate-xt/wiki/Browser-redirection
