### ISSUE TITLE
New Wiki pages!

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#704]
hello,
i wanted to inform you that i have made quite a big update in the code to make all the hyperlinks to point to the new Wiki pages! Here they are: https://github.com/qtranslate/qtranslate-xt/wiki

The main reason is that the legacy website (https://qtranslatexteam.wordpress.com) is not maintained by anyone here. Some parts are already obsolete and it will only lead to more and more confusion as the plugin evolves. Also, i wanted to bring everything back into this project, so we can manage everything here. This was also one of the tasks i wanted to achieve before going on with the new plugin migration. The doc should follow the project and it has to be maintained.

There's still some work to do inside the current Wiki pages, some of the content is obsolete and some links are still pointing to the old website. Many parts still need to be reviewed but it's a good starting base and now we have everything "in the house". The Wiki format has some limitations but the pages structure should not change too much now. I've started to update some of them, this will go on little by little. Also, i'm trying to simplify some parts to make it more maintainable. The previous website is very verbose with many repetitions and it's easy to get lost.

You're welcome to take a look at it. I will later add a toolbar for more convenient menu. There's some useful content for those working with integration... or struggling with it :P

**Comment by herrvigg** [comment]
All right so i've just added a small menu in the Wiki, that should be useful for the overview and also to reach the main guidelines, especially for the integration: https://github.com/qtranslate/qtranslate-xt/wiki

**Comment by herrvigg** [comment]
It was quite a hell of a work but I completely reorganized the old [main FAQ](https://github.com/qtranslate/qtranslate-xt/wiki/FAQ), now with sub-sections for better readability. All the wiki links are internal to wiki which is much better for maintenance (Wiki detects if the internal link is valid or not). A few parts may still be obsolete but this should look way better now!

Among other things. i created a new page for the [front language switching](https://github.com/qtranslate/qtranslate-xt/wiki/Front-language-switching) which was previously lost in the FAQ. 

Last but not least, there is now a [new menu](https://github.com/qtranslate/qtranslate-xt/wiki) that should help a lot for the navigation.

**Comment by HowToSolutions** [comment]
Hi, 

I'm not sure if this is the right place to point out possible mistakes in the Wiki page, but I noticed 2 mistakes and I couldn't find a way to fix them myself.

In Wiki FAQ page, when showing examples of language tags, there is an example of the obsolete way, but it's only showing text without tags:

`English TextDeutsch` 

This should probably be:

`<!--:en-->English Text<!--:--><!--:de-->Deutsch<!--:-->`

Also, right after the above example, there is explanation about "_closing tag right before the opening tag is redundant_" and the example for it still contains the closing tag right before the opening tag.

**Comment by herrvigg** [comment]
@HowToSolutions thanks for reporting this. I've fixed the missing tags and clarified the counter-example.
