### ISSUE TITLE
ACF image field rendering

### ISSUE THREAD

**Issue by doannguyen263** [qtranslate/qtranslate-xt#708]
I use Advanced Custom Fields PRO 5.8.1, Image display error is too large.
Please add class: .image-wrap in class: view show-if-value acf-soh in line 164, 
File: qtranslate-xt/modules/acf/src/acf_5/fields/image.php

**Comment by herrvigg** [comment]
@doannguyen263 Yes the original ACF rendering has this class so this is an easy fix.

But now i see the problem: this code is duplicated and this is bad for maintenance. Ideally you would rather call the ACF rendering code to avoid this kind of problems on the long run, if the parameters allow the special treatment for qTranslate. Only if this is not possible the code should be duplicated. Note this doesn't only concern the image field, it should be done for all the other fields we handle!

For now we can have a quick fix keeping the code duplicated but at least we should double-check the different versions between our rendering and the original ones, here in `advanced-custom-fields/includes/fields/class-acf-field-image.phpclass-acf-field-image.php`. For example we don't have this <label class="acf-basic-uploader">`, which is shown when there is no value i guess. Could you check all this and do some tests?

**Comment by herrvigg** [comment]
@doannguyen263 all right i resynched the whole rendering, merged in master.
I don't think we should do some different rendering for QTX. As said the code duplication is quite bad and it should be solved differently but let me know now if the rendering works for you (it should do exactly as ACF does beside the container div with CSS `multi-language-field multi-language-field-image`).
