### ISSUE TITLE
Post name reset on editing

### ISSUE THREAD

**Issue by Kaique-Masi** [qtranslate/qtranslate-xt#711]
Hi, 
My website has Portuguese, English and Spanish language set and when I creat a new post it works just great but if I need to edit this post later, the title resets and stay empty. The permalink it's okay, only the title crashes. 

![bug title](https://user-images.githubusercontent.com/49401695/61327819-2c602980-a7f0-11e9-8bff-cb0dcf8434ac.JPG)

**Comment by Kaique-Masi** [comment]
I realize now that if I use "quick Edit" it works

**Comment by herrvigg** [comment]
I can't reproduce this so i would need more debug info. Do you see any error in the browser console? What happens if you put the same title value for all the 3 languages? Do you have some special characters in the title?

**Comment by asanti82** [comment]
Not sure if this is the same issue, but in the admin after editing it resets the title back to the original language even though the slugs are saved correctly.  Attaching pictures.

what i did notice inspecting the code the hidden fields for both languages have the same value.

![edit-1](https://user-images.githubusercontent.com/957595/61660721-23f46c80-ac90-11e9-99f5-7877e655801f.png)
![edit-2](https://user-images.githubusercontent.com/957595/61660722-23f46c80-ac90-11e9-95d4-0d723768b177.png)
![edit-3](https://user-images.githubusercontent.com/957595/61660723-248d0300-ac90-11e9-927e-22b4722b00c8.png)

**Comment by asanti82** [comment]
Looking at the database I found that from some reason it's not saving 
`[:en]En title[:cs]Cs title[:]`

I changed it manually in the DB and it shows correctly in the edit screen but as soon as I hit update it reverts back to the english version and removes the other language and removes all lang formatting in the DB.

**Comment by Kaique-Masi** [comment]
Hey @asanti82 it's not the same issue. On my side the languages is working fine what happens is that when I update some post, the title of all languages became blank... If I put the title again and save it becomes blank again. If I use quick edit it works fine.
When I creat the post everything works as it should.

**Comment by Kaique-Masi** [comment]
> I can't reproduce this so i would need more debug info. Do you see any error in the browser console? What happens if you put the same title value for all the 3 languages? Do you have some special characters in the title?

@herrvigg No errors on console. I put the same title for all languages and when I saved it becomes blank again. I have some titles with accent only but I have some other that don't have and it's not working too.

I realized that this error only occurs on a specific post type created by me... The stranger thing is that I have 4 post types and only one have this issue.

**Comment by herrvigg** [comment]
@Kaique-Masi maybe there's some other plugin conflicting for that particular post type?

@asanti82 thanks for the help. I'm not sure where to look. 

For both: could it be the case that you have a auto-save feature activated by another plugin? If i'm not wrong, qt-XT disables the auto-save because it can't manage it correctly.

**Comment by asanti82** [comment]
@herrvigg I think maybe the classic editor plugin could be causing an issue.  I will try to make some more tests and let you know

**Comment by herrvigg** [comment]
Could this be related to https://github.com/qtranslate/qtranslate-xt/issues/724? I didn't make the connection when the new ticket was submitted, but this looks pretty much the same case.

**Comment by herrvigg** [comment]
Still not sure it's the same issue, but it seems we have found a workaround for #724 which consists in deleting the cookies. I also sent a preventive fix in 3.6.3.

However - if it happens before you switch to 3.6.3, please keep your cookies values as they are and let me know before deleting them. From that i may understand better.

**Comment by herrvigg** [comment]
@asanti82 for information, the hidden fields are only updated when you switch tabs OR publish (in that case the page is reloaded from the server). If you first edit EN then switch to CS, the CS fields will remain with the previous values, that's normal.

It seems something can go wrong with the cookies, most likely coming from `qtrans_admin_language` or `qtrans_edit_language`. If you have the values of such when the problem occurs that could be useful.

**Comment by herrvigg** [comment]
The reason of the problem is now much clearer, for more technical details see #741. This one can be closed.
