### ISSUE TITLE
Admin role after accessing WP Customizer section

### ISSUE THREAD

**Issue by gabrielecker** [qtranslate/qtranslate-xt#712]
Whenever an admin enters the "Appearance" > "Customize" in admin panel the session seems to completely break, he can't edit anything and the page shows some default WP permission exception "cheating uh..? no permission ....."
Then if he returns to admin panel it no longer shows admin role in his profile (only subscriber)

May be some incompatibility with another plugin but I've tested multiple times and it only happens when qTranslate is active
I have no idea if this matters but I'm using multisite as well
Also when doing all of this as a superadmin it doesn't crash, only as regular admin

**Comment by herrvigg** [comment]
The multi-site mode is quite a difficult case to test. Maybe there's some admin redirection that doesn't work well but i can't really say. If you can do more investigations it could help.

**Comment by herrvigg** [comment]
@gabrielecker keep us updated if you want the issue fixed. I close for now, feel free to re-open if you can provide more info.
