### ISSUE TITLE
Work plugin with custom layouts (DIVI)

### ISSUE THREAD

**Issue by SDSDsfggg** [qtranslate/qtranslate-xt#717]
Hello to everyone from Russia. An explanation is needed about how the plugin works with custom layouts. I use them to card merchandise. The plugin works fine with everything except custom layouts. He does not translate them, although I am updating the page in the editor, as on regular pages. The plugin simply creates two copies of the content (see screenshot). Should this work with DIVI? 
![22](https://user-images.githubusercontent.com/43116848/62290097-282b4180-b469-11e9-90c4-141fc9af7e59.jpg)

**Comment by herrvigg** [comment]
I don't know this plugin but this is a question of specific integration. You may first look at the [Integration Guide](https://github.com/qtranslate/qtranslate-xt/wiki/Integration-Guide) and possibly some existing code e.g. in the modules. 

If this is about the content of a normal post something prevented the parsing of the language tags. Is there still the closing tag `[:]`?

**Comment by myroslambda** [comment]
I am not a divi expert. Based on what I can see on the web interface, Divi offers us a custom editor, and we have no way of introducing the `[:en]` tags. If I try to switch to the standard wp editor after creating divi content, I am told the divi content will be removed completely.

We have a full divi license and I can try things. I have the latest stable release of qTranslate-XT installed right now.

**Comment by herrvigg** [comment]
See also #769 and #203 which provide more information so I close this one.
