### ISSUE TITLE
Media gallery images not showing when plugin enabled

### ISSUE THREAD

**Issue by gab1982** [qtranslate/qtranslate-xt#719]
Hi I have version 3.6.1 of your plugin and the latest version of wordpress (everything is up-to-date), and have used it for a few months now however only last week I noticed an issue which I hadn't noticed before, I was unable to add or view images in the media gallery. I use ACF and in particular this issue I noticed with the gallery when I went to add photos to the gallery while your plugin was enabled it showed an error when importing and no previously uploaded images in the media gallery (even though there are lots). I found this strange as mentioned I have been using your plugin for sometime now and haven't had an issue before.

**Comment by Tusko** [comment]
duplicate https://github.com/qtranslate/qtranslate-xt/issues/718

**Comment by mlm-support** [comment]
Issue: Add Media (Images ...)
System: PHP 7.3.7, WP 5.2.2, QT-XT 3.6.1
Error: ACF(-Pro) 5.8.3
Success: ACF(-Pro) 5.8.2

**Comment by fminov** [comment]
@Tusko thanks for pointing me to this thread
@mlm-support I tried to go back to ACF-Pro 5.8.2, sadly this doesn't work either

**Comment by herrvigg** [comment]
See #718, i don't understand how qTranslate would be involved here. This looks like an issue in ACF.

**Comment by herrvigg** [comment]
This looks like a duplicate so better keep the discussion in one topic only. I close this for now.
