### ISSUE TITLE
Problem when used with Advanced Custom Fields

### ISSUE THREAD

**Issue by amouratoglou** [qtranslate/qtranslate-xt#721]
Hey guys, first of all, thanks for keeping this alive... I have a bunch of legacy projects that run on this plugin, and it had so many ups and downs, it's great to see it is so active again (after all these years!)

I've found a little bug when using with ACF. While editing the taxonomy term custom fields, the title of the "fields group" appears before the fields, but without being translated, exposing the [:en] language tags directly.

https://ibb.co/TcNJr1f

**Comment by herrvigg** [comment]
It looks like a filter call missing somewhere. I'm not sure the problem is with ACF though, it could be some other plugin reading and displaying the raw field. Are you using another plugin for this block display with the image?

**Comment by herrvigg** [comment]
If you inspect the element (right click with most of the browsers) what kind of classes do you see on it? If you show the part of the DOM tree around this element (even with a screenshot) it could help to identify the origin of the field.

**Comment by herrvigg** [comment]
@amouratoglou keep us updated if you want the issue fixed. I close for now, feel free to re-open if you can provide more info.
