### ISSUE TITLE
Performance hit when no trailing slash for language code

### ISSUE THREAD

**Issue by sailinf** [qtranslate/qtranslate-xt#727]
I tested my site with some different settings and here are the results. Using latest version of XT + Cache Enabler for the cache. Site has Finnish (fi) as default language and English (en) as secondary. Load times for main page using Pingdom, page size is about 3M

site.fi - 1,70 sec
site.fi/en/ - 1,74 sec
site.fi/fi - **2.78** sec
site.fi/en - **6,07** sec

Why are these numbers a problem? The problem is that the language switcher currently omits trailing slashes (eg uses site.fi/en instead of site.fi/en/ ) which gives quite a performance hit for switching language with the language switcher.  

Please add trailing slash (and omit language code all together for default language?)

**Comment by bagaweb** [comment]
@sailinf I'm glad that my line of code worked for you! I noticed that in #660 I forgot to specify which line needed to be changed.

And I absolutely agree with you that slugs should be integrated natively in the plugin without using another plugin or modules but I know that @herrvigg is doing a great amount of work here and unfortunately this is not one of the priorities.

**Comment by herrvigg** [comment]
qTranslate slug is a separate plugin, so i suppose i can close this here. If there is something that can be done please send a PR.
