### ISSUE TITLE
Custom Fields and Standard Fields: LSB doesn't work simultaneously

### ISSUE THREAD

**Issue by valikwork** [qtranslate/qtranslate-xt#731]
When I check the "Enable translation for Standard Field Types", LSB only work properly on option fields (header, footer) and wysiwyg - switches content of each input accordingly to the language. 

![Screenshot_5](https://user-images.githubusercontent.com/50335036/64912184-51134780-d734-11e9-87f8-1eb5011689f5.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/50335036/64912188-55d7fb80-d734-11e9-9b67-acba444ea7c4.jpg)

**At that moment, on pages with custom fields, LSB stops switching content of each input.**

![image](https://user-images.githubusercontent.com/50335036/64912246-13fb8500-d735-11e9-9c0d-9b4c2b11e6ee.png)

![image](https://user-images.githubusercontent.com/50335036/64912251-22e23780-d735-11e9-88f5-ea653d1664dd.png)

Although, it definitely has different languages content.

![image](https://user-images.githubusercontent.com/50335036/64912259-54f39980-d735-11e9-98cc-1b0cfbfc5f3b.png)

When I **don't** check the "Enable translation for Standard Field Types", **the vice versa happens**:
Option Footer/Header/Wysiwyg shows all content with shortcodes.
![image](https://user-images.githubusercontent.com/50335036/64912331-507bb080-d736-11e9-91bc-d40fd42ceda4.png)

And on page with custom fields editing, everything works just fine (exept Wysiwyg fields)

![image](https://user-images.githubusercontent.com/50335036/64912368-be27dc80-d736-11e9-970c-cc43d2e17d83.png)

![image](https://user-images.githubusercontent.com/50335036/64912370-ca139e80-d736-11e9-8e3c-13ce2f6a795e.png)

Can someone, please, help? This is the only issue.
Thanks!

**Comment by herrvigg** [comment]
hello,
this looks like a bit more specific issue with ACF and maybe even another plugin. I don't use ACF, i just installed it for debugging and i couldn't reproduce this. Where is the "Theme Footer settings" coming from? It doesn't look like a standard feature, as what you describe the option fields (header, footer) and wysiwyg. Also, same question for "Home Page / Home Page Main Heading" ? I don't have those, at least i couldn't find them.

**Comment by herrvigg** [comment]
@valikwork keep us updated if you want the issue fixed. I close for now, feel free to re-open if you can provide more info.
