### ISSUE TITLE
/qtx_import_export.php on line 26

### ISSUE THREAD

**Issue by horospoi** [qtranslate/qtranslate-xt#732]
Help me! wp 5.2.2 error activating plugin
https://c2n.me/43CPQaX

**Comment by herrvigg** [comment]
There's just a basic array declaration:
https://github.com/qtranslate/qtranslate-xt/blob/92e7ac1134e3f8a9e6efe7e7ddc4691ff397375b/admin/qtx_import_export.php#L26-L28

Which PHP version are you using? The brackets notation was introduced with PHP 5.4 in 2012... like a century ago 😅

**Comment by herrvigg** [comment]
In fact, on activation qtranslate only checks for PHP5.3+ but it should be PHP5.4+, this is a strict requirement. I won't downgrade the code for support of obsolete PHP versions.

You should really upgrade to PHP7, the current version is 7.3. Unless you have very old non-maintained plugins there is no reason not to upgrade. PHP 5 is not maintained anymore, it ended 31 december 2018.

**Comment by horospoi** [comment]
currently there is php version 5.6 / need to upgrade to php 7?

**Comment by herrvigg** [comment]
I was tempted to put 5.6 as a minimum requirement to give an extra incentive, but i kept 5.4 only to stay conservative. This is the strict minimum. I upgraded the recommended version to 7.3, you should definitely try to use that one. There are huge perf improvements with PHP7, though many of them came already with 5.6. These versions are not maintained anymore, the more you wait to upgrade, the more security issues you will have.

**Comment by horospoi** [comment]
Thanks It works! 
Question. Can a plugin translate texts automatically?

**Comment by alphp** [comment]
> Question. Can a plugin translate texts automatically?

I know of other plugins that have assisted translation, what I like about this is precisely the opposite: all translation is the responsibility of the editor / publishers.
If you want a machine translation you have other solutions.
