### ISSUE TITLE
404 for all pages with pre-path mode

### ISSUE THREAD

**Issue by knyttl** [qtranslate/qtranslate-xt#733]
Hi,

I am getting 404 for all pages in pre-path mode. I am using current `3.6.2` version and current Wordpress (I even tried downgrading).

I am trying to debug the code - I found out about field `wp-path` which should be the clean path that is passed to wordpress. For instance for homepage `/en/` this becomes `/` which is correct, but Wordpress still shows 404. Once I change the pre-path mode to query `?lang=en` it works correctly. Can you lead me to the place where `wp-path` is passed to wordpress?

**Comment by reddo** [comment]
Stupid question, but are you sure your .htaccess is set up correctly?

**Comment by knyttl** [comment]
Yes, everything else works correctly.

**Comment by knyttl** [comment]
If I find the cause, I would even happily create a pull request, but I am stuck as I just don't see where this path is passed to wordpress.

**Comment by knyttl** [comment]
I can see that Wordpress still receives `/en/` and throws 404 as `en` is not a category

**Comment by reddo** [comment]
what is your permalink structure? try playing around with that, but first, try just saving the permalink structure as is.

**Comment by knyttl** [comment]
I tried to save it, change it to something else, but the issue is still the same.

![Screenshot 2019-09-18 at 10 51 00](https://user-images.githubusercontent.com/401107/65133007-3aa21000-da02-11e9-84df-755425a4dbe5.png)

**Comment by knyttl** [comment]
there might be issue that I migrated from the old `qtranslate` plugin. is it possible that there is some old config options in db which influences it?

**Comment by reddo** [comment]
qtranslate without the x? the really old one?

**Comment by knyttl** [comment]
sorry, i meant qtranslatex

**Comment by reddo** [comment]
I've also migrated from that one without any issue.

**Comment by knyttl** [comment]
so would you help me finding the place where the plugin tells wordpress the fixed url?

**Comment by reddo** [comment]
I don't think I can help you with that :(

**Comment by knyttl** [comment]
Can somebody comment on these variables:
- `doing_front_end`
- `language_neutral_path`
- `path` vs `original_url` vs `wp-path`

For instance - I have a request `/en/news` so language should be `en` and wp-path `/news`. Why there is original_url when it is equal to path?

**Comment by herrvigg** [comment]
At first sight this looks like a problem of configuration in your web server, but who knows. It is a bit weird it is taken as a category so it may actually be something from WP or even another plugin. Or some combination with qTranslate going wrong.

What qTranslate does is just redirecting to another URL in case your cookie lang value does not match the language to be displayed (`doing_front_end` is for end-user page by opposition to admin pages). Does this problem still happen if you disable qTranslate and go to a pretty URL on a page? You may try to uncheck "Hide URL language information for default language."
