### ISSUE TITLE
Error: Could not find file ".t-3.5.3/i18n-config.json

### ISSUE THREAD

**Issue by Masikasipa** [qtranslate/qtranslate-xt#734]
Hi,

I recently installed qtranslateXT. Since then the dashboard shows the message 

> 
"qTranslate-XT: Error: Could not find file ".t-3.5.3/i18n-config.json" listed in option "Configuration Files". Please, either put file in place or update the option. Once the problem is fixed, re-save the configuration by pressing button "Save Changes" on plugin settings page." 
> 

(Checked filezilla: Where should "t-3.5..." be? I can't find such a folder neither on the server nor in the zip file of the plugin... )

I thought it might be because qtranslateX was still installed (but deactivated). So I deleted both plugins and reinstalled qtranslateXT manually. Unfortunately the message appears again. 

If you want to write an article, the editor always switches automatically to "English", although the basic language is German. As soon as you have written something in German in the window and click on "Publish", the German input is deleted, German text and title disappear and it is switched back to the English page.

Is the problem already known and if so, is there a solution? At the moment I can neither edit articles nor add new ones... 

Any ideas really appreciated!

Greetings,
Alex

**Comment by herrvigg** [comment]
The options remain in DB even after uninstall so it's likely coming from those.
Check your options in `settings/languages/integration/configuration files`. If you remove all and save, it should come back to the default value which is `./i18n-config.json`. From a clean install you don't need anything else. 

About the switch to english i don't know, this looks like a different issue.

**Comment by herrvigg** [comment]
If you really want to wipe out all the options settings it's possible in SQL but the easiest way is certainly to use the reset feature from the import/export tab in the options. You need to check 2 boxes as a confirmation. This cannot be reverted (unless you dump your DB on your own).

**Comment by Masikasipa** [comment]
Wow, that was a quick fix. The error message has disappeared. And you were right, the problem with the editor switching automatically to the second language and deleting all first language content unfortunately remains. Should I open another thread for this? I'd first check if there was an interference with another plugin.

**Comment by herrvigg** [comment]
Good! Yes please open a new ticket for the other problem, for clarity. I close this one.
