### ISSUE TITLE
php-Warning on php 7.x

### ISSUE THREAD

**Issue by fs-plugins** [qtranslate/qtranslate-xt#735]
PHP Warning: Cannot modify header information - headers already sent in /www/htdocs/..../wp-content/plugins/qtranslate-xt-master/qtranslate_core.php on line 425

WordPress 5.2.3

**Comment by herrvigg** [comment]
This means some data was sent by the server before the HTTP headers, it does not necessarily come from qTranslate though the error is raised here on `setcookie` (which can't do anything if the headers are sent). I don't have this problem, so the first thing would be to see what is the actual content of the sent data. You can also try to disable other plugins.

**Comment by fs-plugins** [comment]
thanks
i activate debug and test other influences

**Comment by fs-plugins** [comment]
no success in the search, it can come from a plugin as well as from your own file
in debug i don't get a more meaningful info

is there any other way to determine the trigger? it's a productive system...

**Comment by herrvigg** [comment]
Open the page source (CTRL+U with Chrome) and check what is written just before "PHP Warning", it should give an indication.

**Comment by fs-plugins** [comment]
i can't provoke it, the error occurs with some user access

**Comment by herrvigg** [comment]
What do you mean? I won't be able to do anything if you can't provide the info. If some other plugin write data before the headers it will have some other impacts, it's not just a warning. For instance if the qtranslate cookie can't be set you won't be able to switch language properly.

**Comment by fs-plugins** [comment]
I mean, I don't know where and where the problem occurs. If any user accesses the pages, the message is triggered - I can't see this in my browser. I cannot deactivate the few plugins, because then the website is no longer usable and the error would not be triggered anyway.
That's why I'm asking how I could identify the triggering point, the php concerned.
All attempts to go through the pages and use the different functions didn't bring the message, but there are also too many possibilities

**Comment by herrvigg** [comment]
Well, ask you user to provide this info...

**Comment by fs-plugins** [comment]
this warning does not appear in the user area?

**Comment by herrvigg** [comment]
I don't see any problem. Sorry but i can't really help more with this, it's up to you to find a solution for your website. Disable the cookie but you will break some functionalities. I can't do much more, this is a far too generic error. To be clear, the warning is not the error but the consequence of another error happening before that.

**Comment by fs-plugins** [comment]
OK, thanks for being so helpful.

**Comment by herrvigg** [comment]
I don't know if this was ironic, but really i can't do anything if you don't provide any information.

**Comment by fs-plugins** [comment]
not ironic!
no, i have no information - no debug entries, no other errors in the log's

**Comment by herrvigg** [comment]
Just to explain what is happening:
```
// some plugin (it can be qtranslate... or any other)
echo " "; // someone write something it was not supposed to... who and what?
// qtranslate init
setcookie(); ->// now this is too late for doing this -> this is the warning you see
```

**Comment by herrvigg** [comment]
It is very likely it comes from another plugin, in a very specific case. But it's impossible in qTranslate to understand where it comes from, because it's already too late.

**Comment by herrvigg** [comment]
The only thing you can try in qtranslate is to raise the priority from 2 to 1 here:

https://github.com/qtranslate/qtranslate-xt/blob/362ee365cd16ba518be771e623a9078d46b90e20/qtranslate_core.php#L142

But i don't recommend this, because it might have some other side effects... there was certainly a good reason of having a priority of 2.

**Comment by herrvigg** [comment]
> I mean, I don't know where and where the problem occurs. If any user accesses the pages, the message is triggered - I can't see this in my browser

But it's not for all users, for example i don't see the error. Do you have a section with special credentials or whatsoever? I really think the best for you is to find a user for which the problem occurs and who can help you to debug. Then try step by step to nail the issue down.

**Comment by fs-plugins** [comment]
thanks again for all your hard work.
I can't find the cause without any problems, but everything seems to work - so I'll leave it at that for the time being

**Comment by herrvigg** [comment]
Two other things:
- it is enough to have a single character sent by having a white space by mistake just before the first opening PHP tag ` <?php your file... `. That can be hard to find from visual inspection.
- if it's related to given users, it can be due to something specific with PHP sessions or user data stored in cookies, or given browser settings. But in that case you should have some useful information that allows you to track the origin of the problem.

Good luck!

**Comment by reekrd** [comment]
I've also run into this warning on a server that runs PHP-FPM and where the function fastcgi_finish_request exists. 

When a WP-Cron is triggered wp_cron.php set's a header and calls fastcgi_finish_request() 

I added a check in `qtranxf_setcookie_language` so it does not set the cookie when a WP-Cron job is running

`
if( !defined( 'DOING_CRON' ) && !headers_sent() ) {
    // only meant for server-side, set 'httponly' flag
    setcookie( $cookie_name, $lang, strtotime( '+1year' ), $cookie_path, null, $q_config['use_secure_cookie'], true );
}
`

Perhaps there is a cleaner way of doing it?

**Comment by herrvigg** [comment]
@reekrd good catch. If this is a problem only with the cron, this could explain it.

See this line:
https://github.com/qtranslate/qtranslate-xt/blob/591fb09c426570d1e0fb216d76827671f264ee37/qtranslate_core.php#L224

Could you try to change it with this?
```
 $url_info['set_cookie'] = ! wp_doing_ajax() && ! wp_doing_cron() && ! qtranxf_is_rest_request_expected(); 
```
Let me know if this fixes the problem.

**Comment by herrvigg** [comment]
@reekrd any news about this?

**Comment by reekrd** [comment]
@herrvigg sorry haven't had a chance to test as it's only our production server that is configured to run PHP-FPM

**Comment by reekrd** [comment]
@herrvigg I've had this running on the production server for a while now and there are no longer any warning in the log.

**Comment by herrvigg** [comment]
@reekrd thanks for the update.

@fs-plugins what's the status on your side? Can we close this ticket?

**Comment by fs-plugins** [comment]
can be closed, thank you
