### ISSUE TITLE
Code formatting: tabs or spaces?

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#737]
The crucial question for all developers, do you prefer tabs or spaces?

Currently i've been using what was the main format from qTranslate-X, using tabs (tab size 4) also because it was the standard WordPress format.

However personally i prefer spaces with size 4. From my experience it is easier to handle when switching between editors or dealing with many pull requests from different users.

One other thing concerns the HTML code, in general the standard is more to use 2 spaces. With the PHPStorm editor it is possible to handle mixed formats for same files, but this can be harder to deal with other editors. The fact is that many PHP files have also big HTML blocks.

The final part concerns Javascript. Here the standard is more 2 spaces (callback hell...), but now it seems that 4 spaces is also becoming quite popular.

I tend to think a unique format of 4 spaces would be the best.

Any comments?

**Comment by mlm-support** [comment]
Since the intensive use of the Zend Framework I follow the recommendations to PHP standards of the PHP Framework Interop Group.

**Website**
https://www.php-fig.org/

**Comment by herrvigg** [comment]
That's really a good point!
https://www.php-fig.org/psr/psr-12/#24-indenting

> Code MUST use an indent of 4 spaces for each indent level, and MUST NOT use tabs for indenting.

Which comforts me for that change that will be part of next release.
I will also apply the same for the JS code. Regarding embedded HTML i will see a bit. PHPStorm is quite powerful to mix different stylings, but it may be a problem for others.
