### ISSUE TITLE
Editor input is deleted in main language upon updating

### ISSUE THREAD

**Issue by Masikasipa** [qtranslate/qtranslate-xt#739]
What happens:
I use two languages with qTranslateXT, the main language is German, the second English. When I write a new article in German and click on "Publish", the content suddenly appears in the English version. The German editor and title are then empty. The same happens if I insert text on a German page again and click on "Update". Again the whole German text disappears and moves to the English translation page. Since the transition from qTranslateX, the problem has appeared in all articles, no matter how old they are. 

Environment:
- last qTranslate-XT version; I also deleted qtranslateX. When that alone didn't work, I deleted qTranslateXT again and reinstalled it manually. Does not change anything. 
- WordPress 5.1.2
- Browser: Chrome, IE, Firefox, Safari... doesn't matter, appears on all browsers
- Plugins used: All plugins switched off and on again. Even if all other plugins are deactivated, this does not change anything. 

Screenshots:
Example how I try to write a new article. Example text on the German page, no text on the English page, then clicking on "Publish". Screenshot 3 shows the result: A blank page on German page, the German text on the English translation site.

![issue1](https://user-images.githubusercontent.com/7370251/66121003-77622f80-e5dc-11e9-9454-ae3a6e7f41a7.jpg)
![issue2](https://user-images.githubusercontent.com/7370251/66121004-77fac600-e5dc-11e9-99b4-18369927ad04.jpg)
![issue3](https://user-images.githubusercontent.com/7370251/66121007-77fac600-e5dc-11e9-99c3-5147cc68226c.jpg)

Any ideas to solve the problem very appreciated. Up to date, I cannot upload or update even one single new article due to this issue.

**Comment by Masikasipa** [comment]
Note: Reading the last posts in #724 I've again deleted all cookies. Now it seems to work in one article using Internet Explorer as browser. I'll check again with others.

**Comment by herrvigg** [comment]
Yeah, there's still a real issue that i never managed to reproduce. I'd need to have the state of the cookies to understand... Hopefully we have a workaround but this will not help to fix the issue. As soon as someone can reproduce this and have no emergency to publish please let me know. We need to find a real fix!

**Comment by herrvigg** [comment]
But what is more surprising here, is that you have switched browsers apparently. They don't share cookies so how is that possible that all fail at the same time?! Complete mystery to me at this point...

**Comment by herrvigg** [comment]
> Since the transition from qTranslateX, the problem has appeared in all articles, no matter how old they are.

Did you migrate recently from -X to -XT? Did this problem appear just after migrating or was it after some time with -XT?

> I've again deleted all cookies. Now it seems to work in one article using Internet Explorer as browser.

If it fails with the other browsers please keep the cookies as they are and let me know.

**Comment by Masikasipa** [comment]
> But what is more surprising here, is that you have switched browsers apparently. They don't share cookies so how is that possible that all fail at the same time?! Complete mystery to me at this point...

It's probably not that mysterious after all. ;) I remember that at the very beginning of the website  I tested its functions on all the browsers mentioned. Probably logged in, even if it wouldn't have been necessary for testing. With Chrome, IE and Firefox I found ancient cookies, after deleting them it works.  

>Did you migrate recently from -X to -XT? Did this problem appear just after migrating or was it after some time with -XT?

It happened right after switching to qTranslate XT, but having still installed qTranslateX (deactivated). After the problems occurred, I first deleted qTranslateX instead of just deactivating it. Then I deleted qTranslateXT again and reinstalled it.

**Comment by herrvigg** [comment]
OK. I really don't see what is special after switch to -XT especially from the client point of view... but let's keep an eye on this. It would be good if others having this problem can confirm this or not.

> With Chrome, IE and Firefox I found ancient cookies, after deleting them it works.

Sad you didn't keep at least one failing... we really need a setup where the problem can be reproduced. Otherwise there's almost no chance it can be understood and fixed.

**Comment by herrvigg** [comment]
The reason of the problem is now much clearer, for more technical details see #741. This one can be closed.
