### ISSUE TITLE
Content overwrite due to duplicate cookies

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#741]
It seems the `qtrans_edit_language` cookie can appear with different values, related to different paths... and THIS is the reason for the problematic bug with the content overwriting reported in #724, #711, #739.

Here is a slightly modified screenshot that @mlm-support provided (thanks again!):

![image](https://user-images.githubusercontent.com/19155375/66345395-4b360e00-e950-11e9-8a97-280e9b7a28f5.png)

This cookie corresponds to the current tab being edited. This tells to the server for which language the visible fields should be stored.

What happens is that the server then reads a wrong value,.. because this cookie is somehow duplicated! Here the problem comes from the version with the trailing slash. By cleaning the cookies, this problem disappear (at least temporarily).

Now let's see more in details...

For some reason, the cookie exists with double path, and apparently both are sent to the server from my custom tests (it seems there is no HTTP filtering here). When the POST data is collected server-side, this cookie tells which are the last fields that have not been transferred to the `qtranslate-fields` counterparts. This happens in that infamous `qtranxf_collect_translations_posted` (which i don't like for other reasons #729). But on the server-side, the PHP engine only keeps a single value. And... in that case it prefers the one with the trailing slash, probably because it matches more closely the REQUEST_URI. No luck, this is the one with the bad value!! 🤦‍♂ 🍾 

Now let's see what happens on the client side. This cookie is supposed to be a session-only cookie. It is written with `document.cookie=' qtrans_edit_language=' + lang`. But no path is given.

So the question is why this double instance? My understanding is that there was a change in how the browsers write those, or another side-effect that is still not clear to me. OR something coming from an old code in qTranslate-X... but i don't think i changed anything here... or i made a mistake. 

In any case it would be great to get rid of this cookie. In general they should be avoided as much as possible because they create many problems. I already managed to get rid of one for the options (`qtrans_admin_section`), which is now managed by sessionStorage because we never need it on the server (see commit  https://github.com/qtranslate/qtranslate-xt/commit/6922e5855eba63edb314e9a45a2fdbc5e98ff8e7).

Now we have those left:
- qtrans_edit_language: set by client, session cookie
- qtrans_admin_language, set by server
- qtrans_front_language, set by server

I think the server ones are pretty okay-ish. The front one is really the key one for all the current redirection system. I'd prefer without them as this can create problems for the REST API and AJAX calls. But we can still live with those for a bit...

Now let's find a good solution for this `qtrans_edit_language`.

**Comment by herrvigg** [comment]
OK fix now merged in master. 

In related news, there are no more session cookies created by the client at all! No more crazy paths. This should improve the stability a lot. There are still 2 cookies created by the server, but they are less problematic (though i'd also like to get rid of those).

In short:
- obsolete session cookies (you can force delete those)
  - qtrans_edit_language
  - qtrans_admin_section
- new items in sessionStorage (replace those cookies, no vital)
  - qtranslate-xt-admin-edit-language
  - qtranslate-xt-admin-section
- still in-use cookies (created by server, yet quite critical)
  - qtrans_front_language
  - qtrans_admin_language

I also added a very strict check on the hidden field when parsing the request server-side. With translatable field it should ALWAYS be provided, otherwise the request would be invalid so i decided to throw an exception there.

For more technical details see commit https://github.com/qtranslate/qtranslate-xt/commit/e26263dfe17b522d42d52569108ee03d85aa9bf3.

Tester welcome!
Important reminder: you have to patch your QTX_VERSION if you don't use DEBUG_MODE in order to go around the client cache. Just add a random text behind like `3.6.3-patch-xxx`.

**Comment by mlm-support** [comment]
The base functionality (no extensions) has been tested ...

**URL Modification Mode**
[-] (1) Use Query Mode
[x] (2) Use Pre-Path Mode (Default)
[x] (3) Hide URL language information for default language 
[-] (4) Use Pre-Domain Mode (Subdomain)
[-] (5) Use Per-Domain mode: specify separate user-defined domain for each language

**Cookie Settings**
[x] (6) Disable language client cookie "**qtrans_front_language**" (not recommended).

**Note**
If (2) and (3) are activated, the language switching (frontend) does not work without the cookie although this would be technically feasible. In this case, (6) must still be disabled for the half-dead cookie to perform its service. This configuration is probably not recommended because the default language could change as well.

**Comment by herrvigg** [comment]
Great, thanks for testing!

Note the two server cookies (qtrans_front_language / qtrans_admin_language) are not involved in these changes, so there should not be any impact here. With the recent changes, the most crucial parameter is the **editor mode**: 
- switching buttons (LSB)
- RAW mode
- single mode

But i've tested those and it works fine for me. The single mode (that i never used until now) didn't allow me to keep my first version of changes. But this was interesting to see how it works and this approach could have some similarities with the first experiments for Gutenberg (other topic, i'll come back to this soon).

**Comment by herrvigg** [comment]
FYI there is a problem with ACF that relies on the old `qtrans_edit_language` cookie. I already noticed that before and marked it as a "TODO", but now it's clear this can't work anymore. This is the hard part with the integration, as there is no clear API and everyone uses whatever he finds at time t... This is not viable. I hope it's easy to fix but be careful if you try with ACF on the master branch.

**Comment by sailinf** [comment]
Hey, this is fantastic!

**Comment by herrvigg** [comment]
OK i think i found a solution for ACF, merged in master with https://github.com/qtranslate/qtranslate-xt/commit/37aff11368fc262d1cf18edf52365c38046c0860.

I'd have many questions for @funkjedi who did really an awesome job with ACF :)
I hope we can find a way to collaborate with the next evolutions. 
There are quite a few topics to solve to come with a better integration API, that's not just for ACF but i'd say this and WooCommerce are the main big ones currently concerned.

At least we should have something working with a much better state regarding this cookie hell. I plan to release the current version very soon but it would be great if someone using ACF more seriously could validate for non-regressions.

The next big step should be Gutenberg that i'd like to pre-release here in a way or another before switching to a new repo (!).

**Comment by sailinf** [comment]
How stable is the main codebase? I'm hugely tempted to replace qt also on my live site, quick testing went well, no language overwrite issues!

**Comment by herrvigg** [comment]
You mean to replace the old qTranslate-X? I don't even want to know how many errors it generates on a fresh PHP version...

I just found a bug in non-debug mode that i introduced with the minified scripts for ACF. All should work now.

Keep in mind the master branch, though it should always remain stable, is mostly meant for developers and testers.  For correct loading of the scripts in non-debug mode, you have to patch your QTX_VERSION, because i won't patch it after every commit. I may also generalize the version parameter from the file timestamp as well.

When testing it is strongly recommended to have good backups of your DB, though this should be a general rule. If you are the only one editing there's no big risk, work first on drafts and go step by step.

**Comment by sailinf** [comment]
No, meant replace 3.6.3 with the current version with your mods for this.

**Comment by herrvigg** [comment]
Yes i'd say it's in a good state now. If a few people can check a bit, i will release this version very soon.

Don't forget about the QTX_VERSION or define SCRIPT_DEBUG to avoid the browser cache (otherwise you may load old versions of the minified JS scripts).

**Comment by herrvigg** [comment]
Version 3.7.0 now released.
