### ISSUE TITLE
Hide "qtranxs-available-language-link"

### ISSUE THREAD

**Issue by AHTOLLlKA** [qtranslate/qtranslate-xt#746]
I enable duplicate content at pages who not translated, but at page i see text 
"Sorry, this entry is only available in %LANG"
How i can remove it without modification plugin ?

**Comment by herrvigg** [comment]
This looks similar to: https://github.com/qtranslate/qtranslate-xt/issues/716#issuecomment-522309129

Try this:
- go in settings > languages > select your language (for which the translation is missing) > edit.
- change the very last field "Not available message" by putting a white space (or other).

Note: an empty string is not allowed, this would reset the default value.

There is no possibility to set this globally, maybe something to think about as future evolutions.

**Comment by AHTOLLlKA** [comment]
thank you for answer, its work but not perfect((
i see now white line in template
https://i.imgur.com/n7hBD27.jpg

**Comment by AHTOLLlKA** [comment]
i see about hooking "i18n_content_translation_not_available", how i can do that ?

**Comment by herrvigg** [comment]
Just use `add_filter` as for any other filter. But before that try to just replace the return value with what you want directly in the code. If this doesn't give the layout you expect there's no point to add a filter.

I close this ticket for now. In general i think all the options should more flexible to allow empty values, but that's not only for that field. The reset to default should be handled differently, but that's more about general evolutions.
