### ISSUE TITLE
BIG NEWS: Gutenberg now available for dev/beta preview!

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#748]
**Gutenberg** now available for developers and early beta-testers! 🍾 🎉 🎉 🎉 

Checkout the branch "gutenberg":
https://github.com/qtranslate/qtranslate-xt/tree/gutenberg

To enable the Gutenberg editor, simply disable the Classic Editor plugin. 

**Disclaimer**: this is the very first version available. This is **not** supposed to be used in production but only on dev sites. I cannot guarantee against any problem with the data, though i don't think something crazy should happen apart from the content of the posts you are editing. In any case, backup your data if you want to try on production site anyway.

Main limitation: this forces the editor mode to SINGLE MODE so you have to edit one language after the other. No switching button at the moment. Currently the option is not saved, but changed on the fly.

It should be safe to switch between master branch and this. If you save the options no problem but remember you will have to reset your previous mode by yourself (usually LSB).

Have fun!

**Comment by herrvigg** [comment]
> No switching button at the moment. 

I mean no Language Switching Button as the usual "metabox". But you can use the language button in top right area of the admin panel. Note the hyperlink has to be updated dynamically (with a patch in post-exec.js) because of Gutenberg changing things constantly in the background.

**Comment by herrvigg** [comment]
So did someone try it? This no harder to install than the current version in master. If you don't use git, just download the last zip archive: https://github.com/qtranslate/qtranslate-xt/archive/gutenberg.zip.

**Comment by herrvigg** [comment]
Glad to read! For precision, the gutenberg branch is based on 3.7.1 and it only adds the gutenberg support as an extra feature, so absolutely nothing is changed in the core part. It adds some REST handlers but those should only process requests concerning the editor safely. Therefore from that branch it's fine to switch between Classic and Gutenberg if you want to experiment now and then. Just keep in mind about the single language mode. Obviously if you edit a Gutenberg post back in the Classic editor you will have to be very careful with the block tags, but this is not due to qTranslate, it's simply not meant to go backwards in WordPress.

**Comment by herrvigg** [comment]
New update to handle all the custom types selected in qTranslate and cleaner init for API REST.

I'm getting quite confident this branch could soon be merged in master, but we'd need a few more testers before that.

**Comment by herrvigg** [comment]
Rebased on master and pushed a small change to display a warning when the single language mode is enforced. In any case the single language mode is shown in the options, but if it's not the current value a warning is shown. You have to save your options to remove that warning. 

Note the raw editor mode is problematic, because the gutenberg blocks are nested inside the qTranslate ones. So i don't really see how the raw mode could work with Gutenberg, unless we remove the whole gutenberg parsing... which makes no sense if you want to use gutenberg. Maybe in the future we might have some qtranslate blocks inside a single post, but that's a whole different story, yet another subject.

Also, for the same reason once you have edited a post in Gutenberg, you can't really switch back to the Classic Editor because the Gutenberg blocks will remain. Still you have to remove by hand and i don't thinking it's really worth having a cleanup function. You should decide which editor to use and stick to that choice, although you could switch for every single post or a subset of post if you want to experiment. There should be not risk in that.

**Comment by herrvigg** [comment]
**MORE TESTERS NEEDED**

I'd like to merge the Gutenberg in master and release it as a beta-version. Though i'm relatively confident now this works quite good with the current limitations (single language mode only) i'd like to have a few more testers before that. So please try it out.

This will probably be among the last big change on that repo before switching to the new one.

**Comment by trebere** [comment]
Hello,

I tested this Gutenberg version in a fresh installation and found that when creating the translations of the pages the last one overwrites the previously created language. This does not happen when translating blog entries. Entries are translated correctly at least with the most basic blocks. 

Thank you very much!

**Comment by marcoacierno** [comment]
Same issue as @trebere, the text gets mixed up between the two languages (sometimes English ends up in the Russian version)

**Comment by herrvigg** [comment]
@trebere can you precise what you mean with "translation of blog entries" vs "translation of pages" ?? I haven't seen any issue of overwriting so far. 

@marcoacierno is that problem only inside ACF blocks or for the main title / content? I haven't tried with ACF yet. Are you sure you are mentioning the same thing as @trebere ?

**Comment by trebere** [comment]
@herrvigg I mean the Default Post Types, 'Posts' as blog entries and 'Pages' as pages.
The error happens at least only with 'Pages'. I've tested with English and Spanish. If I create a 'Page' in English before creating the Spanish translation of the same 'Page', the Spanish translation is already fiiled with the English content. Then when creating the Spanish translation for that same 'Page' it overwrites the English created before and both translations are with the Spanish content.

Hope this helps.

Thank you!

**Comment by herrvigg** [comment]
@trebere Thank you for that! It should have been obvious but i actually didn't test it well on the pages 😅 
So yes i can reproduce the problem and i know why it happens, something missing in the JS event handler.

I can come up with a quick hack but i'm looking for a better solution because the same will certainly happen with custom posts, though the PHP part is handled. Hopefully i can send a fix soon. Will keep you updated.

**Comment by herrvigg** [comment]
@trebere @marcoacierno i have sent a new fix to handle the pages and hopefully any custom type. I'm not super happy with the solution, but this should work better.

Also, i noticed there is now a new experimental local autosave feature which is a bit annoying. The problem is that it saves in SessionStorage the post with current language being edited, but when you switch language it doesn't update immediately so it thinks the post has changed... I haven't found a way to disable it yet. Just ignore the autosave messages for now.

**Comment by herrvigg** [comment]
@trebere @marcoacierno please let me you know when you have tested again to see if this solves the problem with the posts (it should). Would be nice to release gutenberg as an initial version, even if it's not perfect yet.

**Comment by trebere** [comment]
Yes, I did and is working as expected with the 'posts' and 'pages'. Thank you!

**Comment by explorier** [comment]
I'm looking into using this for a new site built with Sage 9 starter theme, ACF Pro & ideally, Gutenberg enabled! I'll give it some testing soon and update here. Would be open to contributing as well if there's other low-hanging fruit. Gutenberg seems like a good place to focus on though, as it's the future default of WP editing! I have some minor React & Gutenberg dev experience (at least have trained up on both 😊) and might be able to help in this area. Cheers!

**Comment by jesusnoe** [comment]
Thanks to all the people behind qtranslateXT project, developers and testers, I was going bananas looking for an alternative to qtranslateX that works in php 7. I will test soon and report the results.

**Comment by Juje** [comment]
@herrvigg You have any update on the development of the implementation?
And what still needs to be done? And are there maybe some things we can do?

**Comment by herrvigg** [comment]
@Juje i'm very busy on other things, didn't find much time for qTranslate. The Gutenberg version is working quite okay as a beta version, with some limitations. But there is a problem with the options with the Classic Editor that qTranslate should handle, so i will fix those in priority before anything else. This is needed before any new release.

Also i won't work on support for issues concerning other plugin integration, unless the solution is very obvious i don't have time for this. Doing the investigations takes a lot of time and i need more people from the community here, can't do this alone. People are welcome to send PRs for changes.

**Comment by picasso** [comment]
@herrvigg I have now some time which I can dedicate for qTranslate.
I'm especially interested in integrating Gutenberg support into the master. What do you need to do for this? I could test something... what we need to check? to implement?...

**Comment by herrvigg** [comment]
@picasso thanks for proposing some help. Tests are always welcome and good PRs even more :)
I'm trying to finish the initial version before merge in master but it's not easy. I realized there is a problem with the options of the Classic Editor, it's not enough to just test the plugin is active to decide whether to branch on Gutenberg or not. See the options of the Classic Editor. It's all about the init sequence to enable or not the Gutenberg features, and the huge mess with the qTranslate loading sequence does not make it easier... 

Apart from that, tests with Gutenberg are always welcome. There are for sure some problems with the additional features such as metabox and so on, but i won't have much time to look at those now.

Once i'm done with the initial Gutenberg release i will try to reboot the project on a different repo and there will be even more to do.

**Comment by herrvigg** [comment]
Gutenberg [branch](https://github.com/qtranslate/qtranslate-xt/tree/gutenberg) now rebased on 3.7.2. The initial release is now approaching, even if there are some minor bugs or limitations i'd like to take this into master.  See especially the topic concerning the editor options, which should now be fixed:
https://github.com/qtranslate/qtranslate-xt/issues/785. More testers needed

**Comment by herrvigg** [comment]
Gutenberg [branch](https://github.com/qtranslate/qtranslate-xt/tree/gutenberg) now rebased on [3.7.3](https://github.com/qtranslate/qtranslate-xt/releases/tag/3.7.3). I have already some quite good feedbacks regarding the last fixes for Gutenberg but if more developers can play with this new version i will merge Gutenberg in master for a new release.

**Comment by almendro** [comment]
@herrvigg thanks a lot for this compatibility! I used the old plugin is many sites for a long time. I hope this works fine and I will try to test, feedback, and collaborate as much as I can. (Sorry for my english, it's not my native language, but I hope to learn more).

Again, many thanks!

**Comment by herrvigg** [comment]
Gutenberg is now merged in master!
Currently labeled as `3.8.0.dev.6`. Official release `3.8.0` coming soon or maybe in pre-release.
More testers are much welcome, you can report issues as usual.
