### ISSUE TITLE
acf_form: qTranslateConfig is not defined

### ISSUE THREAD

**Issue by hirasso** [qtranslate/qtranslate-xt#759]
Hi there! I just noticed a small bug: If I use the function `acf_form()` in my frontend with qtranslate-xt activated, I get this error: 
```console
qTranslateConfig is not defined
```
This is a hotfix, until it's fixed in qtranslate-xt itself:
```php
add_action( 'wp_footer', function() {
  global $q_config;
  ob_start();?>
  <script>
    var qTranslateConfig = <?= json_encode( $q_config ) ?>;
  </script>
  <?php echo ob_get_clean();
}, 999 );
```

**Comment by herrvigg** [comment]
Probably a problem of order in the script loading sequence. You should not use qTranslateConfig until qtranslate is initialized. You need a "on-ready" callback and be sure your script comes after qtranslate.

**Comment by herrvigg** [comment]
This looks the same as #764. But i can't reproduce it with ACF free. Are you also using ACF Pro?

**Comment by hirasso** [comment]
Yes, I'm also using ACF Pro. Please note, that this *only* happens in the frontend for me (when using `acf_form()`.

**Comment by herrvigg** [comment]
I can reproduce with ACF 5.8.7 (Free). It's due to `acf_form_head` that enables the loading of the client scripts, but there's something wrong with the order and the dependencies.

**Comment by herrvigg** [comment]
@hirasso @cyberfly999 i think i found a solution, i sent a patch on master so you are much welcome to test it. Let me know how it works :)

**Comment by herrvigg** [comment]
@hirasso can you check if this solves the problem? I'd like to release the last fixes but i'll wait until you confirm it's fine.

**Comment by hirasso** [comment]
Looks good to me! Thanks a lot!! 👍
