### ISSUE TITLE
Disable language redirect for a single url?

### ISSUE THREAD

**Issue by The3IC** [qtranslate/qtranslate-xt#761]
Problem that I stumbled on is that I have a 360 tour plugin. It uses a "dummy" page/url in the iFrame: .../virtualtour/?parameters. The page URL is essentially not needed, the only thing the iFrame needs are the parameters. Now qT adds a small extra twist to this as it redirects the url (unncessarily) to .../en/virtualtour/... which adds quite a lot of delay to the process.

Is it somehow possible to exclude this one URL from translation/redirect? 

If not, in the settings there is the "ignore links" section, could this be expanded with just a list of URLs?

**Comment by herrvigg** [comment]
It should be possible to come up with a custom solution through http rewrite in your web server. Otherwise it should be possible programmatically with all the current hooks.
Just so you know, i won't work on new features in this repo.
