### ISSUE TITLE
An idea for translated slugs

### ISSUE THREAD

**Issue by asanti82** [qtranslate/qtranslate-xt#762]
While qtranslate-slug still works (tested on wp version 5.3), it does have an issue with parent page and child pages. Anyways, I was thinking what if in qtranslate-xt on post save it creates rewrite rules for each language?

So it would look something like this?
Post Title EN: Terms and Conditions
Post Title ES: Términos y Condiciones

Slug EN: terms-and-conditions
Slug ES: terminos-y-condiciones

So to write the rewrite rule it would loop through the enabled languages: array('en', 'es')
and assign the ES Slug to point to the EN (default) page/post? 

This would obviously replace the permalink text field default by WP, maybe step 2 would be to add a translatable text field for the actual slug that's based on the title as to mimic what the default permalink does?

Hope this makes sense and helps?

**Comment by herrvigg** [comment]
No clue about this, this looks like a basic feature qtranslate-slug should provide. By default WP only has a single slug and i don't even know if it's even to play with rewrite rules. Adding a rewrite rule for every page/post does not sound like a viable solution, on a big website the performance will degrade.

**Comment by herrvigg** [comment]
Maybe this will speak to someone using qtranslate-slug so i leave it open, but at the moment this does not concern qTranslate-XT and normally i would close it.

**Comment by asanti82** [comment]
@herrvigg I understand it's not directly a qTranslate-XT issue but not having translated slugs/permalinks is I think.  Ideally it should be an all-in-one plugin that does all related to translating a site.  The issue with being part of qTranslate-slug is that I checked out their code briefly and noticed they use a table where the slug cannot be duplicated and while this was the case prior to WP 4.something it has changed.  Now child pages if they have different parents it can have the same url. Anyways thought it would be something nice to add at some point in time, I might work on a demo myself and if you want give you access? I'd love to help out but coming in late it'll take me some time to understand the current structure of the plugin :(

**Comment by bagaweb** [comment]
@asanti82 I completely agree with you and I will be very happy if you can help with that!
