### ISSUE TITLE
WPRecidence  URL Modification Mode

### ISSUE THREAD

**Issue by Aldo-ACE** [qtranslate/qtranslate-xt#763]
Hello.
Im using WPresidence with qXT with 3 languages :en :es :de , and I having problems, I gess for intergration.
If  I use Use Pre-Path Mode, when I do a search from fron tend, the results are always shown in German. No matter from what language you search.
If I use "Use Query Mode" every thing works well.

Any ideas will be wellcome.
Aldo.

**Comment by herrvigg** [comment]
I won't be of much help here, unless you provide more precise information at the code level. I leave it open for others.

**Comment by Aldo-ACE** [comment]
Thanks for answer and sorry for a late responce.
I ask to the wpresidence support if is ok to share some files of the theme and if they colud be interested in integrate with qXT. And they say....
​"You can share with the plugin developers the theme file so they can help achieve what you wish.
​At this moment we do not have any plans in testing the plugin but I will add this on our wishlist for future research."
Resently I detect another probem with filters in the property list. if you change the language the filtering options still with the first language until  clear the theme cache.
Sorry but im new on this.

[advanced_search_type4.txt](https://github.com/qtranslate/qtranslate-xt/files/3917940/advanced_search_type4.txt)


.

**Comment by herrvigg** [comment]
I can't do more without further info, closing for now.
