### ISSUE TITLE
constant QTX_EDITOR_MODE_SINGLGE - assumed 'QTX_EDITOR_MODE_SINGLGE' 

### ISSUE THREAD

**Issue by LaMpiR** [qtranslate/qtranslate-xt#765]
All latest versions.

```
constant QTX_EDITOR_MODE_SINGLGE - assumed 'QTX_EDITOR_MODE_SINGLGE' (this will throw an Error in a future version of PHP) in /homepages/13/website/wp-content/plugins/wp-seo-qtranslate-x/wordpress-seo-qtranslate-x.php on line 26

Warning: Cannot modify header information - headers already sent by (output started at /homepages/13/website/wp-content/plugins/wp-seo-qtranslate-x/wordpress-seo-qtranslate-x.php:26) in /homepages/13/website/wp-includes/functions.php on line 5946

Warning: Cannot modify header information - headers already sent by (output started at /homepages/13/website/wp-content/plugins/wp-seo-qtranslate-x/wordpress-seo-qtranslate-x.php:26) in /homepages/13/website/wp-includes/pluggable.php on line 1265

Warning: Cannot modify header information - headers already sent by (output started at /homepages/13/website/wp-content/plugins/wp-seo-qtranslate-x/wordpress-seo-qtranslate-x.php:26) in /homepages/13/website/wp-includes/pluggable.php on line 1268

Warning: Cannot modify header information - headers already sent by (output started at /homepages/13/website/wp-content/plugins/wp-seo-qtranslate-x/wordpress-seo-qtranslate-x.php:26) in /homepages/13/website/wp-admin/includes/misc.php on line 1252

Warning: Cannot modify header information - headers already sent by (output started at /homepages/13/website/wp-content/plugins/wp-seo-qtranslate-x/wordpress-seo-qtranslate-x.php:26) in /homepages/13/website/wp-admin/admin-header.php on line 9
Zum Hauptinhalt springenZur Werkzeugleiste springen
```

**Comment by herrvigg** [comment]
Similar to #738. The plugin `wordpress-seo-qtranslate-x` is obsolete, you should simply disable it.

There is a module in qTranslate-XT that took the last available version of that plugin, but it has some issues and was doing almost nothing, so it has been disabled as well 😕 

The code is available though, so if some people can arrange it i will be happy to turn it on again.

**Comment by LaMpiR** [comment]
Hi,

Thank you.

Do you have a recommendation for a seo with two languages?

Best regards,

Herr Vigg <notifications@github.com> schrieb am Mo., 2. Dez. 2019, 23:55:

**Comment by Tusko** [comment]
I have a temporary fix. 
Add `define('QTX_EDITOR_MODE_SINGLGE', '' );` to `wp-config.php`

**Comment by herrvigg** [comment]
@Tusko you shouldn't need to do that. If you need it, you are either using an obsolete version of qTranslate-XT, either an obsolete integration plugin. All those have been replaced by built-in modules. I recommend you to update to the last release which is 3.7.3 and check the integration options to see the status with the modules.

**Comment by herrvigg** [comment]
Oh... i think i understand now, it's just about `wordpress-seo-qtranslate-x` but i disabled the module.... so i guess you are still using the old plugin which is problematic. Sorry about that. I will try to re-enable the module because i realized it's actually doing useful things in the admin section. See #794.
