### ISSUE TITLE
Essencial Grid 

### ISSUE THREAD

**Issue by jorgept** [qtranslate/qtranslate-xt#767]
Don't work with Essencial Grid plugin...
Any sugestion?

**Comment by herrvigg** [comment]
Please provide more info for debugging this problem.

**Comment by jorgept** [comment]
Hi Herrvigg,

Wath info you need?
You know the Essencial Grid Plugin?

Ok. If i insert another language, in languages tab, admin insert custom post.
In frontend, only show the first language...

**Comment by herrvigg** [comment]
No i don't know that plugin and i won't have time to test more. I would need more developer-level info and relevant errors, you have to investigate a bit on your own with the code. Sorry, won't be able to help much more on this for now.

**Comment by herrvigg** [comment]
Also, the Essencial Grid plugin is not free. If you manage to identify the error in the code i can try to understand why it happens. Otherwise you'd need technical support from developers or other users of Essencial Grid here.

**Comment by herrvigg** [comment]
I can't do more without further info, closing for now.
