### ISSUE TITLE
gravity form multiupload option insite gravity

### ISSUE THREAD

**Issue by kochhase** [qtranslate/qtranslate-xt#770]
Hi there i have an problem with the gravity form multiupload option insite gravity. WPML has there as well some problems in the past. So this is the Problem that WPML had to fixed. Mybe that helps for an solution for qtranslate-x.
Pass session arguments between domains through the language switcher" - we had this (must have been by default) as Pass arguments via GET (the url). We changed that to Pass arguments via POST, and it seems to have resolved the issue with the Gravity Forms multi-file upload button ghosting out.
is there an easy fix for that problem?

Aother problem. no way to use conditional Logic. Ore is this the same problem like before?
thanks for looking. I can send you the gravity form plugin if needed.

_Originally posted by @kochhase in https://github.com/qtranslate/qtranslate-xt/issues/661#issuecomment-564270051_

**Comment by herrvigg** [comment]
Sorry i can't really help you with this, i don't use Gravity Form. Would be nice if some other user could help or explain better what this is about. If you describe the problem more technically in terms of what you expect in qTranslate-XT maybe we could find a solution here.

**Comment by herrvigg** [comment]
I can't do more without further info, closing for now.
