### ISSUE TITLE
Empty posts

### ISSUE THREAD

**Issue by jwendell** [qtranslate/qtranslate-xt#773]
I'm using Wordpress 5.3.2 and latest plugin (3.7.1).

See https://bani.com.br/

**Comment by jwendell** [comment]
Even comments are empty...

**Comment by jwendell** [comment]
Hmm, I disabled https://wordpress.org/plugins/wp-code-highlight/ and it works fine now.

**Comment by herrvigg** [comment]
I don't know this plugin but seen this:
```
Wrap code blocks with <pre> and </pre>
```

It makes me think it will break qTranslate encoding if these tags are added after qTranslate.  Can you check this? You will certainly need some priority change or special hook management to make it work.
