### ISSUE TITLE
Slug translate when?

### ISSUE THREAD

**Issue by lovrenco** [qtranslate/qtranslate-xt#774]
Hello,

as you know, translating slugs is important for SEO. For example:

somesite.com/en/croatia
somesite.com/de/kroatien

Will this be possible soon?

Also, language content shouldnt be mixed within HTML on public pages, also because of SEO.

**Comment by herrvigg** [comment]
Integrating slug is not a priority for me so you know. There is qtranslate-slug. but people using this should work on it, i won't have time for this.

Also i don't think the proper translation of the URL is so crucial for SEO. What really matters is having the control over the canonical URL. What do you mean with "language content shouldnt be mixed"?

**Comment by xcolomer** [comment]
Try the plugin Qtranslate Slug, works fine!!
