### ISSUE TITLE
There is no "Language Switching Buttons" on Adding New Post

### ISSUE THREAD

**Issue by sparkandshine** [qtranslate/qtranslate-xt#776]
I installed the plugin [qTranslate‑XT](https://github.com/qtranslate/qtranslate-xt). There exists "Language Switching Buttons" on Categories, Tags and etc, as shown below:

[![enter image description here][1]][1] 

However, on "Adding New Post", there is no "Language Switching Buttons", as shown below:

[![enter image description here][2]][2]

How do I show the "Language Switching Buttons"?

  [1]: https://i.stack.imgur.com/I5K0y.png
  [2]: https://i.stack.imgur.com/87inM.png

**Comment by herrvigg** [comment]
This is Gutenberg which is only supported in beta phase at the moment, but it's even in a separate branch. You should have a warning telling you to install the Classic Editor plugin.

**Comment by sparkandshine** [comment]
I just switched the editor from **JP Markdown** to **WP Githuber MD**. Now, it works perfectly. Thank you so much.

**Comment by herrvigg** [comment]
OK i don't know either of those, but i'm glad you found a solution :)

So if i understand right JP Markdown is based on Gutenberg while WP Githuber MD is using the classic TinyMCE editor. Did you install the Classic Editor as well or is it part of WP Githuber MD?

The beta support for Gutenberg will be merged soon but other third party editors may have to be considered to activate the proper support in qTranslate.
