### ISSUE TITLE
qTranslate-XT not working with Events Calendar plugin

### ISSUE THREAD

**Issue by laukejas** [qtranslate/qtranslate-xt#778]
It appears that the qTranslate-XT is not working with Events Calendar plugin. Changing the website language does nothing to the Events Calendar. Example site: [www.inre.lt/renginiai_](url). Is this something that can be fixed from qTranslate-XT side?

**Comment by xaviurbs** [comment]
I have the same problem with Car Rental plugin... any solution available?
Plugin: Car Rental Booking System for WordPress

**Comment by herrvigg** [comment]
No plan for built-in support, but you can try on your side following the https://github.com/qtranslate/qtranslate-xt/wiki/Integration-Guide
