### ISSUE TITLE
Front end command 

### ISSUE THREAD

**Issue by osamakamel88** [qtranslate/qtranslate-xt#782]
hi, content in description in the front and back end comes with the command [:en] / [:ar] / [:tr] 
any idea how to remove those , it is translating normally to desired languages however those codes appears!?

**Comment by herrvigg** [comment]
I don't understand the issue. What do you mean by "command"? For integration check https://github.com/qtranslate/qtranslate-xt/wiki/Integration-Guide

**Comment by osamakamel88** [comment]
hi
the attached pic may clarify what i mean, my apologies
Thanks

**Comment by herrvigg** [comment]
I don't see any pic, sorry but you really have to precise the issue much better. I have absolutely no idea what you are referring to.

**Comment by osamakamel88** [comment]
Hi
The pic is right in here attached in this email dear!
