### ISSUE TITLE
Support for translations in Add Media pop-in

### ISSUE THREAD

**Issue by isoph** [qtranslate/qtranslate-xt#786]
While editing multilingual media info (title, alt text…) in the library seems to work just fine, the pop-in window used to add media while editing a post doesn’t seem to display translations or translatable fields. 

![addMedia](https://user-images.githubusercontent.com/1316394/74342939-9357b800-4daa-11ea-97c2-557ca67a5458.png)

**Comment by herrvigg** [comment]
First check the [integration guide](https://github.com/qtranslate/qtranslate-xt/wiki/JSON-Configuration) and see what you can use there. I'm aware it's not really user-friendly but this is the current state of the plugin right now. I can't really help with general support of integration at the moment, please send a ticket if you have a technical problem well described.
