### ISSUE TITLE
Yoast module disabled

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#794]
For the history: the Yoast module was initially created from the the old integration plugin [Yoast SEO & qTranslate-X](https://github.com/qTranslate-Team/wp-seo-qtranslate-x).

Due to many problems with the existing JS code that had not been maintained for too long, also because the PHP part wasn't really relevant, it was preferable to disable the Yoast module for now, as [described here](https://github.com/qtranslate/qtranslate-xt/issues/661#issuecomment-479661609). 

Developers willing to re-activate those features are much welcome. If some PHP components are relevant we may reactivate the module for those and only keep the JS part disabled.

**Comment by herrvigg** [comment]
I will try to re-enable the module because i realized it's actually doing useful things in the admin section. The problem is more the javascript part that needs more work and i don't think i will have much time to look into all the details, but let's do it progressively.

**Comment by ashabelnikov** [comment]
Great news!

**Comment by mohjak** [comment]
@herrvigg I would like to help in this regard, because I am facing issues in integrating qtranslate-xt with YoastSEO, for example,  the metadata like `og:description` appears with the language code [:en].

```html
<meta property="og:description" content="[:en]Around 1.5 million people will be displaced in the Sundarbans, and the process has started[:bn]সুন্দরবন সংলগ্ন এলাকাসমূহে বসবাসকারী প্রায় ১.৫. মিলিয়ন মানুষ বাস্তুচ্যুত হয়ে পড়বে অচিরেই, আর এরই মধ্যে শুরু হয়ে গেছে এই প্রক্রিয়া[:]" />
```

So that, where do you think it is better to start from. I have already started to review the source code of [https://github.com/qTranslate-Team/wp-seo-qtranslate-x](https://github.com/qTranslate-Team/wp-seo-qtranslate-x). 
I would like to know if you have any plan regarding this issue.

**Comment by pjrobertson** [comment]
Yoast have just come out with a new update (14.0) which they claim has [overhauled the backend](https://yoast.com/yoast-seo-14-0/). They state:

> We’ve also found that not all plugins that rely on Yoast SEO have updated to our 14.0 code yet. If you use, for instance, a multilingual plugin, please check that they’re ready for the update.

So I suggest this module be fixed with Yoast 14.0 in mind as opposed to previous versions.

**Comment by pjrobertson** [comment]
I've just re-enabled the Yoast module (running Yoast 13.5) and don't see any JS errors. Do we have an actual running list of issues with Yoast SEO?

Perhaps @herrvigg you can update this issue title to "Yoast Module Issues" and then keep a running checklist of all the issues we're facing so far. I've done a quick sweep of front end and backend and I have not seen any major issues.

Some minor issues (to add to the list):

[ ] `<meta name="twitter:description">` not translated
[ ] `yoast-schema-graph yoast-schema-graph--woo yoast-schema-graph--footer'` not translated on Woocommerce product pages 
[ ] `og:description` not translated (if you set a specific 'description' in the 'edit snippet' section of a page)

**Comment by herrvigg** [comment]
OK i had in mind to enable Yoast for 3.8.1 even with limited features but now this update with Yoast 14 looks interesting. In fact i don't see the JS errors anymore but i can't really say why... it could come from changes they made even in earlier versions.
However Yoast 14 seems to be big overhaul and i agree it would be better to focus only on this and forget all the backlog. But it will probably take more time so i push 3.8.1 as it is now.

**Comment by pjrobertson** [comment]
I've done some debugging on this today. First off - it looks like the `i18n-config.json` file from the old yoast-seo-qtranslate-x plugin didn't get copied over to the module, is there a reason for this? (@herrvigg )

Today I've gone ahead and:

1. Copied over the .json file
2. Added the following to the `front-config` section
```json
"wpseo_opengraph_desc":"20",
"wpseo_twitter_description":"20"
```

Out of my list above, everything now seems to be translated correctly except for the Schema Graph, which I'm looking into. FYI for anybody else debugging this plugin, Yoast has a developer plugin which you can install: https://github.com/Yoast/yoast-test-helper

**Comment by fabianpiau** [comment]
Hi, I notice some incompatibilities with the breadcrumbs in the last version of Yoast 14.1+, I have created https://github.com/qtranslate/qtranslate-xt/issues/838  yesterday but only realised today this issue was existing.

**Comment by bagaweb** [comment]
There is a problem with Yoast 14 https://wordpress.org/support/topic/polylang-does-not-translate-yoast-seo-titles-and-descriptions-on-the-homepage/

**Comment by fabianpiau** [comment]
It's not really a problem, basically they have refactored a lot of logic in version 14, making breaking changes. I'm not familiar with Polylang to be honest. I have been using qTranslate for many years and always very happy with it. Unless qTranslate / Yoast compatibility is definitely abandoned with version 14, I would prefer to stick with qTranslate. I could not see myself not using Yoast. I think it's important to update qTranslate as Yoast is so popular among WordPress users (5+ million active installations).

**Comment by bagaweb** [comment]
I never used Polylang, it just happened that there is the very same problem with Yoast. I will start using AIOSP instead.

**Comment by herrvigg** [comment]
Sorry for late answer, i've been quite busy with other things.

@pjrobertson about the `i18-config.json` good you took a look at it! I actually wrote a comment in `qwpseo-front.php` concerning this. There is also a block in the code that was commented corresponding to the json counterpart.

https://github.com/qtranslate/qtranslate-xt/blob/d1fe64ec3cdfd98dad2878da39b294706335ea0d/modules/wp-seo/qwpseo-front.php#L16-L26

But for some reasons (maybe some other bugs or i missed something else) i concluded the file was not used. Therefore i didn't take it from the old plugin.

My intention was to re-enable the legacy code in the module for a minimal support at least. But now the situation has changed quite a bit.  It's really good they have refactored all in Yoast 14! However this will require even more work. 

The question is what should we really keep from the legacy code?! Imo the best would be to rewrite the module starting again completely from scratch and just cherry-picking the parts we know are useful and that work with the new framework. But new and different code will be needed for sure for their new API that should also give many new possibilities i guess.

I would also be happy to give a hand to integrate it back. Right now i will be probably have other topics to check in qT-XT. If someone can give a try that would be really great!

**Comment by filtah** [comment]
Yoast v14 is a nightmare! as we depend on this plugin for many of our websites, I needed a way to work with the new version, and getting it to work with qtranslateXT has involved a lot of hacks to get around their new database model. I've put together a simple fixer plugin which will correct the titles, descriptions and urls. I post the repo incase anyone finds it useful, its working good for us so far: [https://github.com/filtah/inmedia-yoast-fixer](url)

**Comment by bagaweb** [comment]
Thanks a lot @filtah I will definitely give your fix a try next week and give you seome feedback!

**Comment by bagaweb** [comment]
I tried your plugin, it works fine with pages but doesn't work with custom post types... Had to downgrade to Yoast 13.5.

**Comment by filtah** [comment]
Hi @bagaweb, thanks for your feedback. I don't see any problems with custom post types on any of the websites I've deployed this to, but may be to do with how they have been defined. We set up most custom post types with the CPT UI plugin and the data is correct.
The purpose of this plugin is to correct the title, meta description, og: metas, canonical link url and schema json, which just gets wrecked when using v14 of yoast.

**Comment by filtah** [comment]
I did actually find a bug, but its affecting all post types (incl pages, posts).
When using the default placeholders for the title and description, the title is not correct and the description meta is missing. I'll have a look into that next week.
<img width="681" alt="PastedGraphic-5" src="https://user-images.githubusercontent.com/3319153/84791747-5408d480-aff3-11ea-8b9b-9540565f29ca.png">

**Comment by pjrobertson** [comment]
I've worked on fixing Qtranslate-Xt for Yoast 12.0. I don't have much time right now to package it nicely, but my changes are here: https://github.com/pjrobertson/qtranslate-xt/commit/aa35f3cafe80cdaa355e53ae9478bd4f0d390d1e

I basically:

1. Reinstated the i18n-config.js file, and added more lines to the end (specific to Yoast 12.0)
2. Added a single filter to fix breadcrumbs (`wpseo_breadcrumb_single_link`). For some reason putting this in the .js file didn't seem to work

This has 90% of the front-end stuff working (like OG graphs, schemas etc), but the backend (admin/Yoast analysis) side I haven't touched.

Hopefully this'll prove useful. At the very least, dropping these two files into the the qtranslate Yoast 'module' folder should be a quick fix.

**Comment by bagaweb** [comment]
Thanks for your support, maybe the issue I ran into it depends on the specific title format of the custom post type:
![Opera Snapshot_2020-06-17_154355_www visitfassa com](https://user-images.githubusercontent.com/14122970/84905799-72350a00-b0b1-11ea-95b5-c193c7f2e2f4.png)

**Comment by pjrobertson** [comment]
I've managed to track the issue with breadcrumbs down to the following:

Let's say you have a website in English and French:
1. Yoast 14.0+ re-saves all 'indexables' when you save a post.
2. If you click update a post with your UI language set to English, the breadcrumb indexables will be saved in this language. If you use 'French', the breadcrumb indexables will be saved in French.
3. This is due to this line of code in Yoast: https://github.com/Yoast/wordpress-seo/blob/trunk/src/builders/indexable-post-builder.php#L133

Still need to do some further work on fixing the issue, but I wanted to note down my progress here first.

**Comment by pjrobertson** [comment]
I've escalated this issue to the Yoast team and asked them to modify their code to fix this bug: https://github.com/Yoast/wordpress-seo/issues/15582#issuecomment-652744658

In the meantime, I can confirm that changing https://github.com/Yoast/wordpress-seo/blob/trunk/src/builders/indexable-post-builder.php#L133 to the following works:

`$indexable->breadcrumb_title = \wp_strip_all_tags( $post->post_title, true );` 

(along with my other changes linked to above (relink)[https://github.com/pjrobertson/qtranslate-xt/commit/aa35f3cafe80cdaa355e53ae9478bd4f0d390d1e] )

**Comment by bagaweb** [comment]
Any news about this issues and fixes?

**Comment by herrvigg** [comment]
See also https://github.com/qtranslate/qtranslate-xt/issues/877#issuecomment-686347591
> it seems that Yoast 14.9 has somewhat improved the issue, title is good now and the language indicators `{en}` don't show in the edit section, the only thing remaining is the preview that is still busted but it doesn't affect the SEO calculation so I guess this is much better now and we don't have to downgrade

**Comment by herrvigg** [comment]
Since Yoast 14 is breaking many things and i don't really know the status of what is working or not, i made quite a radical decision:
- rewrite the module from scratch for Yoast 14. So we keep only code that is really doing something useful.
- move all previous code to `qtranslate-xt/dev/wp-seo-yoast-13`. I could have kept this in git history only, but it may be a bit more convenient to have the old code as a reference directly visible in the repo. Note this is not delivered to the releases.

I suggest we close this ticket and we open a new one for the dev of Yoast 14.

**Comment by herrvigg** [comment]
Also for Yoast and @pjrobertson who worked on `i18n-config.json` :
I realized the i18n-config.json is not supported natively in the modules. See #958. So i will rather convert this to PHP code in the modules for now. But the work on the JSON files is always of great use, it's not a big deal to convert.

I suggest we move all the conversation of this topic to #947 as this module has to reboot from zero (or almost). But there is great information here so let's just carry anything that is still valid to the new topic.
