### ISSUE TITLE
qTranslate-XT not working well last update of AVADA theme, 6.2

### ISSUE THREAD

**Issue by monabalo** [qtranslate/qtranslate-xt#800]
Hi, 
The qtranslate-xt is not totally compatible with de last update of AVADA (6.2). The fusion layer is not display.  I don't have any problems until just this moment. 
Can anybody help me? Thanks!

**Comment by herrvigg** [comment]
If you want the problem solved i would need more investigation from your part. I don't use AVADA so you'll have to point out the technical problem very precisely.

**Comment by monabalo** [comment]
With the Avada last update 6.2.2  the problem seems to be solved.  I understand that the problem was an Avada issue.

**Comment by herrvigg** [comment]
@monabalo sounds good, also thank you for the update! :)
