### ISSUE TITLE
New version not updated in WP

### ISSUE THREAD

**Issue by dlambova** [qtranslate/qtranslate-xt#802]
Hi,
I see there is a version 3.7.2. but haven't yet received a notification from GitHub updater for the new version. I am on 3.7.1. Do you know if there is any issue?
Thanks

**Comment by herrvigg** [comment]
Strange, maybe something went wrong with the [tags](https://github.com/afragen/github-updater/wiki/Versions-and-Branches)?
Anyway the [3.7.3]( https://github.com/qtranslate/qtranslate-xt/releases/tag/3.7.3) is just released now. Hopefully it will update by itself this time. You can also launch a scan manually from github updater.
In the worst case, you can reinstall from the github archive (see the clone button).
