### ISSUE TITLE
130-unique-slug integration - bugs

### ISSUE THREAD

**Issue by spleen1981** [qtranslate/qtranslate-xt#805]
my feedback for 130-unique-slug release:
Here follows what happens following the different kind of links.

    Categories and posts translated+translated slug: 404 (both primary and secondary language)
    Categories and posts translated+unique slug: 404 (both primary and secondary language)
    Categories and posts not translated: 404
    Pages translated+translated slug: OK primary language, 404 for secondary language
    Pages translated+unique slug: OK (both primary and secondary language)

Tried to update permalink structure and applied the "Rebuild all slugs" tool (link to settings in this page to be fixed), with same results as above.

**Comment by herrvigg** [comment]
@spleen1981 what is 130-unique-slug compared to [qtranslate-slug](https://github.com/not-only-code/qtranslate-slug)? Is that a fork?

**Comment by spleen1981** [comment]
> @spleen1981 what is 130-unique-slug compared to [qtranslate-slug](https://github.com/not-only-code/qtranslate-slug)? Is that a fork?

@herrvigg it's a branch of [qtranslate-slug](https://github.com/not-only-code/qtranslate-slug).
Ref. [here](https://github.com/qtranslate/qtranslate-xt/issues/608#issuecomment-420823032).

**Comment by herrvigg** [comment]
Let's discuss this in the main thread #671.
