### ISSUE TITLE
Woocommerce - Breadcrumbs partially not translated on language change

### ISSUE THREAD

**Issue by spleen1981** [qtranslate/qtranslate-xt#806]
Breadcrumbs: given the following breadcrumb structure "item1/item2/item3/product", when accessing the product page in one language, changing to another language would result in "item3" remaining stucked in the previous language in the breadcrumbs, while the rest is translated correctly.

**Comment by herrvigg** [comment]
I don't use breadcrumbs so i don't know really what this is about. But i don't see why even item1/item2 would be handled by the WC module, there is no specific handling for such structure as far as i know. What is an item compared to a product?

**Comment by pjrobertson** [comment]
I'm also not able to reproduce this. Breadcrumbs on product pages are working correctly.

@spleen1981 are you sure that 'item3' product category has been translated properly?

**Comment by spleen1981** [comment]
@herrvigg items in the example above are product categories.

@pjrobertson, test:
Site in first language, product page accessed:
![image](https://user-images.githubusercontent.com/43221199/80848727-82357f00-8c14-11ea-82fa-c1755fc11742.png)
Switched language to second one:
![image](https://user-images.githubusercontent.com/43221199/80848768-b0b35a00-8c14-11ea-9ff1-facb2a7b8b71.png)
Note that other references to the untranslated category in the page are traslated correctly.

By clicking on the untranslated link in breadcrumbs this is what happens:
![image](https://user-images.githubusercontent.com/43221199/80848849-fec85d80-8c14-11ea-80e2-4b9765ea5607.png)

**Comment by dlambova** [comment]
Hi,
I have the same issue with breadcrumbs but the translations are random. On some pages the languages appear totally mixed in the breadcrumbs, on both languages. I am not using Woocommerce, though.
Did you happen to find a solution for that?
Thanks
