### ISSUE TITLE
mailpoet forms 

### ISSUE THREAD

**Issue by navajolo** [qtranslate/qtranslate-xt#807]
Hi, i'm using qtranslate-xt for a site.
Everything seems work.
But I have a problem with mailpoet forms creation which use Gutenberg.
I'm not able to translate the labels. The flags in the top-right corner of the backend disappear too when i'm in mailpoet.
Thankyou for the great job, hope you can suggest some solution...

MM

**Comment by navajolo** [comment]
I am using the Gutenberg version of this plugin

**Comment by navajolo** [comment]
I solved. Using shortcodes with html custom code widget in footer.
I created 2 mailpoet forms, one for each language, and they appear only when they shoukd.
Like this...
[:it][mailpoet_form id="1"]
[:en][mailpoet_form id="4"]
[:]

in custom html widget

Bye

**Comment by herrvigg** [comment]
That's great! :)
