### ISSUE TITLE
WooCommerce 4.0.1: Product variations not working on product page

### ISSUE THREAD

**Issue by chrilleferna** [qtranslate/qtranslate-xt#810]
After upgrading to Woocommerce 4 (4.0.1 at this moment) products with variations stopped working when Qtranslate-XT is active.
I get the following warning on the front-end product page:

Warning: implode(): Invalid arguments passed in ..plugins/woocommerce/includes/wc-attribute-functions.php on line 41

and the variations selector has no options.

As a **very temporary** fix which seems to have resolved the problem (but may have caused others I haven't seen yet) I made a patch in the woocommerce file and replaced the line 41:

`return implode( ' ' . WC_DELIMITER . ' ', $attributes );`

with:

` if (is_array($attributes))`
`    return implode( ' ' . WC_DELIMITER . ' ', $attributes );`
`else`
`    return $attributes;`

**Comment by herrvigg** [comment]
@chrilleferna which version are you using? There used to be a problem with implode https://github.com/qtranslate/qtranslate-xt/issues/707 but this was fixed in qT-XT 3.7.3. I didn't try with WooCommerce 4 though, it was released at the same time.

**Comment by chrilleferna** [comment]
OK, thanks. I use 3.7.1. I'll install 3.7.3 later tonight and will come back with the result

**Comment by chrilleferna** [comment]
Done. Result positive. The problem has been fixed in version 3.7.3. Thanks a lot !!!!

**Comment by herrvigg** [comment]
Great to read! 🎉
