### ISSUE TITLE
Proposals for addition

### ISSUE THREAD

**Issue by sviluppomania** [qtranslate/qtranslate-xt#813]
Hello,
why don't you add the functionality of this plugin -> https://it.wordpress.org/plugins/qtranslate-separate-comments/

Separate comments by language without finding comments from each language.
For it is very useful because my site also uses a mobile app and these, as on the site, have separate comments for the language they belong to.

![image](https://user-images.githubusercontent.com/26438200/78459629-93917700-76ba-11ea-8a2c-ec9590698292.png)

![image](https://user-images.githubusercontent.com/26438200/78459633-99875800-76ba-11ea-9728-e7bdfd3d2e48.png)

**Comment by herrvigg** [comment]
I don't know how big that plugin is and it looks very specific so it won't be a priority. I leave it open but won't work on it for now.

**Comment by sviluppomania** [comment]
The plugin is not large and you should consider it as a priority because it is of great help in doing the work explained in the previous comment.  If you want I will give you the source of the plugin, there are few files.

**Comment by sviluppomania** [comment]
@herrvigg

**Comment by herrvigg** [comment]
This feature is way too specific and there is already a plugin for this. Sorry but there are many, many other crucial tasks and i won't work on this so i prefer to close for now.
