### ISSUE TITLE
Create i18n-config.json file for unsupported theme

### ISSUE THREAD

**Issue by lealarcon** [qtranslate/qtranslate-xt#815]
Hello everybody, i've been using qtranstale-X  for my WP site for a long time , then i moved to qtranslate-XT one week ago. 
I have been using the customizr-pro 1.2.27 for about three years (i did not renovate the license)  and everything worked fine until i started to use qtranslate-XT.  There are some  widget's tittles that are shown as follow:

 ![image](https://user-images.githubusercontent.com/14064043/79060398-28abe700-7c4a-11ea-8bd6-54974c2f8143.png)

Searching inside the theme's files i found the filter `fpc_title_block`  which shows every title inside a widget.  Then i went to `wp-admin/options-general.php?page=qtranslate-xt#integration` and put it on Custom Filters.

![image](https://user-images.githubusercontent.com/14064043/79060468-efc04200-7c4a-11ea-9567-b4d299e27800.png)

As i expected, it worked !! 

![image](https://user-images.githubusercontent.com/14064043/79060479-11b9c480-7c4b-11ea-8989-e9baef0461e5.png)

Then i wanted to create the i18n-config.json inside the theme path in order to configure all the filters i want to be translated but i did  not know how to do it. I was reading the Integration WIKI but sincerely i did not understand. If someone have had the same situation and was abled to configure i will appreciate your help.

This is the code that i've been configured inside the theme

`{
  "vendor": {
    "theme/customizr-pro": "1.2.27"
  },
  "admin-config": {
    "all-pages": {
      "filters": {
        "text": {
          "fp-title": "20",
          "fpc_title_block": "20"
        }
      }
    }
  },
"front-config": {
    "all-pages": {
      "filters": {
        "text": {
          "fp-title": "20",
          "fpc_title_block": "20"
        }
      }
    }
  }`

Thank You!

**Comment by herrvigg** [comment]
If you place your ` i18n-config.json` file in your theme folder first check that it is found properly. If you save the options or reactivate the plugin you should normally see this file in the `Options > Integration > Configuration files`. Is that the case?

**Comment by herrvigg** [comment]
Apart from this i know the [JSON format ](https://github.com/qtranslate/qtranslate-xt/wiki/JSON-Configuration)  is very cumbersome and this is one of the main future tasks to improve this plugin, something has to be done there.

The first thing is to clarify if it's admin section for you as editor or just the front-side for any client. For a filter it should rather be a front-side. If so it's enough to `front-config`. You can check an example here:
`wp-content/plugins/qtranslate-xt/i18n-config/plugins/bbpress/i18n-config.json`

Just as an example for the structure
```
{
  "vendor": {
    "plugins/bbpress": "1.0"
  },
  "front-config": {
    "all-pages": {
      "filters": {
        "text": {
          "bbp_get_forum_content": "20"
        }
      }
    }
  }
}
```

But if it's on the admin side you need more structure with pages, anchors and forms. Example here:
`i18n-config/themes/magnium/i18n-config.json`
