### ISSUE TITLE
Call $ post-> post_title

### ISSUE THREAD

**Issue by sviluppomania** [qtranslate/qtranslate-xt#816]
hi, I have to call $ post-> post_title to have the title of the post, how can I set it to have two, one per language ??

  $ post-> post_title how is it in qTranslate-XT?

**Comment by herrvigg** [comment]
This is not an issue but concerns support for very specific development. Please don't open tickets like this because i won't answer them. Also please stop spamming people and different topics for your personal requests. This is not how this community is working. Thank you to respect this.

**Comment by sviluppomania** [comment]
@herrvigg 
I requested assistance for a plugin that you took responsibility for managing and did not respond.

**Comment by sviluppomania** [comment]
@herrvigg 
Is the plugin from the qTranslate-X Community or your plugin?
It seems that you close and open requests for "assistance" as if it were yours, without guaranteeing the right "democracy".

**Comment by herrvigg** [comment]
Updated the Troubleshooting section with new [Guidelines](https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting#guidelines). I hope this clarifies the limits that i maybe considered to be obvious. This is a free plugin and i spend already a lot of my free time. This is not a forum for any kind of assistance and tickets not following these guidelines will be rejected. Constructive help for the community is always welcome.
