### ISSUE TITLE
category_link is deprecated since version 2.5.0! Use term_link instead.

### ISSUE THREAD

**Issue by aunruh** [qtranslate/qtranslate-xt#822]
category_link is deprecated since version 2.5.0! Use term_link instead.

Latest WordPress version throws this error.
WordPress 5.4

👯‍♂️

**Comment by herrvigg** [comment]
This is not due to qTranslate but WordPress, i already commented on their ticket: https://core.trac.wordpress.org/ticket/49759 

It's fixed in 5.4.1 yet to be released. Maybe you can patch the WordPress code until then but i won't work on this.

**Comment by herrvigg** [comment]
Fixed in WP 5.4.1, now available.
