### ISSUE TITLE
Use Pre-Path Mode is disabled 

### ISSUE THREAD

**Issue by hubosh** [qtranslate/qtranslate-xt#828]
I just activated qtranslate-xt in a website and I noticed that the Use Pre-Path Mode is disabled as you can see in the image below.

![image](https://user-images.githubusercontent.com/24465260/80303785-0b832680-87bb-11ea-9158-779d85d7a7fc.png)

Kindly assist

**Comment by herrvigg** [comment]
Very much likely a duplicate of #821.
