### ISSUE TITLE
Error that prevents the Varnish cache from working

### ISSUE THREAD

**Issue by daphnisse** [qtranslate/qtranslate-xt#829]
Hello,

Since the transition from qtranslate X to qtranslate XT we detect standard errors:
PHP Warning: Cannot modify header information - headers already sent in /vhosts/www.****.com/htdocs/wp-content/plugins/qtranslate-xt-3.8.0/qtranslate_core.php on line 462

It seems that this error prevents the varnish cache from working.

When we deactivate qtranslate, the "AGE" increments well and the cache works.
How to resolve this error?

Sorry for my english, I'm french ; don't hesitate to ask for any details.

Chloé

**Comment by herrvigg** [comment]
This code instruction corresponds to the time when the cookie is sent, which sends the headers. So it's already too late. There is something else happening before this event that writes some outputs and which should not happen. You will have to try spotting the output or the error, by debugging or putting some breakpoints.

**Comment by herrvigg** [comment]
Re-try with WP 5.4.1 maybe you had some output with the category_link as #822.

**Comment by herrvigg** [comment]
@daphnisse you should try to capture the output and link the the source of the error. Maybe it's a redirection, such as this one:
https://github.com/qtranslate/qtranslate-xt/blob/4991160d8bbb162f125efa66e62bb3994e36e52d/qtranslate_core.php#L109

Try commenting this line, removing the PHP asserts or play with the debug macros as described in [troubleshooting](https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting). 

Until then there is no much we can do here so i close it for now. Feel free to re-open when you have more information.
