### ISSUE TITLE
How to localize standard woocommerce widgets

### ISSUE THREAD

**Issue by EasyEl** [qtranslate/qtranslate-xt#830]
Hey there,

![Bildschirmfoto 2020-04-29 um 11 34 28](https://user-images.githubusercontent.com/52560/80581464-7af05480-8a0d-11ea-9692-5de41f3a16cb.jpg)

I always struggle with standard widgets like this standard woocommerce product widget not translating product titles correctly (also happens in the order confirmation emails etc. but not as important).

Any idea on how to get those tiles translated?

Best,
Elmar

**Comment by EasyEl** [comment]
Solution: I found out that the easiest way is to overwrite the template in a child theme and call __() in it.

**Comment by herrvigg** [comment]
@EasyEl which template is it? Good if __() works as workaround but it would rather be a kind of temporary fix. Does this problem has something to do with #616 ?

**Comment by herrvigg** [comment]
Sorry i meant #755 which is about the WC widget, it could be related.

**Comment by EasyEl** [comment]
Yes, likely. I put a little pointer about templating for others in the related case. Not ideal but a quick fix. Widget was content-widget-product.php which displays products. The real issue is that some kind of caching seems to be going on. While I use caching systems (wp-fastest-cache + redis) the widget is excluded from it. Still it is getting cached and I don´t know why. So for now I disabled it.

Ill attach a few screenshots
![Bildschirmfoto 2020-05-04 um 09 33 50](https://user-images.githubusercontent.com/52560/80944938-f6298000-8dea-11ea-87d1-e61e68e4adf2.jpg)
![Bildschirmfoto 2020-05-04 um 09 34 14](https://user-images.githubusercontent.com/52560/80944952-faee3400-8dea-11ea-9e09-882b1a7709ba.jpg)
![Bildschirmfoto 2020-05-04 um 09 34 36](https://user-images.githubusercontent.com/52560/80944955-fc1f6100-8dea-11ea-96f5-de9128ff0867.jpg)
