### ISSUE TITLE
Configure redirect page when change language

### ISSUE THREAD

**Issue by MattTrovao** [qtranslate/qtranslate-xt#832]
Hi guys, I am working in one website and the client want the following action:
- If he is a page, like Contact, and change the language he stay in Contact and don't go to Home page.
I look in the settings but didn't find anything like that, there is a way of doing that? 

It's important to say, I have full acess of the code. If anyone could help me, I would be grateful.

**Comment by herrvigg** [comment]
@MattTrovao sorry but this is not about an issue or a feature, but a request for support. I don't even understand your problem. Some people can still try to answer the ticket but i will close directly anything not respecting the conditions given in https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting.

**Comment by MattTrovao** [comment]
I need to stay in the same page when I change the language, I didn't find any code that could help me. In the troubleshooting I didn't find anything like I was trying to do. 
This is my current code, right now I am trying to get the slug of the page to add in the end of the href
`<a href="<?php echo site_url(); ?>/pb">
    Português <img src="<?php echo get_template_directory_uri(); ?>/dist/img/pt.png">
</a>
<a href="<?php echo site_url(); ?>/en">
    English <img src="<?php echo get_template_directory_uri(); ?>/dist/img/en.png">
</a>`

I find one question in slack overflow, where the problem is very similar to what I want to do, they said to use the function `qts_language_menu() ` and will work, but when I put this function nothing happend.
