### ISSUE TITLE
Minority languages and three letter codes

### ISSUE THREAD

**Issue by mikoet** [qtranslate/qtranslate-xt#836]
I want to use this plugin for a website that will contain content in Low Saxon and maybe also North Frisian. Both are minority/regional languages in Northern Germany and for Low Saxon also in the Eastern Netherlands.

Both, Low Saxon and North Frisian have no ISO 639-1 two letter code, but ISO 639-2 and ISO 639-3 three letter codes. Those are "nds" for Low Saxon and "frr" for North Frisian.

Why don't you allow 3 letter codes to be entered?

In the plugin's language settings I can enter a three letter code for the property "Locale at front-end", but for the property "Language code" I have to make up some not existing two letter codes for these languages like "nd" or "ns" for Low Saxon.

Any thought's on this?

**Comment by herrvigg** [comment]
Yes the 2-letter limitation is definitely becoming problematic. See #668 we should handle all those cases within the same improvement as a new feature. Good you pointed out that case with 3 letters.

**Comment by herrvigg** [comment]
We have to take it together with #668 so we can close this ticket.

**Comment by herrvigg** [comment]
Now merged in master for the 3-letter support!

**Comment by herrvigg** [comment]
@mikoet released in 3.9.0. Let me know how it works!
