### ISSUE TITLE
Yoast 14.1+ incompatible with qTranslate XT

### ISSUE THREAD

**Issue by fabianpiau** [qtranslate/qtranslate-xt#838]
I open an issue first on Yoast https://github.com/Yoast/wordpress-seo/issues/15186 but they close it and it seems they have refactored quite a lot of logic on their side since version 14.
The first visible thing that does not work anymore is the breadcrumbs that are not translated anymore (maybe there are other things but I did not spot anything apart from that).
Do you think it will be possible to make some improvement in qTranslate XT to improve compatibility with the latest versions of Yoast?

**Comment by herrvigg** [comment]
hello,
yes i know they have changed a lot of things, certainly in good but this would require even more work on qT-XT side so i don't know yet.

We can keep only one issue for now, no need to open new ones.
