### ISSUE TITLE
Qtranslate-XT doesn't work with JQuery library

### ISSUE THREAD

**Issue by sandrinne** [qtranslate/qtranslate-xt#848]
Hello Github team & community:
I have a problem, and I hope you can help me. When I activate the Qtranslate-XT plugin in my WP, a first pop-up based in JQuery that I have on the web to control the age and accept the cookies, disappears from the web:

jQuery('#menu-item-285').click(function(){ jQuery('.menucontent').hide(); jQuery('html, body').removeClass("sinscroll"); jQuery('html, body').animate({scrollTop: jQuery("#origens").offset().top-80}, 1000); });

jQuery('#no').click(function(){ window.location.href = "https://playdoh.hasbro.com/es-lam/shop"; });
jQuery('#yes').click(function(){ 
	jQuery('.cookies').fadeOut();
	jQuery('.intro').prepend('<img src="https://www.rawalgin.com/wp-content/themes/rawal/images/nadador-ok.gif" />');  
	var scroll = jQuery('#start').offset().top;
	jQuery('html, body').delay(2000).animate({scrollTop: jQuery("#start").offset().top}, 2000);
	jQuery('body').removeClass("sinscroll");
	setTimeout(function(){ jQuery('.intro').remove(); jQuery('html, body').animate({scrollTop: jQuery("#start").offset().top}, 0); }, 5000);
});

And de css style of .cookies:

.cookies {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: white;
    overflow: hidden;
    z-index: 10000;
}

The site is:
https://www.rawalgin.com/es/

When I deactivate the plugin the animation works again and appears, so there seems to be some kind of incompatibility between the plugin and this JQuery programming ... Do you know what I can do to fix it? 
Hopefully you can help me, I'm desperate to fix it and I don't know where to start, I'm a designer and not a programmer. Thank you in advance!

**Comment by herrvigg** [comment]
qTranslate does not execute any JS script on the frontend, jQuery is only used on the admin part in WP so it can simply not come from a jQuery incompatibility from qTranslate. There is maybe another side effect due to qTranslate adds i can't enter in all the specific details of the implementations of the cookie popups on your website. Yes it is a programmer job but this part does not concern qTranslate directly, it is all about specific integration.

**Comment by herrvigg** [comment]
Btw your HTML looks invalid, you have a `<header class="flexat">` appearing before `<body data-rsssl=1 >`, it should come after.

**Comment by sandrinne** [comment]
Hello Herrvigg! Solved! The issue was concerned about the templates of wp and the url's with the plugin Qtranslate activated:
- With /es takes a template that doesn't have the cookie consent, It loaded the page.php instead the index.php. Fortunately I've commented the issue with a programmer friend and help me about this.

Thank also for your help!

**Comment by herrvigg** [comment]
Great to read, happy you solved it! 😎
