### ISSUE TITLE
Problem with the Rank Math SEO plugin

### ISSUE THREAD

**Issue by ramspeed** [qtranslate/qtranslate-xt#855]
Congratulations on this new support for qTranslate.
I have a problem with the meta description and the title tag for google using the Rank Math SEO plugin.
I don't know how to translate it into multiple languages. Are there any solutions?
Thank you

**Comment by herrvigg** [comment]
hello,
take a look at the [Integration Guide](https://github.com/qtranslate/qtranslate-xt/wiki/Integration-Guide) and the [JSON configuration](https://github.com/qtranslate/qtranslate-xt/wiki/JSON-Configuration). If it's about regular fields (no javascript update) it should be very easy. The JSON format is a bit cumbersome but it works. You can take a look at the existing ones and just replace the page info and field names for your case.
