### ISSUE TITLE
Emails language - woocommerce

### ISSUE THREAD

**Issue by mainion** [qtranslate/qtranslate-xt#857]
Hi,
I have shop site in 3 languages ​​(EN, LT, PL) by qtranslate-xt. And two currencies (EUR, PLN) by WooCommerce Currency Switcher. But after every orders woocommerce sending an automatic email in default language (english) no matter the site language chosen by user. Please advise how to fix the issue.

**Comment by herrvigg** [comment]
Sorry but we don't offer free support. Issues not following the rules described here will not be accepted.
https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting
