### ISSUE TITLE
Issue with block editor

### ISSUE THREAD

**Issue by dlambova** [qtranslate/qtranslate-xt#858]
Hi,
I am still using the classic editor on my site but I tested the block editor on staging environment. The first time (en of April) it worked but now it doesn't save the post information after I click on publish. When saving the post, the title disappears and the body stays but it is not visible after preview. I was able to restore the body from the warning that appeared above the post but then it wasn't visible again.

I was actually testing if the the genesis shortcodes work with Qtranslate-XT, when I discovered this bug. I changed the theme to a non genesis one and then disabled one by one multiple plugins but the issue persisted. Only after disabling QTranslate-XT I was able to save the post. When I enabled it again, the issue was the same.

Do you think this can be resolved? I am afraid that we will be all forced to move to Gutenberg soon and I really want to avoid changing to another plugin.

Thank you!

**Comment by herrvigg** [comment]
I can't reproduce that problem but it looks like an integration issue with another plugin. It seems similar to #812. Do you also use Post Type Builder? What other plugins do you have? If you go in the qTranslate-XT settings / Troubleshooting can you give the content given in "Versions"?

**Comment by dlambova** [comment]
I just realised that I don't have the latest version of QTranslate-XT. Must have been an issue with Github updater as it happened already before. I reinstalled Github updater and I will wait to get the update message. Will let you know if it is resolved after the update.
Thanks

**Comment by dlambova** [comment]
Hi,
The plugin was updated and now it seems to work perfectly with Gutenberg. Initially I thought the post can't beedited after published but the languages are switched through the top language switching button, which also switches the language of the whole admin panel of Wordpress. The only issue that still remains is #841. It would be really nice if there would be future integration with Yoast Breadcrumbs as they seem to be important for SEO.
Thank you!
