### ISSUE TITLE
Integration with Asgaros Forum

### ISSUE THREAD

**Issue by georgio-1** [qtranslate/qtranslate-xt#859]
Hi there!
Thank you for this excellent translation tool!
Please, could you add support for [Asgaros Forum](https://wordpress.org/plugins/asgaros-forum/) on your todo list?

Best regards

**Comment by herrvigg** [comment]
hello,
sorry no plan for this.
You can try by looking at https://github.com/qtranslate/qtranslate-xt/wiki/Integration-Guide
though we are aware it is not very convenient with the i18n-config, but this is what we have for now.
