### ISSUE TITLE
[WC] Unable to change product variations

### ISSUE THREAD

**Issue by progcode** [qtranslate/qtranslate-xt#865]
Woocommerce version: 3.9.1
Qtranslate-XT version: 3.8.1

How can i change product prices and attributes with simple or variable products? Currently this fields aren't changes on different languages.

![Screenshot 2020-07-31 at 19 50 06](https://user-images.githubusercontent.com/5430762/89062647-1ffd2f00-d367-11ea-9f58-47f54e647ead.png)

**Comment by herrvigg** [comment]
If you enter raw ML values with the tags it should work. Technically we can't handle that fields with the buttons at the moment because it's handled by WC client-side in Javascript.

**Comment by progcode** [comment]
OK, it works with this "hack". thx
