### ISSUE TITLE
No language switch button on the editor after updating to WP 5.5

### ISSUE THREAD

**Issue by rkovachev88** [qtranslate/qtranslate-xt#867]
Hello,

After updating to WP 5.5 there is no language switch button on the classic editor.

**Comment by bagaweb** [comment]
Same problem here!

**Comment by aldoalexandre** [comment]
Worked for me after a hard refresh on Chrome (cmd+shift+R)

**Comment by bagaweb** [comment]
Update following @aldoalexandre comment:
after clearing Opera cache, the problem is solved.

**Comment by rkovachev88** [comment]
Not showing even after cleaning the browser cache.

**Comment by rkovachev88** [comment]
After deleting the cache it is ok.

**Comment by herrvigg** [comment]
OK good tip for the cache for those having problems. I upgraded to WP 5.5 but it worked without doing that.
