### ISSUE TITLE
Language switching does not work in admin interface - Wordpress 5.5

### ISSUE THREAD

**Issue by hejhim** [qtranslate/qtranslate-xt#869]
Hi qtranslaters!
There seems to be a problem within the post editor with the new Wordpress 5.5. There are no language switching buttons anymore and all languages are displayed in the classic editor. Any hint how to activate them again?
Best,
Martin

**Comment by bagaweb** [comment]
Hi Martin, have a look here https://github.com/qtranslate/qtranslate-xt/issues/867

**Comment by hejhim** [comment]
@bagaweb Thanks for your tip but the problem remains. I've deactived qtranslate-XT, deleted it and reinstalled it with the current version, I also updated the Classic Editor plugin and tested it in serveral browsers (with deleting the whole caches).

I've figured out that there is also a problem with the featured image box and the screen options on the top right. These problems remain even if I deactivate qtranslate-XT. So it might be not a plugin problem but a Wordpress or Classic Editor problem.

**Comment by bagaweb** [comment]
@hejhim sorry to hear that.

Have you tried this plugin? https://wordpress.org/plugins/enable-jquery-migrate-helper/

I had a different problem on another website after updating to WP 5.5 and this plugin helped me to solve.

**Comment by hejhim** [comment]
@bagaweb You are great! Thank you! By chance I just installed this plugin before and found an old jQuery function in my theme which I replaced. Now everything is working again! 👍

**Comment by bagaweb** [comment]
Excellent :)
