### ISSUE TITLE
feature to use the available Yoast SEO API?¿

### ISSUE THREAD

**Issue by raulfg** [qtranslate/qtranslate-xt#878]
"Unfortunately, qTranslate-XT as well as the other versions of qTranslate have not added compatibility with the latest versions of Yoast SEO. Since this means that qTranslate-XT has to add a feature to use the available Yoast SEO APIs, we’re not able to fix the issue on our side. We recommend contacting the qTranslate-XT developers to report any issues or to request compatibility with Yoast SEO. If you can give us any updates on that progress, please feel free to reply."     Yoast SEO Support

Are you working on these compatibilities? All updates in WP with latest yoast plugin are causing wordress to stop working with 3.8.1 of qtranslate xt. 

Thanks in advance.!

**Comment by herrvigg** [comment]
For yoast we are aware of this, i suggest we keep the discussion in #794. The integration of Yoast and the new API is quite a bit task.

Personally i don't have time to work on Yoast and it's quite specific. I didn't have much time either for qTranslate these last weeks but i will try to focus on the important generic features such as lang formats with #668 and maybe even more important the transition to a new official repo.
