### ISSUE TITLE
ACF REST API  Endpoint not working when switching language

### ISSUE THREAD

**Issue by amouratoglou** [qtranslate/qtranslate-xt#881]
Hi guys, first thanks for keeping it real and alive... This plugin, well, has it's own history. I have followed since day 1.

Well now I still favour it vs other , because it is fast and I love the series of resurrections, the last obs the most glorious one.

I have found a strange behaviour that is breaking my site. Well this particular page uses Vue.js and calls the REST API endpoint: ie:

https://herzlin.com/wp-json/wp/v2/postypecoolname

I tested if the translation was picked up automatically or if I would have to create 3 post types for each language, as a solution to overcome the issue, but noticed that even If I do that, there is some kind of dark redirection that kills my fetch to the endpoint... showing a 404 page of WP.

I'm using also A[PI REST for ACF plugin](https://wordpress.org/support/topic/qtranslate-xt-2/) that made it easier to work and expose ACF fields. is this the right approach? 

Any hint is deeply appreciated.  

cheers

**Comment by amouratoglou** [comment]
@herrvigg  do you know any way to overcome the redirection?

**Comment by herrvigg** [comment]
REST calls should not redirect, see #609. Check that you have your rewrites rules flushed from the permalinks page.

**Comment by amouratoglou** [comment]
I did the  2 times. flush, did not work, will double check just in case.
thanks for your quick response. btw do you know if there is any wayt access translated fields via REST API? does it uses the /lang/ prefix logic?

**Comment by herrvigg** [comment]
The REST API works fine for standard qTranslate as shown in #609. For the integration with ACF this is more specific, i don't know because i don't use this API REST for ACF plugin. It's more work to investigate what is going on.

**Comment by amouratoglou** [comment]
I will probably have to create a custom solution to expose ACF fields, that probably works better than using this plugin which doesn't seem to play well with QtranslateXT. Do you know if there is any documentation that could help me related with ACF/REST/QtranslateXT ? thanks so much for your time. have a great day/night.

**Comment by herrvigg** [comment]
There is no section in the documentation but all the information can be found in #609  and #621. There should be no redirection and the cookies are ignored. The REST calls should be entirely deterministic and stateless, by definition.
I don't know what this plugin does, the case should be investigated more in depth with all the necessary context. The best to debug is to use a real debugger with breakpoints.

**Comment by amouratoglou** [comment]
I had to update my fetch url...my bad, need more coffee!!
it works now

**Comment by herrvigg** [comment]
Great! Good to know.

**Comment by herrvigg** [comment]
But the rewrite rules are essential for this REST part.
