### ISSUE TITLE
Javascript rebirth: Babel and ES6

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#887]
Currently all the JS code is in such a prehistoric shape that it's giving me serious headaches... 

I'm currently experimenting a few things with Babel to upgrade all the classic JS code of qTranslate to a whole new world - ES6! The Gutenberg part is already ES6 but it's very little code. What is at stake are:
- the many functions in the common module
- the script loading mechanism defined in qTranslate PHP
- how the libraries are built for debug and production
- the interface for integration.

Having modern JS everywhere would open a million new possibilities - but this may be quite a big jump so i will need testers. I hope to have something soon!

**Comment by picasso** [comment]
I fully support it. Continuing to write in vanilla script is already very tedious and annoying

**Comment by herrvigg** [comment]
For information, i've started to work on the evolution of the JS framework in this branch:
https://github.com/qtranslate/qtranslate-xt/tree/refactor-js-es6

**Comment by herrvigg** [comment]
Closed with PR #990, under evaluation.

**Comment by herrvigg** [comment]
Now merged in master!
