### ISSUE TITLE
WPForms + new plugin

### ISSUE THREAD

**Issue by mstudioIL** [qtranslate/qtranslate-xt#888]
Hey,
Is this the right place for support?
I got site using qTranslate X (the old plugin), the site using the WPForms plugin, I used the shortcode to show the form labels and it work on the site, but on the mail I getting, I see the shortcode and not the right label by the language.
Is it WPForms' problem I need to contact them?
How do I moving from the old plugin to the new and how I update the new when there is updates?

**Comment by herrvigg** [comment]
> I got site using qTranslate X (the old plugin), the site using the WPForms plugin, I used the shortcode to show the form labels and it work on the site, but on the mail I getting, I see the shortcode and not the right label by the language.

You certainly need a specific integration of qTranslate with that plugin, this is not a basic feature.

> How do I moving from the old plugin to the new and how I update the new when there is updates?

Please read the [README](https://github.com/qtranslate/qtranslate-xt/blob/master/README.md).

**Comment by mstudioIL** [comment]
Thanks

**Comment by herrvigg** [comment]
You can also take a look at the https://github.com/qtranslate/qtranslate-xt/wiki/Integration-Guide
We are aware it is not really user-friendly, but this is the current state.
