### ISSUE TITLE
q-translate xt

### ISSUE THREAD

**Issue by cologne123** [qtranslate/qtranslate-xt#889]
Hello everyone,

I want to make my website multilingual with q-translate xt, but after installing the plugin I can't see a button to view the English and German pages. Can someone explain to me how I can see the language-switch-button. Do I need to install another plugin?

Best, Marina

**Comment by herrvigg** [comment]
You can check the startup page in the wiki: https://github.com/qtranslate/qtranslate-xt/wiki/Startup-Guide

I recommend you to install the Classic Editor to get the switching buttons. It allows you to select the default editor (Classic / Gutenberg) or you can switch for any article. With Gutenberg we have a limitation, you have to edit one language at a time.

As a complement to the wiki, check that you have the type of page enabled in qTranslate-XT advanced options, but it should be the case by default.
