### ISSUE TITLE
Deprecated Javascript code in ACF module

### ISSUE THREAD

**Issue by drlovable** [qtranslate/qtranslate-xt#890]
I updated to qtranslate-xt version 3.9 with Wordpress Version 5.5

The media library no longer shows any items. The page loads, but no items appear.

If I disable the Q-Translate XT plugin the Media library does work.

jQuery Migrate Helper — Warnings encountered
This page generated the following warnings:

jQuery is not compatible with Quirks Mode

I suspect this is a javascript error somewhere inside qtranslate-xt.  Any ideas?

**Comment by herrvigg** [comment]
The media library works fine for me. 

What browser do you have? You should see errors in the console but i don't know what it switches to Quirks Mode.

I didn't make big changes in the Javascript code, i even reverted a change that would not work for old IE... (and i will certainly drop this retro-compatibility at some point).

**Comment by drlovable** [comment]
I'm using Chrome Version 85.0.4183.121 (Latest version)

I'm getting this js error when trying to open the media library.

wp-content/plugins/qtranslate-xt-3.9.0/modules/acf/assets/acf_5/qtranslatex.min.js: jQuery.fn.load() is deprecated

**Comment by drlovable** [comment]
To be perfectly clear, the issue wasn't with the media library itself, it was with something called Foo Gallery not being able to load the media gallery
I got this working by altering jQuery(window).load(function ()  to jQuery(window).on('load',function ()  in both the minified and non minified javascript files.

**Comment by herrvigg** [comment]
OK i see the problem... after updating Chrome. It was not due to the last changes in qT-XT 3.9.0 but it's some old code in the ACF module so you need the ACF plugin to be enabled. Also, jQuery Migrator is not part of WP 5.5 anymore, it must be installed separately. 

Good you found a temporary solution. I will send a more complete fix. Thanks for reporting!

**Comment by herrvigg** [comment]
Yet another reason to move to modern JS...  #887
