### ISSUE TITLE
Categories & taxonomies being translated in dashboard

### ISSUE THREAD

**Issue by hubosh** [qtranslate/qtranslate-xt#891]
Is it possible to switch categories and taxonomies names based on the current language

**Comment by herrvigg** [comment]
Which dashboard?
What do you mean by "**switch** categories and taxonomies names"?

**Comment by hubosh** [comment]
> Which dashboard?
> What do you mean by "**switch** categories and taxonomies names"?

@herrvigg 

I mean in here
![Capture](https://user-images.githubusercontent.com/24465260/94037910-871aeb00-fdce-11ea-8489-8052e191b6cc.JPG)

**Comment by herrvigg** [comment]
I can't find this in the main dashboard (/wp-admin/index.php). Did you customize some layout or is it something else?

If i go in the categories (/wp-admin/edit-tags.php?taxonomy=category) everything works with the switching buttons.
