### ISSUE TITLE
WP Gutenberg Editor Support

### ISSUE THREAD

**Issue by DevWael** [qtranslate/qtranslate-xt#896]
Hi there,
I'm using qtranslate-xt plugin in my projects and I'm willing to contribute to Gutenberg editor support.

- What stage have you reached in the editor support development?
- How can I contribute to development?

Thank you,
Best regards.

**Comment by herrvigg** [comment]
hello,
the initial support for Gutenberg was released in 3.8.0, April 2020, with the limitation of language switch. Enabling switching buttons would be much more complex. Nothing special in progress at the moment.
It would be good to fix #809 and investigate more about #873.

**Comment by herrvigg** [comment]
You can find the issues specific to Gutenberg with the labels: https://github.com/qtranslate/qtranslate-xt/labels/gutenberg
