### ISSUE TITLE
Languages detection in CPT without content

### ISSUE THREAD

**Issue by Abdipour** [qtranslate/qtranslate-xt#898]
Hi,
When a custom post type haven't editor in "support" parameter (or the content is empty), qTranslate can not detect the languages.
Is there any action or hook to change this function? If it can detect languages based on post title (or a custom field) problem will solve.

**Comment by herrvigg** [comment]
What do you mean by "qTranslate can not detect the languages"? Front or admin side?
If the post type is not enabled, the switching buttons won't be shown. This is what we want.
If the content is empty i don't really understand what you are expecting. You can edit the post normally. On the front side there are all the options available to show alternate content.

**Comment by Abdipour** [comment]
Sure. there isn't any issue. I mean admin side in edit posts list, Language column. When I want to find posts without translation this will help.

**Comment by herrvigg** [comment]
Actually the language column is there even if you don't enable the post type in qTranslate, which we shouldn't even display if we were strict about the logic. If you enable the post type, edit some multi-lingual content for a post and disable the post type again, you will even see all the languages detected in the language column. You can also change the post content with raw tags and you will get the same. If the content is empty there is no language to detect and qTranslate displays this correctly. I don't see any problem.
