### ISSUE TITLE
Translate wp_terms_checklist

### ISSUE THREAD

**Issue by xabispacebiker** [qtranslate/qtranslate-xt#902]
By now wp_terms_checklist is not translated so the users get something like this:

![Captura de pantalla 2020-10-08 a las 23 16 36](https://user-images.githubusercontent.com/1733884/95514704-ad3eae80-09bc-11eb-811c-91e77ecdd6e6.png)

Would it be possible to get those terms translated ?

**Comment by herrvigg** [comment]
> By now wp_terms_checklist is not translated 

Is that something new?

Is this related to a specific URL or just the function?
