### ISSUE TITLE
Term name of translation

### ISSUE THREAD

**Issue by efoula** [qtranslate/qtranslate-xt#903]
Hello,

I've searched all over the internet and didn't find any answer yet to my question. I hope anyone could help me here, many thanks in advance.

I am trying to reach out the term name in a specific language (EN), whatever is the current active language or the default language

`$term = get_term_by( 'id', absint($cityname), 'city'); $term_name = $term->name;`

I have tried many methods with no luck at all :(
`qtrans_use('en', $term->name,false);`
`$term = apply_filters('translate_term', $term, $lang='en', $taxonomy='city');`

unfortunately, it always return in the current language instead of the requested language which is 'en'.

Much appreciated your prompt answer!

**Comment by herrvigg** [comment]
There is a hook on `get_term` (and all related functions) so it will be translated for the current language.

If you want a specific language, you have to use lower-level functions such a `qtranxf_use('en', $term_name)` but you need the raw term value.

You can also disable the qTranslate hook and rewrite your own one but that's a more hacky solution that i don't recommend, it will be harder to maintain.
