### ISSUE TITLE
Contact form 7

### ISSUE THREAD

**Issue by francescocortese** [qtranslate/qtranslate-xt#906]
Can't change language when I use contact form 7. There is not integration.

**Comment by antonzol** [comment]
I gust create new contact form for each language

**Comment by MountainKing20** [comment]
You can still use the short tags inside the contact form, e.g. [:en] English text [:de]German text[:] etc. No need to create multiple contact forms.

**Comment by abclution** [comment]
"Short Tags / RAW Editor mode" is by far the most compatible way to handle translations.

Ultimately in my experience it was the easiest to maintain as well.

**Comment by ozankonrot** [comment]
> You can still use the short tags inside the contact form, e.g. [:en] English text [:de]German text[:] etc. No need to create multiple contact forms.

For this to work I used _e(), echo didn't work.
_e(do_shortcode('[contact-form-7 id="xxx" title="xxx"]'))
