### ISSUE TITLE
Taxonomy custom fields - ACF titles of custom field groups render raw [:en] instead of the correct language

### ISSUE THREAD

**Issue by amouratoglou** [qtranslate/qtranslate-xt#908]
hi guys, I noticed that ACF field group titles are not showing correctly, instead of seeing the right language I can see the raw language language "tags" [:en] when editing the content for example of a Taxonomy.

**Comment by leonardola** [comment]
Same problem here

**Comment by amouratoglou** [comment]
mmm that's a different issue I haven't seen on my end. any errors in the console? @leonardola

**Comment by leonardola** [comment]
@amouratoglou you can ignore my comment above. When creating the custom field I did not select the proper option "Text(qtranslate)". When I did so it worked perfectly. Including the fields on Taxonomies.

**Comment by herrvigg** [comment]
Related to #1255 but there was one specific part missing for the field descriptions in a taxonomy.
Now fixed in master.
