### ISSUE TITLE
woocommerce shop page doesn't show products

### ISSUE THREAD

**Issue by madmonkeyworks** [qtranslate/qtranslate-xt#911]
Hi, 

for some reason, the woocommerce shop page doesn't show products in the translation. Default language works fine.

My setting:
- main domain > https://zebrasaurus.nl
- Shop page in Dutch > /winkel
- Shop page in English > /en/shop (this one doesn't show any products)
- woocommerce 3.7
- using qTranslate slug plugin version 1.1.18

Strange enough, the slug "en/winkel" does return the products.

Somebody who can shed a light on this or can help debug?

Thnx and cheers

**Comment by herrvigg** [comment]
@madmonkeyworks I don't use qtranslate slug but i can't see any page in english. If i go to ` https://zebrasaurus.nl/en/` it says page not found and this should not even depend on WooCommerce. Maybe try first without qtranslate slug.
