### ISSUE TITLE
Ediding widgets in wp-admin/widgets.php is broken

### ISSUE THREAD

**Issue by Hr0bar** [qtranslate/qtranslate-xt#912]
Editing widgets doesnt work at:
/wp-admin/widgets.php
it works at:
/wp-admin/customize.php

Here you can see a video of the latest XT, all kinds of bugs happen, not all were captured in the video...

https://www.youtube.com/watch?v=dA03SXlyhLg&feature=youtu.be

https://www.youtube.com/watch?v=FyChSDyRiXA&feature=youtu.be

Basically you can overwrite other languages just by clicking around and modifying that language after qTranslate wrongly puts content from other language in there

I assume some kind of dynamic updates on button click needs to be done to the content. Some of those happen when you expand/close the individual widgets already, but also very inconsistent.

**Comment by herrvigg** [comment]
Duplicate https://github.com/qtranslate/qtranslate-xt/issues/616, but i haven't investigated further on this.
The videos are useful to visualize the problem.
