### ISSUE TITLE
Woocommerce 4.6.2    Attributes - dont have qtranslate tabs

### ISSUE THREAD

**Issue by andreysneg** [qtranslate/qtranslate-xt#915]
Woocommerce 4.6.2  
Attributes - dont have qtranslate tabs

Picture:
https://bit.ly/2I4Rz6N

**Comment by herrvigg** [comment]
There was some code but it didn't work anymore. I pushed a patch to fix it, this should work now.

**Comment by herrvigg** [comment]
Fix released in 3.9.2
