### ISSUE TITLE
Warning: _() expects exactly 1 parameter, 2 given

### ISSUE THREAD

**Issue by nabi009** [qtranslate/qtranslate-xt#916]
( ! ) Warning: _() expects exactly 1 parameter, 2 given in /wp-content/plugins/qtranslate-xt-3.9.0/admin/qtx_admin_settings.php on line 110
--

( ! ) Warning: _() expects exactly 1 parameter, 2 given in /wp-content/plugins/qtranslate-xt-3.9.0/admin/qtx_admin_settings.php on line 112
--

![Screenshot from 2020-11-08 11-23-29](https://user-images.githubusercontent.com/3170831/98459088-db2e3300-21b4-11eb-9f92-1478787855d5.png)

**Comment by herrvigg** [comment]
Fixed in https://github.com/qtranslate/qtranslate-xt/pull/900, merged in master.
Until the next release you can apply the same patch.

**Comment by herrvigg** [comment]
Fix released in 3.9.1.
