### ISSUE TITLE
Back-end: Translation of "Custom field" column of "Custom post type" on page '/wp-admin/edit.php?post_type=custom_post_type'

### ISSUE THREAD

**Issue by Wewill** [qtranslate/qtranslate-xt#918]
Hello team, 

Back-end: Translation of "Custom field" column ( e.g. a custom taxonomy ) of a "Custom post type" on page '/wp-admin/edit.php?post_type=custom_post_type'

How can I achieve this ? By a json config ? I tried but not successfully. 

Front-end is translated "Jardin", back-end is not "[:fr]Jardin[:en]Garden[:]". 

Thanks a lot, 
Best regards, 
Wilhem

**Comment by Wewill** [comment]
Hello, Anyone can help me with this ?

**Comment by Wewill** [comment]
![Capture d’écran 2021-01-05 à 11 51 37](https://user-images.githubusercontent.com/3178443/103637963-8c024580-4f4c-11eb-8a22-25f9f965ec4b.png)
![Capture d’écran 2021-01-05 à 11 51 15](https://user-images.githubusercontent.com/3178443/103637966-8c9adc00-4f4c-11eb-8be9-bf6eecddb231.png)

**Comment by herrvigg** [comment]
I made a quick test and this works perfectly fine for me, with an existing taxonomy or even a custom one.

The translation is done in `qtranxf_term_sanitize_name` which is called in the `term_name` filter with context = display.

https://github.com/qtranslate/qtranslate-xt/blob/d506d09de694e362e408cc52645fc5b731950451/admin/qtx_admin_taxonomy.php#L114-L123

How did you link this category taxonomy to your custom post type?

**Comment by herrvigg** [comment]
@Wewill any update on this?

**Comment by Wewill** [comment]
@herrvigg hello, sorry for my late reply.

> How did you link this category taxonomy to your custom post type?

Yes, it is. 

But the issu was from a custom column declaration in theme with `manage_posts_custom_column` filter :

`
[...]
    function _sf_posts_custom_columns( $column ) {
        global $post;
        switch ( $column ) {
            case "description":
                the_excerpt();
                break;
            case "thumbnail":
                the_post_thumbnail( 'thumbnail' );
                break;
            case "portfolio-category":
                echo get_the_term_list( $post->ID, 'portfolio-category', '', ', ', '' );
                break;
            case "wa-slider-category":
                echo get_the_term_list( $post->ID, 'wa-slider-category', '', ', ', '' );
                break;
            case "spb-section-category":
                echo get_the_term_list( $post->ID, 'spb-section-category', '', ', ', '' );
                break;
            case "gallery-category":
                echo get_the_term_list( $post->ID, 'gallery-category', '', ', ', '' );
                break;
            case "testimonials-category":
                echo get_the_term_list( $post->ID, 'testimonials-category', '', ', ', '' );
                break;
            case "team-category":
                echo get_the_term_list( $post->ID, 'team-category', '', ', ', '' );
                break;
            case "clients-category":
                echo get_the_term_list( $post->ID, 'clients-category', '', ', ', '' );
                break;
           /* HERE */
           case "directory-category":
                echo get_the_term_list( $post->ID, 'directory-category', '', ', ', '' );
                break;
           /* HERE */
            case "directory-location":
                echo get_the_term_list( $post->ID, 'directory-location', '', ', ', '' );
                break;
            case "faqs-category":
                echo get_the_term_list( $post->ID, 'faqs-category', '', ', ', '' );
                break;
        }
    }
    add_action( "manage_posts_custom_column", "_sf_posts_custom_columns" );
`

I managed like this : 

`
add_filter( 'manage_edit-directory_columns', 'directory_columns' ) ;
function directory_columns( $columns ) {
	//$columns['sf_directory_address'] = __( 'Address', 'swift-framework-plugin');
	$columns['directory-category'] = __( 'Category', 'swift-framework-plugin');
	$columns['directory-project'] = __( 'Project', 'swift-framework-plugin');
	$columns['directory-location'] = __( 'Location', 'swift-framework-plugin');
	$columns['directory-artist'] = __( 'Artist', 'swift-framework-plugin');
	return $columns;
}

add_filter( 'manage_edit-directory_sortable_columns', 'directory_sortable_columns' );
function directory_sortable_columns( $columns ) {
	//$columns['directory-category'] = 'directory-category';
	return $columns;
}

add_action( 'manage_directory_posts_custom_column', 'directory_manage_columns', 10, 2);
function directory_manage_columns($column_name, $post_id) {
    switch ($column_name) {
		case 'location' :
			$out = get_meta('sf_directory_address', $post_id);			
			break;
		case 'sf_directory_address' :
			$out = get_meta($column_name, $post_id);			
			break;
		case 'directory-category' :
			$out = get_term_translated_list($column_name, $post_id);			
			break;
		case 'directory-project' :
			$out = get_term_translated_list($column_name, $post_id);			
			break;
		case 'directory-location' :
			$out = get_term_translated_list($column_name, $post_id);			
			break;
		case 'directory-artist' :
			$out = get_term_translated_list($column_name, $post_id);			
			break;
   		default:
            break;
    }
    return $out; // this is the display value
}

// Get term meta
function get_term_translated_list($taxonomy, $post_id) {
	$terms = get_the_terms($post_id, $taxonomy );
	$currentLang = qtranxf_getLanguage();
	$terms_ = array();
	
	foreach ($terms as $term) {
		$translated = $term->i18n_config['name']['ts'][$currentLang];
		$terms_links[] =  '<a href="'.get_edit_term_link ( $term->term_id, $taxonomy ).'">'.(($translated!='')?$translated:$term->name).'</a>';
	}
	$terms_string = join(', ', $terms_links );

	if ( empty( $terms ) )
		echo __( '<span style="color:silver;">—</span>' );
	else
		printf( __( '<p>%s</p>' ), $terms_string );
	
}
[...]
`

Thank you, 
Best regards, 
Wilhem

**Comment by herrvigg** [comment]
@Wewill so you managed to fix the problem? Can we close this ticket?

**Comment by Wewill** [comment]
@herrvigg yes you can !
