### ISSUE TITLE
Display Ugly language on the cart removal in woocommerce 

### ISSUE THREAD

**Issue by Dezueka** [qtranslate/qtranslate-xt#923]
Display Ugly language on the cart removal in woocommerce when adding product to cart and remove the cart from the cart basket.

![Opera Snapshot_2020-11-24_100252_www laocommerce com](https://user-images.githubusercontent.com/26108578/100041648-568e1680-2e3c-11eb-880e-3062efdb7c3e.png)

![Opera Snapshot_2020-11-24_095859_www laocommerce com](https://user-images.githubusercontent.com/26108578/100041512-16c72f00-2e3c-11eb-8bba-76123ebd89bc.png)

**Comment by herrvigg** [comment]
@Dezueka I can't reproduce this problem. Can you retry with latest versions of qTranslate-XT and WooCommerce, to see if this is still the case?

![image](https://user-images.githubusercontent.com/19155375/104809452-98f52380-57ed-11eb-99a2-cf46d05e28f0.png)
