### ISSUE TITLE
Translations don't show

### ISSUE THREAD

**Issue by TommyB124** [qtranslate/qtranslate-xt#924]
I have qtranslate-xt running on 2 sites. The first is working really well. The second was working well until I migrated it to a new URL (same domain just in a different folder). It looks like it should be working from the admin pages, all translations are still in place. But, the site itself will not display the translated pages or products. The flags are there to select the language but all pages in Engligh show a 404 error, pages in Spanish work fine.

Any ideas what I need to do to fix this?

Thanks in advance

**Comment by herrvigg** [comment]
At first sight this doesn't seem to be a problem of qTranslate. You have to investigate more on your side and create a precise issue for qTranslate if you find something going wrong.
