### ISSUE TITLE
Disable translation on WooCommerce emails pages

### ISSUE THREAD

**Issue by bichonnages** [qtranslate/qtranslate-xt#925]
Same thing here from https://github.com/qtranslate/qtranslate-xt/issues/652#issue-419586809.

Email addresses should not be translatable on WooCommerce emails settings.
For exemple on https://[website]/wp-admin/admin.php?page=wc-settings&tab=email&section=wc_email_new_order, the email input #woocommerce_new_order_recipient can be translated and if you do enter an email, email cannot be sent anymore. If you leave it blank, its value goes back to the default WP email address it works again since it is not a string with [:xx]email[:xx][:]

I am having difficulties finding the right way to disable the translation of the input field with the Custom Configuration json tool.

**Comment by bichonnages** [comment]
```
"admin": {
		"pages": {
			"admin.php": ""
		},
		"forms": {
		  "mainform": {
			"fields": {
			  "woocommerce_new_order_recipient" : {
				"jquery": "input[id^='woocommerce_new_order_recipient']", 
				"encode": "none"
			  }
			}
		  }
		}	
	},
```

does not work

**Comment by herrvigg** [comment]
I re-opened #652 as it contains more information. We can close this one instead.
