### ISSUE TITLE
Notice using qtranslate-xt

### ISSUE THREAD

**Issue by cbacchini** [qtranslate/qtranslate-xt#928]
I am getting 
Notice: Uninitialized string offset: 9 in C:\Apache24\htdocs\testmass\wp-content\plugins\qtranslate-xt\qtranslate_utils.php on line 298
which I was able to correct modifying qtranslate_utils.php as follows
function qtranxf_complete_url_info_path( &$urlinfo ) {
    if ( isset( $urlinfo['path-base'] ) ) {
        if ( empty( $urlinfo['path-base'] ) ) {
            $urlinfo['wp-path'] = $urlinfo['path'];
        } elseif ( ! empty( $urlinfo['path'] ) && qtranxf_startsWith( $urlinfo['path'], $urlinfo['path-base'] ) ) {
	      if ($urlinfo['path-base'] != $urlinfo['path'] ) {
		      $base_length = strlen( $urlinfo['path-base'] );
		      if ( $urlinfo['path'][ $base_length ] === '/' ) {
			      $urlinfo['wp-path'] = substr( $urlinfo['path'], $base_length );
			      }
		      }
	      else 
		      $urlinfo['wp-path'] = $urlinfo['path'];
        }
    }
}
I am not sure it's the right thing to do, however.

Coudl this be fixed the right way ? 

Thanks!

**Comment by herrvigg** [comment]
I have to look better but this is a file i changed recently, so it's possible i missed something. 

https://github.com/qtranslate/qtranslate-xt/pull/893/files#diff-c4a78e8f6df2bcb7c9161adc2912ee3d684e2b74ea28f4976b81c0b4eb52ee16

**Comment by cbacchini** [comment]
thanks
Cesare Bacchini





*_________________Ing. Cesare BacchiniVia Pantano 1120122 Milano335 8319413*

**Comment by herrvigg** [comment]
@cbacchini i pushed a fix to master, please let me know if this works.

**Comment by cbacchini** [comment]
works fine now, thanks a lot !!

Cesare




*_________________Cesare BacchiniVia Pantano 1120122 Milano335 8319413*

**Comment by herrvigg** [comment]
Fix released in 3.9.2
