### ISSUE TITLE
Notice: wpdb::prepare was called incorrectly

### ISSUE THREAD

**Issue by S-mardii** [qtranslate/qtranslate-xt#929]
I recently clone the plugin from `master` branch in to the latest `WP v5.6` on local environment.

After activated and configuring the Setting of the plugin, I got this error once creating a new Page on my WordPress admin page.

> Notice: wpdb::prepare was called incorrectly. The query argument of wpdb::prepare() must have a placeholder. Please see Debugging in WordPress for more information. (This message was added in version 3.9.0.) in /var/www/html/wp-includes/functions.php on line 5311 

> Notice: wpdb::prepare was called incorrectly. The query does not contain the correct number of placeholders (0) for the number of arguments passed (1). Please see Debugging in WordPress for more information. (This message was added in version 4.8.3.) in /var/www/html/wp-includes/functions.php on line 5311

**Comment by herrvigg** [comment]
We need to better understand the origin of the query. It might not be qTranslate directly.

What are these versions 3.9.0 and 4.8.3? What versions of plugins do you see in the qTranslate troubleshooting section?

You can also change the message to `message . $wpdb->last_query` to possibly get more info.

**Comment by herrvigg** [comment]
@S-mardii any news? Without more information from your side i will have to close this issue.
