### ISSUE TITLE
Issue AM/PM format

### ISSUE THREAD

**Issue by JuanDaniel** [qtranslate/qtranslate-xt#936]
Hi everyone,

I have detected a problem with the date functions when using custom formats.

To be clearer, when I try to display the date of a post through any of the following functions:

`echo get_the_date('h:i a')`
`echo get_the_time('h:i a')`

I get an empty result, however when I remove the 'a' from the format to specify the am/pm it works fine but I am very interested in displaying it using that format.

Have any of you detected this problem ?

I thank you for your help

**Comment by herrvigg** [comment]
Is that really related to qTranslate? What happens if you disable qTranslate?
