### ISSUE TITLE
curious to know how you are generating urls for each language

### ISSUE THREAD

**Issue by snake-venom-nk** [qtranslate/qtranslate-xt#938]
Hi there, 
this is really not an issue, 
but I am curious to know how you are generating URLs for each language like 
/th/ for that , /se/  Swedish language, etc..

what is the specific logic where I can learn to generate such dynamic URLs? 
I was reading this plugin, totally impressive but I can't understand the main place where the URLs are generating. 

I tried to connect with you guys in another way but did not get my email or your blog post URLs. sorry to connect here.

please help.

**Comment by herrvigg** [comment]
It depends on the URL mode. But with the prefix mode (default) which you are mentioning, this is done essentially via the hook `home_url` that we filter in qTranslate. The machinery to handle the path is quite complicated and i often get lost myself... i didn't write the original code but some parts are quite spaghetti code that i'm trying to make more readable and easier to maintain.
