### ISSUE TITLE
qTranslate-xt version 3.9.1 fail to parse url

### ISSUE THREAD

**Issue by manh-trinhquoc** [qtranslate/qtranslate-xt#939]
I had used version 3.8.1 for a long time and it work perfectly. But when I upgrade to version 3.9.1. Some bug appear!!

On pretty permalink mode it detect my page as an attachment and return 404.
![image](https://user-images.githubusercontent.com/34735335/104564504-907ddb00-567d-11eb-88e2-3d4a647e1c13.png)

For default language it return the right page
![image](https://user-images.githubusercontent.com/34735335/104564681-cb800e80-567d-11eb-921a-c3e355be2980.png)

**Comment by herrvigg** [comment]
Is that fixed by your change in #940 ?
Anyhow you should try with the last version available here, which includes the fix for #928 .

**Comment by manh-trinhquoc** [comment]
I try the master branch and the problem is fixed. I think you should announce a new release 3.9.2.

**Comment by herrvigg** [comment]
Fix released in 3.9.2
