### ISSUE TITLE
qTranslate-xt version 3.9.1 function qtranxf_complete_url_info_path throw an ErrorException

### ISSUE THREAD

**Issue by manh-trinhquoc** [qtranslate/qtranslate-xt#940]
In version 3.9.1 the function "qtranxf_complete_url_info_path" was re-written.  When I use Lumberjack framework it throw ErrorException.
![image](https://user-images.githubusercontent.com/34735335/104565800-675e4a00-567f-11eb-800e-a70579c8e930.png)

It throw exception because the statement $urlinfo['path'][ $base_length ] is out of index. I hot fix it by checking !empty($urlinfo['path'][ $base_length ]) first.

The old function in version 3.8.1 work perfectly.

**Comment by herrvigg** [comment]
Duplicate #928.
How did you install qTranslate-XT? If you take the last source from github you should not have this problem.

**Comment by manh-trinhquoc** [comment]
I installed the release 3.9.1 on Nov 12.  I try the master branch and the problem is fixed. I think you should announce a new release 3.9.2.

**Comment by herrvigg** [comment]
Fix released in 3.9.2
