### ISSUE TITLE
There has been a critical error on your website.  

### ISSUE THREAD

**Issue by alexFragoso** [qtranslate/qtranslate-xt#950]
I'm developing this site: https://legacyconsulting.com.pt/

I'm using WPBakery Page Builder and I was using the qtranslate-x plugin, didn't have any problems with the Portuguese version. But when I started doing the English version of the site and tried to see the page in english, I started getting the "There has been a critical error on your website. " white page... I read about it and installed (following the instructions) you new plugin qtranslate-xt. But I still have the same problem.

The back-end editor looks like its working fine... All the information its there in English and Portuguese...

![image](https://user-images.githubusercontent.com/5167073/106298018-484ce400-624b-11eb-838d-c205c03b846a.png)
![image](https://user-images.githubusercontent.com/5167073/106298155-75999200-624b-11eb-81ac-d2b1850686c5.png)

We can see the pages in portuguese:
https://legacyconsulting.com.pt/consultoria-formacao-02/
![image](https://user-images.githubusercontent.com/5167073/106298405-c01b0e80-624b-11eb-9eba-50f01661eaea.png)

But if I try to see the English page:
![image](https://user-images.githubusercontent.com/5167073/106298470-d628cf00-624b-11eb-8f48-9a79b37ad1bc.png)

I deactivated and reactivated all the plugins that are related with the qtranslate (Integration: Yoast SEO & qTranslate-X and WPBakery Visual Composer & qTranslate-X) and didn't make any difference.

**What else should I do?

Please, help...**

Versions
{
  "PHP_VERSION": "7.4.14",
  "WP_VERSION": "5.5.3",
  "QTX_VERSION": "3.9.2",
  "Plugins": [
    "Ultimate Addons for WPBakery Page Builder 3.19.6",
    "Ajax Load More 5.4.2.1",
    "amr shortcode any widget 3.7",
    "FullScreen Menu - Mobile Friendly and Responsive 2.1.8",
    "Cookie Notice 1.3.2",
    "Disable Comments 2.0.2",
    "Duplicate Page 4.3",
    "Duplicator Pro 3.0.9",
    "Imagify 1.9.13",
    "Insert Headers and Footers 1.5.0",
    "Collapse-O-Matic 1.7.13",
    "WPBakery Visual Composer &amp; qTranslate-X 1.0",
    "WPBakery Page Builder 6.4.1",
    "Loginizer 1.6.5",
    "Ninja Forms 3.4.33",
    "Ocean Extra 1.6.9",
    "Ocean Hooks 1.1.1",
    "Ocean Sticky Header 1.1.11",
    "Page scroll to id 1.7.1",
    "Preloader Image Size Extension 1.0.0",
    "qTranslate-XT 3.9.2",
    "Slider Revolution 6.3.5",
    "Preloader 1.0.9",
    "PostX - Gutenberg Post Blocks 2.2.2",
    "Yoast SEO 15.5",
    "WP Google Maps - Pro Add-on 8.1.1",
    "WP Google Maps 8.1.2",
    "WP Mail SMTP 2.5.1",
    "WP Maintenance Mode 2.3.0",
    "WPForms Lite 1.6.4.1"
  ]
}
--------------------------------------------------------------------------------
Configuration
{
  "default_language": "pt",
  "enabled_languages": [
    "pt",
    "en"
  ],
  "flag_location": "plugins/qtranslate-xt/flags/",
  "language_name": {
    "pt": "Português",
    "en": "English"
  },
  "locale": {
    "pt": "pt_PT",
    "en": "en_US"
  },
  "locale_html": {
    "pt": "",
    "en": ""
  },
  "not_available": {
    "pt": "Desculpe, este conteúdo só está disponível em %LANG:, : e %.",
    "en": "Sorry, this entry is only available in %LANG:, : and %."
  },
  "date_format": {
    "pt": "%A, %e \\d\\e %B \\d\\e %Y",
    "en": "%A %B %e%q, %Y"
  },
  "time_format": {
    "pt": "%H:%M",
    "en": "%I:%M %p"
  },
  "flag": {
    "pt": "pt.png",
    "en": "gb.png"
  },
  "url_mode": 2,
  "use_strftime": 3,
  "filter_options_mode": 0,
  "language_name_case": 0,
  "detect_browser_language": false,
  "hide_untranslated": false,
  "show_displayed_language_prefix": true,
  "show_alternative_content": false,
  "hide_default_language": true,
  "use_secure_cookie": false,
  "header_css_on": true,
  "header_css": ".qtranxs_flag_pt {background-image: url(https://legacyconsulting.com.pt/wp-content/plugins/qtranslate-xt/flags/pt.png); background-repeat: no-repeat;}\n.qtranxs_flag_en {background-image: url(https://legacyconsulting.com.pt/wp-content/plugins/qtranslate-xt/flags/gb.png); background-repeat: no-repeat;}\n",
  "text_field_filters": [],
  "term_name": [],
  "disable_client_cookies": false,
  "ignore_file_types": [
    "gif",
    "jpg",
    "jpeg",
    "png",
    "svg",
    "pdf",
    "swf",
    "tif",
    "rar",
    "zip",
    "7z",
    "mpg",
    "divx",
    "mpeg",
    "avi",
    "css",
    "js",
    "mp3",
    "mp4",
    "apk"
  ],
  "url_info": {
    "cookie_lang_front": "en",
    "cookie_lang_admin": "pt",
    "cookie_front_or_admin_found": true,
    "scheme": "https",
    "host": "legacyconsulting.com.pt",
    "path": "/wp-admin/admin-ajax.php",
    "query": "action=admin_debug_info&_fs_blog_admin=true",
    "path-base": "",
    "wp-path": "/wp-admin/admin-ajax.php",
    "language_neutral_path": true,
    "http_referer": "https://legacyconsulting.com.pt/wp-admin/options-general.php?page=qtranslate-xt",
    "referer_admin": true,
    "doing_front_end": false,
    "lang_cookie_admin": "pt",
    "lang_admin": "pt",
    "language": "pt",
    "set_cookie": false,
    "page_referer": "options-general.php"
  },
  "language": "pt",
  "editor_mode": 0,
  "highlight_mode": 1,
  "auto_update_mo": true,
  "hide_lsb_copy_content": false,
  "lsb_style": "Simple_Buttons.css",
  "config_files": [
    "./i18n-config.json"
  ],
  "custom_i18n_config": [],
  "custom_fields": [],
  "custom_field_classes": [],
  "post_type_excluded": [],
  "translator": {},
  "qtrans_compatibility": false
}
----------------------------------------------------------------------
Browser
{
  "cookies": [],
  "navigator": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36"
}

**Comment by herrvigg** [comment]
This is a very generic error, typically a 500 internal error. It can come from anything, bad system configuration, web server, integration with other plugins. Sorry but as for many others, there is nothing i can do with so little information. You have to investigate more on your side.
Take a look here: https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting
Try to run in WP_DEBUG and so on.

**Comment by herrvigg** [comment]
Also thanks for providing the troubleshooting info, but this looks like a very standard configuration, very close to the default and what i have in production. So nothing crazy coming from this. If the admin part works, it's some other configuration which i believe is not related to qTranslate directly. But if you find more elements showing it's really an issue in qTranslate you can re-open this ticket.
