### ISSUE TITLE
can't find .t-3.9.2/i18n-config.json

### ISSUE THREAD

**Issue by webstudio24fr** [qtranslate/qtranslate-xt#951]
After installing qtranslate-xt and deactivating the qtranslate-x plugin I get this error message:
Error: Could not find file ".t-3.9.2/i18n-config.json" listed in option "Configuration Files". 
In the config. files there are 2 files listed:
./i18n-config.json
.t-3.9.2/i18n-config.json

When I remove the 2nd one the issue seems to be solved, is this correct? Thanks!

**Comment by herrvigg** [comment]
Strange, i assume you had a double installation with `qtranslate-xt-3.9.2` aside and you renamed the folders.
You can just remove the 2d entry `.t-3.9.2/i18n-config.json` and the problem should be solved.
The first one is the main config (default).

**Comment by webstudio24fr** [comment]
Thank you herrvigg, I didn't have a double installation or renamed folders, I only had the old version of qtranslate-X, version 3.4.6.8
For your info: I had this same issue on 4 of my sites (all the same regarding qtranslate-x). Removing the 2d entry solves it indeed.

**Comment by herrvigg** [comment]
But you had a double install qTranslate-X and qTranslate-XT? It looks like the `.t-3.9.2` comes from an install in `qtranslate-xt.3.9.2`. XT still share the same options with X so they may even be changes coming from X if you still use it (which i highly discourage since it's completely obsolete).

**Comment by webstudio24fr** [comment]
I had qTranslate-X active when I installed XT and activated, then immediately de-activated X.
Thanks for answering, it works fine since I removed the 2d entry.
