### ISSUE TITLE
product has been removed from your cart because it has since been modified

### ISSUE THREAD

**Issue by Adilhl** [qtranslate/qtranslate-xt#956]
Hello,
 i have this problem with multi variation product, i use WooCommerce TM Extra Product Options plugin as product variation.
and the last version of qtranslate
can you help please.

**Comment by Adilhl** [comment]
Also, i have issue with cart language

**Comment by herrvigg** [comment]
Please provide the precise steps to reproduce if you want to give a change to understand the problem.

Same for the other issue, but check also in the current issues if it's not already existing.

Invalid issues (lack of description, not reproducible) are going to be closed.
https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting
