### ISSUE TITLE
Qtranslate and .po/.mo files, why not working?

### ISSUE THREAD

**Issue by Otta230** [qtranslate/qtranslate-xt#962]
Hello everybody,
I have translated a .po and .mo file of a booking plugin and translation is fine.
I have checked translation changing default language inside general > language and in front-end I see the booking form in different language.
Then I have installed Qtranslate-xt, which I know very well, it works fine with titles and contents … but booking form in front page is not changing language . 
What can I do?

**Comment by herrvigg** [comment]
I don't think it is up to qTranslate to load the .mo file (`load_textdomain`) which is dependent on the locale. There is a hook in qTranslate `qtranxf_localeForCurrentLanguage` but that only manipulates the locale itself, it will not load any textdomain.

The only part where a textdomain is loaded is `qtranxf_getLanguageName` but that's to read the language names from a .mo file specific for that purpose.

**Comment by herrvigg** [comment]
How would qTranslate even know which textdomain file to load if it's in a different plugin?

**Comment by herrvigg** [comment]
I don't see how to solve this. Please re-open if you can better explain what you expect.
