### ISSUE TITLE
WooCommerce PDF Invoices & Packing Slips - 

### ISSUE THREAD

**Issue by valerensi** [qtranslate/qtranslate-xt#963]
Hi,
in several projects we have add "WooCommerce PDF Invoices & Packing Slips" plugin to create invoices and packaging lists from WooCommerce orders. 
Unfortunately the product title is display with lang tag [:it]nome prodotto[:en]product name[:]
Anyone has found out a work around to fix this issue? Thanks.

**Comment by herrvigg** [comment]
hi,
perhaps this has just been solved by #957. It's merged in master, can you try with the current version (just download the zip again) or make the same change in the code by adding `woocommerce_product_get_name` in `qwc_add_filters_front`.
Would be nice to check.

**Comment by isoph** [comment]
I use version 3.9.3 on a site that has WooCommerce PDF Invoices & Packing Slips and PDF Invoices in both languages are fine, no qtranslate code is visible. 

But I use a custom WooCommerce PDF Invoices & Packing Slips theme and strings are pulled either from WooCommerce PDF Invoices & Packing Slips or from my theme’s translated strings.

**Comment by herrvigg** [comment]
@valerensi was this solved with the last release (3.9.3)?
The last changes in `master` don't concern this but it could have been fixed before.

**Comment by valerensi** [comment]
Hello @herrvigg, yes I confirm that the issue is solved with the latest release :)
