### ISSUE TITLE
preg_match() expects parameter 2 to be string

### ISSUE THREAD

**Issue by Buildbetter** [qtranslate/qtranslate-xt#966]
Warning: preg_match() expects parameter 2 to be string, array given in /home/xxx/xxxx.com/wp-content/plugins/qtranslate-xt/qtranslate_utils.php on line 407

Warning: Cannot modify header information - headers already sent by (output started at /home/xxx/xxx.com/wp-content/plugins/qtranslate-xt/qtranslate_utils.php:407) in /home/xxx/xxx.com/wp-includes/functions.php on line 6360

I use plugin [Custom Field Suite](https://wordpress.org/plugins/custom-field-suite/)
I have a page in admin with metabox with additional textarea with editor, when save page the bug is present. I think its because we have second editor on the page!

I add a fix here -> plugins\qtranslate-xt\qtranslate_utils.php line 407 on function qtranxf_isMultilingual

`	if( is_array($str) ) {
		$str = $str[0];
	} `

The new code is 

`function qtranxf_isMultilingual( $str ) {
    $lang_code = QTX_LANG_CODE_FORMAT;
	if( is_array($str) ) {
		$str = $str[0];
	} 
    return preg_match( "/|\[:$lang_code]|{:$lang_code}/im", $str );
}`

And the Bug is gone. Can you check id and add it to plugin. i Think its useful and important fix!

**Comment by herrvigg** [comment]
`qtranxf_isMultilingual` is not meant to be call with an array, so the problem comes from the caller side. The fix you propose makes it more robust but it "hides" the real problem. Why would you  just take the first item? What is contained in the next ones and why should we ignore them?

Imo we need to handle that case earlier. Can you should me the call stack in that case?
You can perhaps trigger an error with `assert(is_string($str))`.

**Comment by herrvigg** [comment]
@Buildbetter any news about this?

**Comment by Buildbetter** [comment]
I test it and it works! Here is my code is it correct? 

function qtranxf_isMultilingual( $str ) {
    $lang_code = QTX_LANG_CODE_FORMAT;
	$str = assert(is_string($str)); // added line qtranslate-xt/qtranslate_utils.php on line 409
    return preg_match( "/|\[:$lang_code]|{:$lang_code}/im", $str );
}

**Comment by herrvigg** [comment]
We can add the assert but we should do that in any case, not only for `is_admin()`.
However, asserts are mainly for debug. Ideally we should not have them in the code, I limit them as much as possible.
We've never had issues with that function before, if this helped to find and fix your bug that's great. I'd say we can close this.

**Comment by herrvigg** [comment]
Oh I see you also changed the regex from
`return preg_match( "/|[:$lang_code]|{:$lang_code}/im", $str );`
to 
`return preg_match( "/|[:$lang_code]|{:$lang_code}/im", $str );`

No, that will not work for delimiters other that brackets. Sorry, we can't do that.
