### ISSUE TITLE
qtranslate-xt admin js not being loaded on certain ACF options pages

### ISSUE THREAD

**Issue by hirasso** [qtranslate/qtranslate-xt#967]
Hi there! 

I am registering an ACF options page like this:

```php
// I have a custom post type 'product'
register_post_type('product', $args);
// And I am adding an option page as a child of this post type
acf_add_options_page([
  'page_title' => __('Product Options', 'rhseo'),
  'menu_slug' => 'options--product',
  'post_id' => 'options--product', 
  'parent_slug' => "edit.php?post_type=product", // <-- This puts the options page underneath the post type in the admin
]);
```

![image](https://user-images.githubusercontent.com/869813/108044531-ac8ce780-7042-11eb-8f93-343ef3f16bbf.png)

See the third Submenu item? This is my custom ACF options page.

This all works great, except that the qtranslate language switcher scripts are not being loaded, so I can't switch the language on this page. Could you look into this?

**Comment by herrvigg** [comment]
Sorry i won't have time to investigate more on this. The ACF part with Javascript is more complex than the other but this should be possible to do.

**Comment by Tusko** [comment]
+1

**Comment by bichonnages** [comment]
+1

Any clue?

**Comment by herrvigg** [comment]
I think this is solved by the last changes in master mentioned in #1233.
A bit unclear why it didn't work with 3.12.0, there was a regression with 3.12.1.
Please try with the master branch a report any issue with ACF custom options pages in #1233. There will be a new release soon.
