### ISSUE TITLE
ACF  wordpress editor

### ISSUE THREAD

**Issue by tlonovoi** [qtranslate/qtranslate-xt#968]
Hello! 
It is all OK when working with text fields, text areas or WP editor in text mode. But when you switch custom ACF field (wp editor field) to visual mode, it doensn't work :(
Is there any way to fix it?
Thank you very much in advance!

**Comment by herrvigg** [comment]
Maybe some other developers using ACF could help here, this will not be the priority on my side.

**Comment by MK-RD** [comment]
@tlonovoi Use the field type WYSIWYG editor (qTranslate)

**Comment by herrvigg** [comment]
@tlonovoi can we close this ticket with the proposed solution?

**Comment by tlonovoi** [comment]
> @tlonovoi Use the field type WYSIWYG editor (qTranslate)

Yes! Thanx! It's all ok with WYSIWYG !

**Comment by tlonovoi** [comment]
> @tlonovoi can we close this ticket with the proposed solution?

yes!
