### ISSUE TITLE
 Use Pre-Path Mode is disabled

### ISSUE THREAD

**Issue by andreysneg** [qtranslate/qtranslate-xt#969]
Use Pre-Path Mode is disabled

Picture:
https://bit.ly/3aDxZd1

WP 5.6.1
qtransleta 3.91 and 3.92

Something new ?

**Comment by herrvigg** [comment]
You probably need to select pretty URLs in the permalinks, duplicate #821.

**Comment by herrvigg** [comment]
@andreysneg did it solve the problem? Can we close this?

**Comment by herrvigg** [comment]
@andreysneg I suppose it's due to missing pretty URLs. I close for now, re-open if it's something else.
