### ISSUE TITLE
Issue when updating the page?

### ISSUE THREAD

**Issue by BrandoCatastrofe** [qtranslate/qtranslate-xt#973]
Hi, thanks for all the work that everyone is putting in the plugin development.
I have a strange issue where when the plugin is active, if I try to update a page after making changes, the server goes blank to a 403 page. I don't think it's a permission issue, as when I deactivate the plugin the website works just fine.
I've uploaded the plugin as the website had qtranslate-X on it, but it was giving out the same error.

Can someone help me? Thank you very much!

**Comment by herrvigg** [comment]
Very difficult to tell, this looks like a specific problem in your setup. You might find a few tips here: https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting

I close this ticket for now. You can re-open it if you can investigate better and provide more information.
