### ISSUE TITLE
Wrong Locale at front-end

### ISSUE THREAD

**Issue by andreysneg** [qtranslate/qtranslate-xt#974]
I setup  Locale at front-end:  ru-EE

pic: https://bit.ly/3pTaTUc

But result is: ru-RU  ?

pic:  https://bit.ly/2ZP3SsZ

**Comment by herrvigg** [comment]
Yes I also realized there could be a discrepancy, there is some weird detection happening to link it to the WordPress locale and I don't know the reasons for this choice. That could explain why it's not the same. For now the front-end setting applies to hreflang in first place.

**Comment by herrvigg** [comment]
More info in #1030, see also #668.
