### ISSUE TITLE
Add Secure to "SameSite" attribute

### ISSUE THREAD

**Issue by sean-pk-mcgrath** [qtranslate/qtranslate-xt#976]
I have the following warning on my browser (in newer browsers it should already be an error):

> Cookie “qtrans_front_language” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

The fix, according to the site, is:

> To fix this, you will have to add the Secure attribute to your SameSite=None cookies.
> 
> Set-Cookie: flavor=choco; SameSite=None; Secure

**Comment by herrvigg** [comment]
I didn't know about the "SameSite" attribute but the Secure attribute is already handled:
Advanced options /  Make qTranslate‑XT cookies available only through HTTPS connections.

This was handled for the front cookie long ago. For the admin cookie it was fixed in 3.7.0 with #467.

**Comment by sean-pk-mcgrath** [comment]
Thanks for the quick reply, herrvigg. You are correct: enabling that option eliminated the error message.

I missed the reply in [https://github.com/qtranslate/qtranslate-xt/issues/644](url)
