### ISSUE TITLE
Pre-Path mode (url_mode) disabled by default after fresh install

### ISSUE THREAD

**Issue by mangeot** [qtranslate/qtranslate-xt#979]
Dear qtranslators,

I'm using qtranslate-xt on one site and it works pretty well.
I tried a fresh install of wp and qtranslate-xt on another server with php8 but the pre-path mode (url_mode) is disabled by default on the admin form. I cannot select and activate it. 

I first though that pre-path mode was using url rewriting but it does not seem so. Could you tell me what is the mechanism behind so that I can debug my installation?

Any help would be greatly appreciated.

Best regards,

{
  "PHP_VERSION": "8.0.3",
  "WP_VERSION": "5.6.2",
  "QTX_VERSION": "3.9.2.p.3",
  "Plugins": [
    "qTranslate-XT 3.9.2",
    "WordPress Importer 0.7"
  ]
}
{
  "default_language": "fr",
  "enabled_languages": [
    "fr",
    "en"
  ],
  "flag_location": "plugins/qtranslate-xt/flags/",
  "language_name": {
    "fr": "Français",
    "en": "English"
  },
  "locale": {
    "fr": "fr_FR",
    "en": "en_US"
  },
  "locale_html": {
    "fr": "",
    "en": ""
  },
  "not_available": {
    "fr": "Désolé, cet article est seulement disponible en %LANG:, : et %.",
    "en": "Sorry, this entry is only available in %LANG:, : and %."
  },
  "date_format": {
    "fr": "%A %e %B %Y",
    "en": "%A %B %e%q, %Y"
  },
  "time_format": {
    "fr": "%H:%M",
    "en": "%I:%M %p"
  },
  "flag": {
    "fr": "fr.png",
    "en": "gb.png"
  },
  "url_mode": "1",
  "use_strftime": 3,
  "filter_options_mode": 0,
  "language_name_case": 0,
  "detect_browser_language": true,
  "hide_untranslated": false,
  "show_displayed_language_prefix": true,
  "show_alternative_content": false,
  "hide_default_language": true,
  "use_secure_cookie": false,
  "header_css_on": true,
  "header_css": ".qtranxs_flag_fr {background-image: url(http://xxx/wpfr/wp-content/plugins/qtranslate-xt/flags/fr.png); background-repeat: no-repeat;}\n.qtranxs_flag_en {background-image: url(http://xxx/wpfr/wp-content/plugins/qtranslate-xt/flags/gb.png); background-repeat: no-repeat;}\n",
  "text_field_filters": [],
  "term_name": [],
  "disable_client_cookies": false,
  "ignore_file_types": [
    "gif",
    "jpg",
    "jpeg",
    "png",
    "svg",
    "pdf",
    "swf",
    "tif",
    "rar",
    "zip",
    "7z",
    "mpg",
    "divx",
    "mpeg",
    "avi",
    "css",
    "js",
    "mp3",
    "mp4",
    "apk"
  ],
  "url_info": {
    "cookie_lang_front": "en",
    "cookie_lang_admin": "fr",
    "cookie_front_or_admin_found": true,
    "scheme": "http",
    "host": "xxx",
    "path": "/wpfr/wp-admin/admin-ajax.php",
    "query": "action=admin_debug_info",
    "path-base": "/wpfr",
    "wp-path": "/wp-admin/admin-ajax.php",
    "language_neutral_path": true,
    "http_referer": "http://xxx/wpfr/wp-admin/options-general.php?page=qtranslate-xt",
    "referer_admin": true,
    "doing_front_end": false,
    "lang_cookie_admin": "fr",
    "lang_admin": "fr",
    "language": "fr",
    "set_cookie": false
  },
  "language": "fr",
  "editor_mode": "2",
  "highlight_mode": 1,
  "auto_update_mo": true,
  "hide_lsb_copy_content": false,
  "lsb_style": "Simple_Buttons.css",
  "config_files": [
    "./i18n-config.json"
  ],
  "custom_i18n_config": [],
  "custom_fields": [],
  "custom_field_classes": [],
  "post_type_excluded": [],
  "translator": {},
  "qtrans_compatibility": false
}
{
  "cookies": [],
  "navigator": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0"
}

**Comment by herrvigg** [comment]
Most likely a problem of redirection.
Good you found about the permalink structure (#821). Since this question is so recurrent I added a notice when the permalink is not compatible.
