### ISSUE TITLE
Changing content in ACF WYSIWYG fields leads to changes in both languages

### ISSUE THREAD

**Issue by EyefinityMedia** [qtranslate/qtranslate-xt#984]
Hi there,

After migrating I use QTranslate XT now for a website and have setup 2 languages. The website is built up with ACF fields. I had also this issue before migrating.

The problem is that when I change the English or French Content in the front page in one of the ACF area textfields (WYSIWYG), the other language is being changed as well.

This makes it impossible for me to have separated languages

Any fixes/solutions for this?

**Comment by herrvigg** [comment]
I'm not sure I understand well ("in the front page"?), but first, are you sure you are using the "Wysiwyg Editor (qTranslate)" field? The basic Wysiwyg Editor certainly does not work for the translations, you need the qTranslate counterpart.

**Comment by EyefinityMedia** [comment]
You are my hero! I didn't know there were different ACF fields for using the translation. It works so my problem seems to be solved :)
