### ISSUE TITLE
Undefined text variable in JS admin

### ISSUE THREAD

**Issue by SarcasticSaint** [qtranslate/qtranslate-xt#995]
When im switching language, i have content from maing language and error in console"

Uncaught ReferenceError: text is not defined
    at y (main.js?ver=3.10.0.dev.0:formatted:381)
    at t.<anonymous> (main.js?ver=3.10.0.dev.0:formatted:807)
    at t.switchActiveLanguage (main.js?ver=3.10.0.dev.0:formatted:638)
    at HTMLLIElement.clickSwitchLanguage (main.js?ver=3.10.0.dev.0:formatted:649)

in main.js its here
 text = e.contentField.value,
![error1](https://user-images.githubusercontent.com/30025259/113703263-412ad200-96e3-11eb-85e4-cc16eeb9a223.png)
![error2](https://user-images.githubusercontent.com/30025259/113703265-41c36880-96e3-11eb-857e-7d63d00c7f64.png)

Problem in LSB mode, in Single Language Mode everything ok

**Comment by herrvigg** [comment]
Great you are testing on master :)
Strange this error didn't trigger in my case... there must be something with the strict mode. But I just pushed a patch now, should be fixed.

**Comment by SarcasticSaint** [comment]
Stable builds are boring xD
Yes, your fix working for me. 
Thanks
